---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 10184.
--- DateTime: 2020/6/4 21:29
---
CustomShopPet.curSwordLight = nil
CustomShopPet.curTimerKey = 0

local function playAction(setting)
    GUICustomShop.awPet1:SetActor1("", "", 0)
    GUICustomShop.awPet2:SetActor1("", "", 0)
    GUICustomShop:playSkill(setting.uiPlayerSkill)
    GUICustomShop.awPet1:SetActor1(setting.ActorName, setting.uiSkillName, 0)
    GUICustomShop.awPet2:SetActor1(setting.ActorName, setting.uiSkillName, 0)
    GUICustomShop.awPet2:SetRotateY(GUICustomShop.awPlayer2:GetRotateY())
    GUICustomShop.awPet1:SetRotateY(GUICustomShop.awPlayer1:GetRotateY())
end

function CustomShopPet:onTabChange(isSelect)
    LuaTimer:cancel(self.curTimerKey)
    GUIManager:getWindowByName("BedWarCustomShop-Pet-Layout1"):SetVisible(isSelect)
    GUIManager:getWindowByName("BedWarCustomShop-Pet-Layout2"):SetVisible(isSelect)
end

function CustomShopPet:onSelectGoods(goods)
    local setting = self.Settings[goods.SettingId]
    if not setting then
        return
    end
    GUICustomShop.awPet1:SetXPosition({ setting.uiXOffset, 0 })
    GUICustomShop.awPet1:SetYPosition({ setting.uiYOffset, 0 })
    GUICustomShop.awPet2:SetXPosition({ setting.uiXOffset, 0 })
    GUICustomShop.awPet2:SetYPosition({ setting.uiYOffset, 0 })
    GUICustomShop.awPet1:SetWidth({ setting.scale, 0 })
    GUICustomShop.awPet2:SetWidth({ setting.scale, 0 })

    playAction(setting)
    local playerTime = GUICustomShop.awPlayer1:GetActor():GetSkillTimeLength(setting.uiPlayerSkill)
    local petTime = GUICustomShop.awPet1:GetActor():GetSkillTimeLength(setting.uiSkillName)
    local time = petTime
    if playerTime > petTime then
        time = playerTime
    end

    LuaTimer:cancel(self.curTimerKey)
    self.curTimerKey = LuaTimer:scheduleTimer(function()
        playAction(setting)
    end, time)
end

function CustomShopPet:getPendantById(id)
    if self.Settings[tostring(id)] ~= nil then
        return self.Settings[tostring(id)].pendant
    end
    return nil
end