---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangpq.
--- DateTime: 2019/10/9 18:15
---
Test = {}

function Test.doTest()
    --UnitConfig:init(FileUtil.getConfigFromCsv("setting/Unit.csv", 2))
    --HostApi.log("Utility.toKMBString0 " .. Utility.toKMBString(tostring(123456789000), 0))
    --HostApi.log("Utility.toKMBString1 " .. Utility.toKMBString(tostring(123456789000), 1))
    --HostApi.log("Utility.toKMBString2 " .. Utility.toKMBString(tostring(123456789000), 2))
    --HostApi.log("math.huge " .. tostring(BigNum.new(math.huge)))
end

function Test.changeHoldItemActor()
    --TODO
end

return Test