---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangpq.
--- DateTime: 2019/10/11 16:56
---
GameClient = {}

GameClient.poleControlState = 1

GameClient.gamePauseStartTime = 0
GameClient.gamePauseTime = 0

return GameClient