---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 10184.
--- DateTime: 2020/6/3 20:29
---

GUIBlockShopGoods = class("GUIBlockShopGoods", IGUIWindow)

function GUIBlockShopGoods:onLoad()
    self.root:registerEvent(GUIEvent.Click, function()
        SoundUtil.playSound(SoundConfig.selectGoodsStore)
        GUIBlockShop:onSelectGoods(self.data)
        ReportUtil.reportBlockShopSelect(self.data.Id)
    end)
    self.llBg = self:getChildWindowByName("BedWarBlockShopGoods", GUIType.Layout)
    self.ivImage = self:getChildWindowByName("BedWarBlockShopGoods-Icon", GUIType.StaticImage)
    self.ivPrice = self:getChildWindowByName("BedWarBlockShopGoods-Price-Icon", GUIType.StaticImage)
    self.tvPrice = self:getChildWindowByName("BedWarBlockShopGoods-Price-Text", GUIType.StaticText)
    self.ivUseIcon = self:getChildWindowByName("BedWarBlockShopGoods-Equip", GUIType.StaticImage)
    self.llLock = self:getChildWindowByName("BedWarBlockShopGoods-Mask")
    self.ivSelect = self:getChildWindowByName("BedWarBlockShopGoods-Select", GUIType.StaticImage)
end

function GUIBlockShopGoods:onDataChanged(data)
    self.data = data
    self.ivImage:SetImage(data.Image)
    --self.tvName:SetText(Lang:getString(data.Name))
    self.tvPrice:SetText(tostring(data.Price))
    self.ivSelect:SetVisible(GUIBlockShop.curSelectGoods == data)
    if data.Time == -1 or data.Time > 0 then
        self.llLock:SetVisible(false)
        self.ivPrice:SetVisible(false)
        self.tvPrice:SetVisible(false)
    else
        self.llLock:SetVisible(true)
        self.ivPrice:SetVisible(true)
        self.tvPrice:SetVisible(true)
    end
    self.ivUseIcon:SetVisible(data.Status == CustomShopGoodsStatus.Equiped)
end