---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by JY-032.
--- DateTime: 2019/10/14 20:55
---
require "listener.GameListener"
require "packet.S2CPacketHandler"

PluginMain = {}

function PluginMain:init()
    GameListener:init()
end

PluginMain:init()
return PluginMain