---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/7/23 17:39
---
require "common.ui.window.GUIBlockShopTab"
require "common.ui.window.GUIBlockShopGoods"

local UIBlockShop = class("GUIBlockShop", IGUILayout)

function UIBlockShop:onLoad()
    self.scale = 1
    self.curSelectTab = nil
    self.curSelectGoods = nil

    local width = self.root:GetPixelSize().x
    if width < 1000 then
        self.scale = math.floor(width / 100) / 10
    end
    self.llContent = self:getChildWindow("BedWarBlockShop-Content", GUIType.Layout)
    self.llContent:SetHeight({ 0, 528 * self.scale })
    self.llContent:SetWidth({ 0, 850 * self.scale })
    self.btnClose = self:getChildWindow("BedWarBlockShop-Close", GUIType.Button)
    self.llClose = self:getChildWindow("BedWarBlockShop-Continue", GUIType.Layout)
    self.llTabs = self:getChildWindow("BedWarBlockShop-Big-Tabs", GUIType.Layout)
    self.awDetail = self:getChildWindow("BedWarBlockShop-Detail-Actor", GUIType.ActorWindow)
    self.awDetailEffect = self:getChildWindow("BedWarBlockShop-Effect", GUIType.Layout)
    local llMoney = self:getChildWindow("BedWarBlockShop-Money", GUIType.Layout)
    self.llCurrency = GUICurrency.new("BedWarCurrency.json")
    self.llCurrency:onDataChanged({ ItemId = 0, RealId = Define.Money.DIAMOND })
    self.llCurrency.tvMoney:SetFont(GUIFontManager:Instance():GetFont("YSB20"))
    llMoney:AddChildWindow(self.llCurrency.root)

    self:getChildWindow("BedWarBlockShop-Title-Text"):SetText(Lang:getString("bed.war.block.shop.title"))

    self.btnClose:registerEvent(GUIEvent.ButtonClick, function()
        self:hide(true)
    end)

    self.llClose:registerEvent(GUIEvent.Click, function()
        self:hide(true)
    end)

    self.btnBuy = self:getChildWindow("BedWarBlockShop-Operation-Btn", GUIType.Button)
    self.btnBuy:registerEvent(GUIEvent.ButtonClick, function()
        self:onBuyClick()
    end)

    self.bigTabGroup = RadioBoxGroup.new()
    self:initGoodsListUI()
    self:initTabs()

    self.smallTabGroup = RadioBoxGroup.new()
    self.leftTab = self:getChildWindow("BedWarBlockShop-Small-Tab1", GUIType.CheckBox)
    self.rightTab = self:getChildWindow("BedWarBlockShop-Small-Tab2", GUIType.CheckBox)
    self.smallTabGroup:addCheckBox(self.leftTab, function(check)
        if check then
            self.curType = BlockShopConfig.Type.Skin
            self:onSelectSubTab(self.curSelectTab)
        end
    end)
    self.smallTabGroup:addCheckBox(self.rightTab, function(check)
        if check then
            self.curType = BlockShopConfig.Type.Wall
            self:onSelectSubTab(self.curSelectTab)
        end
    end)

    ---设置方块自转逻辑
    self:setBlockActor()
    ---需要延后一帧处理,等UI new完成,设置成全局变量
    LuaTimer:schedule(function()
        self.bigTabGroup:selectIndex(1)
    end, 0)
end

function UIBlockShop:initGoodsListUI()
    local llGoodsList = self:getChildWindow("BedWarBlockShop-List-Content")
    self.gvGoodsList = IGUIGridView.new("BedWarBlockShop-Goods-List", llGoodsList)
    self.gvGoodsList:setConfig(20 * self.scale, 16 * self.scale, 2)
    self.goodsAdapter = require("common.ui.adapter.BlockShopGoodsAdapter").new()
    local contentWidth = self.gvGoodsList:getWidth()
    local itemWidth = (contentWidth - 20 * self.scale) / 2
    self.goodsAdapter:setItemSize(itemWidth, itemWidth)
    self.gvGoodsList:setAdapter(self.goodsAdapter)
end

function UIBlockShop:isShowAnim()
    return false
end

function UIBlockShop:setBlockActor()
    local llSlideBlock = self:getChildWindow("BedWarBlockShop-Slide-Block")
    llSlideBlock:registerMouseEvent(GUIEvent.TouchDown, function(events)
        self.lockDetail = true
        llSlideBlock:SetHeight({ 0, 2000 })
        llSlideBlock:SetWidth({ 0, 3000 })
    end)

    llSlideBlock:registerMouseEvent(GUIEvent.TouchMove, function(events)
        self.awDetail:TouchMove(events.position)
        self.awDetail:TouchMove(events.position)
    end)

    llSlideBlock:registerMouseEvent(GUIEvent.TouchUp, function()
        self.lockDetail = false
        llSlideBlock:SetHeight({ 0.8, 0 })
        llSlideBlock:SetWidth({ 1, 0 })
    end)

    self.blockKey = LuaTimer:scheduleTimer(function()
        if not self.lockDetail then
            self.awDetail:SetRotateY(self.awDetail:GetRotateY() + 1)
        end
    end, 20)
    --
end

function UIBlockShop:initTabs()
    self.bigTabGroup:addCheckBox()
    local BlockShop = BlockShopConfig:getBlockShop()
    for index, tab in pairs(BlockShop) do
        local tabUI = GUIBlockShopTab.new("BedWarBlockShopTab.json")
        tabUI.root:SetHorizontalAlignment(HorizontalAlignment.Right)
        tabUI:setArea({ 0, 0 }, { 0, 84 * (index - 1) * self.scale }, { 0, 122 * self.scale }, { 0, 70 * self.scale })
        tabUI:onDataChanged(tab)
        self.llTabs:AddChildWindow(tabUI.root)
        self.bigTabGroup:addCheckBox(tabUI.cbTab, function(check)
            tabUI:setChecked(check)
            self.leftTab:SetText(Lang:getString(tab.LeftLang))
            self.rightTab:SetText(Lang:getString(tab.RightLang))
            self:onSelectSubTab(tab)
            self.smallTabGroup:selectIndex(1)
        end)
    end
end

local function updateTabsLayout(tabs, tab)
    local itemHeight = tab.root:GetPixelSize().y
    local listHeight = tabs.root:GetPixelSize().y
    tabs.root:SetItemHeight(itemHeight + listHeight + math.random(1, 100))
    local items = tabs.items
    local _tab
    for _, item in pairs(items) do
        if item == tab then
            _tab = tab
        end
    end
    if not _tab then
        return
    end
    itemHeight = _tab.root:GetPixelSize().y
    local itemPosY = _tab.root:GetYPosition()[2]
    listHeight = tabs:getHeight()
    local currentOffset = tabs.root:GetScrollOffset()
    if itemPosY + itemHeight + currentOffset < listHeight and itemPosY >= -currentOffset then
        return
    end
    local container = tabs.root:GetChildByIndex(0)
    local containerHeight = container:GetPixelSize().y
    local maxOffset = listHeight - containerHeight
    local needOffset = itemPosY + currentOffset
    local offset = currentOffset - needOffset
    tabs.root:SetScrollOffset(math.min(math.max(offset, maxOffset), 0))
end

function UIBlockShop:updateTabsLayout(tab)
    updateTabsLayout(self.lvTabs, tab)
end

function UIBlockShop:onShow(tabId)
    GUIMain.ivBlockShopPoint:SetVisible(false)
    if tabId then
        local BlockShop = BlockShopConfig:getBlockShop()
        for index, tab in pairs(BlockShop) do
            if tab.TabId == tabId then
                self.bigTabGroup:selectIndex(index)
                return
            end
        end
        self:hide()
    end
end

function UIBlockShop:onSelectGoods(goods)
    local oldGoods = self.curSelectGoods
    self.curSelectGoods = nil
    self.goodsAdapter:notifyItemDataChange(oldGoods)
    self.curSelectGoods = goods
    self.goodsAdapter:notifyItemDataChange(goods)
    self.awDetail:SetActor1(goods.ActorName, "idle", 0)
    self.awDetail:SetArea({ tonumber(goods.ActorPos[1]), 0 }, { tonumber(goods.ActorPos[2]), 0 }, { goods.ActorScale, 0 }, { 0, 0 })
    self.awDetailEffect:SetVisible(goods.EffectName ~= "#")
    self.awDetailEffect:SetEffectName(goods.EffectName)
    self.awDetailEffect:SetArea({ tonumber(goods.EffectPos[1]), 0 }, { tonumber(goods.EffectPos[2]), 0 }, { goods.EffectScale, 0 }, { 0, 0 })
    self.awDetailEffect:SetHeight({ 0, self.awDetailEffect:GetPixelSize().x })

    self:updateBuyButtonUI()
    --CustomShop:onSelectGoods(self.curSelectGoods)
end

function UIBlockShop:updateBuyButtonUI()
    if not self.curSelectGoods then
        return
    end
    self.btnBuy:SetVisible(true)
    self.btnBuy:SetNormalImage("set:bed_war_block_shop.json image:btn_yellow")
    self.btnBuy:SetPushedImage("set:bed_war_block_shop.json image:btn_yellow")
    if self.curSelectGoods.Time == -1 or self.curSelectGoods.Time > 0 then
        if self.curSelectGoods.Status == CustomShopGoodsStatus.Equiped then
            self.btnBuy:SetNormalImage("set:bed_war_block_shop.json image:btn_blue")
            self.btnBuy:SetPushedImage("set:bed_war_block_shop.json image:btn_blue")
            self.btnBuy:SetText(Lang:getString("bed.war.custom.shop.unload"))
        else
            self.btnBuy:SetText(Lang:getString("bed.war.custom.shop.equip"))
        end
    else
        local reward = SumRechargeConfig:getRechargeReward(self.curSelectGoods.Id)
        if reward then
            self.btnBuy:SetVisible(false)
            return
        end
        self.btnBuy:SetText(Lang:getString("shop_btn_buy"))
    end
end

function UIBlockShop:onTick()
    self.llCurrency:onTick()
end

function UIBlockShop:onSelectSubTab(tab)
    if self.curSelectTab then
        if self.curSelectTab.TabId == tab.TabId then
            return
        end
    end
    self.curSelectTab = tab
    ReportUtil.reportBlockShopPage(tostring(tab.TabId))
    local goodsList = BlockShopConfig:getGoodsList(tab.TabId, self.smallTabGroup:getCurIndex() or BlockShopConfig.Type.Skin)
    self.goodsAdapter:setData(goodsList)
    if #goodsList > 0 then
        self:onSelectGoods(goodsList[1])
    end
    self.goodsAdapter:setScrollOffset(0)
end

function UIBlockShop:updateListUI()
    self.goodsAdapter:notifyDataChange()
    self:updateBuyButtonUI()
end

function UIBlockShop:updateGoodsUI(goods)
    self.goodsAdapter:notifyItemDataChange(goods)
end

function UIBlockShop:onBuyClick()
    if not self.curSelectGoods then
        return
    end
    if self.curSelectGoods.Time == -1 or self.curSelectGoods.Time > 0 then
        if self.curSelectGoods.Status == CustomShopGoodsStatus.Equiped then
            BlockShop:onUnloadGoods(self.curSelectGoods) --卸下装备
        else
            SoundUtil.playSound(SoundConfig.useGoodsStore)
            BlockShop:onEquipGoods(self.curSelectGoods) --去装备
        end
    else
        ReportUtil.reportBlockShopBuy("button1", self.curSelectGoods.Id)
        GameAnalytics:design(1, { "buy_customshop", "button1", tostring(self.curSelectGoods.Id) })
        SoundUtil.playSound(SoundConfig.buyGoodsStore)
        if self.curSelectGoods.Price < 0 then
            return
        end
        BlockDetailContent:setGoodsInfo(self.curSelectGoods.Image)
        CustomDialog.builder().setContentView(BlockDetailContent)
                    .setHideLeftButton()
                    .setTitleText("gui_bird_store_desc")
                    .setRightIcon("set:bed_war_block_shop.json image:icon_cube_border")
                    .setRightText(tostring(self.curSelectGoods.Price))
                    .setRightClickListener(function()
            LuaTimer:schedule(function()
                CheckMoneyContent:setTextColor(Color.BLACK)
                PayHelper.checkMoney(Define.Money.DIAMOND, self.curSelectGoods.Price, function(canBuy)
                    if canBuy then
                        ReportUtil.reportBlockShopBuy("button2", self.curSelectGoods.Id)
                        GameAnalytics:design(1, { "buy_customshop", "button2", tostring(self.curSelectGoods.Id) })
                        BlockShop:onBuyGoods(self.curSelectGoods) --去购买
                    end
                end)
            end, 100)
        end)        .show()
    end
end

function UIBlockShop:showBuyGoodsSuccess(goodsId)
    local goods = BlockShopConfig:getGoodsConfig(goodsId)
    if not goods then
        return
    end
    if not GUIBlockShop:isShow() then
        return
    end
    BlockDetailContent:setGoodsInfo(goods.Image)
    CustomDialog.builder()
                .setContentView(BlockDetailContent)
                .setHideLeftButton()
                .setRightText("custom.shop.equip.immediate")
                .setRightClickListener(function()
        BlockShop:onEquipGoods(goods)
    end)        .show()
end

return UIBlockShop

