---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/11/18 16:09
---

local PriceGroups = {}

LuckyLotteryPriceConfig = {}

local function init()
    local path = FileUtil:getMapPath() .. "common/LuckyLotteryPrice.csv"
    local file = io.open(path, "r")
    if not file then
        return
    end
    io.close(file)

    local config = CsvUtil.loadCsvFile(path, 3)
    for _, item in pairs(config) do
        local group = PriceGroups[tostring(item.groupId)] or {}
        local price = {
            id = tonumber(item.id),
            moneyType = tonumber(item.moneyType) or 1,
            moneyImage = item.moneyImage,
            price = tonumber(item.price) or 999,
            times = tonumber(item.times) or 1,
            priceLang = item.priceLang,
            discountPrice = tonumber(item.discountPrice) or 999,
            discountType = tonumber(item.discountType) or 0,
            discountCycle = tonumber(item.discountCycle) or 0
        }
        table.insert(group, price)
        PriceGroups[tostring(item.groupId)] = group
    end
    for _, group in pairs(PriceGroups) do
        table.sort(group, function(a, b)
            return a.times < b.times
        end)
    end
end

function LuckyLotteryPriceConfig:getPriceConfigByGroupId(groupId)
    return PriceGroups[tostring(groupId)]
end

function LuckyLotteryPriceConfig:getDisCountPrice(priceGroupId,type,lastLotteryTime)
    local priceConfigGroup = LuckyLotteryPriceConfig:getPriceConfigByGroupId(priceGroupId)
    local priceConfig = priceConfigGroup[type]
    local realPrice = priceConfig.price
    if priceConfig.discountPrice < priceConfig.price and (os.time() - lastLotteryTime) > priceConfig.discountCycle then
        realPrice = priceConfig.discountPrice
    end
    return realPrice
end

init()