
---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Hesh.
--- DateTime: 2020/2/8 21:38
---
LuaTimerHelper = {}

local function onLastTime(taskInfo)
    if taskInfo.callBack then
        taskInfo.callBack()
    end
end

local function timerCalled(taskInfo)
    if taskInfo.times ~= 0 then
        taskInfo.action(taskInfo.args)
        taskInfo.times = taskInfo.times - 1
        if taskInfo.times == 0 then
            onLastTime(taskInfo)
        end
    end
end

function LuaTimerHelper:cancel(key)
    LuaTimer:cancel(key)
end

function LuaTimerHelper:scheduleTimer(action, period, times, finalCallBack , ...)
    local taskInfo = {
        action = action,
        callBack = finalCallBack,
        times = times,
        args = (...)
    }
    return LuaTimer:scheduleTimer(timerCalled, period, times , taskInfo)
end

return LuaTimerHelper