---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/9/14 20:33
---
local LicenseRewardShowItemAdapt = class("LicenseRewardShowItemAdapt", IDataAdapter)

function LicenseRewardShowItemAdapt:setItemSize(width, height)
    self.width = width
    self.height = height
end

function LicenseRewardShowItemAdapt:getWindowClass()
    return GUILicenseShowItem
end

function LicenseRewardShowItemAdapt:getJsonName()
    return "BedWarLicenseShowItem.json"
end

function LicenseRewardShowItemAdapt:getItemWidth()
    return { 0, self.width }
end

function LicenseRewardShowItemAdapt:getItemHeight()
    return { 0, self.height }
end

return LicenseRewardShowItemAdapt