---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/7/18 12:17
---
LicenseExchangeAdapt = class("LicenseExchangeAdapt", IDataAdapter)

function LicenseExchangeAdapt:setItemSize(width, height)
    self.width = width
    self.height = height
end

function LicenseExchangeAdapt:getWindowClass()
    return GUILicenseExchangeItem
end

function LicenseExchangeAdapt:getJsonName()
    return "BedWarLicenseExchangeItem.json"
end

function LicenseExchangeAdapt:getItemWidth()
    return { 0, self.width }
end

function LicenseExchangeAdapt:getItemHeight()
    return { 0, self.height }
end

return LicenseExchangeAdapt