---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/7/16 16:43
---
local LicenseRewardListAdapt = class("LicenseRewardListAdapt", IDataAdapter)

function LicenseRewardListAdapt:setItemSize(width, height)
    self.width = width
    self.height = height
end

function LicenseRewardListAdapt:getWindowClass()
    return UILicenseRewardListItem
end

function LicenseRewardListAdapt:getJsonName()
    return "BedWarLicenseRewardListItem.json"
end

function LicenseRewardListAdapt:getItemWidth()
    return { 0, self.width }
end

function LicenseRewardListAdapt:getItemHeight()
    return { 0, self.height }
end

return LicenseRewardListAdapt