---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangpq.
--- DateTime: 2019/9/17 10:32
---
GameListener = {}

local function hideEngineWindow(name)
    local window = GUIManager:getWindowByName(name)
    if not window then
        return
    end
    window:SetXPosition({ 0, 6000 })
    window:SetVisible(false)
end

function GameListener:init()
    BaseListener.registerCallBack(GameReadyEvent, self.onGameReady)
    Listener.registerCallBack(CallPluginFunctionEvent, function(func, extra)
        if func == "ProbabilityDialog" then
            ProbabilityDialog.show(extra)
        end
    end)
end

function GameListener.onGameReady()
    hideEngineWindow("PlayerInfo-Health")
    hideEngineWindow("PlayerInfo-FoodSaturation")
end

return GameListener