---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 10184.
--- DateTime: 2020/4/30 14:48
---

IGUIDataView = class("IGUIDataView", EventObservable) ---@class IGUIDataView : EventObservable

function IGUIDataView:init(root)
    self.root = root
    self.items = {}
    self.adapter = nil
    self.orientation = Orientation.Vertical
end

function IGUIDataView:setAdapter(adapter)
    self.adapter = adapter
    self.adapter:setView(self)
    self.root:EnableVirtualList() ---设置使用虚拟列表模式
end

function IGUIDataView:getAdapter()
    return self.adapter
end

function IGUIDataView:setArea(xPos, yPos, width, height)
    if not self.root then
        return
    end
    self.root:SetArea(xPos, yPos, width, height)
end

function IGUIDataView:addItem(item, force)
    if self.adapter and not force then
        LogUtil.log("Currently using the adapter mode, you need to add item, please use the adapter to add.", LogUtil.LogLevel.Error)
        return false
    end
    if not self.root then
        GUIManager:destroyGUIWindow(item.root)
        item:destroy()
        return false
    end
    self.root:AddItem(item.root)
    table.insert(self.items, item)
    return true
end

function IGUIDataView:removeItem(remove, destroy, force)
    if self.adapter and not force then
        LogUtil.log("Currently using the adapter mode, you need to remove item, please use the adapter to remove.", LogUtil.LogLevel.Error)
        return false
    end
    if not self.root then
        return false
    end
    if destroy == nil then
        destroy = true
    end
    for pos, item in pairs(self.items) do
        if item == remove then
            self.root:RemoveItem(item.root, destroy)
            if destroy then
                item:destroy()
                table.remove(self.items, pos)
            end
            return true
        end
    end
    return false
end

function IGUIDataView:getItem(type, object)
    for _, item in pairs(self.items) do
        if item[type] == object then
            return item
        end
    end
    return nil
end

function IGUIDataView:getItemCount()
    if self.adapter then
        return self.adapter:getItemCount()
    else
        return #self.items
    end
end

function IGUIDataView:getChildCount()
    return #self.items
end

function IGUIDataView:getWidth()
    if not self.root then
        return 0
    end
    return self.root:GetPixelSize().x
end

function IGUIDataView:getHeight()
    if not self.root then
        return 0
    end
    return self.root:GetPixelSize().y
end

function IGUIDataView:getHorizontalSpace()
    return 0
end

function IGUIDataView:getVerticalSpace()
    return 0
end

function IGUIDataView:getRowSize()
    return 1
end

function IGUIDataView:destroy()
    self:clearItems()
    GUIManager:destroyGUIWindow(self.root)
    self.root = nil
end