#!/usr/bin/env bash
PROJECT_DIR=$(pwd)

BUILD_TYP="0"
APP_APP_ABI="armeabi-v7a"
APK_NAME="app-blockmango-v0.2.16-build-16.apk"
BUILD_ARG="assembleDebug"

while getopts "t:i:" opt; do
    case $opt in
		t)
		 	if [ $OPTARG == "1" ] || [ $OPTARG == 0 ]; then
		 		BUILD_TYP=$OPTARG
		 		echo "this is -t the arg is ! $BUILD_TYP"
		 	else
		 		echo "error: argument -t=$OPTARG ,-t value 1(Debug) or 0 (Release)"
		 		exit 1
		 	fi
	 	;;
	 	i)
			if [ $OPTARG == "all" ] || [ $OPTARG == "arm64-v8a" ] || [ $OPTARG == "armeabi" ] || [ $OPTARG == "armeabi-v7a" ] || [ $OPTARG == "mips" ] || [ $OPTARG == "mips64" ] || [ $OPTARG == "x86" ] || [ $OPTARG == "x86_64" ]  ; then
				APP_APP_ABI=$OPTARG
				echo "this is -i the arg is ! $APP_APP_ABI"
			else
				echo "error: argument -i=$OPTARG , '-i' value is phone CPU architecture : [ all arm64-v8a armeabi armeabi-v7a mips mips64 x86 x86_64 ]"
		 		exit 1
			fi
		;;
		?)
			echo "unkonw argument : argument -i [ all arm64-v8a armeabi armeabi-v7a mips mips64 x86 x86_64 ]  , -t [ 1(Debug)   0 (Release) ]"
			exit 1
		;;
    esac
done

if [ $BUILD_TYP == "1" ] ; then
	BUILD_ARG="assembleDebug"
else
	BUILD_ARG="assembleDebug"
fi

echo "the arg is ! $BUILD_TYP     $APP_APP_ABI   $APK_NAME    $BUILD_ARG  "


# build FreeType FreeImage zlib libLua
cd "$PROJECT_DIR/../../../../libraries/ApkBuild/"
ndk-build NDK_DEBUG=$BUILD_TYP APP_ABI=$APP_APP_ABI -j4
if [ $? != 0 ]; then
	echo "error:build FreeType FreeImage zlib libLua"
	exit 1
fi

# build LordCore LordGLES2Render
cd "$PROJECT_DIR/../../../../engine/NDKBuild/"
ndk-build NDK_DEBUG=$BUILD_TYP APP_ABI=$APP_APP_ABI -j4
if [ $? != 0 ]; then
	echo "error:build LordCore LordGLES2Render"
	exit 1
fi

# build libLogic
cd "$PROJECT_DIR/../../../../logic/ApkBuild/"
ndk-build NDK_DEBUG=$BUILD_TYP APP_ABI=$APP_APP_ABI -j4
if [ $? != 0 ]; then
	echo "error:build libLogic"
	exit 1
fi

# build libGameClient
cd "$PROJECT_DIR/../../../ApkBuild/"
ndk-build NDK_DEBUG=$BUILD_TYP APP_ABI=$APP_APP_ABI -j4
if [ $? != 0 ]; then
	echo "error:build libGameClient"
	exit 1
fi

# build libMineCraft
cd "$PROJECT_DIR/app/"
ndk-build NDK_DEBUG=$BUILD_TYP APP_ABI=$APP_APP_ABI -j4
if [ $? != 0 ]; then
	echo "error:build libMineCraft"
	exit 1
fi

cd "$PROJECT_DIR"

rm -rf $PROJECT_DIR/app/src/main/assets/resources/Media
rm -rf $PROJECT_DIR/app/src/main/assets/resources/recipe
cp -rf $PROJECT_DIR/../../../../../res/client/Media  $PROJECT_DIR/app/src/main/assets/resources/Media/
cp -rf $PROJECT_DIR/../../../../../res/client/recipe  $PROJECT_DIR/app/src/main/assets/resources/recipe/
cp -rf $PROJECT_DIR/../../../../../res/client/resource.cfg  $PROJECT_DIR/app/src/main/assets/resources/resource.cfg
cp -rf $PROJECT_DIR/../../../../../res/client/version.json  $PROJECT_DIR/app/src/main/assets/resources/version.json

#build apk
cd "$PROJECT_DIR/"
./gradlew $BUILD_ARG
if [ $? != 0 ]; then
	echo "error:build apk"
	exit 1
fi

#install akp
adb install -r "$PROJECT_DIR/app/build/outputs/apk/$APK_NAME"
if [ $? != 0 ]; then
	echo "error:install apk"
	exit 1
fi
adb shell am start -n com.sandboxol.blockmango/com.sandboxol.blockmango.EchoesActivity


