---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jimmy.
--- DateTime: 2019/9/3 0003 10:31
---
require "config.GameConfig"

local function registerCallBack()
    local observable = EventObservable.new()
    observable:registerDataCallBack("TowerList", function(data)
        GamePlayer:Instance():setOwnedTowerList(data)
    end, JsonBuilderProcessor)

    observable:registerDataCallBack("GetNewTowerBook", function(data)
        GamePlayer:Instance():onGetNewTowerBook(data)
    end, JsonBuilderProcessor)

    observable:registerDataCallBack("GetNewTower", function(data)
        GamePlayer:Instance():onGetNewTower(data)
    end, JsonBuilderProcessor)

    observable:registerDataCallBack("PayItemList", function(data)
        GamePlayer:Instance():setOwnedPayItemList(data)
    end, JsonBuilderProcessor)

    observable:registerDataCallBack("BuyPayItemSuccess", function(data)
        GamePlayer:Instance():onGetNewPayItem(data)
    end, DataBuilderProcessor)

    observable:registerDataCallBack("ExchangeRate", function(data)
        GamePlayer:Instance():setExchangeRate(data)
    end, DataBuilderProcessor)

    observable:registerDataCallBack("GGExchangeRate", function(data)
        GamePlayer:Instance():setGameGoldExchangeRate(data)
    end, DataBuilderProcessor)

    observable:registerDataCallBack("EquipSkin", function(data)
        GamePlayer:Instance():EquipSkin(data)
    end, JsonBuilderProcessor)
end

GameListener = {}

function GameListener:init()
    registerCallBack()
    BaseListener.registerCallBack(GameReadyEvent, self.onGameReady)
    BaseListener.registerCallBack(GameDestroyEvent, self.onGameDestroy)
    Listener.registerCallBack(AddChatMessageEvent, self.onAddMessage)
    Listener.registerCallBack(RenderPlayerShowNameEvent, self.onRenderPlayerShowName)

    Listener.registerCallBack(ClickScenePlayActionEvent, function()
        return false
    end)

    Listener.registerCallBack(PlayUpperActionEvent, function()
        return false
    end)
    Listener.registerCallBack(ClickSceneToControllerEvent, function()
        return false
    end)

    Listener.registerCallBack(SumRechargeCreateItemsEvent, function()
        local defineContentWidth = 925
        local defineContentHeight = 512
        local defineRewardWidth = 105

        local name = string.gsub(GUISumRechargeLayout.__name, ".json", "-")
        local llContent = GUISumRechargeLayout:getChildWindow(name .. "Content", GUIType.Layout)
        local btnClose = GUISumRechargeLayout:getChildWindow(name .. "Close", GUIType.Button)
        local totalWidth = btnClose:GetPixelSize().x
        if totalWidth < defineContentWidth then
            defineContentHeight = math.floor(defineContentHeight / defineContentWidth * totalWidth * 0.9)
            defineRewardWidth = math.floor(defineRewardWidth / defineContentWidth * totalWidth * 0.9)
            defineContentWidth = math.floor(totalWidth * 0.9)
        end
        llContent:SetWidth({ 0, defineContentWidth })
        llContent:SetHeight({ 0, defineContentHeight })
        GUISumRechargeLayout:setRewardWidth(defineRewardWidth)
        ---禁止奖励窗滑动
        GUISumRechargeLayout.gvRewards.root:SetMoveAble(false)

        ---调整首充UI Title
        local config = SumRechargeConfig:getSumRecharge(GUISumRechargeLayout.currentId)
        GUISumRechargeLayout:getChildWindow(name .. "Title_c", GUIType.StaticText):SetText(Lang:getString(config.TitleLang))
        GUISumRechargeLayout:getChildWindow(name .. "Title_c_c", GUIType.StaticText):SetText(Lang:getString(config.TitleLang))
        return true
    end)
end

function GameListener.onGameReady()
    GameConfig:init()
    require "ui.GUIFactory"
    PlayerManager:getClientPlayer().Player.m_holdItemId = 200001
    DataBuilderProcessor:registerMapping("UpdateWallet", { "coinId", "count" })
    DataBuilderProcessor:registerMapping("TowerAttack", { "towerId", "targetIds" })
    DataBuilderProcessor:registerMapping("TowerEjections", { "towerId", "targetId", "preTargetId" })
    DataBuilderProcessor:registerMapping("SynHp", { "monsterId", "hp" })
    DataBuilderProcessor:registerMapping("CreateBox", { "yaw", "userId", "pos" })

    if Platform.isWindow() == false then
        GamePlayer:Instance().poleControlState = Blockman.Instance().m_gameSettings.usePole
        local isUsePole = ClientHelper.getBoolForKey(tostring(GamePlayer:Instance().userId) .. ("isTDUsePole"), true)
        if isUsePole == true or isUsePole == nil then
            Utility.refreshPoleControlState(1)
        else
            Utility.refreshPoleControlState(0)
        end
    end

    GamePlayer:Instance().formulaTip = LuaTimer:schedule(function()
        GamePlayer:Instance():setFormulaTip()
    end,15000,1500)

    ClientHelper.putStringPrefs("RechargeGameType", "g1057")
end

function GameListener.onGameDestroy()
    if not Blockman.Instance() or not GamePlayer:Instance() then
        return
    end

    LuaTimer:cancel(GamePlayer:Instance().formulaTip)

    if Platform.isWindow() == false then
        local isUsePole = Blockman.Instance().m_gameSettings.usePole
        if isUsePole == 1 then
            ClientHelper.putBoolForKey(tostring(GamePlayer:Instance().userId) .. ("isTDUsePole"), true)
        else
            ClientHelper.putBoolForKey(tostring(GamePlayer:Instance().userId) .. ("isTDUsePole"), false)
        end
        Utility.refreshPoleControlState(GamePlayer:Instance().poleControlState)
    end
end

function GameListener.onAddMessage(windowName)
    GUIMain:onAddMessage(windowName)
end

function GameListener.onRenderPlayerShowName(pPlayer, actor, position)
    if not pPlayer or not actor then
        return true
    end
    pPlayer:setFloatProperty("PlayerShowNameOffset", (pPlayer:getHeight() + 0.1) * (actor:GetTotalScale().y) - (pPlayer:getYOffset() + 0.25))
    pPlayer:setFloatProperty("PlayerShowNameScale", 0.4 * pPlayer:getHeight())
    return false
end