// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

#ifndef _BEHAVIAC_MEMBER_VISITOR_H_
#define _BEHAVIAC_MEMBER_VISITOR_H_

#include "behaviac_agent_headers.h"

// Agent property and method handlers




struct PROPERTY_TYPE_CommonAgent_attackRange { };
template<> inline int& CommonAgent::_Get_Property_<PROPERTY_TYPE_CommonAgent_attackRange>()
{
	return this->attackRange;
}

struct PROPERTY_TYPE_CommonAgent_chaseRange { };
template<> inline int& CommonAgent::_Get_Property_<PROPERTY_TYPE_CommonAgent_chaseRange>()
{
	return this->chaseRange;
}

struct PROPERTY_TYPE_CommonAgent_isReturning { };
template<> inline bool& CommonAgent::_Get_Property_<PROPERTY_TYPE_CommonAgent_isReturning>()
{
	return this->isReturning;
}

struct PROPERTY_TYPE_CommonAgent_senseRange { };
template<> inline int& CommonAgent::_Get_Property_<PROPERTY_TYPE_CommonAgent_senseRange>()
{
	return this->senseRange;
}

struct METHOD_TYPE_CommonAgent_checkReturning { };
template<> inline bool CommonAgent::_Execute_Method_<METHOD_TYPE_CommonAgent_checkReturning>()
{
	return this->CommonAgent::checkReturning();
}


struct PROPERTY_TYPE_MonsterG1049_patrolInterval { };
template<> inline float& MonsterG1049::_Get_Property_<PROPERTY_TYPE_MonsterG1049_patrolInterval>()
{
	return this->patrolInterval;
}

struct PROPERTY_TYPE_MonsterG1049_patrolRange { };
template<> inline int& MonsterG1049::_Get_Property_<PROPERTY_TYPE_MonsterG1049_patrolRange>()
{
	return this->patrolRange;
}

struct METHOD_TYPE_MonsterG1049_attackEnemy { };
template<> inline void MonsterG1049::_Execute_Method_<METHOD_TYPE_MonsterG1049_attackEnemy>()
{
	this->MonsterG1049::attackEnemy();
}

struct METHOD_TYPE_MonsterG1049_backToPatrolPosBeforBattle { };
template<> inline void MonsterG1049::_Execute_Method_<METHOD_TYPE_MonsterG1049_backToPatrolPosBeforBattle>()
{
	this->MonsterG1049::backToPatrolPosBeforBattle();
}

struct METHOD_TYPE_MonsterG1049_prepareAttack { };
template<> inline void MonsterG1049::_Execute_Method_<METHOD_TYPE_MonsterG1049_prepareAttack>()
{
	this->MonsterG1049::prepareAttack();
}

struct METHOD_TYPE_MonsterG1049_quitBattle { };
template<> inline void MonsterG1049::_Execute_Method_<METHOD_TYPE_MonsterG1049_quitBattle>()
{
	this->MonsterG1049::quitBattle();
}

struct METHOD_TYPE_MonsterG1049_setIdleAction { };
template<> inline void MonsterG1049::_Execute_Method_<METHOD_TYPE_MonsterG1049_setIdleAction>()
{
	this->MonsterG1049::setIdleAction();
}

struct METHOD_TYPE_MonsterG1049_startMoveToPatrolPos { };
template<> inline void MonsterG1049::_Execute_Method_<METHOD_TYPE_MonsterG1049_startMoveToPatrolPos>()
{
	this->MonsterG1049::startMoveToPatrolPos();
}

struct METHOD_TYPE_MonsterG1049_waitMoveOver { };
template<> inline behaviac::EBTStatus MonsterG1049::_Execute_Method_<METHOD_TYPE_MonsterG1049_waitMoveOver>()
{
	return this->MonsterG1049::waitMoveOver();
}


#endif // _BEHAVIAC_MEMBER_VISITOR_H_
