// -------------------------------------------------------------------------------
// THIS FILE IS ORIGINALLY GENERATED BY THE DESIGNER.
// YOU ARE ONLY ALLOWED TO MODIFY CODE BETWEEN '///<<< BEGIN' AND '///<<< END'.
// PLEASE MODIFY AND REGENERETE IT IN THE DESIGNER FOR CLASS/MEMBERS/METHODS, ETC.
// -------------------------------------------------------------------------------

#ifndef _BEHAVIAC_SERVERAGENT_H_
#define _BEHAVIAC_SERVERAGENT_H_

#include "behaviac_headers.h"

///<<< BEGIN WRITING YOUR CODE FILE_INIT
#include <memory>

class TableVisitor;
///<<< END WRITING YOUR CODE

class ServerAgent : public behaviac::Agent
///<<< BEGIN WRITING YOUR CODE ServerAgent
///<<< END WRITING YOUR CODE
{
public:
	ServerAgent();
	virtual ~ServerAgent();

	BEHAVIAC_DECLARE_AGENTTYPE(ServerAgent, behaviac::Agent)

	public: bool FuncBoolean(const behaviac::string& FuncName);

	public: int FuncInt(const behaviac::string& FuncName);

	public: behaviac::EBTStatus FuncStatus(const behaviac::string& FuncName);

	public: void FuncVoid(const behaviac::string& FuncName);

	public: bool ValueBoolean(const behaviac::string& ValueName);

	public: int ValueInt(const behaviac::string& ValueName);

///<<< BEGIN WRITING YOUR CODE CLASS_PART
public:
	public: void Init(TableVisitor tableVisitor, int uniqueId);

private:
	std::shared_ptr<TableVisitor> m_luaVisitor;
	int m_uniqueId = 0;
///<<< END WRITING YOUR CODE
};

///<<< BEGIN WRITING YOUR CODE FILE_UNINIT

///<<< END WRITING YOUR CODE

#endif
