// -------------------------------------------------------------------------------
// THIS FILE IS ORIGINALLY GENERATED BY THE DESIGNER.
// YOU ARE ONLY ALLOWED TO MODIFY CODE BETWEEN '///<<< BEGIN' AND '///<<< END'.
// PLEASE MODIFY AND REGENERETE IT IN THE DESIGNER FOR CLASS/MEMBERS/METHODS, ETC.
// -------------------------------------------------------------------------------

#include "ServerAgent.h"

///<<< BEGIN WRITING YOUR CODE FILE_INIT
#include "LuaRegister/Template/TableVisitor.h"
///<<< END WRITING YOUR CODE

ServerAgent::ServerAgent()
{
///<<< BEGIN WRITING YOUR CODE CONSTRUCTOR

///<<< END WRITING YOUR CODE
}

ServerAgent::~ServerAgent()
{
///<<< BEGIN WRITING YOUR CODE DESTRUCTOR
	m_luaVisitor = NULL;
///<<< END WRITING YOUR CODE
}

bool ServerAgent::FuncBoolean(const behaviac::string& FuncName)
{
///<<< BEGIN WRITING YOUR CODE FuncBoolean
	bool result = false;
	if (m_luaVisitor)
		m_luaVisitor->callFunc(result, "callFunction", FuncName.c_str(), m_uniqueId);
	return result;
///<<< END WRITING YOUR CODE
}

int ServerAgent::FuncInt(const behaviac::string& FuncName)
{
///<<< BEGIN WRITING YOUR CODE FuncInt
	int result = 0;
	if (m_luaVisitor)
		m_luaVisitor->callFunc(result, "callFunction", FuncName.c_str(), m_uniqueId);
	return result;
///<<< END WRITING YOUR CODE
}

behaviac::EBTStatus ServerAgent::FuncStatus(const behaviac::string& FuncName)
{
///<<< BEGIN WRITING YOUR CODE FuncStatus
	int status = 0;
	if (m_luaVisitor)
		m_luaVisitor->callFunc(status, "callFunction", FuncName.c_str(), m_uniqueId);
	return (behaviac::EBTStatus)(status);
///<<< END WRITING YOUR CODE
}

void ServerAgent::FuncVoid(const behaviac::string& FuncName)
{
///<<< BEGIN WRITING YOUR CODE FuncVoid
	int status = 0;
	if (m_luaVisitor)
		m_luaVisitor->callFunc(status, "callFunction", FuncName.c_str(), m_uniqueId);
///<<< END WRITING YOUR CODE
}

bool ServerAgent::ValueBoolean(const behaviac::string& ValueName)
{
///<<< BEGIN WRITING YOUR CODE ValueBoolean
	bool result = false;
	if (m_luaVisitor)
		m_luaVisitor->callFunc(result, "callValue", ValueName.c_str(), m_uniqueId);
	return result;
///<<< END WRITING YOUR CODE
}

int ServerAgent::ValueInt(const behaviac::string& ValueName)
{
///<<< BEGIN WRITING YOUR CODE ValueInt
	int result = 0;
	if (m_luaVisitor)
		m_luaVisitor->callFunc(result, "callValue", ValueName.c_str(), m_uniqueId);
	return result;
///<<< END WRITING YOUR CODE
}


///<<< BEGIN WRITING YOUR CODE FILE_UNINIT
void ServerAgent::Init(TableVisitor tableVisitor, int uniqueId)
{
	std::shared_ptr<TableVisitor> luaVisitor(new TableVisitor(tableVisitor));
	m_luaVisitor = luaVisitor;
	m_uniqueId = uniqueId;
}
///<<< END WRITING YOUR CODE
