---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jimmy.
--- DateTime: 2019/9/3 0003 15:09
---
--肌肉量改变
MuscleMassChangeEvent = IScriptEvent.new()
CommonDataEvents:registerEvent("MuscleMassChange", MuscleMassChangeEvent)

--Hp改变
HpChangeEvent = IScriptEvent.new()
CommonDataEvents:registerEvent("HpChange", HpChangeEvent)

--金币改变
GoldChangeEvent = IScriptEvent.new()
CommonDataEvents:registerEvent("GoldChange", GoldChangeEvent)

--健身器材改变
FitnessEquipChangeEvent = IScriptEvent.new()
CommonDataEvents:registerEvent("FitnessEquipChange", FitnessEquipChangeEvent)

--商店的进阶改变
ShopAdvancedChangeEvent = IScriptEvent.new()
CommonDataEvents:registerEvent("ShopAdvancedChange", ShopAdvancedChangeEvent)

--点击ToolBar的金币旁的按钮
ToolBarGoldClickEvent = IScriptEvent.new()
CommonDataEvents:registerEvent("ToolBarGoldClick", ToolBarGoldClickEvent)

ShopItemClickEvent =IScriptEvent.new()
CommonDataEvents:registerEvent("ShopItemClick", ShopItemClickEvent)

PayDataInitEvent =IScriptEvent.new()
CommonDataEvents:registerEvent("PayDataInitEvent", PayDataInitEvent)

--付费商店item点击事件
PayShopItemClickEvent =IScriptEvent.new()
CommonDataEvents:registerEvent("PayShopItemClick", PayShopItemClickEvent)

--付费商店Toolbar点击事件
PayShopToolbarClickEvent=IScriptEvent.new()
CommonDataEvents:registerEvent("PayShopToolbarClick", PayShopToolbarClickEvent)

--付费商店商品初始化
PayShopItemUpdateEvent = IScriptEvent.new()
CommonDataEvents:registerEvent("PayShopItemUpdate", PayShopItemUpdateEvent)

--主界面点击皮肤按钮
MainControlClickSkinEvent = IScriptEvent.new()
CommonDataEvents:registerEvent("MainControlClickSkin", MainControlClickSkinEvent)

MainControlClickVipEvent = IScriptEvent.new()
CommonDataEvents:registerEvent("MainControlClickVip", MainControlClickVipEvent)

MainControlCustomDialogClickEvent = IScriptEvent.new()
CommonDataEvents:registerEvent("MainControlCustomDialogClick", MainControlCustomDialogClickEvent)

MainControlPretendUpdateEvent = IScriptEvent.new()
CommonDataEvents:registerEvent("MainControlPretendUpdate", MainControlPretendUpdateEvent)

MainControlToolGoldUpdateEvent = IScriptEvent.new()
CommonDataEvents:registerEvent("MainControlToolGoldUpdate", MainControlToolGoldUpdateEvent)

--付费商店item的button点击事件
PayShopItemClickButtonEvent = IScriptEvent.new()
CommonDataEvents:registerEvent("PayShopItemClickButton", PayShopItemClickButtonEvent)

TipItemShowEvent = IScriptEvent.new()
CommonDataEvents:registerEvent("TipItemShow", TipItemShowEvent)

RefreshPayFitnessEquipItemEvent = IScriptEvent.new()
CommonDataEvents:registerEvent("RefreshPayFitnessEquipItem", RefreshPayFitnessEquipItemEvent)

ToolBarNewGuideClickEvent = IScriptEvent.new()
CommonDataEvents:registerEvent("ToolBarNewGuideClick", ToolBarNewGuideClickEvent)

ToolBarSeasonRankClickEvent = IScriptEvent.new()
CommonDataEvents:registerEvent("ToolBarSeasonRankClick", ToolBarSeasonRankClickEvent)

SeasonRankTipOpenEvent = IScriptEvent.new()
CommonDataEvents:registerEvent("SeasonRankTipOpen", SeasonRankTipOpenEvent)

TokenShopItemClickEvent =IScriptEvent.new()
CommonDataEvents:registerEvent("TokenShopItemClick", TokenShopItemClickEvent)
