---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/4/14 0014 17:22
---
require "hall.config.DressStoreConfig"
require "hall.ui.window.GUIDressStoreTabItem"
require "hall.ui.window.GUIDressStorePanItem"
require "hall.ui.window.GUIDressStoreInfoItem"

UIDressStore = class("UIDressStore", IGUILayout)

local curTableIndex = 0
local curSelectId = 0
local dressData = {}
local initTabFlag = 0
local changeFlag = 0

function UIDressStore:onLoad()

    self.layMain = self:getChildWindow("DressStore-Main", GUIType.Layout)
    self.layDetail = self:getChildWindow("DressStore-Detail", GUIType.Layout)
    self.layModel = self:getChildWindow("DressStore-Preview-Model", GUIType.Layout)
    self.layInfos = self:getChildWindow("DressStore-Preview-Infos", GUIType.Layout)
    self.Tabs = self:getChildWindow("DressStore-Content-Tabs", GUIType.Layout)
    self.layPanel = self:getChildWindow("DressStore-Content-Panels", GUIType.Layout)

    self.awModel = self:getChildWindow("DressStore-Model", GUIType.ActorWindow)

    self.btnClose = self:getChildWindow("DressStore-Close", GUIType.Button)

    self.stTitle = self:getChildWindow("DressStore-Title", GUIType.StaticText)

    self.siResult = self:getChildWindow("DressStore-Result", GUIType.StaticImage)
    self.siResultActor = self:getChildWindow("DressStore-Result-Actor", GUIType.EffectViewOfObtainment)
    self.siResultActor:SetActorPos(0.0, 0.0, 0.0, -90.0)
    self.siResult:SetVisible(false)

    self:updateLanguage()

    self:register()

    self:initModel()

    self:initInfo()
end

function UIDressStore:updateLanguage()
    self.stTitle:SetText(Lang:getString("gui_dress_stroe_name"))
end

function UIDressStore:register()
    self.btnClose:registerEvent(GUIEvent.ButtonClick, function()
        SoundUtil.playSound(SoundType.ClosePanel)
        self:hide()
    end)

    self.siResult:registerEvent(GUIEvent.TouchDown, function()
        if false then
            return false
        end
        self.siResult:SetVisible(false)
    end)

    self:registerDataCallBack("ShowDressStore", function()
        if curTableIndex ~= 0 or curTableIndex ~= 1 then
            if self.gvTabItems then
                local curitem = self.gvTabItems:getItem("index", curTableIndex)
                curitem.btnButton:SetChecked(false)
                curitem.btnButton:SetTouchable(true)
                local item = self.gvTabItems:getItem("index", 1)
                item.btnButton:SetChecked(true)
                item.btnButton:SetTouchable(false)
            end
        end
        GUIDressStore:show()
    end)

    self:registerDataCallBack("DressStoreData", function(data)
        for _, dress in pairs(data) do
            self:initDressData(dress)
        end
        if initTabFlag == 1 then
            self:showPanelByType(curTableIndex)
        else
            self:initTabs()
        end
    end, JsonBuilderProcessor)

    self:registerEvent(DressStoreTabChangeEvent, function(index)
        changeFlag = 1
        self:cbChangeState(index)
    end)

    self:registerEvent(UIDressStorePanItemChangeEvent, function(id)
        self:panelItemChange(id)
    end)

    self:registerEvent(ShowUseDressEvent, function(id)
        self:setUseDress(id)
    end)
end

function UIDressStore:initTabs()
    self.Tabs:CleanupChildren()
    local tabs = DressConfig:getDressTables()
    local len = 0
    local MinCount
    for _, k in pairs(tabs) do
        len = len + 1
    end
    if len > 5 then
        MinCount = len
    else
        MinCount = 5
    end
    if self.gvTabItems ~= nil then
        self.gvTabItems:destroy()
    end
    self.gvTabItems = IGUIGridView.new("DressStore-Content-Tabs-Item", self.Tabs)
    self.gvTabItems:setArea({ 0, 0 }, { 0, 0 }, { 1, 0 }, { 1, 0 })
    self.gvTabItems:setConfig(1, 1, 1)
    self.gvTabItems.root:SetHorizontalAlignment(HorizontalAlignment.Center)
    self.gvTabItems.root:SetVerticalAlignment(VerticalAlignment.Center)
    self.gvTabItems.root:SetClipChild(false)
    local TabSize = (self.Tabs:GetPixelSize().y - 1 - MinCount) / MinCount
    local TabWidth = self.Tabs:GetPixelSize().x
    local tabCount = 0
    local index = 0
    for _, tab in pairs(tabs) do
        tabCount = tabCount + 1
        index = index + 1
        local newNum = self:getNewCountByType(tab.Type)
        local item = UIDressStoreTableItem.new("DressStoreTab.json")
        item:setWidth({ 0, TabWidth })
        item:setHeight({ 0, TabSize })
        item:initTab(tab, newNum)
        item:setIndex(index)
        item:registerClick(tab.Type)
        self.gvTabItems:addItem(item)
    end
    local item = self.gvTabItems:getItem("index", 1)
    item.btnButton:SetChecked(true)
    self:initPanel()
    self:showPanelByType(1)
    initTabFlag = 1
end

function UIDressStore:onShow()
    local GuideWindow = GUIManager:getWindowByName("GuideSystem")
    if GuideWindow:IsVisible() then
        self:cbChangeState(1)
    end
end

function UIDressStore:cbChangeState(index)
    if index ~= curTableIndex then
        local curItem = self.gvTabItems:getItem("index", curTableIndex)
        if curItem ~= nil then
            curItem.btnButton:SetChecked(false)
            curItem.btnButton:SetTouchable(true)
        end
        local newItem = self.gvTabItems:getItem("index", index)
        if newItem ~= nil then
            newItem.btnButton:SetChecked(true)
            newItem.btnButton:SetTouchable(false)
        end
        self:initPanel()
        self:showPanelByType(index)
    end
end

function UIDressStore:initPanel()
    self.layPanel:CleanupChildren()
    if self.gvDreItems ~= nil then
        self.gvDreItems:destroy()
    end
    self.gvDreItems = IGUIGridView.new("DressStore-Content-Panels-Item", self.layPanel)
    self.gvDreItems:setArea({ 0, 0 }, { 0, 0 }, { 1, 0 }, { 1, 0 })
    self.gvDreItems:setConfig(6, 6, 4)
    self.gvDreItems.root:SetHorizontalAlignment(HorizontalAlignment.Center)
    self.gvDreItems.root:SetVerticalAlignment(VerticalAlignment.Center)

    local ContentSize = self.layPanel:GetPixelSize().x
    local ChildWidth = (ContentSize - 4 * 4) / 4
    local DressAdapter = require "hall.ui.adapter.DressAdapter"
    self.adapter = DressAdapter.new()
    self.adapter:setItemSize({ ChildWidth, math.floor(ChildWidth * 0.88) })
    self.gvDreItems:setAdapter(self.adapter)
end

function UIDressStore:showPanelByType(type)
    curTableIndex = type
    curSelectId = nil
    local dressConfig = DressConfig:getDressConfigByType(type)
    self.adapter:setData(dressConfig)
    if dressConfig and dressConfig[1] then
        local curItem = self.gvDreItems:getItem("Id", dressConfig[1].Id)
        if curItem then
            curItem:onClock()
        end
    end
end

function UIDressStore:panelItemChange(id)
    local statue = self:getStatuesById(curSelectId)
    local newStatue = self:getStatuesById(id)
    if curSelectId == nil then
        self.info:updateAndShow(id)
    elseif id ~= curSelectId and changeFlag ~= 1 then
        local curItem = self.gvDreItems:getItem("Id", curSelectId)
        if curItem == nil then
            curSelectId = id
            self.adapter:notifyDataChange()
            return false
        end
        if statue == 2 or statue == 1 then
            --1 = NOT_GET   2 = NEW
            curItem.siStatueBox:SetImage("set:dress_shop.json image:not_get")
        elseif statue == 0 then
            --0 = LOCK
            curItem.siStatueBox:SetImage("set:dress_shop.json image:lock")
        elseif statue == 3 or statue == 4 then
            curItem.siStatueBox:SetImage("set:dress_shop.json image:has_get")
        end
    end
    if changeFlag == 1 then
        changeFlag = 0
    end
    if newStatue ~= 0 then
        self.info:updateAndShow(id)
    else
        self.info:cleanInfo()
    end
    curSelectId = id
    self.adapter:notifyDataChange()
end

function UIDressStore:initInfo()
    --local gvInfoItem = IGUIGridView.new("DressStore-Preview-Info-Item", self.layInfos)
    --gvInfoItem:setArea({ 0, 0 }, { 0, 0 }, { 1, 0 }, { 1, 0 })
    --gvInfoItem:setConfig(0, 0, 1)
    --gvInfoItem.root:SetHorizontalAlignment(HorizontalAlignment.Center)
    --gvInfoItem.root:SetVerticalAlignment(VerticalAlignment.Center)
    self.info = UIDressStoreInfoItem.new("DressStoreInfos.json")
    self.info:setWidth({ 1, 0 })
    self.info:setHeight({ 1, 0 })
    self.layInfos:AddChildWindow(self.info.root)
end

function UIDressStore:initModel()
    local sex = PlayerManager:getClientPlayer():getSex()
    if sex <= 1 then
        self.awModel:SetActor1("boy.actor", "idle", -45)
    else
        self.awModel:SetActor1("girl.actor", "idle", -45)
    end
end

function UIDressStore:setUseDress(dressId)
    self.awModel:reflreshArmor(Game:getPlayer())
    local config = DressConfig:findStoreDressById(dressId)
    self.awModel:UseBodyPart(config.ModelActorBody, config.ModelActorBodyId)
    if "armor_head" == config.ModelActorBody then
        self.awModel:UseBodyPart("custom_hair", 0)
    end
end

function UIDressStore:initDressData(data)
    local dress = UIDressStore:getDressData(data.Id)
    if dress then
        if data.Status then
            dress.Status = data.Status
            if tonumber(dress.Status) == 5 then
                GUIStoreDressDetail:init(data.Id, data.Chip)
                local config = DressConfig:findStoreDressByItemId(data.Id)
                if config then
                    self.siResult:SetVisible(true)

                    self.siResultActor:SetActor("g1008_skin2.actor")
                    self.siResultActor:UseBodyPart("body", config.BodyId)
                end
            end
        end
        if data.Chip then
            dress.Chip = data.Chip
        end
    else
        dress = {}
        dress.Id = data.Id
        dress.Status = data.Status
        dress.Chip = data.Chip or 0
        table.insert(dressData, dress)
    end
end

function UIDressStore:changeStatue(id, statue)
    for i, item in pairs(dressData) do
        if item.Id == id then
            dressData[i].Status = statue
        end
    end
end

function UIDressStore:getStatuesById(id)
    for _, statue in pairs(dressData) do
        if statue.Id == id then
            return statue.Status
        end
    end
    return 0
end

function UIDressStore:getDressData(id)
    for _, dress in pairs(dressData) do
        if dress.Id == id then
            return dress
        end
    end
end

function UIDressStore:isSelect(id)
    if curSelectId == id then
        return true
    else
        return false
    end
end

function UIDressStore:getNewCountByType(type)
    local dress = DressConfig:findStoreDressByTabType(type)
    local count = 0
    for _, dre in pairs(dress) do
        local statue = self:getStatuesById(dre.Id)
        if statue == 2 then
            count = count + 1
        end
    end
    return count
end

return UIDressStore