---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/9/9 15:42
---

local GUIIndieAdContent = class("GUIIndieAdContent", IGUILayout)

function GUIIndieAdContent:onLoad()
    self:getChildWindow("BedWarIndieAdContent-tip1", GUIType.StaticText):SetText(Lang:getString("bed.war.cube.vedio.ad.content"))
    self:getChildWindow("BedWarIndieAdContent-tip2", GUIType.StaticText):SetText(Lang:getString("bed.war.cube.vedio.ad.count"))
end

IndieAdContent = buildCustomDialogContent(GUIIndieAdContent, "BedWarIndieAdContent.json")