---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/5/14 14:28
---

GameInfoChangeEvent = IScriptEvent.new()

GameInfo = class("GameInfo")

local infoIndex = 0

function GameInfo:ctor(index)
    infoIndex = infoIndex + 1
    self.index = index or infoIndex
    self.keyIndex = 0
    self.isChange = false
    self.data = {}
    self.KeyType = {}
    self:initKey()
end

function GameInfo:initKey()
    self:addKey("name", "test", false)
end

function GameInfo:addKey(key, initValue, needSync)
    self.keyIndex = self.keyIndex + 1
    self.KeyType[key] = tostring(self.keyIndex)
    self.KeyType[tostring(self.keyIndex)] = key
    self.data[tostring(key)] = {
        keyIndex = self.keyIndex,
        needSync = needSync,
        isChange = false,
        value = initValue,
    }
end

function GameInfo:buildChangePacket()
    if not self.isChange then
        return ""
    end
    self.isChange = false
    local valueChangeList = { self.index }
    for _, keyTable in pairs(self.data) do
        if keyTable.isChange then
            keyTable.isChange = false
            table.insert(valueChangeList, keyTable.keyIndex .. "'" .. keyTable.value)
        end
    end
    return table.concat(valueChangeList, ":")
end

function GameInfo:buildAllPacket()
    local valueChangeList = { self.index }
    for _, keyTable in pairs(self.data) do
        if keyTable.needSync then
            table.insert(valueChangeList, keyTable.keyIndex .. "'" .. keyTable.value)
        end
    end
    return table.concat(valueChangeList, ":")
end

function GameInfo:forceSync(keyList)
    for _, key in pairs(keyList) do
        local keyTable = self.data[key]
        if keyTable then
            keyTable.isChange = true
            self.isChange = true
        end
    end
end

function GameInfo:haveSameValue(key, value)
    local dataValue = self:getValue(key)
    if not dataValue then
        ---not have key
        return false
    end
    if dataValue == value then
        return true
    end
    return false
end

function GameInfo:setValue(key, value)
    key = tostring(key)
    if not self.KeyType[key] then
        ---not have key
        return
    end
    local keyTable = self.data[key]
    if keyTable.value == tostring(value) then
        return
    end
    keyTable.value = tostring(value)
    keyTable.isChange = keyTable.needSync
    self.isChange = self.isChange or keyTable.needSync
end

function GameInfo:setValueByIndex(keyIndex, value)
    if not self.KeyType[tostring(keyIndex)] then
        ---not have key
        return
    end
    self:setValue(self.KeyType[tostring(keyIndex)], value)
end

function GameInfo:getValue(key)
    key = tostring(key)
    if not self.KeyType[key] then
        ---not have key
        return
    end
    return self.data[key].value
end

function GameInfo:print()
    print("InfoKey:", self.infoKey)
    for key, keyTable in pairs(self.data) do
        print(key, "=", keyTable.value)
    end
    print("--------------------")
end