---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Hesh.
--- DateTime: 2020/2/7 17:56
---

local UIInterlude = class("UIInterlude", IGUILayout)

function UIInterlude:onLoad()
    self.data = {}
    self.textChangeTimerKey = 0

    self.mainLayout = self:getChildWindow("TowerDefenseSettlement-OnGameOverInterlude", GUIType.Layout)

    self.backgroundGray = self:getChildWindow("TowerDefenseSettlement-Gray", GUIType.Layout)
    self.mainWinEffect = self:getChildWindow("TowerDefenseSettlement-InterludeWin", GUIType.StaticImage)
    self.mainFailEffect = self:getChildWindow("TowerDefenseSettlement-InterludeFail", GUIType.StaticImage)
    self.continueBtn = self:getChildWindow("TowerDefenseSettlement-ContinueBtn", GUIType.Button)

    -- 目标为200 / 255 的Aplya值共变化20次 200 / 255 / 20
    self.backgroundAlphaAmountChange = 0.0392157

    self:registerDataCallBack("Reward", function(data)
        self:onGameOver(data)
    end, DataBuilderProcessor)

    self.continueBtn:registerEvent(GUIEvent.ButtonClick, function()
        self:onClickScreen()
    end)
end

function UIInterlude:onClickScreen()
    self.mainLayout:SetVisible(false)
    self.mainWinEffect:SetVisible(false)
    self.mainFailEffect:SetVisible(false)
    LuaTimer:cancel(self.NotClickTimerKey)
    self:hide()
    GUITowerDefenseSettlement:updateRewardInfo(self.data)
    self.backgroundColor[4] = 0
    self.backgroundGray:SetBackgroundColor(self.backgroundColor)
end

function UIInterlude:onGameOver(data)
    self.continueBtn:SetTouchable(false)
    self.data = data
    self.backgroundColor = GUIInterlude.backgroundGray:GetBackgroundColor()
    self:show()
    self.mainLayout:SetVisible(true)
    LuaTimerHelper:scheduleTimer(function()
        GUIInterlude.backgroundColor[4] = GUIInterlude.backgroundColor[4] + GUIInterlude.backgroundAlphaAmountChange
        GUIInterlude.backgroundGray:SetBackgroundColor(GUIInterlude.backgroundColor)
    end, 50, 10, function()
        GUIInterlude:showEffect()
    end)
end

function UIInterlude:showEffect()
    LuaTimer:scheduleTimer(function()
        GUIInterlude.backgroundColor[4] = GUIInterlude.backgroundColor[4] + GUIInterlude.backgroundAlphaAmountChange
        GUIInterlude.backgroundGray:SetBackgroundColor(GUIInterlude.backgroundColor)
    end, 50, 10)
    if self.data:getNumberParam("round") == self.data:getNumberParam("allRound") and tonumber(GUIMain.stHomeHpNum:GetText()) > 0 then
        if Game:isChina() then
            self.mainWinEffect:SetEffectName("g1056_win_china.effect")
        else
            self.mainWinEffect:SetEffectName("g1056_win.effect")
        end
        self.mainWinEffect:SetVisible(true)
    else
        if Game:isChina() then
            self.mainFailEffect:SetEffectName("g1056_defeat_china.effect")
        else
            self.mainFailEffect:SetEffectName("g1056_defeat.effect")
        end
        self.mainFailEffect:SetVisible(true)
    end

    LuaTimer:scheduleTimer(function()
        self.continueBtn:SetTouchable(true)
    end, 2500, 1)

    LuaTimer:cancel(self.NotClickTimerKey or 0)
    self.NotClickTimerKey = LuaTimer:scheduleTimer(function()
        GUIInterlude:onClickScreen()
    end, 12000, 1)
end

return UIInterlude