---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by JY-032.
--- DateTime: 2019/12/16 15:08
---

require "packet.GamePacketSender"

local GUIBuyJobTip = class("", IGUILayout)

function GUIBuyJobTip:onLoad()
    self.startGameTime = 0
    self.gameTime = 5000
    self.startGameErrorTime = 0
    self.gameErrorTime = 1000

    self.tipKey = ""
    self.btnCancel = self:getChildWindow("LuckyBlockBuyJobTip-Cancel-Button", GUIType.Button)
    self.btnCancel:registerEvent(GUIEvent.ButtonClick, function()
        SoundUtil.clickUI()
        self:onClickCancelButton()
    end)

    self.btnConfirm = self:getChildWindow("LuckyBlockBuyJobTip-Confirm-Button", GUIType.Button)
    self.btnConfirm:registerEvent(GUIEvent.ButtonClick, function()
        SoundUtil.clickUI()
        self:onClickConfirmButton()
    end)

    self.tvTitle = self:getChildWindow("LuckyBlockBuyJobTip-Title", GUIType.StaticText)
    self.tvTip = self:getChildWindow("LuckyBlockBuyJobTip-Buy-Tip", GUIType.StaticText)
    self.tvPrice = self:getChildWindow("LuckyBlockBuyJobTip-Price-Text", GUIType.StaticText)
    self.ivPriceBg = self:getChildWindow("LuckyBlockBuyJobTip-Price-Bg", GUIType.StaticImage)

    self:registerDataCallBack("SendCustomTipData", function(data)
        self:onCustomTipData(data)
    end, JsonBuilderProcessor)
end

function GUIBuyJobTip:onCustomTipData(data)
    self.tipKey = data.key
    self:show()
end

function GUIBuyJobTip:onShow()
    if self.tipKey == tostring("StartGame") then
        self.tvTip:SetText(Lang:getString("lucky.sky.game.start"))
        self.btnCancel:SetText(Lang:getString("lucky.sky.game.cancel"))
        self.btnConfirm:SetText(Lang:getString("lucky.sky.game.confirm"))
        self.ivPriceBg:SetVisible(false)
        self.tvTitle:SetVisible(false)
        self.btnCancel:SetVisible(true)
        self.btnConfirm:SetVisible(true)
    end
end

function GUIBuyJobTip:onTick(nTimeElapse)
    self:updateCustomTip(nTimeElapse)
end

function GUIBuyJobTip:onClickConfirmButton()
    if self.tipKey == tostring("StartGame") then
        self.startGameTime = self.gameTime
        self.tvTip:SetText(Lang:getString("lucky.sky.game.start.time.tip"))
        self.ivPriceBg:SetVisible(false)
        self.btnCancel:SetVisible(false)
        self.btnConfirm:SetVisible(false)
        GamePacketSender:sendPlayerStartGameEvent()
    end
end

function GUIBuyJobTip:onClickCancelButton()
    if self.tipKey == tostring("StartGame") then
        self:hide()
    end
end

function GUIBuyJobTip:updateCustomTip(nTimeElapse)
    if self.startGameTime > 0 then
        self.startGameTime = self.startGameTime - nTimeElapse
        if self.startGameTime <= 0 then
            self.startGameTime = 0
            self.startGameErrorTime = self.gameErrorTime
            self.tvTip:SetText(Lang:getString("lucky.sky.game.start.error.time.tip"))
            self.btnCancel:SetVisible(true)
            self.btnConfirm:SetVisible(true)
        end
    end

    if self.startGameErrorTime > 0 then
        if self.startGameErrorTime <= 0 then
            self.startGameErrorTime = 0
            self.tvTip:SetText(Lang:getString("lucky.sky.game.start"))
            self.btnCancel:SetVisible(true)
            self.btnConfirm:SetVisible(true)
        end
    end
end

return GUIBuyJobTip