---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/12/21 16:42
---

local GUIRankRule = class("", IGUILayout)

function GUIRankRule:onLoad()
    --Button
    self:getChildWindow("LuckySkyHallRankRule-Close", GUIType.Button):registerEvent(GUIEvent.ButtonClick, function()
        self:hide()
    end)

    self:getChildWindow("LuckySkyHallRankRule-Title", GUIType.StaticText):SetText(Lang:getString("lucky.sky.rank.rule.title.text"))
    self:getChildWindow("LuckySkyHallRankRule-Desc-Text", GUIType.StaticText):SetText(Lang:getString("lucky.sky.rank.rule.desc.text"))
    self:getChildWindow("LuckySkyHallRankRule-Tip-Text", GUIType.StaticText):SetText(Lang:getString("lucky.sky.rank.rule.tip.text"))

    self:initGradings()
end

function GUIRankRule:initGradings()
    local setting = SeasonConfig:getSeasonSetting()
    if not setting then
        self:hide()
        return
    end
    for _, grading in pairs(setting) do
        self:getChildWindow("LuckySkyHallRankRule-" .. Define.Gradings[grading.id] .. "-Icon", GUIType.StaticImage):SetImage(grading.icon)
        self:getChildWindow("LuckySkyHallRankRule-" .. Define.Gradings[grading.id], GUIType.StaticImage):SetImage(grading.flag)
        self:getChildWindow("LuckySkyHallRankRule-" .. Define.Gradings[grading.id] .. "-Name-Text", GUIType.StaticText):SetText(Lang:getString(grading.honorName))
        self:getChildWindow("LuckySkyHallRankRule-" .. Define.Gradings[grading.id] .. "-Text", GUIType.StaticText):SetText(grading.defaultScore)
    end
end

return GUIRankRule