---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jimmy.
--- DateTime: 2019/10/9 0009 14:19
---
GamePacketSender = {}

function GamePacketSender:sendPlaceTower(data)
    PacketSender:sendLuaCommonData("PlaceTower", data)
end

function GamePacketSender:sendLockTower(serverId, isLock)
    local params = {
        entityId = serverId,
        isLock = isLock,
    }
    local data = DataBuilder.new():fromTable(params):getData()
    PacketSender:sendLuaCommonData("LockTower", data)
end

function GamePacketSender:sendSellTower(serverId)
    local data = DataBuilder.new():addParam("entityId", serverId):getData()
    PacketSender:sendLuaCommonData("SellTower", data)
end

function GamePacketSender:sendSupportTeammate(mateUserId, moneyNum)
    local params = {
        mateUserId = mateUserId,
        moneyNum = moneyNum,
    }
    local data = DataBuilder.new():fromTable(params):getData()
    PacketSender:sendLuaCommonData("SupportTeammate", data)
end

function GamePacketSender:sendRequestLogout()
    PacketSender:sendLuaCommonData("requestLogout")
end

function GamePacketSender:sendRequestPlayAgain()
    PacketSender:sendLuaCommonData("requestPlayAgain")
end

function GamePacketSender:sendOpenBookDetail(towerId)
    local data = DataBuilder.new():addParam("towerId", towerId):getData()
    PacketSender:sendLuaCommonData("OpenBookDetail", data)
end

function GamePacketSender:sendBuySkill(skillId)
    local data = DataBuilder.new():addParam("skillId", skillId):getData()
    PacketSender:sendLuaCommonData("OnBuyPaySkill", data)
end

function GamePacketSender:sendBuyShopItem(itemId)
    local params = {
        itemId = itemId,
    }
    local data = DataBuilder.new():fromTable(params):getData()
    PacketSender:sendLuaCommonData("BuyShopItem", data)
end

function GamePacketSender:sendExchangeHallGold(itemId, extraDiamondsNum)
    local params = {
        itemId = itemId,
        extraDiamondsNum = extraDiamondsNum,
    }
    local data = DataBuilder.new():fromTable(params):getData()
    PacketSender:sendLuaCommonData("ExchangeHallGold", data)
end

function GamePacketSender:sendBuyPayItem(itemId, num)
    local params = {
        itemId = itemId,
        num = num
    }
    local data = DataBuilder.new():fromTable(params):getData()
    PacketSender:sendLuaCommonData("BuyPayItem", data)
end

function GamePacketSender:sendSetShortCurBar(BarId, TowerId)
    local params = {
        BarId = BarId,
        TowerId = TowerId,
    }
    local data = DataBuilder.new():fromTable(params):getData()
    PacketSender:sendLuaCommonData("ShortCurBar", data)
end