
# 帧数默认选择{ 1, 2 ,3}
defaultFPS: 2

# 视角默认选择{ 1, 2 ,3}
defaultCamera: 1

# 亮度进度条 [0-1]
defaultLuminance: 1

# 按钮大小进度条 [0-1]
defaultButtonSize: 1

# 灵敏度进度条 [0-1]
defaultSensitivity: 0.5

# 视野距离进度条 [0-1]
defaultHorizon: 0.7

# 操作遥感选择{ 1, 2 ,3} 3是灵活摇杆,2是旧摇杆
defaultOperation: 1

# 背景音乐开关{ 1, 2} 2是关 1是开
defaultBackGroundSwitch: 1

# 背景音乐大小进度条 [0-1]
defaultBackGroundVolume: 1

# 音效开关{ 1, 2} 2是关 1是开
defaultEffectSwitch: 1

# 音效大小进度条 [0-1]
defaultEffectVolume: 1