---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by bell.
--- DateTime: 2020/2/10 15:27
---
GUISubAnim = class("GUISubAnim")

function GUISubAnim:ctor(window, child)
    self.window = window
    self.config = child
    self.isEnd = false

    if self.config.time then
        self.ticks = math.ceil(tonumber(self.config.time) / GUIAnimManager:getUpdateTime())
    end

    --LogUtil.log(string.format("GUISubAnim:ctor %s", tostring(self.ticks)))
end

function GUISubAnim:play()
    --TODO
end

function GUISubAnim:update()
    --TODO
end

function GUISubAnim:stop()
    --TODO
end

function GUISubAnim:onEnd()
    --TODO
end

return GUISubAnim