---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jimmy.
--- DateTime: 2019/10/9 0009 9:50
---
local UIMain = require "ui.layout.GUIMain"
GUIMain = UIMain.new("ThrowPotMain.json", GUIManager:getMainControl())
GUIMain:show()
