---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 10184.
--- DateTime: 2020/6/3 20:29
---
require "common.ui.window.GUICustomShopSubTab"

local BigTabColor = { Normal = { 0.596, 0.439, 0.309, 1 }, Select = { 0.964, 0.894, 0.403, 1 } }
local SmallTabColor = { Normal = { 0.361, 0.361, 0.361, 1 }, Select = { 0.964, 0.894, 0.403, 1 } }

GUIBlockShopTab = class("GUIBlockShopTab", IGUIWindow)

function GUIBlockShopTab:onLoad()
    self.cbTab = self:getChildWindowByName("BedWarBlockShopTab", GUIType.CheckBox)

    self.tvNormal = self:getChildWindowByName("BedWarBlockShopTab-Normal-Icon", GUIType.StaticImage)
    self.tvSelect = self:getChildWindowByName("BedWarBlockShopTab-Select-Icon", GUIType.StaticImage)
    --self.tvName = self:getChildWindowByName("BedWarCustomShopTab-Name", GUIType.StaticText)
    --self.llTabs = self:getChildWindowByName("BedWarCustomShopTab-SubTabs", GUIType.Layout)
    --self.tabs = {}
    --self.cbTab:registerEvent(GUIEvent.CheckStateChanged, function()
    --    if self.cbTab:GetChecked() then
    --        self.cbTab:SetTouchable(#self.tabs > 0)
    --        self.llTabs:SetVisible(true)
    --        if #self.tabs > 0 then
    --            self.root:SetArea({ 0, 0 }, self.root:GetYPosition(), { 1, 0 }, { 0, self.contentHeight + self.closeHeight })
    --            self.tabs[1]:setChecked(true)
    --        end
    --        GUICustomShop:onSelectTab(self)
    --        self.tvName:SetTextColor(BigTabColor.Select)
    --    else
    --        self.llTabs:SetVisible(false)
    --        if #self.tabs > 0 then
    --            self.root:SetArea({ 0, 0 }, self.root:GetYPosition(), { 1, 0 }, { 0, self.closeHeight })
    --        end
    --        self.tvName:SetTextColor(BigTabColor.Normal)
    --    end
    --    self.tvName:SetBordered(self.cbTab:GetChecked())
    --    GUICustomShop:updateTabsLayout(self)
    --end)
    --
    --self.cbTab:registerEvent(GUIEvent.Click, function()
    --    SoundUtil.playSound(SoundConfig.selectTabStore)
    --end)
end

function GUIBlockShopTab:onDataChanged(tab)
    self.tvNormal:SetImage(tab.Image)
    self.tvSelect:SetImage(tab.Image)
end

function GUIBlockShopTab:setChecked(check)
    self.tvNormal:SetVisible(not check)
    self.tvSelect:SetVisible(check)
end

function GUIBlockShopTab:onSelectSubTab(tab)
    for _, _tab in pairs(self.tabs) do
        _tab:setChecked(_tab.tabId == tab.tabId)
    end
    GUICustomShop:onSelectSubTab(tab)
end