/********************************************************************
filename: 	BM_TypeDef.h
file path:	dev\client\Src\Blockman

version:	1
author:		ajohn
company:	supernano
date:		2016-11-3
*********************************************************************/
#ifndef __BM_TYPE_DEFINATION_HEADER__
#define __BM_TYPE_DEFINATION_HEADER__

#include "Core.h"
using namespace LORD;

namespace BLOCKMAN
{

//#define SHOW_RASTERIZER_RENDER
//#define SHOW_RASTERIZER_MAP

typedef Vector3i BlockPos;

enum GAME_TYPE
{
	GAME_TYPE_INVALID = -1,

	GAME_TYPE_SURVIVAL,
	GAME_TYPE_CREATIVE,
	GAME_TYPE_ADVENTURE,

	GAME_TYPE_COUNT
};

enum TERRAIN_TYPE
{
	TERRAIN_TYPE_INVALID = -1,

	TERRAIN_TYPE_DEFAULT,
	TERRAIN_TYPE_FLAT,
	TERRAIN_TYPE_LARGE_BIOMES,
	TERRAIN_TYPE_DEFAULT_1_1,

	TERRAIN_TYPE_COUNT
};

enum ENTITY_SIZE
{
	ENTITY_SIZE_INVALID = -1,
	
	ENTITY_SIZE_1,
	ENTITY_SIZE_2,
	ENTITY_SIZE_3,
	ENTITY_SIZE_4,
	ENTITY_SIZE_5,
	ENTITY_SIZE_6,

	ENTITY_SIZE_COUNT,
};

enum ENTITY_STATUS
{
	ENTITY_STATUS_INVALID = -1,

	ENTITY_STATUS_BURNING,
	ENTITY_STATUS_SNEAKING,
	ENTITY_STATUS_RIDING,
	ENTITY_STATUS_SOMETHING,
	ENTITY_STATUS_SPRINTING,
	ENTITY_STATUS_EATING,

	ENTITY_STATUS_COUNT,
};

enum RAYTRACE_TYPE
{
	RAYTRACE_TYPE_INVALID = -1,

	RAYTRACE_TYPE_MISS,
	RAYTRACE_TYPE_BLOCK,
	RAYTRACE_TYPE_ENTITY,

	RAYTRACE_TYPE_COUNT,
};

enum ENCHANTMENT_TYPE
{
	ENCHANTMENT_TYPE_INVALID = -1,
	
	ENCHANTMENT_TYPE_ALL,
	ENCHANTMENT_TYPE_ARMOR,
	ENCHANTMENT_TYPE_ARMOR_FEET,
	ENCHANTMENT_TYPE_ARMOR_LEGS,
	ENCHANTMENT_TYPE_ARMOR_TORSO,
	ENCHANTMENT_TYPE_ARMOR_HEAD,
	ENCHANTMENT_TYPE_WEAPON,
	ENCHANTMENT_TYPE_DIGGER,
	ENCHANTMENT_TYPE_BOW,

	ENCHANTMENT_TYPE_COUNT,
};

enum CREATURE_ATTRIBUTE
{
	CREATURE_ATTRIBUTE_INVALID = -1,

	CREATURE_ATTRIBUTE_UNDEFINED,
	CREATURE_ATTRIBUTE_UNDEAD,
	CREATURE_ATTRIBUTE_ARTHROPOD,
	CREATURE_ATTRIBUTE_VILLAGER,

	CREATURE_ATTRIBUTE_COUNT,
};

enum ACTION_TYPE
{
	ACTION_TYPE_INVALID = -1,

	ACTION_TYPE_NONE,
	ACTION_TYPE_EAT,
	ACTION_TYPE_DRINK,
	ACTION_TYPE_BLOCK,
	ACTION_TYPE_BOW,
	ACTION_TYPE_FIRE,
	ACTION_TYPE_RELOAD,			 // reload bullet
	ACTION_TYPE_USE_COMMON_ITEM, // use common item

	ACTION_TYPE_COUNT,
};

enum RARITY_TYPE
{
	RARITY_TYPE_INVALID = -1,

	RARITY_TYPE_COMMON,
	RARITY_TYPE_UNCOMMON,
	RARITY_TYPE_RARE,
	RARITY_TYPE_EPIC,

	RARITY_TYPE_COUNT,
};

enum TILE_ENTITY
{
	TILE_ENTITY_INVALID = -1,

	TILE_ENTITY_BASE,
	TILE_ENTITY_FURNACE,
	TILE_ENTITY_CHEST,
	TILE_ENTITY_ENDERCHEST,
	TILE_ENTITY_RECORDPLAYER,
	TILE_ENTITY_TRAP,
	TILE_ENTITY_DROPPER,
	TILE_ENTITY_SIGN,
	TILE_ENTITY_MOBSWPAWER,
	TILE_ENTITY_MUSIC,
	TILE_ENTITY_PISTON,
	TILE_ENTITY_CAULDRON,
	TILE_ENTITY_ENCHANTTABLE,
	TILE_ENTITY_AIRPORTAL,
	TILE_ENTITY_CONTROL,
	TILE_ENTITY_BEACON,
	TILE_ENTITY_SKULL,
	TILE_ENTITY_DLDETECTOR,
	TILE_ENTITY_HOPPER,
	TILE_ENTITY_COMPARATOR,

	TILE_ENTITY_COUNT,
};

enum SLEEP_RESULT
{
	SLEEP_RESULT_INVALID = -1,
	SLEEP_RESULT_OK,
	SLEEP_RESULT_NOT_POSSIBLE_HERE,
	SLEEP_RESULT_NOT_POSSIBLE_NOW,
	SLEEP_RESULT_TOO_FAR_AWAY,
	SLEEP_RESULT_OTHER_PROBLEM,
	SLEEP_RESULT_NOT_SAFE,
	SLEEP_RESULT_COUNT,
};

enum ENTITY_CLASS_ID
{
	ENTITY_CLASS_INVALID = -1,

	ENTITY_CLASS_ENTITY,
	ENTITY_CLASS_LIVING_BASE,
	ENTITY_CLASS_LIVING,
	ENTITY_CLASS_CREATURE,
	ENTITY_CLASS_PLAYER,
	ENTITY_CLASS_PLAYER_OTHERMP,
	ENTITY_CLASS_PLAYERMP,
	ENTITY_CLASS_PLAYER_SP,
	ENTITY_CLASS_PLAYER_SPMP,
	ENTITY_CLASS_ARROW,
	ENTITY_CLASS_BULLET,
	ENTITY_CLASS_XPORB,
	ENTITY_CLASS_MOB,
	ENTITY_CLASS_ITEM,
	ENTITY_CLASS_ZOMBIE,
	ENTITY_CLASS_HANGING,
	ENTITY_CLASS_BOAT,
	ENTITY_CLASS_SQUID,
	ENTITY_CLASS_WITHER,
	ENTITY_CLASS_BAT,
	ENTITY_CLASS_BLOCKMAN,
	ENTITY_CLASS_PID,
	ENTITY_CLASS_ITEM_FRAME,
	ENTITY_CLASS_ANIMALS,
	ENTITY_CLASS_DRAGON,
	ENTITY_CLASS_FISHHOOK,
	ENTITY_CLASS_FISHHOOK_CLIENT,
	ENTITY_CLASS_POTION,
	ENTITY_CLASS_EXP_BOTTLE,
	ENTITY_CLASS_ENDER_PEARL,
	ENTITY_CLASS_ENDER_EYE,
	ENTITY_CLASS_FIREWORK_ROCKET,
	ENTITY_CLASS_SMALL_FIRE_BALL,
	ENTITY_CLASS_FIRE_BALL,
	ENTITY_CLASS_EGG,
	ENTITY_CLASS_TNT_PRIMED,
	ENTITY_CLASS_TNT_THROWABLE,
	ENTITY_CLASS_ENDER_CRYSTAL,
	ENTITY_CLASS_FALLING_SAND,
	ENTITY_CLASS_PAINTING,
	ENTITY_CLASS_LEASH_KNOT,
	ENTITY_CLASS_CONTAINER,
	ENTITY_CLASS_SNOWBALL,
	ENTITY_CLASS_THROWABLE,
	ENTITY_CLASS_MERCHANT,
	ENTITY_CLASS_GRENADE,
	ENTITY_CLASS_VEHICLE,
	ENTITY_CLASS_VEHICLE_CLIENT,
	ENTITY_CLASS_RANK_NPC,
	ENTITY_CLASS_AIRCRAFT,
	ENTITY_CLASS_ACTOR_NPC,
	ENTITY_CLASS_SESSION_NPC,
	ENTITY_CLASS_CREATUREAI,
	ENTITY_CLASS_CREATURE_BULLET,
	ENTITY_CLASS_ITEM_SKILL,
	ENTITY_CLASS_BLOCKMAN_EMPTY,
	ENTITY_CLASS_ACTOR_CANNON,
	ENTITY_CLASS_ACTOR_CANNON_CLIENT,
	ENTITY_CLASS_BUILD_NPC,
	ENTITY_CLASS_LAND_NPC,
	ENTITY_CLASS_GUN_FLAME,
	ENTITY_CLASS_BULLETIN,
	ENTITY_CLASS_BIRD,
	ENTITY_CLASS_BIRDAI,
	ENTITY_CLASS_DECORATION,
	ENTITY_CLASS_ROBOT,
	ENTITY_CLASS_FLYING_MOUNT,
	ENTITY_CLASS_FLOATING_MOUNT,
	ENTITY_CLASS_BULLET_CLIENT,
	ENTITY_CLASS_WALKING_DEAD_AI,
	ENTITY_CLASS_PLAYER_AI,
};

enum MOB_TYPE
{
	MOB_TYPE_EVERYTHING = 0,
	MOB_TYPE_MOBS,
	MOB_TYPE_PLAYERS,
	MOB_TYPE_ITEM,
};

enum ENTITY_TRACE_TYPE
{
	NONE_TRACE_TYPE = 0,
	BLOCK_TRACE_TYPE,
	ENTITY_PLAYER_TRACE_TYPE,
	ENTITY_VEHICLE_TRACE_TYPE,
	ENTITY_CREATUREAI_TRACE_TYPE,
	ENTITY_ACTOR_NPC_TRACE_TYPE,
	ENTITY_FLYING_MOUNT_TRACE_TYPE,
	ENTITY_FLOATING_MOUNT_TRACE_TYPE
};

enum ENTITY_CREATE_TYPE
{
	ENTITY_CREATE_TYPE_INVALID = 0,
	ENTITY_CREATE_TYPE_BOAT,
	ENTITY_CREATE_TYPE_ITEM,
	ENTITY_CREATE_TYPE_ARROE,
	ENTITY_CREATE_TYPE_BULLET,
	ENTITY_CREATE_TYPE_VEHICLE,
	ENTITY_CREATE_TYPE_POTION,
	ENTITY_CREATE_TYPE_TNT_PRIMED,
	ENTITY_CREATE_TYPE_SNOWBALL,
	ENTITY_CREATE_TYPE_GRENADE,
	ENTITY_CREATE_TYPE_TNT_THROWABLE,
	ENTITY_CREATE_TYPE_MERCHANT,
	ENTITY_CREATE_TYPE_RANK_NPC,
	ENTITY_CREATE_TYPE_AIRCRAFT,
	ENTITY_CREATE_TYPE_ACTOR_NPC,
	ENTITY_CREATE_TYPE_SESSION_NPC,
	ENTITY_CREATE_TYPE_CREATURE,
	ENTITY_CREATE_TYPE_FIREBALL,
	ENTITY_CREATE_TYPE_FISHHOOK,
	ENTITY_CREATE_TYPE_BLOCKMAN,
	ENTITY_CREATE_TYPE_BLOCKMAN_EMPTY,
	ENTITY_CREATE_TYPE_BUILD_NPC,
	ENTITY_CREATE_TYPE_LAND_NPC,
	ENTITY_CREATE_TYPE_GUN_FLAME,
	ENTITY_CREATE_TYPE_BULLETIN,
	ENTITY_CREATE_TYPE_BIRD,
	ENTITY_CREATE_TYPE_DECORATION,
};

enum PLAYER_ATTACK_CREATURE_TYPE
{
	PLAYER_ATTACK_CREATURE_NONE = 0,
	PLAYER_ATTACK_CREATURE_GUN,
	PLAYER_ATTACK_CREATURE_DAMAGE
};

enum GRME_ROUND_STATUS 
{
	GRME_ROUND_STATUS_WAIT,
	GRME_ROUND_STATUS_START
};

enum PLAYER_ATTACK_TYPE
{
	PLAYER_ATTACK_NONE = 0,
	PLAYER_ATTACK_GUN,
	PLAYER_ATTACK_DAMAGE
};

enum CROSS_HAIR_TYPE
{
	NONE_TYPE = 0,
	COMMON_CROSS_HAIR,
	RIFLE_CROSS_HAIR,
	SHOTGUN_CROSS_HAIR,
	MACHINE_CROSS_HAIR,
};

enum GUN_TYPE
{
	GUN_TYPE_INVALID,
	PISTOL_GUN = 1,
	RIFLE_GUN,
	SNIPER_GUN,
	SHOTGUN_GUN,
	SUBMACHINE_GUN,
	RIFLE_EFFECT_GUN,
	SNIPER_EFFECT_GUN,
	SHOTGUN_EFFECT_GUN,
	MORTAR_EFFECT_GUN,
	LASER_EFFECT_GUN,
	ELECTRICITY_EFFECT_GUN,
	MOMENTARY_LASER_EFFECT_GUN,
	MOMENTARY_PIERCING_LASER_EFFECT_GUN,
	GUN_TYPE_ALL,
};

//1:Basement 2:Monster 3:Boss 4:Tower
enum CRETURE_AI_TYPE
{
	CRETURE_AI_TYPE_NONE = 0,
	CRETURE_AI_TYPE_BASE,
	CRETURE_AI_TYPE_MONSTER,
	CRETURE_AI_TYPE_MONSTER_BOSS,
	CRETURE_AI_TYPE_TOWER,
	CRETURE_AI_TYPE_G1049,
};

enum CRETURE_AI_ATTACK_TYPE
{
	CRETURE_AI_ATTACK_TYPE_MELEE = 0,
	CRETURE_AI_ATTACK_TYPE_REMOTE,
	CRETURE_AI_ATTACK_TYPE_GROUP,
	CRETURE_AI_ATTACK_TYPE_TOWER,
};

enum USE_ITEM_STATUS 
{
	NOT_CAN_USE_ITEM = 0,
	CAN_USE_ITEM,
};

const ui32 ENCHANTMENT_CLASS_PROTECTION		= 0x00000001;
const ui32 ENCHANTMENT_CLASS_OXYGEN			= 0x00000002;
const ui32 ENCHANTMENT_CLASS_WATERWORKER	= 0x00000004;
const ui32 ENCHANTMENT_CLASS_THORNS			= 0x00000008;
const ui32 ENCHANTMENT_CLASS_DAMAGE			= 0x00000010;
const ui32 ENCHANTMENT_CLASS_KNOCKBACK		= 0x00000020;
const ui32 ENCHANTMENT_CLASS_FIREASPECT		= 0x00000040;
const ui32 ENCHANTMENT_CLASS_LOOTBONUS		= 0x00000080;
const ui32 ENCHANTMENT_CLASS_DIGGING		= 0x00000100;
const ui32 ENCHANTMENT_CLASS_UNTOUCHING		= 0x00000200;
const ui32 ENCHANTMENT_CLASS_DURABILITY		= 0x00000400;
const ui32 ENCHANTMENT_CLASS_ARROWDAMAGE	= 0x00000800;
const ui32 ENCHANTMENT_CLASS_ARROWKBACK		= 0x00001000;
const ui32 ENCHANTMENT_CLASS_ARROWFIRE		= 0x00002000;
const ui32 ENCHANTMENT_CLASS_ARROWINFINITE	= 0x00004000;

const int MAX_WORLD_X = 30000000;
const int MAX_WORLD_Y = 256;
const int MAX_WORLD_Z = 30000000;

enum LIGHTCHANNEL
{
	LC_INVALID=-1,
	
	LC_BLOCK_R = 0,
	LC_BLOCK_G,
	LC_BLOCK_B,
	LC_SKY,

	LC_CNT
};


const int BLOCK_ID_STONE = 1;
const int BLOCK_ID_GRASS = 2;
const int BLOCK_ID_DIRT = 3;
const int BLOCK_ID_COBBLE_STONE = 4;
const int BLOCK_ID_PLANKS = 5;
const int BLOCK_ID_SAPLING = 6;
const int BLOCK_ID_BEDROCK = 7;
const int BLOCK_ID_WATERMOVING = 8;
const int BLOCK_ID_WATERSTILL = 9;
const int BLOCK_ID_LAVAMOVING = 10;
const int BLOCK_ID_LAVASTILL = 11;
const int BLOCK_ID_SAND = 12;
const int BLOCK_ID_GRAVEL = 13;
const int BLOCK_ID_ORE_GOLD = 14;
const int BLOCK_ID_ORE_IRON = 15;
const int BLOCK_ID_ORE_COAL = 16;
const int BLOCK_ID_WOOD = 17;
const int BLOCK_ID_LEAVES = 18;
const int BLOCK_ID_SPONGE = 19;
const int BLOCK_ID_GLASS = 20;
const int BLOCK_ID_ORE_LAPIS = 21;
const int BLOCK_ID_BLOCK_LAPIS = 22;
const int BLOCK_ID_DISPENSER = 23;
const int BLOCK_ID_SAND_STONE = 24;
const int BLOCK_ID_MUSIC = 25;
const int BLOCK_ID_BED = 26;
const int BLOCK_ID_RAIL_POWERED = 27;
const int BLOCK_ID_RAIL_DETECTOR = 28;
const int BLOCK_ID_PISTON_STICKY_BASE = 29;
const int BLOCK_ID_WEB = 30;
const int BLOCK_ID_TALL_GRASS = 31;
const int BLOCK_ID_DEADBUSH = 32;
const int BLOCK_ID_PISTON_BASE = 33;
const int BLOCK_ID_PISTON_EXTENSION = 34;
const int BLOCK_ID_CLOTH = 35;
const int BLOCK_ID_PISTON_MOVING = 36;
const int BLOCK_ID_PLANT_YELLOW = 37;
const int BLOCK_ID_PLANT_RED = 38;
const int BLOCK_ID_MUSHROOM_BROWN = 39;
const int BLOCK_ID_MUSHROOM_RED = 40;
const int BLOCK_ID_BLOCK_GOLD = 41;
const int BLOCK_ID_BLOCK_IRON = 42;
const int BLOCK_ID_STONE_DOUBLE_SLAB = 43;
const int BLOCK_ID_STONE_SINGLE_SLAB = 44;
const int BLOCK_ID_BRICK = 45;
const int BLOCK_ID_TNT = 46;
const int BLOCK_ID_BOOKSHELF = 47;
const int BLOCK_ID_COBBLE_STONE_MOSSY = 48;
const int BLOCK_ID_OBSIDIAN = 49;
const int BLOCK_ID_TORCH_WOOD = 50;
const int BLOCK_ID_FIRE = 51;
const int BLOCK_ID_MOB_SPAWNER = 52;
const int BLOCK_ID_STAIRS_WOOD_OAK = 53;
const int BLOCK_ID_CHEST = 54;
const int BLOCK_ID_REDSTONE_WIRE = 55;
const int BLOCK_ID_ORE_DIAMOND = 56;
const int BLOCK_ID_BLOCK_DIAMOND = 57;
const int BLOCK_ID_WORK_BENCH = 58;
const int BLOCK_ID_CROPS = 59;
const int BLOCK_ID_TILLED_FIELD = 60;
const int BLOCK_ID_FURNACE_IDLE = 61;
const int BLOCK_ID_FURNACE_BURNING = 62;
const int BLOCK_ID_SIGN_POST = 63;
const int BLOCK_ID_DOOR_WOOD = 64;
const int BLOCK_ID_LADDER = 65;
const int BLOCK_ID_RAIL = 66;
const int BLOCK_ID_STAIRS_COBBLE_STONE = 67;
const int BLOCK_ID_SIGN_WALL = 68;
const int BLOCK_ID_LEVER = 69;
const int BLOCK_ID_PRESSURE_PLATE_STONE = 70;
const int BLOCK_ID_DOOR_IRON = 71;
const int BLOCK_ID_PRESSURE_PLATE_PLANKS = 72;
const int BLOCK_ID_ORE_REDSTONE = 73;
const int BLOCK_ID_ORE_REDSTONE_GLOWING = 74;
const int BLOCK_ID_TORCH_REDSTONE_IDLE = 75;
const int BLOCK_ID_TORCH_REDSTONE_ACTIVE = 76;
const int BLOCK_ID_STONE_BUTTON = 77;
const int BLOCK_ID_SNOW = 78;
const int BLOCK_ID_ICE = 79;
const int BLOCK_ID_BLOCK_SNOW = 80;
const int BLOCK_ID_CACTUS = 81;
const int BLOCK_ID_BLOCKCLAY = 82;
const int BLOCK_ID_REED = 83;
const int BLOCK_ID_JUKE_BOX = 84;
const int BLOCK_ID_FENCE = 85;
const int BLOCK_ID_PUMPKIN = 86;
const int BLOCK_ID_NETHERRACK = 87;
const int BLOCK_ID_SLOW_SAND = 88;
const int BLOCK_ID_GLOW_STONE = 89;
const int BLOCK_ID_PORTAL = 90;
const int BLOCK_ID_PUMPKIN_LANTERN = 91;
const int BLOCK_ID_CAKE = 92;
const int BLOCK_ID_REDSTONE_REPEATER_IDLE = 93;
const int BLOCK_ID_REDSTONE_REPEATER_ACTIVE = 94;
//const int BLOCK_ID_LOCKED_CHEST = 95;
const int BLOCK_ID_STAINED_GLASS = 95;
const int BLOCK_ID_TRAP_DOOR = 96;
const int BLOCK_ID_SILVER_FISH = 97;
const int BLOCK_ID_STONE_BRICK = 98;
const int BLOCK_ID_MUSHROOMCAP_BROWN = 99;
const int BLOCK_ID_MUSHROOMCAP_RED = 100;
const int BLOCK_ID_FENCE_IRON = 101;
const int BLOCK_ID_THIN_GLASS = 102;
const int BLOCK_ID_MELON = 103;
const int BLOCK_ID_PUMPKIN_STEM = 104;
const int BLOCK_ID_MELON_STEM = 105;
const int BLOCK_ID_VINE = 106;
const int BLOCK_ID_FENCE_GATE = 107;
const int BLOCK_ID_STAIRS_BRICK = 108;
const int BLOCK_ID_STAIRS_STONE_BRICK = 109;
const int BLOCK_ID_MYCELIUM = 110;
const int BLOCK_ID_WATERLILY = 111;
const int BLOCK_ID_NETHER_BRICK = 112;
const int BLOCK_ID_NETHER_FENCE = 113;
const int BLOCK_ID_STAIRS_NETHER_BRICK = 114;
const int BLOCK_ID_NETHER_STALK = 115;
const int BLOCK_ID_ENCHANTMENT_TABLE = 116;
const int BLOCK_ID_BREWING_STAND = 117;
const int BLOCK_ID_CAULDRON = 118;
const int BLOCK_ID_END_PORTAL = 119;
const int BLOCK_ID_END_PROTAL_FRAME = 120;
const int BLOCK_ID_WHITE_STONE = 121;
const int BLOCK_ID_DRAGON_EGG = 122;
const int BLOCK_ID_REDSTONE_LAMP_IDLE = 123;
const int BLOCK_ID_REDSTONE_LAMP_ACTIVE = 124;
const int BLOCK_ID_WOOD_DOUBLE_SLAB = 125;
const int BLOCK_ID_WOOD_SINGLE_SLAB = 126;
const int BLOCK_ID_COCOAPLANT = 127;
const int BLOCK_ID_STAIRS_SAND_STONE = 128;
const int BLOCK_ID_ORE_EMERALD = 129;
const int BLOCK_ID_ENDER_CHEST = 130;
const int BLOCK_ID_TRIP_WIRE_SOURCE = 131;
const int BLOCK_ID_TRIP_WIRE = 132;
const int BLOCK_ID_BLOCK_EMERALD = 133;
const int BLOCK_ID_STAIRS_WOOD_SPURCE = 134;
const int BLOCK_ID_STAIRS_WOOD_BIRCH = 135;
const int BLOCK_ID_STAIRS_WOOD_JUNGLE = 136;
const int BLOCK_ID_BEACON = 138;
const int BLOCK_ID_COBBLE_STONE_WALL = 139;
const int BLOCK_ID_FLOWER_POT = 140;
const int BLOCK_ID_CARROT = 141;
const int BLOCK_ID_POTATO = 142;
const int BLOCK_ID_WOODEN_BUTTON = 143;
const int BLOCK_ID_SKULL = 144;
const int BLOCK_ID_ANVIL = 145;
const int BLOCK_ID_CHEST_TRAPPED = 146;
const int BLOCK_ID_PRESSURE_PLATE_GOLD = 147;
const int BLOCK_ID_PRESSURE_PLATE_IRON = 148;
const int BLOCK_ID_REDSTONE_COMPARATOR_IDLE = 149;
const int BLOCK_ID_REDSTONE_COMPARATOR_ACTIVE = 150;
const int BLOCK_ID_DAYLIGHT_DETECTOR = 151;
const int BLOCK_ID_BLOCK_REDSTONE = 152;
const int BLOCK_ID_ORE_NETHER_QUARTZ = 153;
const int BLOCK_ID_HOPPER = 154;
const int BLOCK_ID_BLOCK_NETHER_QUARTZ = 155;
const int BLOCK_ID_STAIRS_NETHER_QUARTZ = 156;
const int BLOCK_ID_RAIL_ACTIVATOR = 157;
const int BLOCK_ID_DROPPER = 158;
const int BLOCK_ID_CLAY_HARDENED_STAINED = 159;
const int BLOCK_ID_STAINED_GLASS_PANE = 160;
const int BLOCK_ID_WOOD2 = 162;
const int BLOCK_ID_STAIRS_WOOD_DARK_OAK = 164;
const int BLOCK_ID_SEA_LANTERN = 168;
const int BLOCK_ID_CLAY_BLOCK = 170;
const int BLOCK_ID_WOOL_CARPET = 171;
const int BLOCK_ID_CLAY_HARDENED = 172;
const int BLOCK_ID_BLOCK_COAL = 173;
const int BLOCK_ID_BLOCK_PACKED_ICE = 174;
const int BLOCK_ID_RAIL_RECEIVE = 175;
const int BLOCK_ID_BANNER = 176;
const int BLOCK_ID_REDSAND_STONE_DOUBLESLAB = 181;
const int BLOCK_ID_REDSAND_STONE_SINGLESLAB = 182;
const int BLOCK_ID_BIRCH_FENCE_GATE = 184;
const int BLOCK_ID_BIRCH_FENCE = 189;
const int BLOCK_ID_MAGMA = 213;
const int BLOCK_ID_RED_NETHER_BRICK = 215;
const int BLOCK_ID_PRESSURE_PLATE_WEIGHT_WOOD = 217;
const int BLOCK_ID_CHEST_NEW = 219;
const int BLOCK_ID_ENDER_CHEST_NEW = 220;
const int BLOCK_ID_CHEST_TRAPPED_NEW = 221;
const int BLOCK_ID_DEFENCE_TOWER = 1417;
const int BLOCK_ID_DEFENCE_WALL = 1418;
const int BLOCK_ID_PRISMARINE = 1419;
const int BLOCK_ID_PRISMARINE_BRICK = 1420;
const int BLOCK_ID_DARK_PRISMARINE = 1421;
const int BLOCK_ID_STARRY_SKY = 1422;
const int BLOCK_ID_STAIRS_PRISMARINE = 1423;
const int BLOCK_ID_STAIRS_PRISMARINE_BRICK = 1424;
const int BLOCK_ID_STAIRS_DARK_PRISMARINE = 1425;
const int BLOCK_ID_STAIRS_RED_NETHER_BRICK = 1426;
const int BLOCK_ID_PRISMARINE_DOUBLE_SLAB = 1427;
const int BLOCK_ID_PRISMARINE_SINGLE_SLAB = 1428;
const int BLOCK_ID_LUCKY_BLOCK_RED = 1431;
const int BLOCK_ID_LUCKY_BLOCK_YELLOW = 1432;
const int BLOCK_ID_LUCKY_BLOCK_BLUE = 1433;
const int BLOCK_ID_LUCKY_BLOCK_GREEN = 1434;
const int BLOCK_ID_LUCKY_BLOCK_COLORFUL = 1435;
const int BLOCK_ID_LUCKY_BLOCK_HOLLOW = 1436;

const int ITEM_ID_TNT                   = 46;
const int ITEM_ID_PICK_AXE_IRON			= (256 + 1);
const int ITEM_ID_FLINT_AND_STEEL		= (256 + 3);
const int ITEM_ID_ARROW                 = (256 + 6);
const int ITEM_ID_COAL					= (256 + 7);

const int ITEM_ID_DIAMOND				= (256 + 8);
const int ITEM_ID_INGOT_IRON			= (256 + 9);
const int ITEM_ID_INGOT_GOLD			= (256 + 10);
const int ITEM_ID_REDSTONE				= (256 + 75);
const int ITEM_ID_DYE_POWER				= (256 + 95);
const int ITEM_ID_BREAD					= (256 + 41);
const int ITEM_ID_MELON_SEEDS			= (256 + 106);
const int ITEM_ID_PUMPKIN_SEEDS			= (256 + 105);
const int ITEM_ID_SADDLE				= (256 + 73);
const int ITEM_ID_HORSE_ARMOR_METAL		= (256 + 161);
const int ITEM_ID_HORSE_ARMOR_GOLD		= (256 + 162);
const int ITEM_ID_HORSE_ARMOR_DIAMOND	= (256 + 163);
const int ITEM_ID_SWORD_GOLD			= (256 + 27);
const int ITEM_ID_PLATE_GOLD			= (256 + 59);
const int ITEM_ID_NETHER_STALK_SEEDS	= (256 + 116);
const int ITEM_ID_SEED					= (256 + 39);
const int ITEM_ID_SNOW_BALL				= (256 + 76);
const int ITEM_ID_POTION				= (256 + 117);
const int ITEM_ID_WHEAT					= (256 + 40);
const int ITEM_ID_GUNPOWDER				= (256 + 33);
const int ITEM_ID_SILK					= (256 + 31);
const int ITEM_ID_BUCKETEMPTY			= (256 + 69);
const int ITEM_ID_APPLEGOLD				= (256 + 66);
const int ITEM_ID_RECORD13				= (256 + 230); // max item id
const int ITEM_ID_RECORDCAT				= (256 + 231);
const int ITEM_ID_FIELD_CI				= (256 + 165);
const int ITEM_ID_FIELD_CF				= (256 + 162);
const int ITEM_ID_FIELD_CE				= (256 + 161);
const int ITEM_ID_FIELD_CG				= (256 + 163);
const int ITEM_ID_BOOK					= (256 + 84);
const int ITEM_ID_CLAY					= (256 + 81);
const int ITEM_ID_FLOWERPOT				= (256 + 134);
const int ITEM_ID_REED					= (256 + 82);
const int ITEM_ID_DOOR_WOOD				= (256 + 68);
const int ITEM_ID_DOOR_IRON				= (256 + 74);
const int ITEM_ID_CAKE					= (256 + 98);
const int ITEM_ID_MELON					= (256 + 104);
const int ITEM_ID_EMERALA				= (256 + 132);
const int ITEM_ID_NETHER_QUARTZ			= (256 + 150);
const int ITEM_ID_CARROT				= (256 + 135);
const int ITEM_ID_POTATO				= (256 + 136);
const int ITEM_ID_BREWING_STAND			= (256 + 123);
const int ITEM_ID_CAULDRON				= (256 + 124);
const int ITEM_ID_GLOWSTONE				= (256 + 92);
const int ITEM_ID_GRENADE				= (256 + 169);
const int ITEM_ID_FIRE_BALL				= (256 + 129);
const int ITEM_ID_DOOR_BIRCH			= (256 + 254);
const int ITEM_ID_DEFENCE_TOWER = (1000 + BLOCK_ID_DEFENCE_TOWER);
const int ITEM_ID_DEFENCE_WALL = (1000 + BLOCK_ID_DEFENCE_WALL);

const int ITEM_ID_LUCKY_BLOCK_RED = (1000 + BLOCK_ID_LUCKY_BLOCK_RED);
const int ITEM_ID_LUCKY_BLOCK_YELLOW = (1000 + BLOCK_ID_LUCKY_BLOCK_YELLOW);
const int ITEM_ID_LUCKY_BLOCK_BLUE = (1000 + BLOCK_ID_LUCKY_BLOCK_BLUE);
const int ITEM_ID_LUCKY_BLOCK_GREEN = (1000 + BLOCK_ID_LUCKY_BLOCK_GREEN);
const int ITEM_ID_LUCKY_BLOCK_COLORFUL = (1000 + BLOCK_ID_LUCKY_BLOCK_COLORFUL);
const int ITEM_ID_LUCKY_BLOCK_HOLLOW = (1000 + BLOCK_ID_LUCKY_BLOCK_HOLLOW);

const i64 BLOCK_TYPE_BASE			= 0x0000000000000001LL;
const i64 BLOCK_TYPE_STAIRS			= 0x0000000000000002LL;
const i64 BLOCK_TYPE_HALFSLAB		= 0x0000000000000004LL;
const i64 BLOCK_TYPE_HOPPER			= 0x0000000000000008LL;
const i64 BLOCK_TYPE_SNOW			= 0x0000000000000010LL;
const i64 BLOCK_TYPE_DIRECTIONAL	= 0x0000000000000020LL;

enum BM_FACE
{
	BM_FACE_INVALID = -1,

	BM_FACE_DOWN,
	BM_FACE_UP,
	BM_FACE_NORTH,
	BM_FACE_SOUTH,
	BM_FACE_WEST,
	BM_FACE_EAST,

	BM_FACE_COUNT,
};

enum BM_ROTATE
{
	BM_ROTATE_INVALID = -1,

	BM_ROTATE_NONE,
	BM_ROTATE_90,
	BM_ROTATE_180,
	BM_ROTATE_270,

	BM_ROTATE_ALL,
};

enum BLOCKE_DESTROYE_FAILURE 
{
	INVALID = -1,
	TIME_SHORT,
	NOT_BREAKING,
};

const int oppositeSide[6] = { 1, 0, 3, 2, 5, 4 };
const int offsetXForSide[6] = { 0, 0, 0, 0, -1, 1 };
const int offsetYForSide[6] = { -1, 1, 0, 0, 0, 0 };
const int offsetZForSide[6] = { 0, 0, -1, 1, 0, 0 };
const Vector3i offsetForSide[6] = { Vector3i(0, -1, 0), Vector3i(0, 1, 0), Vector3i(0, 0, -1), Vector3i(0, 0, 1), Vector3i(-1, 0, 0), Vector3i(1, 0, 0) };
const String facing[6] = { "DOWN", "UP", "NORTH", "SOUTH", "WEST", "EAST" };

const int dir_offsetX[4] = {0, -1, 0, 1};
const int dir_offsetZ[4] = {1, 0, -1, 0};
const Vector3i dir_offset[4] = { Vector3i(0, 0, 1), Vector3i(-1, 0, 0), Vector3i(0, 0, -1), Vector3i(1, 0, 0) };
const int dir_directionToFacing[4] = {3, 4, 2, 5};
const int dir_facingToDirection[6] = { -1, -1, 2, 0, 1, 3};
const int dir_rotateOpposite[4] = {2, 3, 0, 1};
const int dir_rotateRight[4] = {1, 2, 3, 0};
const int dir_rotateLeft[4] = {3, 0, 1, 2};
const int bedDirection[4][6] = { { 1, 0, 3, 2, 5, 4 },{ 1, 0, 5, 4, 2, 3 },{ 1, 0, 2, 3, 4, 5 },{ 1, 0, 4, 5, 3, 2 } };
const String dir_directions[4] = { "SOUTH", "WEST", "NORTH", "EAST" };

const int COLOR_AIR =		0;
const int COLOR_GRASS =		0x007FB238;
const int COLOR_SAND =		0x00F7E9A3;
const int COLOR_CLOTH =		0x00A7A7A7;
const int COLOR_TNT =		0x00FF0000;
const int COLOR_ICE =		0x00A0A0FF;
const int COLOR_IRON =		0xA7A7A7;
const int CLOLOR_FOLIAGE =	0x00007C00;
const int COLOR_SNOW =		0x00FFFFFF;
const int COLOR_CLAY =		0x00A4A8B8;
const int COLOR_DIRT =		0x00B76A2F;
const int COLOR_STONE =		0x00707070;
const int COLOR_WATER =		0x004040FF;
const int COLOR_WOOD =		0x00685332;
const int COLOR_MAGMA =     0x00FF0000;

}

#endif
