---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 10184.
--- DateTime: 2020/11/16 21:10
---
require "base.ui.window.GUICommonActivityChestGroup"

GUICommonActivityPanel = class("GUICommonActivityPanel", IGUIWindow) ---@class GUICommonActivityPanel : IGUIWindow

local function saveSetUI(window, key, ...)
    if window and window[key] then
        window[key](window, ...)
    end
end

function GUICommonActivityPanel:onLoad(activity)
    local name = self.__name:gsub(".json", "-")
    self.tvTitle = self:getChildWindowByName(name .. "Title", GUIType.StaticText)
    self.tvTime = self:getChildWindowByName(name .. "Time", GUIType.StaticText)
    self.tvDesc = self:getChildWindowByName(name .. "Desc", GUIType.StaticText)
    self.awActor = self:getChildWindowByName(name .. "Actor", GUIType.ActorWindow)
    self.ivImage = self:getChildWindowByName(name .. "Image", GUIType.StaticImage)
    self.tvPrice = self:getChildWindowByName(name .. "Price", GUIType.StaticText)
    self.ivPriceIcon = self:getChildWindowByName(name .. "Price-Icon", GUIType.StaticImage)
    self.tvName = self:getChildWindowByName(name .. "Name", GUIType.StaticText)

    self.activity = activity
    self.root = DynamicCast.dynamicCastWindow(GUIType.Layout, self.root)
    self.root:SetVisible(false)
    self.root:SetBackImage(activity.background)
    saveSetUI(self.tvTitle, "SetText", Lang:getString(activity.titleLang))
    saveSetUI(self.tvDesc, "SetText", Lang:getString(activity.descLang))
    self.root:SetWidth({ 1, 0 })
    self.root:SetHeight({ 1, 0 })
    self:onChildLoad()
    self:showRewardDetail(activity)

    self:addTimer(LuaTimer:scheduleTimer(function()
        self:onSecondTick()
    end, 1000))

    if CommonActivityChestConfig:getChestGroupById(self.activity.chestGroupId) then
        self.wChestGroup = GUICommonActivityChestGroup.new(activity, self)
    end
end

function GUICommonActivityPanel:onSecondTick()
    if not self.activity.lastTime or self.activity.lastTime <= 0 then
        return
    end
    self.activity.lastTime = self.activity.lastTime - 1
    if self.activity.lastTime >= DateUtil.getDaySeconds() then
        local text = string.format(Lang:getString("common.activity.day"), tostring(math.floor(self.activity.lastTime / DateUtil.getDaySeconds())))
        saveSetUI(self.tvTime, "SetText", text)
    else
        saveSetUI(self.tvTime, "SetText", DateUtil.getFormatTime(self.activity.lastTime))
    end
end

function GUICommonActivityPanel:showRewardDetail(activity)
    local reward = CommonActivityRewardConfig:getRewardById(activity.mainRewardId)
    if not reward then
        return
    end
    saveSetUI(self.tvName, "SetText", Lang:getString(reward.name))
    if reward.priceIcon and #reward.priceIcon > 0 then
        if reward.price == -1 then
            saveSetUI(self.ivPriceIcon, "SetImage", "")
            saveSetUI(self.tvPrice, "SetText", "")
        else
            saveSetUI(self.ivPriceIcon, "SetImage", reward.priceIcon)
            saveSetUI(self.tvPrice, "SetText", tostring(reward.price))
            if self.tvPrice then
                local extent = self.tvPrice:GetFont():GetTextExtent(tostring(reward.price), 1)
                saveSetUI(self.ivPriceIcon, "SetXPosition", { 0, -extent / 2 - 5 })
            end
        end
    else
        saveSetUI(self.ivPriceIcon, "SetImage", "")
    end
    if activity.actor and #activity.actor > 7 then
        local pos
        if self.awActor and self.awActor["GetPosition"] then
            pos = self.awActor:GetPosition()
        end
        saveSetUI(self.awActor, "SetXPosition", { pos.x[1], activity.actorXOffset })
        saveSetUI(self.awActor, "SetYPosition", { pos.y[1], activity.actorYOffset })
        saveSetUI(self.awActor, "SetWidth", { 0, activity.actorScale })
        saveSetUI(self.awActor, "SetActor1", activity.actor, "idle")
    else
        saveSetUI(self.awActor, "RemoveActor")
        if reward.image and #reward.image > 10 then
            UIHelper:setImageAdjustSize(self.ivImage, reward.image, 250, 250)
        else
            saveSetUI(self.ivImage, "SetImage", "")
        end
    end
end

function GUICommonActivityPanel:onChildLoad()

end

function GUICommonActivityPanel:onShow()

end

function GUICommonActivityPanel:isShow()
    return self.root:IsVisible()
end

function GUICommonActivityPanel:onTick()
    if self.wChestGroup then
        self.wChestGroup:onTick()
    end
end

return GUICommonActivityPanel