---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 10184.
--- DateTime: 2020/7/23 15:25
---
GUIProbabilityItem = class("GUIProbabilityItem", IGUIWindow)

function GUIProbabilityItem:onLoad()
    self.tvName = self:getChildWindowByName("ProbabilityItem-Name", GUIType.StaticText)
    self.tvProbability = self:getChildWindowByName("ProbabilityItem-Probability", GUIType.StaticText)
end

function GUIProbabilityItem:onDataChanged(data)
    self.tvName:SetText(Lang:getString(data.Name))
    self.tvProbability:SetText(Lang:getString(data.ProbabilityLang))
end