---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jimmy.
--- DateTime: 2019/10/8 0008 16:31
---
SoundType = {
    Sure = 0, ---确定按钮
    Cancel = 1, ---取消按钮
    ErrorOperation = 2, ---错误操作
    InvalidOperation = 3, ---无效操作
    OpenPanel = 4, ---打开一级面板(例如商店)
    ClosePanel = 5, ---关闭一级面板
    OpenSubPanel = 6, ---打开二级面板(例如商品描述)
    CloseSubPanel = 7, ---关闭二级面板
    PopUpTips = 8, ---弹出提示框
    GetItem = 13, ---获得物品
    GetCoin = 14, ---获得金币
    GetDiamond = 15, ---获得钻石
    Click = 70 ---点击按钮
}

SoundUtil = {}

function SoundUtil.playSound(type)
    if not type or type < 0 then
        return
    end
    return SoundSystem.Instance():playEffectByType(type, VectorUtil.INVALID)
end

function SoundUtil.playSound3D(type, x, y, z)
    if not type or type < 0 then
        return
    end
    local position = VectorUtil.newVector3(x, y, z)
    SoundSystem.Instance():playEffectByType(type, position)
end

function SoundUtil.clickUI()
    SoundUtil.playSound(SoundType.Click)
end

function SoundUtil.stopSoundById(SoundId)
    SoundSystem.Instance():stopEffect(SoundId)
end