---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/6/10 22:44
---

GUIChatRecordItem = class("GUIChatRecordItem", IGUIWindow)

function GUIChatRecordItem:onLoad()
    self.stText = self:getChildWindow(0, GUIType.StaticText)
end

function GUIChatRecordItem:onGetChat(name, text)
    self.stText:SetText(string.format("<%s>▢FFCCCCCC %s", name, tostring(text)))
    return self.stText:GetTextStringHigh()
end

function GUIChatRecordItem:onGetSystemTip(text)
    self.stText:SetText(string.format("▢FFCCCCCC %s", tostring(text)))
    return self.stText:GetTextStringHigh()
end

function GUIChatRecordItem:getHeight()
    return self.stText:GetTextStringHigh()
end