---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 10184.
--- DateTime: 2020/6/16 10:41
---
local Settings = {}

GMSetting = {}

function GMSetting:addTab(tab_name, index)
    for _, setting in pairs(Settings) do
        if setting.name == tab_name then
            setting.items = {}
            return
        end
    end
    index = index or #Settings + 1
    table.insert(Settings, index, { name = tab_name, items = {} })
end

function GMSetting:addItem(tab_name, item_name, func_name, ...)
    local settings
    for _, group in pairs(Settings) do
        if group.name == tab_name then
            settings = group
        end
    end
    if not settings then
        return
    end
    table.insert(settings.items, { name = item_name, func = func_name, params = { ... } })
end

function GMSetting:getSettings()
    return Settings
end

GMSetting:addTab("常用")
GMSetting:addItem("常用", "开启飞行", "setAllowFlying")
GMSetting:addItem("常用", "找活着的玩家", "findLifePlayer")
GMSetting:addItem("常用", "清数据退游戏", "clearDBAndLogout")
GMSetting:addItem("常用", "重置首充", "resetSumRecharge")
GMSetting:addItem("常用", "", "")
GMSetting:addItem("常用", "开启Debug", "openDebug")
GMSetting:addItem("常用", "关闭Debug", "closeDebug")
GMSetting:addItem("常用", "打开Common包Log", "openCommonPacketDebug")
GMSetting:addItem("常用", "关闭Common包Log", "closeCommonPacketDebug")
GMSetting:addItem("常用", "", "")
GMSetting:addItem("常用", "Debug左移(←)", "moveDebugInfo", -5, 0)
GMSetting:addItem("常用", "Debug右移(→)", "moveDebugInfo", 5, 0)
GMSetting:addItem("常用", "Debug上移(↑)", "moveDebugInfo", 0, -5)
GMSetting:addItem("常用", "Debug下移(↓)", "moveDebugInfo", 0, 5)
GMSetting:addItem("常用", "", "")
GMSetting:addItem("常用", "开始性能测试", "setCPUTimerEnabled", true)
GMSetting:addItem("常用", "结束性能测试", "setCPUTimerEnabled", false)
GMSetting:addItem("常用", "打印性能测试结果", "printCPUTimerResult")

GMSetting:addTab("加道具")
LuaTimer:schedule(function()
    for id = 1, 6000 do
        local item = Item.getItemById(id)
        if item then
            local name = item:getUnlocalizedName() .. ".name"
            local lang = Lang:getString(name)
            if lang == name then
                name = "item." .. string.gsub(item:getUnlocalizedName(), "item.", "") .. ".name"
                lang = Lang:getString(name)
                if lang == name then
                    lang = "Item:" .. tostring(id)
                else
                    lang = lang .. "(" .. tostring(id) .. ")"
                end
            else
                lang = lang .. "(" .. tostring(id) .. ")"
            end
            GMSetting:addItem("加道具", lang, "addItem", id)
        end
    end
    GMSetting:addItem("加道具", "", "")
    GMSetting:addItem("加道具", "", "")
end, 1000)

GMSetting:addTab("平台功能")
GMSetting:addItem("平台功能", "+在线时长(5分钟)", "addGameTime")
GMSetting:addItem("平台功能", "领取集换卡片", "receiveExchange")
GMSetting:addItem("平台功能", "领取集换道具", "receiveExchangeProps")

GMSetting:addTab("集换系统")
GMSetting:addItem("集换系统", "测试*1", "addExchangeProps", "Test:1", 1, 300)

GMSetting:addTab("平台装饰")
local dress_master = { "custom_hair", "custom_face", "clothes_tops", "clothes_pants",
                       "custom_shoes", "custom_glasses", "custom_scarf", "custom_wing",
                       "custom_hat", "custom_decorate_hat", "custom_hand", "custom_tail",
                       "custom_wing_flag", "custom_foot_halo", "custom_back_effect", "custom_crown",
                       "custom_head_effect", "custom_bag", "custom_privilege", "custom_suits" }

for pos, master in pairs(dress_master) do
    GMSetting:addItem("平台装饰", master .. "(change)", "changeCloth", master)
    GMSetting:addItem("平台装饰", master .. "(reset)", "resetCloth", master)
    if pos % 2 == 0 then
        GMSetting:addItem("平台装饰", "", "")
    end
end

GMHelper = {}

function GMHelper:callCommand(name, ...)
    local data = { name = name, params = { ... } }
    PacketSender:sendLuaCommonData("GMCommand", json.encode(data))
    local func = self[name]
    if type(func) ~= "function" then
        return
    end
    func(self, ...)
end

function GMHelper:openDebug()
    CGame.Instance():toggleDebugMessageShown(true)
end

function GMHelper:closeDebug()
    CGame.Instance():toggleDebugMessageShown(false)
end

function GMHelper:moveDebugInfo(offsetX, offsetY)
    ClientHelper.putFloatPrefs("DebugInfoRenderOffsetX", ClientHelper.getFloatPrefs("DebugInfoRenderOffsetX") + offsetX)
    ClientHelper.putFloatPrefs("DebugInfoRenderOffsetY", ClientHelper.getFloatPrefs("DebugInfoRenderOffsetY") + offsetY)
end

function GMHelper:setCPUTimerEnabled(value)
    CPUTimer.SetEnabled(value)
end

function GMHelper:printCPUTimerResult()
    CPUTimer.PrintResults(5000)
end

function GMHelper:openCommonPacketDebug()
    CommonDataEvents.IsDebug = true
end

function GMHelper:closeCommonPacketDebug()
    CommonDataEvents.IsDebug = false
end