---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jimmy.
--- DateTime: 2019/9/3 0003 10:31
---
require "hall.config.GameConfig"

local function checkShowMoreGame()
    if not Game:isEnableIndie() then
        ---主包不需要，只有分包需要展示更多游戏
        return
    end
    local showMoreGameDate = ClientHelper.getStringForKey("showMoreGameDate", "")
    if showMoreGameDate == DateUtil.getYearDay() then
        ---今天展示过了
        return
    end
    if not ClientHelper.getBoolForKey("canShowMoreGame", false) then
        ---需进入过游戏才能展示
        return
    end
    ClientHelper.putStringForKey("showMoreGameDate", DateUtil.getYearDay())
    ClientHelper.putBoolForKey("canShowMoreGame", false)
    --ClientHelper.onAppActionTrigger(7)
end

GameListener = {}

function GameListener:init()
    BaseListener.registerCallBack(GameReadyEvent, self.onGameReady)
    Listener.registerCallBack(CallPluginFunctionEvent, function(func, extra)
        if func == Define.StartGame then
            local npc = FuncNpcConfig:getFuncNpc("param1", extra or "g1008")
            if npc then
                npc:onCallFunc()
            end
        end
    end)
end

function GameListener.onGameReady()
    BaseGameConfig:init()
    GameConfig.loadConfig()
    require "common.data.ClientRecharge"
    require "common.config.PrivilegeConfig"
    require "hall.ui.GUIFactory"
    if Game.isOpenGM and Game:isOpenGM() then
        require "hall.data.GMBedWar"
        require "common.data.GMBedWarCommon"
    end
    checkShowMoreGame()
    TreasureChallenge:init()
    GameInfoManager.Instance()
end

return GameListener