---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangpq.
--- DateTime: 2019/10/14 14:49
---
Define = {}

Define.Area = {
    ShopArea = 1,
    SellArea = 2,
    AutoArea = 3,
    SafeArea = 4,

    CommonArea = 10000,
}

--选中状态1-器材，2-拳击，3-脚踩
Define.SelectMode = {
    Equip = 1,
    Punch = 2,
    Step = 3,
    NotSelect =4
}

Define.PretendSelectMode = {
    NotSelect = 1,
    Select = 2,
}

Define.ActionId = {
    quanji = 100000,
    jiaocai = 100001,
    zhuaqu = 100002,
    juzhong = 100003
}

Define.AutoWorkoutSelectMode = {
    NotSelect = 1,
    Select = 2,
}
--0.金魔方
--1.金魔方
--2.平台金币
--3.游戏绿钞
--4.健身金币

Define.MoneyType = {

    DiamondGolds1 = 0,
    DiamondGolds2 = 1,
    Gold = 2,
    currey = 3,
    SLGolds = 4,
    Token = 5
}

Define.RewardType = {
    Muscle = 1,
    Gold = 2,
}

Define.PayStoreItem =
{
    PayItem = 1, --特权
    Skin = 2, --皮肤
}

Define.PayItemType =
{
    AutoWorkout = 1, --自动锻炼
    DoubleGold = 2, --双倍金币
    DoubleMuscle = 3, --双倍肌肉
    ConcealPower = 4, --伪装弱者
    InfinityMuscle = 5, --无限肌肉
    DoubleDamage = 6, --双倍伤害
    DoubleSpeed = 7, --双倍速度
    DoubleHp = 8, --双倍血量
}

Define.SelectSkinType =
{
    Default = 1, --默认
    Free = 2, --免费
}

Define.SkillType = {
    Throw = 1,
    Beat = 2,
    Toy = 3,
    Common = 4,
}

Define.OpenPrivilegeType = {
    ClickToolBarGold = 1,
    ClickVip = 2,
}

Define.SelectAction = 1012
Define.AS_IDLE = 0