---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 98632.
--- DateTime: 2019/10/17 14:58
---

FitnessEquipConfig = {}

FitnessEquipConfig.Equips = MemoryPool.newTable()



function FitnessEquipConfig:loadConfig()

    local temp = FileUtil.getConfigFromCsv("setting/FitnessEquip.csv", 2)

    for _, Value in pairs(temp) do
        table.insert(self.Equips, {
            Id = tonumber(Value.n_id),
            Name = Value.s_name,
            Desc = Value.s_desc,
            Actor = Value.s_actor,
            Icon = Value.s_icon,
            Efficiency = tonumber(Value.n_efficiency),
            MoneyType = tonumber(Value.n_moneyType),
            Price = tonumber(Value.n_price),
            sortId = tonumber(Value.n_sortId) or 0,
            payConfigId = tonumber(Value.n_payConfigId) or 0,
            Status = ItemBuyStatus.Lock, --购买状态
            Effect = Value.s_effect or "#"
        })

        --print("+++++++++"..tonumber(Value.n_id).."++++++++")
    end
end

function FitnessEquipConfig:getFitnessEquips()
    return self.Equips
end

function FitnessEquipConfig:getFitnessEquipById(Id)
    for _, Value in pairs(self.Equips) do
        if Value.Id==Id then
            return Value
        end
    end
    return nil
end