---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by JY-032.
--- DateTime: 2019/10/15 16:32
---

GamePacketSender = {}

--发送刷新奖池的信息
function GamePacketSender:sendRefreshJobList(price)
    local data = DataBuilder.new():addParam("price", price):getData()
    PacketSender:sendLuaCommonData("RefreshJobListInfo", data)
end

function GamePacketSender:sendSelectJobId(id)
    local data = DataBuilder.new():addParam("JobId", id):getData()
    PacketSender:sendLuaCommonData("SelectJobId", data)
end

--点击卡牌时发包送给服务器随机一个职业出来
function GamePacketSender:sendExtractRandomJobId(price)
    local data = DataBuilder.new():addParam("price", price):getData()
    PacketSender:sendLuaCommonData("ExtractRandomJobId", data)
end


function GamePacketSender:sendPlayerBackHallEvent()
    PacketSender:sendLuaCommonData("BackHallEvent", "")
end

function GamePacketSender:sendPlayerNextGameEvent()
    PacketSender:sendLuaCommonData("NextGameEvent", "")
end