---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jimmy.
--- DateTime: 2019/11/4 0004 11:46
---
local PacketHandler = class("PacketHandler", EventObservable)

function PacketHandler:init()
    self:registerDataCallBack("MountHurt", function(data)
        self:onMountHurt(data)
    end, DataBuilderProcessor)
    self:registerDataCallBack("PlayerMotionData", function(data)
        self:onPlayerMotionData(data)
    end, DataBuilderProcessor)
    self:registerDataCallBack("HoldHotPotato", function(data)
        self:onPlayerHoldHotPotato(data)
    end, DataBuilderProcessor)
end

function PacketHandler:onMountHurt(data)
    local entityId = EntityCache:getClientId(data:getNumberParam("entityId"))
    local function setOnHurt(isHurting)
        local entity = EntityCache:getEntity(entityId)
        if not entity then
            return
        end
        entity.entity:setHurting(isHurting)
    end
    setOnHurt(true)
    LuaTimer:schedule(function()
        setOnHurt(false)
    end, 300)
end

function PacketHandler:onPlayerMotionData(data)
    local player = Game:getPlayer()
    local motion = data:getVector3Param("Motion")
    player.motion = motion
end

function PacketHandler:onPlayerHoldHotPotato(data)
    local player = Game:getPlayer()
    local index = data:getNumberParam("Index")
    local inv = player:getInventory()
    inv:putItemToHotbarByIndex(index, 0)
end

S2CPacketHandler = PacketHandler.new()
S2CPacketHandler:init()