---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jimmy.
--- DateTime: 2019/9/3 0003 10:01
---
require "listener.GameListener"

PluginMain = {}

function PluginMain:init()
    GameListener:init()
    ClientHelper.putBoolPrefs("IsCreatureCollision", false)
    ClientHelper.putBoolPrefs("IsCreatureBloodBar", true)
    ClientHelper.putBoolPrefs("IsGunShootActor", true)
    ClientHelper.putIntPrefs("HurtProtectTime", 0)
    ClientHelper.putBoolPrefs("IsShowItemDurability", true)
end

PluginMain:init()

return PluginMain