/********************************************************************
filename: 	GUIEventArgs.h
file path:	dev\engine\Src\Core\UI\

version:	1
author:		ajohn from CEGUI
company:	supernano
*********************************************************************/

#ifndef _CEGUIEventArgs_h_
#define _CEGUIEventArgs_h_

#include "Core.h"
// Start of CEGUI namespace section
namespace LORD
{
/*!
\brief
	Base class used as the argument to all subscribers Event object.

	The base EventArgs class does not contain any useful information, it is intended
	to be specialised for each type of event that can be generated by objects within
	the system.  The use of this base class allows all event subscribers to have the
	same function signature.

	The \a handled field is used to signal whether an event was actually handled or not.  While
	the event system does not look at this value, code at a higher level can use it to determine
	how far to propagate an event.
*/
class LORD_CORE_API EventArgs
{
public:
	/*************************************************************************
		Construction
	*************************************************************************/
	EventArgs(void) : handled(0) {}
	virtual ~EventArgs(void) {}


	/*************************************************************************
		Data members
	*************************************************************************/
    //! handlers should increment this if they handled the event.
    uint handled;
};

class GUIWindow;
class LORD_CORE_API WindowEventArgs : public EventArgs
{
public:
	WindowEventArgs(GUIWindow* wnd) : window(wnd) {}

	GUIWindow*	window;		//!< pointer to a Window object of relevance to the event.
};

class LORD_CORE_API MouseEventArgs : public WindowEventArgs
{
public:
	MouseEventArgs(GUIWindow* wnd) : WindowEventArgs(wnd) {}

	Vector2		position;		//!< holds current mouse position.
	Vector2		moveDelta;		//!< holds variation of mouse position from last mouse input
};

class Touch;

class LORD_CORE_API TouchEventArgs : public WindowEventArgs
{
public:
	TouchEventArgs(GUIWindow* wnd) : WindowEventArgs(wnd) {}

	const Touch* touch;		//!< holds touch position.
};

class LORD_CORE_API ScrollEventArgs : public EventArgs
{
public:
	ScrollEventArgs(float _offset) : offset(_offset) {}
	float offset;
};

} // End of  CEGUI namespace section

#endif	// end of guard _CEGUIEventArgs_h_
