---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangpq.
--- DateTime: 2019/9/17 10:26
---
require "listener.GameListener"
require "listener.PlayerListener"
require "listener.UIListener"

require "data.PlayerProperty"
require "data.ClientPlayer"
require "data.MyClientPlayer"
require "data.MyOtherPlayer"

require "util.Utility"
require "Test"
require "GameClient"
GMHandler = (require "GMHandler").new()
GamePacketHandler = (require "packet.GamePacketHandler").new()
AreaManager = (require "manager.AreaManager").new()
TeamManager = (require "manager.TeamManager").new()

require "controller.BaseController"
MainControlController = (require "controller.MainControlController").new()

require "events.ClientEvents"
require "events.S2CPackets"

require "config.ShopTabConfig"
require "config.FitnessEquipConfig"
require "config.GeneConfig"
require "config.AdvancedConfig"
require "config.SkillConfig"
require "config.GameConfig"
require "config.CommonConfig"
require "config.Define"
require "config.UnitConfig"
require "config.EffectConfig"
require "config.SkinConfig"
require "config.PayItemConfig"
require "config.PayShopTabConfig"
require "config.NewGuideConfig"
require "config.PayFitnessEquipConfig"
require "config.ScaleFormulaConfig"
require "config.ChampionShipConfig"
require "config.TokenFitnessEquipConfig"
require "config.TokenGeneConfig"
require "config.TokenSkillConfig"
require "config.TokenSkinConfig"

require "ui.window.GUIShopItem"
require "ui.window.GUIShopTab"
require "ui.window.GUIPayShopItem"
require "ui.window.GUIPayShopTab"