/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sandboxol_blockmango_EchoesRenderer */

#ifndef _Included_com_sandboxol_blockmango_EchoesRenderer
#define _Included_com_sandboxol_blockmango_EchoesRenderer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sandboxol_blockmango_EchoesRenderer
 * Method:    nativeTouchesBegin
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_com_sandboxol_blockmango_EchoesRenderer_nativeTouchesBegin
        (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     com_sandboxol_blockmango_EchoesRenderer
 * Method:    nativeTouchesEnd
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_com_sandboxol_blockmango_EchoesRenderer_nativeTouchesEnd
        (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     com_sandboxol_blockmango_EchoesRenderer
 * Method:    nativeTouchesMove
 * Signature: ([I[F[F)V
 */
JNIEXPORT void JNICALL Java_com_sandboxol_blockmango_EchoesRenderer_nativeTouchesMove
        (JNIEnv *, jclass, jintArray, jfloatArray, jfloatArray);

/*
 * Class:     com_sandboxol_blockmango_EchoesRenderer
 * Method:    nativeTouchesCancel
 * Signature: ([I[F[F)V
 */
JNIEXPORT void JNICALL Java_com_sandboxol_blockmango_EchoesRenderer_nativeTouchesCancel
        (JNIEnv *, jclass, jintArray, jfloatArray, jfloatArray);

/*
 * Class:     com_sandboxol_blockmango_EchoesRenderer
 * Method:    nativeKeyDown
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_sandboxol_blockmango_EchoesRenderer_nativeKeyDown
        (JNIEnv *, jclass, jint);

/*
 * Class:     com_sandboxol_blockmango_EchoesRenderer
 * Method:    nativeKeyDown
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_sandboxol_blockmango_EchoesRenderer_nativeKeyUp
        (JNIEnv *, jclass, jint);

/*
 * Class:     com_sandboxol_blockmango_EchoesRenderer
 * Method:    nativeRender
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sandboxol_blockmango_EchoesRenderer_nativeRender
        (JNIEnv *, jclass);

/*
 * Class:     com_sandboxol_blockmango_EchoesRenderer
 * Method:    nativeInit
 * Signature: (Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_com_sandboxol_blockmango_EchoesRenderer_nativeInit
        (JNIEnv *, jclass, jfloat,jstring, jstring, jstring, jint, jint);

/*
 * Class:     com_sandboxol_blockmango_EchoesRenderer
 * Method:    nativeInitGame
 * Signature: (Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_com_sandboxol_blockmango_EchoesRenderer_nativeInitGame
        (JNIEnv *, jclass, jfloat, jstring, jlong, jstring, jstring, jint, jlong, jstring, jstring, jstring, jstring, jstring, jstring, jstring,
         jint, jint, jstring, jboolean, jboolean);

/*
 * Class:     com_sandboxol_blockmango_EchoesRenderer
 * Method:    nativeOnSurfaceChanged
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_sandboxol_blockmango_EchoesRenderer_nativeOnSurfaceChanged
        (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_sandboxol_blockmango_EchoesRenderer
 * Method:    nativeOnPause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sandboxol_blockmango_EchoesRenderer_nativeOnPause
        (JNIEnv *, jclass);

/*
 * Class:     com_sandboxol_blockmango_EchoesRenderer
 * Method:    nativeOnResume
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sandboxol_blockmango_EchoesRenderer_nativeOnResume
        (JNIEnv *, jclass);


JNIEXPORT jint JNICALL Java_com_sandboxol_blockmango_EchoesRenderer_nativeCheckVersion
        (JNIEnv *, jclass, jstring);

JNIEXPORT jint JNICALL Java_com_sandboxol_blockmango_EchoesRenderer_nativeUpdateFiles
        (JNIEnv *, jclass);

JNIEXPORT jfloat JNICALL Java_com_sandboxol_blockmango_EchoesRenderer_nativeGetDownloadPercent
        (JNIEnv *, jclass);

JNIEXPORT jint JNICALL Java_com_sandboxol_blockmango_EchoesRenderer_nativeGetDownloadState
        (JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_com_sandboxol_blockmango_EchoesRenderer_nativeOnGetPhoneType
        (JNIEnv *, jclass, jstring);

JNIEXPORT jint JNICALL Java_com_sandboxol_blockmango_EchoesRenderer_nativeGetTotalDownloadSize
        (JNIEnv *, jclass);

JNIEXPORT jint JNICALL Java_com_sandboxol_blockmango_EchoesRenderer_nativeGetCurrentDownloadSize
        (JNIEnv *, jclass);

JNIEXPORT jstring JNICALL Java_com_sandboxol_blockmango_EchoesRenderer_nativeGetLocalVersion
        (JNIEnv *, jclass);

JNIEXPORT jstring JNICALL Java_com_sandboxol_blockmango_EchoesRenderer_nativeGetServerVersion
        (JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_com_sandboxol_blockmango_EchoesRenderer_nativeOnDestroy
        (JNIEnv *env, jclass type);

JNIEXPORT void JNICALL Java_com_sandboxol_blockmango_EchoesRenderer_nativeUseProp
        (JNIEnv *env, jclass type, jstring);

JNIEXPORT jint JNICALL Java_com_sandboxol_blockmango_EchoesRenderer_getPing
        (JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_com_sandboxol_blockmango_EchoesRenderer_nativeOnFriendOperationForAppHttpResult
        (JNIEnv *, jclass, jint, jlong);

JNIEXPORT void JNICALL Java_com_sandboxol_blockmango_EchoesRenderer_nativeOnResetGameResult
        (JNIEnv *, jclass, jint);

JNIEXPORT void JNICALL Java_com_sandboxol_blockmango_EchoesRenderer_nativeSetUserInfo
        (JNIEnv *, jclass, jstring, jstring, jlong);

JNIEXPORT void JNICALL Java_com_sandboxol_blockmango_EchoesRenderer_nativeOnRechargeResult
        (JNIEnv *env, jclass type, jint, jint);

JNIEXPORT void JNICALL Java_com_sandboxol_blockmango_EchoesRenderer_nativeHideRechargeBtn
        (JNIEnv *env, jclass type);

JNIEXPORT void JNICALL Java_com_sandboxol_blockmango_EchoesRenderer_nativeBuyActionResult
        (JNIEnv *env, jclass type, jint, jint);

JNIEXPORT void JNICALL Java_com_sandboxol_blockmango_EchoesRenderer_nativeExitGame
        (JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_com_sandboxol_blockmango_EchoesRenderer_nativeOnWatchAdResult
        (JNIEnv *, jclass, jint, jstring, jint);

JNIEXPORT void JNICALL Java_com_sandboxol_blockmango_EchoesRenderer_nativeOnGameActionTrigger
        (JNIEnv *, jclass, jint, jstring);

JNIEXPORT void JNICALL Java_com_sandboxol_blockmango_EchoesRenderer_nativePlayAdVideoMultiParamResult
        (JNIEnv *, jclass, jstring, jint);

JNIEXPORT void JNICALL Java_com_sandboxol_blockmango_EchoesRenderer_nativeConnectServer
        (JNIEnv *, jclass, jstring, jint, jstring);

JNIEXPORT jint JNICALL Java_com_sandboxol_blockmango_EchoesRenderer_nativeGetRaknetPing
        (JNIEnv *, jclass);

JNIEXPORT jint JNICALL Java_com_sandboxol_blockmango_EchoesRenderer_nativeGetFps
        (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
