---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xiaolai.
--- DateTime: 2019/11/26 20:00
---

local UISkyBlockMiningAreaSellPreciousTip = class("UISkyBlockMiningAreaSellPreciousTip", IGUILayout)

function UISkyBlockMiningAreaSellPreciousTip:onLoad()
    print("UISkyBlockMiningAreaSellPreciousTip:onLoad()")

    self.title = self:getChildWindow("SkyBlockMiningAreaSellPreciousTip-Title")
    self.title:SetText(Lang:getString("gui_dialog_tip_title_tip"))
    self.imgBg = self:getChildWindow("SkyBlockMiningAreaSellPreciousTip-Icon-Bg")
    self.icon = self:getChildWindow("SkyBlockMiningAreaSellPreciousTip-Icon")

    self.cancelBtn = self:getChildWindow("SkyBlockMiningAreaSellPreciousTip-Cancel-Btn", GUIType.Button)
    self.cancelBtn:SetText(Lang:getString("gui_dialog_tip_btn_cancel"))
    self.cancelBtn:registerEvent(GUIEvent.ButtonClick, function()
        self:onClickCancle()
    end)

    self.sureBtn = self:getChildWindow("SkyBlockMiningAreaSellPreciousTip-Sure-Btn", GUIType.Button)
    self.sureBtn:SetText(Lang:getString("gui_dialog_tip_btn_sure"))
    self.sureBtn:registerEvent(GUIEvent.ButtonClick, function()
        self:onClickSure()
    end)

    self.closeBtn = self:getChildWindow("SkyBlockMiningAreaSellPreciousTip-Close", GUIType.Button)
    self.closeBtn:registerEvent(GUIEvent.ButtonClick, function()
        self:onClickClose()
    end)

    self.pricePanel = self:getChildWindow("SkyBlockMiningAreaSellPreciousTip-Msg-Panel", GUIType.Layout)
    self.pricePanel:SetVisible(true)

    self.message = self:getChildWindow("SkyBlockMiningAreaSellPreciousTip-Info")
end

function UISkyBlockMiningAreaSellPreciousTip:onClickCancle()
    self:hide()
    if self.callBack then
        self.callBack(false)
        self.callBack = nil
    end
end

function UISkyBlockMiningAreaSellPreciousTip:onClickClose()
    self:hide()
    if self.callBack then
        self.callBack(false)
        self.callBack = nil
    end
end

function UISkyBlockMiningAreaSellPreciousTip:onClickSure()
    self:hide()
    if self.callBack then
        self.callBack(true)
        self.callBack = nil
    end
end

function UISkyBlockMiningAreaSellPreciousTip:onShowPreciousTipDialog(itemId, itemMeta, type, callBack)
    self.callBack = callBack
    self:show()
    local meta = itemMeta
    if SellPreciousTipConfig:isSpItemMeta(itemId) then
        meta = 0
    end
    GuiItemStack.showItemIcon(self.icon, tonumber(itemId), tonumber(meta), "")
    self.type = type
    local str = "drop_precious_tip"
    if self.type == 1 then
        if itemId == 2802 or itemId == 2803 then
            str = "sell_christmas_gift_tip"
        else
            str = "sell_precious_tip"
        end
    else
        if itemId == 2802 or itemId == 2803 then
            str = "drop_christmas_gift_tip"
        else
            str = "drop_precious_tip"
        end
    end
    self.message:SetText(Lang:getString(str))
end


GUISkyBlockMiningAreaSellPreciousTip = UISkyBlockMiningAreaSellPreciousTip.new("SkyBlockMiningAreaSellPreciousTip.json")
GUISkyBlockMiningAreaSellPreciousTip:hide()