#ifndef _HELPER_REGISTER_H__
#define _HELPER_REGISTER_H__

#include "Plugins/DynamicCastHelper.h"
#include "Plugins/DynamicCastClientEntity.h"
#include "LuaRegister/Template/LuaRegister.h"

using namespace LUA_REGISTER;

// Register Class DynamicCastHelper
_BEGIN_REGISTER_CLASS(DynamicCastHelper)
#pragma region
_CLASSREGISTER_AddStaticMember(dynamicCastLayout, DynamicCastHelper::dynamicCastLayout)
_CLASSREGISTER_AddStaticMember(dynamicCastStaticText, DynamicCastHelper::dynamicCastStaticText)
_CLASSREGISTER_AddStaticMember(dynamicCastStaticImage, DynamicCastHelper::dynamicCastStaticImage)
_CLASSREGISTER_AddStaticMember(dynamicCastButton, DynamicCastHelper::dynamicCastButton)
_CLASSREGISTER_AddStaticMember(dynamicCastGridView, DynamicCastHelper::dynamicCastGridView)
_CLASSREGISTER_AddStaticMember(dynamicCastListBox, DynamicCastHelper::dynamicCastListBox)
_CLASSREGISTER_AddStaticMember(dynamicCastListHorizontalBox, DynamicCastHelper::dynamicCastListHorizontalBox)
_CLASSREGISTER_AddStaticMember(dynamicCastCheckBox, DynamicCastHelper::dynamicCastCheckBox)
_CLASSREGISTER_AddStaticMember(dynamicCastProgressBar, DynamicCastHelper::dynamicCastProgressBar)
_CLASSREGISTER_AddStaticMember(dynamicCastRadioButton, DynamicCastHelper::dynamicCastRadioButton)
_CLASSREGISTER_AddStaticMember(dynamicCastTableView, DynamicCastHelper::dynamicCastTableView)
_CLASSREGISTER_AddStaticMember(dynamicCastAnimateWindow, DynamicCastHelper::dynamicCastAnimateWindow)
_CLASSREGISTER_AddStaticMember(dynamicCastBubbleContain, DynamicCastHelper::dynamicCastBubbleContain)
_CLASSREGISTER_AddStaticMember(dynamicCastCell, DynamicCastHelper::dynamicCastCell)
_CLASSREGISTER_AddStaticMember(dynamicCastEditBox, DynamicCastHelper::dynamicCastEditBox)
_CLASSREGISTER_AddStaticMember(dynamicCastInputBox, DynamicCastHelper::dynamicCastInputBox)
_CLASSREGISTER_AddStaticMember(dynamicCastMultiLineEdit, DynamicCastHelper::dynamicCastMultiLineEdit)
_CLASSREGISTER_AddStaticMember(dynamicCastPageView, DynamicCastHelper::dynamicCastPageView)
_CLASSREGISTER_AddStaticMember(dynamicCastSceneMap, DynamicCastHelper::dynamicCastSceneMap)
_CLASSREGISTER_AddStaticMember(dynamicCastScrollablePane, DynamicCastHelper::dynamicCastScrollablePane)
_CLASSREGISTER_AddStaticMember(dynamicCastScrollCard, DynamicCastHelper::dynamicCastScrollCard)
_CLASSREGISTER_AddStaticMember(dynamicCastScrolledContainer, DynamicCastHelper::dynamicCastScrolledContainer)
_CLASSREGISTER_AddStaticMember(dynamicCastSlider, DynamicCastHelper::dynamicCastSlider)
_CLASSREGISTER_AddStaticMember(dynamicCastUrlImage, DynamicCastHelper::dynamicCastUrlImage)
_CLASSREGISTER_AddStaticMember(dynamicCastActorWindow, DynamicCastHelper::dynamicCastActorWindow)
_CLASSREGISTER_AddStaticMember(dynamicCastEffectViewOfObtainment, DynamicCastHelper::dynamicCastEffectViewOfObtainment)
_CLASSREGISTER_AddStaticMember(dynamicCastItemStack, DynamicCastHelper::dynamicCastItemStack)
_CLASSREGISTER_AddStaticMember(dynamicCastItemSlot, DynamicCastHelper::dynamicCastItemSlot)
_CLASSREGISTER_AddStaticMember(dynamicCastSlotTable, DynamicCastHelper::dynamicCastSlotTable)
_CLASSREGISTER_AddStaticMember(dynamicCastScrollableInventory, DynamicCastHelper::dynamicCastScrollableInventory)
#pragma endregion
#pragma region
_CLASSREGISTER_AddStaticMember(dynamicCastGuiMenu, DynamicCastHelper::dynamicCastGuiMenu)
_CLASSREGISTER_AddStaticMember(dynamicCastGuiGameSetting, DynamicCastHelper::dynamicCastGuiGameSetting)
_CLASSREGISTER_AddStaticMember(dynamicCastGuiMainControl, DynamicCastHelper::dynamicCastGuiMainControl)
_CLASSREGISTER_AddStaticMember(dynamicCastGuiChat, DynamicCastHelper::dynamicCastGuiChat)
#pragma endregion
_END_REGISTER_CLASS()


// Register Class DynamicCastClientEntity
_BEGIN_REGISTER_CLASS(DynamicCastClientEntity)
_CLASSREGISTER_AddStaticMember(dynamicCastActorCannonClient, DynamicCastClientEntity::dynamicCastActorCannonClient)
_CLASSREGISTER_AddStaticMember(dynamicCastBulletClient, DynamicCastClientEntity::dynamicCastBulletClient)
_CLASSREGISTER_AddStaticMember(dynamicCastFishHookClient, DynamicCastClientEntity::dynamicCastFishHookClient)
_CLASSREGISTER_AddStaticMember(dynamicCastFlyingMountClient, DynamicCastClientEntity::dynamicCastFlyingMountClient)
_CLASSREGISTER_AddStaticMember(dynamicCastGunFlame, DynamicCastClientEntity::dynamicCastGunFlame)
_CLASSREGISTER_AddStaticMember(dynamicCastOtherPlayerMP, DynamicCastClientEntity::dynamicCastOtherPlayerMP)
_CLASSREGISTER_AddStaticMember(dynamicCastPlayerSP, DynamicCastClientEntity::dynamicCastPlayerSP)
_CLASSREGISTER_AddStaticMember(dynamicCastPlayerSPMP, DynamicCastClientEntity::dynamicCastPlayerSPMP)
_CLASSREGISTER_AddStaticMember(dynamicCastVehicleClient, DynamicCastClientEntity::dynamicCastVehicleClient)
_END_REGISTER_CLASS()

#endif