---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jimmy.
--- DateTime: 2019/8/28 0028 15:52
---
BaseListener = {}
BaseListener.callbacks = {}

function BaseListener.registerCallBack(event, func)
    BaseListener.callbacks[event] = func
end

function BaseListener:destroy()
    BaseListener.callbacks = {}
    Listener.unregisterAll()
end

function BaseListener:init()
    GameDestroyEvent.unregisterAll()
    GameInitEvent.unregisterAll()
    GameInitEvent.registerCallBack(self.onGameInit)
    GameDestroyEvent.registerCallBack(self.onGameDestroy)
end

function BaseListener.onGameInit(gameType)
    GameType = gameType
    BaseMain:setGameType(gameType)
    AnalyticsListener:init()
    ExchangeHelper:init()
    Listener.registerCallBack(LuaHotUpdateEvent, BaseListener.onLuaHotUpdate)
    Listener.registerCallBack(GameLoadMapSuccessEvent, BaseListener.onGameLoadMapSuccess)
    Listener.registerCallBack(LuaLoadWorldEndEvent, BaseListener.onLuaLoadWorldEnd)
    Listener.registerCallBack(GameReadyEvent, BaseListener.onGameReady)
    Listener.registerCallBack(ServerCommonDataEvent, BaseListener.onServerCommonData)
    Listener.registerCallBack(GameMainTickEvent, BaseListener.onGameMainTick)
    Listener.registerCallBack(HideAllLayoutEvent, BaseListener.onHideAllLayout)
    Listener.registerCallBack(RecoverAllLayoutEvent, BaseListener.onRecoverAllLayout)
    Listener.registerCallBack(ShowPluginLayoutEvent, BaseListener.onShowPluginLayout)
    Listener.registerCallBack(GameActionTriggerEvent, BaseListener.onGameActionTrigger)
    Listener.registerCallBack(SpawnEntityEvent, BaseListener.onSpawnEntity)
    Listener.registerCallBack(RemoveEntityEvent, BaseListener.onRemoveEntity)
    Listener.registerCallBack(OtherPlayerSpawnEvent, BaseListener.onOtherPlayerSpawn)
    Listener.registerCallBack(PlayerRebirthEvent, BaseListener.onPlayerRebirth)
    Listener.registerCallBack(PlayerLoginEvent, BaseListener.onPlayerLogin)
    Listener.registerCallBack(PlayerLogoutEvent, BaseListener.onPlayerLogout)
    Listener.registerCallBack(LuaPlayerDeathEvent, BaseListener.onPlayerDeath)
    Listener.registerCallBack(GameOverEvent, BaseListener.onGameOver)

    if Game:isOpenGM() then
        ---测试服
        require "base.helper.GMHelper"
    end

    local callback = BaseListener.callbacks[GameInitEvent]
    if callback then
        callback()
    end

    if Platform.isWindow() then
        local path = string.gsub(FileUtil:getScriptPath(), "ClientGame", "BaseGame")
        HU.Init("base.hotupdate.hotupdatelist", { ".\\Media\\Scripts\\ClientGame\\Common", FileUtil:getScriptPath(), path })
        LuaTimer:scheduleTimer(function()
            HU.Update()
        end, 1000)
    end
end

function BaseListener.onLuaHotUpdate()
    if HU then
        HU.Update()
    end
    return true
end

function BaseListener.onGameLoadMapSuccess(mapPath, rootPath)
    FileUtil:setMapPath(mapPath)
    FileUtil:setRootPath(rootPath)
    local callback = BaseListener.callbacks[GameLoadMapSuccessEvent]
    if callback then
        callback()
    end
end

function BaseListener.onLuaLoadWorldEnd()
    PlayerManager:createClientPlayer()
    local callback = BaseListener.callbacks[LuaLoadWorldEndEvent]
    if callback then
        callback()
    end
end

function BaseListener.onGameReady()
    Game:init()
    Lang:init()
    WebService:init()
    GUIManager:init()
    PacketSender:init()
    EntityCache:init()
    MaxRecordHelper:init()
    require "base.ui.layout.GUICustomDialog"
    require "base.ui.layout.GUIProbabilityDialog"
    require "base.config.SumRechargeConfig"
    require "base.config.GeneralProbabilityConfig"
    require "base.config.CommonActivityChestConfig"
    require "base.config.CommonActivityConfig"
    require "base.config.CommonActivityRewardConfig"
    require "base.config.MustLotteryPriceConfig"
    require "base.config.LuckyLotteryPrice"
    require "base.config.LuckyValueConfig"
    SumRechargeConfig:init()

    require "base.config.GUIAnimConfig"
    GUIAnimManager:init()
    local customUI = require "base.ui.CCustomGUI"
    customUI:init()
    local callback = BaseListener.callbacks[GameReadyEvent]
    if callback then
        callback()
    end
    initCustomDialog("CustomDialog.json")
    require "base.ui.layout.GUICheckMoneyContent"
    initProbabilityDialog("ProbabilityDialog.json")

    local UIFriendFollow = require "base.ui.layout.GUIFriendsFollow"
    GUIFriendFollow = UIFriendFollow.new("FriendsFollow.json", GUIManager:getMainControl())

    local UIFriendsFollowTip = require "base.ui.layout.GUIFriendsFollowTip"
    GUIFriendsFollowTip = UIFriendsFollowTip.new("FriendsFollowTip.json")

    if Game:isOpenGM() then
        ---测试服
        local UIGMControlPanel = require "base.ui.layout.GUIGMControlPanel"
        GUIGMControlPanel = UIGMControlPanel.new("GMControlPanel.json")
        GUIGMControlPanel:hide()
        local UIGMMain = require "base.ui.layout.GUIGMMain"
        local GUIGMMain = UIGMMain.new("GMMain.json", GUIManager:getMainControl())
        GUIGMMain:show()
    end
end

function BaseListener.onGameDestroy()
    local callback = BaseListener.callbacks[GameDestroyEvent]
    if callback then
        local result, info = pcall(callback)
        if not result then
            LogUtil.log(info, LogUtil.LogLevel.Error)
        end
    end
    WebService:destroy()
    DataBuilderProcessor:clearMapping()
    CommonDataEvents:unregisterAll()
    GameAnalyticsCache:destroy()
    BaseListener:destroy()
    LuaTimer:cancelAll()
    Game:destroy()
    Lang:destroy()
    PlayerManager:destroy()
    TaskQueueManager:destroy()
    EntityCache:destroy()
    PacketSender:destroy()
    PlayerWallet:destroy()
    GUIManager:destroy()
    MemoryPool.clearPool()
    BaseMain:destroy()
    GameAnalytics.Enable = false
end

function BaseListener.onServerCommonData(key, data)
    CommonDataEvents:dispatchEvent(key, data)
end

function BaseListener.onGameMainTick(frameTime)
    GUIManager:onTick(frameTime)
    LuaTimer:onTick(frameTime)
    EntityCache:onTick(frameTime)
    GameAnalyticsCache:trySendEvents()

    local callback = BaseListener.callbacks[GameMainTickEvent]
    if callback then
        callback(frameTime)
    end
end

function BaseListener.onHideAllLayout()
    GUIManager:hideAllLayout()
end

function BaseListener.onRecoverAllLayout()

end

function BaseListener.onShowPluginLayout(name, params)
    local layout = GUIManager:getLayout(name)
    if not layout then
        return
    end
    layout:show(params)
end

function BaseListener.onGameActionTrigger(type, params)
    if type == 3 then
        PayHelper.disableRecharge()
    end
    local callback = BaseListener.callbacks[GameActionTriggerEvent]
    if callback then
        callback(type, params)
    end
end

function BaseListener.onOtherPlayerSpawn(otherPlayerMP)
    local player = PlayerManager:getPlayerByPlayerMP(otherPlayerMP)
    if not player then
        player = PlayerManager:createOtherPlayer(otherPlayerMP)
    else
        player:onSpawn(otherPlayerMP)
    end
    local callback = BaseListener.callbacks[OtherPlayerSpawnEvent]
    if callback then
        callback(player)
    end
end

function BaseListener.onPlayerRebirth(playerSPMP)
    if not PlayerManager:getClientPlayer() then
        PlayerManager:createClientPlayer()
    else
        PlayerManager:getClientPlayer():onSpawn(playerSPMP)
    end
    local callback = BaseListener.callbacks[PlayerRebirthEvent]
    if callback then
        callback(PlayerManager:getClientPlayer())
    end
end

function BaseListener.onSpawnEntity(entity, type, properties)
    if not EngineWorld:getWorld() then
        return
    end
    local lEntity = EntityCache:createEntityCache(entity, type, properties)
    local callback = BaseListener.callbacks[SpawnEntityEvent]
    if callback then
        callback(lEntity)
    end
end

function BaseListener.onRemoveEntity(entityId)
    EntityCache:removeEntityCache(entityId)
    local callback = BaseListener.callbacks[RemoveEntityEvent]
    if callback then
        callback(entityId)
    end
end

function BaseListener.onPlayerLogin(userId, teamId)

end

function BaseListener.onPlayerLogout(userId)
    local callback = BaseListener.callbacks[PlayerLogoutEvent]
    local player = PlayerManager:getPlayerByUserId(userId)
    if not player then
        return
    end
    if callback then
        callback(player)
    end
    player:onLogout()
    player.Player = nil
    PlayerManager:subPlayer(userId)
end

function BaseListener.onPlayerDeath(userId)
    local player = PlayerManager:getPlayerByUserId(userId)
    if not player then
        return
    end
    player:onSpawn(nil)
end

function BaseListener.onGameOver(message)
    ClientHelper.callAppJsonFunction("onGameOver", { message = message })
    ExchangeHelper:cancelExchangeTimer()
end

return BaseListener
