/********************************************************************
filename: 	DataPacket
file path:	H:\sandboxol\client\blockmango-client\dev\common\Src\network\packet\DataPacket.h

version:	1
author:		qutianxiang
company:    sandboxol
date:		2017/06/19
*********************************************************************/


//-----------------------------------------
//| id | data |
//----------------------------------------


#ifndef __DATAPACKET_HEADER__
#define __DATAPACKET_HEADER__

#include <cstdint>
#include "raknet/include/BitStream.h"
#include "Serializer.h"

enum class S2CPacketType : uint16_t
{
	ProtocolBegin = 0,
	ServerCommonData = 1,
	SyncPlayerMovementInput = 2,
	SyncPlayerRotation = 3,
	EntityPlayerTeleport = 4,
	UpdateBlockChunks = 5,
	SyncVehicleMovement = 6,
	SyncVehicleInput = 7,
	SyncVehicleHornSound = 8,
	SpawnFlyingMount = 9,
	FlyingMountMovement = 10,
	MountFlyingMount = 11,
	SpawnFloatingMount = 12,
	FloatingMountMovement = 13,
	MountFloatingMount = 14,
	GameInfo = 15,
	Disconnect = 16,
	AddPlayer = 17,
	UpdateBlocks = 18,
	PlayerList = 19,
	MovePlayer = 20,
	EntityMovement = 21,
	EntityTeleport = 22,
	EntityVelocity = 23,
	EntityHeadRotation = 24,
	SpawnVehicle = 25,
	SpawnPlayer = 26,
	SpawnExpOrb = 27,
	SpawnMob = 28,
	RemoveEntity = 29,
	Animate = 30,
	UpdatePlayerAttribute = 31,
	Rebirth = 32,
	PlayerAction = 33,
	CraftItem = 34,
	EquipArmors = 35,
	UnequipArmor = 36,
	DestroyArmor = 37,
	ChangeItemInHand = 38,
	ChangeCurrentItem = 39,
	PlayerInventory = 40,
	ChatMessageString = 41,
	ChatMessageTranslation = 42,
	PlayerInvisible = 43,
	AddEntityEffect = 44,
	RemoveEntityEffect = 45,
	ChestInventory = 46,
	UsePropResults = 47,
	UserIn = 48,
	UserOut = 49,
	LoginFailure = 50,
	Ping = 51,
	SyncWorldTime = 52,
	ChatMessageNotification = 53,
	Settlement = 54,
	Gameover = 55,
	CloseContainer = 56,
	PlaySound = 57,
	Explosion = 58,
	SetSignTexts = 59,
	SetAllowFlying = 60,
	ChangePlayerInfo = 61,
	GameStatus = 62,
	SetWatchMode = 63,
	UpdateMerchant = 64,
	SetFlying = 65,
	PlayerSettlement = 66,
	GameSettlement = 67,
	UserAttr = 68,
	DebugString = 69,
	PlayerLifeStatus = 70,
	SyncWorldWeather = 71,
	BedDestroy = 72,
	CheckCSVersionResult = 73,
	RespawnCountdown = 74,
	AllPlayerTeamInfo = 75,
	ChangePlayerTeam = 76,
	PlayerChangeActor = 77,
	PlayerRestoreActor = 78,
	ReloadBullet = 79,
	UpdateShop = 80,
	UpdateShopGoods = 81,
	ShoppingResult = 82,
	InitMoney = 83,
	SyncGunFireResult = 84,
	SyncTakeVehicle = 85,
	ChangeMaxHealth = 86,
	UpdateCurrency = 87,
	SelectRoleData = 88,
	SyncPlayerOwnVehicle = 89,
	SyncLockVehicle = 90,
	SyncVehicleState = 91,
	SyncVehicleAction = 92,
	NotifyGetMoney = 93,
	NotifyGetItem = 94,
	BuyCommodityResult = 95,
	ShowBuyRespawn = 96,
	//BuyRespawnResult = 97,
	ShowGoNpcMerchant = 98,
	UpdateBackpack = 99,
	RankData = 100,
	ActivateTrigger = 101,
	UpdateRankNpc = 102,
	TakeAircraft = 103,
	AircraftStartFly = 104,
	SyncAircraftState = 105,
	FriendOperation = 106,
	ChangeAircraftUI = 107,
	AirDorp = 108,
	PoisonCircleRange = 109,
	MemberLeftAndKill = 110,
	SyncBlockDestroyeFailure = 111,
	SkillType = 112,
	SyncChangePlayerActorInfo = 113,
	SyncNpcActorInfo = 114,
	SyncHideAndSeekBtnStatus = 115,
	EntitySkillEffect = 116,
	PickUpItemOrder = 117,
	RequestResult = 118,
	SyncGameTimeShowUi = 119,
	//SyncCreateArrowTipMark = 120,
	SyncCameraLock = 121,
	DeathUnequipArmor = 122,
	SyncChangeEntityPerspece = 123,
	ChangeHeart = 124,
	UpdateRealTimeRankInfo = 125,
	UpdateGameMonsterInfo = 126,
	UpdateBossBloodStrip = 127,
	SwitchablePropsData = 128,
	UpgradePropsData = 129,
	PersonalShopTip = 130,
	CreateHouseFromSchematic = 131,
	SyncEntityCreature = 132,
	SyncCreatureEntityAction = 133,
	EntitySpeedLevel = 134,
	PlayerExpInfo = 135,
	FillAreaByBlockIdAndMate = 136,
	ShowPlayerOperation = 137,
	ManorBtnVisible = 138,
	CallOnManorResetClient = 139,
	UpdateManorOwner = 140,
	SpawnCreatureBullet = 141,
	ShowUpgradeResourceUI = 142,
	UpdateBasementLife = 143,
	CustomTipMsg = 144,
	EntityPlayerOccupation = 145,
	SpwanSkillItemThrowable = 146,
	SyncSessionNpc = 147,
	UpdateManor = 148,
	SyncPlayerJumpChanged = 149,
	SyncPlayerDownChanged = 150,
	SyncPlayerSetFlyingState = 151,
	GameTipNotification = 152,
	UpdateChestInventory = 153,
	UpdateMerchantInfo = 154,
	UpdateMerchantCommodities = 155,
	//SyncShowMaskTime = 156,
	ShowBuildWarBlockBtn = 157,
	ShowBuildWarPlayNum = 158,
	ShowBuildWarLeftNum = 159,
	OpenShopByEntityId = 160,
	ShowBuildWarGrade = 161,
	ShowBuildWarGuessResult = 162,
	ShowBuildWarGuessUi = 163,
	GameSettlementExtra = 164,
	UnlockedCommodity = 165,
	InitUnlockedCommodity = 166,
	CloseBGM = 167,
	SetArmItem = 168,
	TeamResourcesUpdate = 169,
	ActorNpcContent = 170,
	BuildProgress = 171,
	EnchantmentPropsData = 172,
	PersonalSuperPropsData = 173,
	EnableMovement = 174,
	ConsumeCoinTip = 175,
	SuperPropsData = 176,
	SuperShopTip = 177,
	ChangeDefense = 178,
	ChangeAttack = 179,
	AddSimpleEffect = 180,
	EnterOtherGame = 181,
	KillMsg = 182,
	ShowPersonalShop = 183,
	PersonalShopArea = 184,
	AddGunBulletNum = 185,
	SubGunRecoil = 186,
	CustomPropsData = 187,
	UpdateCustomProps = 188,
	SyncEntityBlockman = 189,
	BlockmanMoveAttr = 190,
	CarDirection = 191,
	CarProgress = 192,
	EntityFrozenTime = 193,
	EntityPlayerTeleportWithMotion = 194,
	SyncCannonActorInfo = 195,
	SpawnCannon = 196,
	SyncCannonFire = 197,
	SubGunFireCd = 198,
	CropInfo = 199,
	SyncRanchInfo = 200,
	SyncRanchHouse = 201,
	SyncRanchStorage = 202,
	SyncRanchRank = 203,
	SyncRanchBuild = 204,
	SyncEntityBuildNpc = 205,
	SyncEntityLandNpc = 206,
	RanchGain = 207,
	SyncRanchOrder = 208,
	SyncRanchAchievement = 209,
	SyncPlayerSpecialJump = 210,
	ShowRanchExTip = 211,
	ShowRanchExTask = 212,
	BroadcastMessage = 213,
	//GotoOtherGame = 214, --support the old version, temporarily reserved
	RanchUnlockItem = 215,
	ShowRanchExCurrentItemInfo = 216,
	ShowRanchExItem = 217,
	RanchTimePrice = 218,
	RanchShortcutFreeTimes = 219,
	AppExpResult = 220,
	OccupationUnlock = 221,
	BuyFlying = 222,
	PlayCloseup = 223,
	ShowBuyKeepItemTip = 224,
	SendOpenEnchantment = 225,
	EntityHurtTime = 226,
	LotteryData = 227,
	LotteryResult = 228,
	HideAndSeekHallResult = 229,
	EntityColorfulTime = 230,
	EntitySelected = 231,
	SyncPlayerSetSpYaw = 232,
	EntityDisableMoveTime = 233,
	SyncEffectGunFire = 234,
	SyncEffectGunFireAtEntityResult = 235,
	SyncEffectGunFireAtBlockResult = 236,
	SyncEffectGunFireExplosionResult = 237,
	StopLaserGun = 238,
	LogicSettingInfo = 239,
	EnableAutoShoot = 240,
	Disarmament = 241,
	SetPlayerOpacity = 242,
	NotifyGetGoods = 243,
	PlayerNamePerspective = 244,
	AddEntityFeature = 245,
	SyncEntityFeature = 246,
	SyncEntityBulletin = 247,
	SyncEntityBird = 248,
	SyncPlayerBagInfo = 249,
	SyncBirdStore = 250,
	SyncBirdPersonalStore = 251,
	SyncBirdBag = 252,
	SyncBirdPlayerInfo = 253,
	SyncBirdDress = 254,
	SyncBirdFood = 255,
	SyncBirdTask = 256,
	SyncBirdAtlas = 257,
	BirdGain = 258,
	BirdNestOperation = 259,
	SyncBirdScope = 260,
	SyncBirdActivity = 261,
	BirdLotteryResult = 262,
	SyncEntityAction = 263,
	SyncBirdTimePrice = 264,
	BirdAddScore = 265,
	SyncBirdBuff = 266,
	SyncEntityHealth = 267,
	SyncBirdSimulatorStoreItem = 268,
	SyncBirdSimulatorTaskItem = 269,
	SyncBirdSimulatorPersonStoreTab = 270,
	BirdAddMessage = 271,
	ChangeGuideArrowStatus = 272,
	AddWallText = 273,
	DeleteWallText = 274,
	SetPlayerGlide = 275,
	ShowAddCarryGuide = 276,
	BirdCheckinData = 277,
	ShowBirdFeedGuide = 278,
	BirdShowWingTip = 279,
	DefaultNotification = 280,
	NotifyKills = 281,
	SupplyTip = 282,
	KeepItemAndReviveCountDown = 283,
	ActorNpcSuspended = 286,
	ActorNpcHeadInfoMultilang = 287,
	ChangeApple = 288,
	ChangeQuicklyBuildBlockStatus = 289,
	AppleFresh = 290,
	PickUpEntityItem = 291,
	PlayingSelectableAction = 292,
	AllowUseItemStatus = 293,
	UpdateSelectableAction = 294,
	AppItemsSettingInfo = 295,
	UpdateGuideData = 298,
	BedWarHallLackChipTip = 299,
	AttackScore = 301,
	PlayerActionArea = 302,
	SyncEntityDecoration = 303,
	SyncTakeDecoration = 304,
	SyncBlockCityManorManager = 305,
	SyncBlockCityPlayerInfo = 306,
	ShowBlockCityCommonTip = 307,
	SyncBlockCityStore = 308,
	SyncBlockCityManorInfo = 309,
	SyncBlockCityBuyLackItems = 310,
	BlockCityStorageOperation = 311,
	ShowRotateView = 312,
	UpdateBlockCityItems = 313,
	CommonTip = 314,
	SyncClientPeerProp = 315,
	PlaceBlocks = 316,
	CraftItemUpdate = 317,
	ShowSkyBlockInfo = 318,
	UpdateSkyBlockMainLineTaskData = 319,
	SkyBlockDareTaskInfo = 320,
	ContentTipMsg = 321,
	UpdateFurnaceTime = 322,
	ShowSkyShopInfo = 323,
	SynSellItemSuc = 324,
	SetMoveState = 325,
	SkyBlockRankData = 326,
	CanUseItemBucket = 327,
	SceneSettingInfo = 328,
	SceneSettingSwitch = 329,
	ShowUpdateProductInfo = 330,
	SkyBlockShowAppShopPage = 331,
	NotifyGetGoodsByItemId = 332,
	//StopSound = 333,  --support the old version, temporarily reserved
	SyncBlockFortManorInfo = 334,
	ShowFlotTip = 335,
	SyncBlockFortManorManager = 336,
	SyncBlockFortPlayerInfo = 337,
	SyncBlockFortStore = 338,
	UpdateBlockFortItems = 339,
	ShowBlockFortBuildingInfo = 340,
	SyncBlockCityArchive = 341,
	SyncBlockCityManorArea = 342,
	SetPlayerElevator = 343,
	SyncBlockCityPackTab = 344,
	SyncBlockCityElevatorArea = 345,
	SyncBlockCityHouseShop = 346,
	SyncBlockCityWeekReward = 347,
	DBDataReady = 348,
	SyncCreatureTargetId = 349,
	SyncBindEntity = 350,
	SyncUnbindEntity = 351,
	SyncEntityConnection = 352,
	RemoveSimpleEffect = 353,
	OpenCraftTable = 354,
	SyncUserRelation = 356,
	SyncGameWeather = 357,
	SyncPlayerSprintChanged = 358,
	SpawnEntityItem = 359,
	ProtocolEnd
};

constexpr  S2CPacketType operator -(S2CPacketType type, int  i)
{
	return static_cast<S2CPacketType>(static_cast<int>(type) - i);
}

constexpr  S2CPacketType operator +(S2CPacketType type, int  i)
{
	return static_cast<S2CPacketType>(static_cast<int>(type) + i);
}


enum class C2SPacketType : uint16_t
{
	ProtocolBegin = 0,
	None = 1,
	Login = 2,
	Logout = 3,
	ClientReady = 4,
	Attack = 5,
	Animate = 6,
	PlayerMovement = 7,
	VehicleMovement = 8,
	Rebirth = 9,
	PlayerAction = 10,
	CraftWithCraftingTable = 11,
	CraftWithHand = 12,
	SwapItemPosition = 13,
	DropItemPosition = 14,
	EquipArmor = 15,
	UnequipArmor = 16,
	ChangeItemInHand = 17,
	ChangeCurrentItem = 18,
	UseItem = 19,
	StartBreakBlock = 20,
	AbortBreakBlock = 21,
	FinishBreakBlock = 22,
	PlaceBlock = 23,
	ChatMessageString = 24,
	ChatMessageTranslation = 25,
	ActivateBlock = 26,
	ExchangeItemStack = 27,
	UseProp = 28,
	Ping = 29,
	LaunchArrow = 30,
	LaunchBullet = 31,
	SpawnVehicle = 32,
	GunFireResult = 33,
	CloseContainer = 34,
	UseThrowableItem = 35,
	SplashPotion = 36,
	SetFlying = 37,
	BuyCommodity = 38,
	TakeVehicle = 39,
	GunShootTarget = 40,
	ReloadBullet = 41,
	BuyGoods = 42,
	//ResumeOrder = 43,
	SelectRole = 44,
	BuyVehicle = 45,
	LockVehicle = 46,
	VehicleAction = 47,
	BuyRespawn = 48,
	GoNpcMerchant = 49,
	ClickTeleport = 50,
	LeaveAircraft = 51,
	ChangeClothes = 52,
	RestClothes = 53,
	FriendOperation = 54,
	SetParachute = 55,
	SkillType = 56,
	ChangePlayerActor = 57,
	ClickChangeActor = 58,
	CameraLockMovement = 59,
	CameraLock = 60,
	PickUpItemPay = 61,
	AttackActorNpc = 62,
	GetManor = 63,
	SellManor = 64,
	UpgradeManor = 65,
	BuyHouse = 66,
	BuyFurniture = 67,
	DeleteManorMessage = 68,
	BuildHouse = 69,
	PutFurniture = 70,
	RecycleFurniture = 71,
	ManorTeleport = 72,
	CallOnManor = 73,
	GiveRose = 74,
	RequestUpdateRealTimeRank = 75,
	BuySwitchableProp = 76,
	BuyUpgradeProp = 77,
	AttackCreatureEntity = 78,
	UpgradeResource = 79,
	WatchRespawn = 80,
	MovementInput = 81,
	SendJumpChanged = 82,
	SendPlayerRotation = 83,
	SendDownChanged = 84,
	NeedUpdateMerchantCommodities = 85,
	SyncCustomTipResult = 86,
	RelaseItemSkill = 87,
	BuildWarOpenShop = 88,
	BuildWarGrade = 89,
	BuildWarOpenGuessResult = 90,
	BuildWarGuessVisit = 91,
	BuildWarGuessSuc = 92,
	BuildWarShowResult = 93,
	GetCommodity = 94,
	UnlockCommodity = 95,
	BreakBlockInstantly = 96,
	PlayerInteractionActionMesage = 97,
	AttackEntity = 98,
	BuyEnchantmentProp = 99,
	ConsumeTipResult = 100,
	BuySuperProp = 101,
	BuyCustomProp = 102,
	ClickBackHall = 103,
	LongHitEntity = 104,
	UseFishingRod = 105,
	UseCannon = 106,
	UpdateUserMoney = 107,
	BuyBullet = 108,
	RanchBuyItem = 109,
	RanchBuyBuildItem = 110,
	RanchOperation = 111,
	RanchReceive = 112,
	RanchExpand = 113,
	RanchShortcut = 114,
	RanchDestroyHouse = 115,
	RanchSellItem = 116,
	RanchBuyItems = 117,
	RanchBuildTakeProduct = 118,
	RanchBuildQueueOperation = 119,
	RanchBuildRemove = 120,
	RanchOrderOperate = 121,
	RanchExBegin = 122,
	RanchExTaskFinish = 123,
	RanchGiftsOrInvite = 124,
	RanchHelpFinish = 125,
	ReceiveMailReward = 126,
	ReceiveRanchAchievementReward = 127,
	RanchGoExplore = 128,
	ChangeCurrentItemInfo = 129,
	SpeedUpCrop = 130,
	UseCubeFinshOrder = 131,
	BuyFlyingPermissionResult = 132,
	ResetCloseup = 133,
	KeepItem = 134,
	OpenEnchantMent = 135,
	EnchantmentEffectClick = 136,
	EnchantmentQuick = 137,
	SelectLottery = 138,
	LotteryAgain = 139,
	HallLotteryAgain = 140,
	SetSpYaw = 141,
	EffectGunFire = 142,
	EffectGunFireResult = 143,
	EffectGunFireExplosionResult = 144,
	StopLaserGun = 145,
	ConsumeBullet = 146,
	BirdBagOperation = 147,
	BirdStoreOperation = 148,
	BirdPersonalStoreBuyGoods = 149,
	BirdFuse = 150,
	BirdOpenTreasureChest = 151,
	BirdLottery = 152,
	BirdTask = 153,
	BirdFeed = 154,
	BirdSetDress = 155,
	GlideOperation = 156,
	BirdOpenEggChest = 157,
	BirdCheckin = 158,
	BuyQuicklyBuildBlock = 160,
	PlayingSelectableAction = 161,
	UpdateUserSelectableAction = 162,
	SendGuideInfo = 163,
	WatchAdFinished = 164,
	PlaceSchematic = 165,
	FormulationSubmit = 166,
	RemoveItemPosition = 167,
	RechgargeResult = 168,
	ClientCommonData = 169,
	SkyBlockProductNpc = 170,
	SyncVehicleInput = 171,
    VehicleHornSoundSource = 172,
	SkyBlockOpenGame = 173,
	BindEntity = 174,
	UnbindEntity = 175,
	FlyingMountMovement = 176,
	FloatingMountMovement = 177,
	PlayerSprintChanged = 178,
	ProtocolEnd
};

constexpr  C2SPacketType operator -(C2SPacketType type, int  i)
{
	return static_cast<C2SPacketType>(static_cast<int>(type) - i);
}

constexpr  C2SPacketType operator +(C2SPacketType type, int  i)
{
	return static_cast<C2SPacketType>(static_cast<int>(type) + i);
}

class DataPacket : public LORD::ObjectAlloc
{

public:
	enum PacketChannel // 不同的Channel 采用不同的 PRIORITY.暂时只支持3个等级的PRIORITY.所以只支持3种Channel，超过三种需要改Raknet。
	{
		emNormal = 1,
		emMapData = 2
	};

public:
	DataPacket(void) {};
	virtual ~DataPacket(void) {};

	virtual ui16  pid() const { return 0; };
	virtual int  channel() const { return 0; }
	virtual bool isConnEvent() { return false; }

	virtual void encode(RakNet::BitStream*) const {};
	virtual void decode(RakNet::BitStream*) {};

	void    setSender(ui64 ssid) { this->m_sender = ssid; }
	ui64    getSender() const { return m_sender; }
private:

	ui64  m_sender = 0;
};
#endif
