---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jimmy.
--- DateTime: 2019/9/20 0020 10:57
---

local dialog = nil

local function getChildWindow(window, name, type)
    local child = window:getChildWindow(name, type)
    if not child then
        error("CustomDialog must have" .. name .. " child window.")
    end
    return child
end

local GUICustomDialog = class("GUICustomDialog", IGUILayout)

function GUICustomDialog:onLoad()
    self.contents = {}
    self.contentView = nil
    self.customParams = nil
    self.leftClickListener = nil
    self.rightClickListener = nil
    self.closeClickListener = nil
    local name = string.gsub(self.__name, ".json", "-")
    self.llContent = getChildWindow(self, name .. "Content", GUIType.Layout)
    self.tvTitleText = getChildWindow(self, name .. "Title-Text", GUIType.StaticText)
    self.btnClose = getChildWindow(self, name .. "Close", GUIType.Button)
    self.tvContentText = getChildWindow(self, name .. "Content-Text", GUIType.StaticText)
    self.ivExtraIcon = getChildWindow(self, name .. "Extra-Icon", GUIType.StaticImage)
    self.tvExtraText = getChildWindow(self, name .. "Extra-Text", GUIType.StaticText)
    self.btnLeftButton = getChildWindow(self, name .. "Left-Button", GUIType.Button)
    self.ivLeftIcon = getChildWindow(self, name .. "Left-Icon", GUIType.StaticImage)
    self.btnRightButton = getChildWindow(self, name .. "Right-Button", GUIType.Button)
    self.ivRightIcon = getChildWindow(self, name .. "Right-Icon", GUIType.StaticImage)
    self.btnClose:registerEvent(GUIEvent.ButtonClick, function()
        if self.closeClickListener then
            self.closeClickListener()
        end
        self:hide()
        SoundUtil.playSound(SoundType.ClosePanel)
    end)
    self.btnLeftButton:registerEvent(GUIEvent.ButtonClick, function()
        if self.leftClickListener ~= nil then
            local close = self.leftClickListener() ---返回true拦截dialog不关闭
            if not close then
                self:hide()
            end
        else
            self:hide()
        end
        SoundUtil.playSound(SoundType.ClosePanel)
    end)
    self.btnRightButton:registerEvent(GUIEvent.ButtonClick, function()
        if self.rightClickListener ~= nil then
            local close = self.rightClickListener() ---返回true拦截dialog不关闭
            if not close then
                self:hide()
            end
        else
            self:hide()
        end
        SoundUtil.playSound(SoundType.ClosePanel)
    end)
    self.leftButtonPos = self.btnLeftButton:GetXPosition()
    self.leftIconPos = self.ivLeftIcon:GetXPosition()
    self.rightButtonPos = self.btnRightButton:GetXPosition()
    self.rightIconPos = self.ivRightIcon:GetXPosition()
end

function GUICustomDialog:setDefault()
    self.customParams = nil
    self.leftClickListener = nil
    self.rightClickListener = nil
    self.closeClickListener = nil
    self.tvTitleText:SetText(Lang:getString("gui_dialog_tip_title_tip"))
    self.btnClose:SetVisible(true)
    self.tvContentText:SetText("")
    self.ivExtraIcon:SetVisible(false)
    self.ivLeftIcon:SetVisible(false)
    self:setLeftText(Lang:getString("gui_dialog_tip_btn_cancel"))
    self:setLeftDisable(true)

    self.ivLeftIcon:SetArea({ 0, 15 }, { 0, 0 }, { 0, 34 }, { 0, 38 })

    self.ivRightIcon:SetVisible(false)
    self:setRightText(Lang:getString("gui_dialog_tip_btn_sure"))
    self.disableTime = 0
    if self.contentView ~= nil then
        self.contentView:hide()
        self.contentView = nil
    end
    if self.hideTimer then
        LuaTimer:cancel(self.hideTimer)
    end
    if self.disableTimer then
        LuaTimer:cancel(self.disableTimer)
    end
end

function GUICustomDialog:hide()
    self.disableTime = self.disableTime or 0
    if self.disableTime > 0 then
        print("GUICustomDialog:hide " .. self.disableTime)
        return
    end
    if self:isAlwaysShow() then
        return
    end
    if self:isShow() then
        self.root:SetVisible(false)
        self:onHide()
    end
end

function GUICustomDialog:onHide()
    self:setDefault()
end

function GUICustomDialog:builder()
    self:setDefault()
end

function GUICustomDialog:setContentView(view)
    self.contentView = self.contents[view.__name]
    if self.contentView ~= nil then
        self.contentView:show()
    else
        HostApi.log("GUICustomDialog [can't find content view --- name:" .. view.__name .. "]", 1)
    end
end

local function setButtonUI(button, icon, iconPos)
    if not button:IsVisible() then
        return
    end
    local oldOffsetY = button:GetRenderOffset()
    if icon:IsVisible() then
        local offset = icon:GetPixelSize().x / 2
        button:SetRenderOffset({ x = offset, y = oldOffsetY })
        if #button:GetText() == 0 then
            icon:SetHorizontalAlignment(HorizontalAlignment.Center)
            icon:SetXPosition({ 0, 0 })
        else
            icon:SetHorizontalAlignment(HorizontalAlignment.Left)
            icon:SetXPosition(iconPos)
        end
    else
        button:SetRenderOffset({ x = 0, y = oldOffsetY })
    end
end

function GUICustomDialog:setUI()
    if self.btnLeftButton:IsVisible() and self.btnRightButton:IsVisible() then
        self.btnLeftButton:SetHorizontalAlignment(HorizontalAlignment.Left)
        self.btnLeftButton:SetXPosition(self.leftButtonPos)
        self.btnRightButton:SetHorizontalAlignment(HorizontalAlignment.Right)
        self.btnRightButton:SetXPosition(self.rightButtonPos)
    elseif self.btnLeftButton:IsVisible() then
        self.btnLeftButton:SetHorizontalAlignment(HorizontalAlignment.Center)
        self.btnLeftButton:SetXPosition({ 0, 0 })
    elseif self.btnRightButton:IsVisible() then
        self.btnRightButton:SetHorizontalAlignment(HorizontalAlignment.Center)
        self.btnRightButton:SetXPosition({ 0, 0 })
    end
    setButtonUI(self.btnLeftButton, self.ivLeftIcon, self.leftIconPos)
    setButtonUI(self.btnRightButton, self.ivRightIcon, self.rightIconPos)
    if self.contentView ~= nil then
        self.tvContentText:SetText("")
        self.ivExtraIcon:SetVisible(false)
    end
end

function GUICustomDialog:setLeftText(text)
    if not text or #text == 0 then
        self.btnLeftButton:SetText("")
        self.btnLeftButton:SetVisible(self.ivLeftIcon:IsVisible())
    else
        self.btnLeftButton:SetVisible(true)
        self.btnLeftButton:SetText(Lang:getString(text))
    end
end

function GUICustomDialog:setRightText(text)
    if not text or #text == 0 then
        self.btnRightButton:SetText("")
        self.btnRightButton:SetVisible(self.ivRightIcon:IsVisible())
    else
        self.btnRightButton:SetVisible(true)
        self.btnRightButton:SetText(Lang:getString(text))
    end
end

function GUICustomDialog:setLeftDisable(value)
    if self.btnLeftButton then
        self.btnLeftButton:SetEnabled(value)
    end
end

function GUICustomDialog:setLeftIconArea(x, y, w, h)
    self.ivLeftIcon:SetArea(x, y, w, h)
end

CustomDialog = {}

---构造一个初始化状态的自定义对话框
function CustomDialog.builder()
    dialog:builder()
    return CustomDialog
end

---设置对话框标题(默认是：提示)
---@text string 标题多语言或标题
function CustomDialog.setTitleText(title)
    dialog.tvTitleText:SetText(Lang:getString(title))
    return CustomDialog
end

---设置对话框详情内容
---详情内容不会自动转成多语言，需自己设置
---@content  string 文字内容
function CustomDialog.setContentText(content)
    dialog.tvContentText:SetText(content)
    return CustomDialog
end

---设置对话框自定义详情显示的view
---@view IGUILayout 自定义内容体
function CustomDialog.setContentView(view)
    dialog:setContentView(view)
    return CustomDialog
end

---设置对话框关闭按钮是否可见(默认是可见的)
---@visible bool 是否可见
function CustomDialog.setCloseVisible(visible)
    dialog.btnClose:SetVisible(visible)
    return CustomDialog
end

---设置对话框额外信息图片和文字(默认不可见)
---@image string 图片名称
---@text string 文字多语言或文字
function CustomDialog.setExtraInfo(image, text)
    dialog.ivExtraIcon:SetVisible(true)
    dialog.ivExtraIcon:SetImage(image)
    dialog.tvExtraText:SetText(Lang:getString(text))
    return CustomDialog
end

---设置对话框左按钮图片(默认不可见)
---@image string 图片名称
function CustomDialog.setLeftIcon(image)
    dialog.ivLeftIcon:SetVisible(true)
    dialog.ivLeftIcon:SetImage(image)
    return CustomDialog
end

---设置对话框左按钮背景
---@image string 图片名称
function CustomDialog.setLeftButtonImage(image)
    dialog.btnLeftButton:SetNormalImage(image)
    dialog.btnLeftButton:SetPushedImage(image)
    return CustomDialog
end

---设置对话框左按钮文字
---@text string 文字多语言或文字
function CustomDialog.setLeftText(text)
    dialog:setLeftText(text)
    return CustomDialog
end

function CustomDialog.setLeftDisable(value)
    dialog:setLeftDisable(value)
    return CustomDialog
end

function CustomDialog.setLeftIconArea(x, y, w, h)
    dialog:setLeftIconArea(x, y, w, h)
    return CustomDialog
end
---设置对话框右按钮图片(默认不可见)
---@image string 图片名称
function CustomDialog.setRightIcon(image)
    dialog.ivRightIcon:SetVisible(true)
    dialog.ivRightIcon:SetImage(image)
    return CustomDialog
end

---设置对话框右按钮背景
---@image string 图片名称
function CustomDialog.setRightButtonImage(image)
    dialog.btnRightButton:SetNormalImage(image)
    dialog.btnRightButton:SetPushedImage(image)
    return CustomDialog
end

---设置对话框右按钮文字
---@text string 文字多语言或文字
function CustomDialog.setRightText(text)
    dialog:setRightText(text)
    return CustomDialog
end

---设置对话框左按钮点击监听
---@listener function 监听回调函数
function CustomDialog.setLeftClickListener(listener)
    dialog.leftClickListener = listener
    return CustomDialog
end

---设置对话框右按钮点击监听
---@listener function 监听回调函数
function CustomDialog.setRightClickListener(listener)
    dialog.rightClickListener = listener
    return CustomDialog
end

function CustomDialog.setCloseClickListener(listener)
    dialog.closeClickListener = listener
    return CustomDialog
end

---设置显示时间
---@time s 显示时间
function CustomDialog.setShowTime(time, showCountDown)
    dialog.countDownTime = time

    dialog.hideTimer = LuaTimer:scheduleTimer(function()
        if dialog.countDownTime <= 0 then
            dialog:hide()
            return
        end
        if showCountDown then
            dialog:setRightText(string.format("%s(%d)",
                    Lang:getString("gui_dialog_tip_btn_sure"), dialog.countDownTime))
        end
        dialog.countDownTime = dialog.countDownTime - 1
    end, 1000, time + 1)

    return CustomDialog
end

---设置不能点击时间
---@time s 时间
function CustomDialog.setDisableTime(time)
    dialog.disableTime = time

    dialog.disableTimer = LuaTimer:schedule(function()
        if dialog.disableTime <= 0 then
            if dialog.disableTimer then
                LuaTimer:cancel(dialog.disableTimer)
            end
            return
        end
        dialog.disableTime = dialog.disableTime - 1
    end, 0, 1000)

    return CustomDialog
end

---显示对话框
function CustomDialog.show()
    dialog:setUI()
    dialog:show()
    SoundUtil.playSound(SoundType.OpenPanel)
end

---关闭对话框
function CustomDialog.hide()
    dialog:hide()
end

function CustomDialog.setCustomParams(customParams)
    dialog.customParams = customParams
    return CustomDialog
end

function CustomDialog.getCustomParams()
    return dialog.customParams
end

function CustomDialog.isShow()
    if not dialog then
        return false
    end
    return dialog:isShow()
end

---设置对话框(隐藏左按钮，右按钮且居中)
function CustomDialog.setHideLeftButton()
    dialog.btnLeftButton:SetVisible(false)
    dialog.btnRightButton:SetHorizontalAlignment(HorizontalAlignment.Center)
    dialog.btnRightButton:SetXPosition({ 0, 0 })
    return CustomDialog
end

---设置对话框(隐藏右按钮，左按钮且居中)
function CustomDialog.setHideRightButton()
    dialog.btnRightButton:SetVisible(false)
    dialog.btnLeftButton:SetHorizontalAlignment(HorizontalAlignment.Center)
    dialog.btnLeftButton:SetXPosition({ 0, 0 })
    return CustomDialog
end

---设置对话框是否显示在最前
function CustomDialog.setAlwaysOnTop(isTop)
    return dialog:setAlwaysOnTop(isTop)
end

---初始化对话框，可是设置使用的布局json
---@name 对话框的json文件名，默认CustomDialog.json
function initCustomDialog(name)
    if dialog ~= nil then
        return
    end
    dialog = GUICustomDialog.new(name)
end

---构造一个自定义对话框内容体
---@class 内容体的类名，必须继承IGUILayout
---@name 内容体的json文件名
function buildCustomDialogContent(class, name)
    local content = class.new(name, dialog.llContent)
    content:hide()
    dialog.contents[name] = content
    return content
end
