---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/9/4 16:51
---
local UIFriendsFollowTip = class("UIFriendsFollowTip", IGUILayout)

function UIFriendsFollowTip:onLoad()
    self.stText = self:getChildWindow("FriendsFollowTip-Text", GUIType.StaticText)
    self.stClose = self:getChildWindow("FriendsFollowTip-Close", GUIType.Button)

    self:register()
end

function UIFriendsFollowTip:register()
    self.stClose:registerEvent(GUIEvent.ButtonClick, function()
        LuaTimer:cancel(self.key)
        self:hide()
    end)

    self:registerDataCallBack("WatcherInfo", function(name)
        self:onGetFollowerInfo(name, "Watcher")
    end)

    self:registerDataCallBack("FollowerInfo", function(name)
        self:onGetFollowerInfo(name, "Follow")
    end)
end

function UIFriendsFollowTip:onShow()
    LuaTimer:cancel(self.key or 0)
    self.key = LuaTimer:schedule(function()
        self:hide()
    end, 10000)
end

function UIFriendsFollowTip:onGetFollowerInfo(name, followType)
    local nameString
    if followType == "Watcher" then
        nameString = Lang:getString("user_watch_game")
    elseif followType == "Follow" then
        nameString = Lang:getString("user_follow_join_game")
    end
    local text = string.gsub(nameString, "{}", name)
    local width = math.max(self.stText:GetFont():GetTextExtent(text, 1) + 30, 450)
    self.root:SetWidth({ 0, width })
    self.stText:SetText(text)
    self:show()
end

function UIFriendsFollowTip:isIgnoreLock()
    return true
end

return UIFriendsFollowTip