#圣诞活动结束时间戳
christmasFinishTime: 4102470000

#饥饿扣血[值,时间间隔]
hungerSubHP: [2,5]

#满饱食度回血[回血值,扣饱食度值,饱食度回血最低值（配0会触发饥饿扣血）,每隔几秒扣食和回血###最好都配整数]
maxFoodAddHp: [4,1,16,1]

#初始血量
initHP : 40

#矿区初始位置和朝向
initPos : [91.5, 51, 145.5, 180]

#矿区地图刷新时间（秒）
map_resetCD : 1200

#一堆金钱的数量
monetaryUnit: 200

#死亡掉落物品随机散开半径
drop_radius: 1

#矿区刷新前几秒倒计时提示(配置小于30）
map_resetTip : 5

#矿洞文字提示
hintText:
    -
        #pvp区域多语言位置
        pos: [91.5, 54, 88.5]
        #文字朝向
        yaw: 180
        #文字多语言
        text: "gui_pvp"
        #文字缩放比例
        scale: 4
    -
        pos: [91.5, 55, 102.5]
        yaw: 0
        text: "gui_safe"
        scale: 4
    -
        pos: [124.5, 55, 53.5]
        yaw: 270
        text: "gui_underground_palace"
        scale: 4
#岩浆秒伤系数
lavaDamageCoe: 0.15

#岩浆着火时间
lavaFireTime: 6

#燃烧伤害
onFireDamage: 1

#可破坏区域
canBreakArea :
    #startPos为XYZ的最小值
    #endPos  为XYZ的最大值
    #区域数量不限，少增多删
    #区域1
    -
        startPos: [83, 41, 113]
        endPos: [100, 51, 128]
    #区域2
    -
        startPos: [83, 41, 46] 
        endPos: [100, 51, 61]
#pve区域
pvpArea :
    -
        #XYZ的最小值
        pvpStartPos: [56, 39, 88]
        #XYZ的最大值
        pvpEndPos: [119, 77, 152]
        
#刷新任务
refreshDareTask:
    -
        coinId: 1 
        coinNum: 3
        msg: "refresh_dare_task_cost_money"
        nextTime: 14400    #多少时间刷新1次
        freeTimes: 1    #最多可攒多少次数
#购买任务完成次数
buyDaretask:
    -
        coinId: 1
        coinNum: 1      #购买价格
        buyMsg: "buy_dare_task_times_cost_money"
        maxTimes: "buy_dare_task_times_cost_money" 
        initCount: 6    #每天可完成数量上限
        
#宝箱刷新倒计时（秒）
chestCD: 7200

#宝箱刷新倒计时与宝箱的相对高度
chestCDHeight: 5

#宝箱刷新地点
chestPos :
    -
        Pos1: [231, 30, 104]
    -
        Pos2: [250, 29, 125]
    -
        Pos3: [225, 31, 179]
        
#宝箱物品
chestItems:
    -
        id: 511
        num: 1
        meta: 0

#宝箱（自带带闪光）Actor
chestActor: g1048_chest.actor

#宝箱打开时播放的特效
chestOpenEffect : g1008_chestopen2.effect

#宝箱刷新处带有特效的Actor
chestPosActor: g1048_chest_pos.actor

#宝箱附近可以点击范围
clickRange: 2

#箭头引导位置
ArrowPos: [92, 51, 97]

#取消箭头引导范围半径
cancelArrowRadius: 2

#回家按钮冷却时间
backHomeCD: 3

#向前弹方块坐标
flipFront:
    -
        id: 1
        pos: [242, 30, 169]
    -
        id: 2
        pos: [241, 30, 169]
    -
        id: 3
        pos: [239, 30, 169]
    -
        id: 4
        pos: [242, 30, 168]
    -
        id: 5
        pos: [239, 30, 168]
    -
        id: 6
        pos: [238, 30, 168]
    -
        id: 7
        pos: [241, 30, 167]
    -
        id: 8
        pos: [240, 30, 167]
    -
        id: 9
        pos: [238, 30, 167]
    -
        id: 10
        pos: [237, 30, 167]
    -
        id: 11
        pos: [242, 30, 169]
    -
        id: 12
        pos: [240, 29, 140]
    -
        id: 13
        pos: [240, 29, 141]
    -
        id: 14
        pos: [240, 29, 142]
    -
        id: 15
        pos: [236, 31, 119]
    -
        id: 16
        pos: [235, 31, 119]
    -
        id: 17
        pos: [234, 31, 119]
    -
        id: 18
        pos: [233, 31, 119]
    -
        id: 19
        pos: [178, 29, 115]
    -
        id: 20
        pos: [178, 29, 113]
    -
        id: 21
        pos: [180, 29, 115]
    -
        id: 22
        pos: [180, 29, 113]
    -
        id: 23
        pos: [176, 28, 142]
    -
        id: 24
        pos: [176, 28, 141]
    -
        id: 25
        pos: [176, 28, 140]
#向后弹方块坐标
flipBack:
    -
        id: 1
        pos: [240, 30, 169]
    -
        id: 2
        pos: [238, 30, 169]
    -
        id: 3
        pos: [241, 30, 168]
    -
        id: 4
        pos: [240, 30, 168]
    -
        id: 5
        pos: [237, 30, 168]
    -
        id: 6
        pos: [242, 30, 167]
    -
        id: 7
        pos: [239, 30, 167]
    -
        id: 8
        pos: [241, 29, 137]
    -
        id: 9
        pos: [241, 29, 138]
    -
        id: 10
        pos: [241, 29, 139]
    -
        id: 11
        pos: [241, 29, 140]
    -
        id: 12
        pos: [241, 29, 141]
    -
        id: 13
        pos: [241, 29, 142]
    -
        id: 14
        pos: [240, 29, 137]
    -
        id: 15
        pos: [240, 29, 138]
    -
        id: 16
        pos: [240, 29, 139]
    -
        id: 17
        pos: [239, 29, 140]
    -
        id: 18
        pos: [239, 29, 141]
    -
        id: 19
        pos: [239, 29, 142]
    -
        id: 20
        pos: [239, 29, 143]
    -
        id: 21
        pos: [226, 30, 126]
    -
        id: 22
        pos: [226, 30, 127]
    -
        id: 23
        pos: [226, 30, 128]
    -
        id: 24
        pos: [226, 30, 129]
    -
        id: 25
        pos: [226, 30, 130]
    -
        id: 26
        pos: [226, 30, 131]
    -
        id: 27
        pos: [226, 30, 132]
    -
        id: 28
        pos: [225, 30, 126]
    -
        id: 29
        pos: [225, 30, 127]
    -
        id: 30
        pos: [225, 30, 128]
    -
        id: 31
        pos: [225, 30, 129]
    -
        id: 32
        pos: [225, 30, 130]
    -
        id: 33
        pos: [225, 30, 131]
    -
        id: 34
        pos: [225, 30, 132]
    -
        id: 35
        pos: [224, 30, 126]
    -
        id: 36
        pos: [224, 30, 127]
    -
        id: 37
        pos: [224, 30, 128]
    -
        id: 38
        pos: [224, 30, 129]
    -
        id: 39
        pos: [224, 30, 130]
    -
        id: 40
        pos: [224, 30, 131]
    -
        id: 41
        pos: [224, 30, 132]
    -
        id: 42
        pos: [236, 31, 120]
    -
        id: 43
        pos: [235, 31, 120]
    -
        id: 44
        pos: [234, 31, 120]
    -
        id: 45
        pos: [233, 31, 120]
    -
        id: 46
        pos: [231, 31, 120]
    -
        id: 47
        pos: [230, 31, 120]
    -
        id: 48
        pos: [229, 31, 120]
    -
        id: 49
        pos: [228, 31, 120]
    -
        id: 50
        pos: [231, 31, 119]
    -
        id: 51
        pos: [230, 31, 119]
    -
        id: 52
        pos: [229, 31, 119]
    -
        id: 53
        pos: [228, 31, 119]
    -
        id: 54
        pos: [178, 29, 114]
    -
        id: 55
        pos: [179, 29, 114]
    -
        id: 56
        pos: [180, 29, 114]
    -
        id: 57
        pos: [179, 29, 115]
    -
        id: 58
        pos: [179, 29, 113]
    -
        id: 59
        pos: [175, 28, 138]
    -
        id: 60
        pos: [175, 28, 137]
    -
        id: 61
        pos: [175, 28, 136]
    -
        id: 62
        pos: [176, 28, 102]
    -
        id: 63
        pos: [176, 28, 139]
    -
        id: 64
        pos: [176, 28, 138]
    -
        id: 65
        pos: [176, 28, 137]
    -
        id: 66
        pos: [176, 28, 136]
    -
        id: 67
        pos: [177, 28, 142]
    -
        id: 68
        pos: [177, 28, 141]
    -
        id: 69
        pos: [177, 28, 140]
    -
        id: 70
        pos: [177, 28, 139]
    -
        id: 71
        pos: [177, 28, 138]
    -
        id: 72
        pos: [177, 28, 137]

#一次金魔方数量
onceBuyMoneyCost: 60

#最大数量：
maxBuyMoneyCost: 600

#一次购买的金币数量
onceMoneyNum: 100000