---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by JY-032.
--- DateTime: 2019/10/29 19:34
---


Define = {}

Define.JobType = {
    Card = 0,       --抽卡(入抽取界面)
    DefaultJob = 1, --默认职业
    PayJob = 2         --付费职业
}

return Define