---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangpq.
--- DateTime: 2019/12/28 14:57
---
TaskQueueManager = {}

local taskQueue = queue.new()

function TaskQueueManager:init()
    LuaTimer:cancel(self.updateTimer)
    self.updateTimer = LuaTimer:schedule(function()
        self:update()
    end, 0, 500)
end

function TaskQueueManager:addTask(task)
    if not task then
        return
    end

    if taskQueue:empty() then
        task:executeTask()
    end

    taskQueue:push(task)

    LogUtil.log("TaskQueueManager:addTask " .. taskQueue:size())
end

function TaskQueueManager:update()
    if not taskQueue then
        return
    end

    if taskQueue:empty() then
        return
    end

    local current = taskQueue:front()
    if current and current.taskFinished then
        taskQueue:pop()
        local next = taskQueue:front()
        if next then
            next:executeTask()
        end
    end

    LogUtil.log("TaskQueueManager:update " .. taskQueue:size())
end

function TaskQueueManager:destroy()
    LuaTimer:cancel(self.updateTimer)
    taskQueue:clear()
end

return TaskQueueManager