---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by JY-032.
--- DateTime: 2019/10/14 20:55
---
require "listener.GameListener"
require "listener.PlayerListener"
require "packet.S2CPacketHandler"

PluginMain = {}

function PluginMain:init()
    GameListener:init()
    PlayerListener:init()
    ClientHelper.putBoolPrefs("IsUseCustomArmor", true)
    ClientHelper.putBoolPrefs("IsShowTeamUI", false)
end

PluginMain:init()
return PluginMain