---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 10184.
--- DateTime: 2020/6/1 11:49
---
local Blocks = {}

local function init()
    local config = FileUtil.getConfigFromCsv("setting/BlockSetting.csv")
    for _, item in pairs(config) do
        local block = Blocks[item.BlockId] or { BreakToolIds = {} }
        if item.BreakToolId ~= "#" then
            table.insert(block.BreakToolIds, tonumber(item.BreakToolId))
        end
        Blocks[item.BlockId] = block
    end
end

init()

BlockConfig = {}

function BlockConfig:isCanBreakBlock(player, blockId)
    local block = Blocks[tostring(blockId)]
    if not block then
        return true
    end
    if #block.BreakToolIds == 0 then
        return true
    end
    local toolId = player:getHeldItemId()
    for _, _toolId in pairs(block.BreakToolIds) do
        if _toolId == toolId then
            return true
        end
    end
    return false
end