---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 10184.
--- DateTime: 2020/6/2 14:23
---
TeamGainType = {
    IronForge = "1001",
    ToolItem = "1002",
    ArmorItem = "1003",
    SwordItem = "1004",
    AddHP = "1005",
}

if isClient then
    return
end

require "game.gain.team.AddHPGain"
require "game.gain.team.ArmorItemGain"
require "game.gain.team.IronForgeGain"
require "game.gain.team.SwordItemGain"
require "game.gain.team.ToolItemGain"

local TeamGains = {
    [TeamGainType.IronForge] = IronForgeGain,
    [TeamGainType.ToolItem] = ToolItemGain,
    [TeamGainType.ArmorItem] = ArmorItemGain,
    [TeamGainType.SwordItem] = SwordItemGain,
    [TeamGainType.AddHP] = AddHPGain,
}

local function init()
    local config = FileUtil.getConfigFromYml("setting/TeamGainSetting")
    for _, item in pairs(config.TeamGains) do
        local class = TeamGains[item.Id]
        if class then
            class:init(item)
        end
    end
end

init()

GainsConfig = {}

function GainsConfig:getTeamGains()
    return TeamGains
end

function GainsConfig:onGameStart()
    for _, gain in pairs(TeamGains) do
        for _, team in pairs(GameMatch.Teams) do
            team.info:setValue(gain.id, gain.initLv)
        end
        if gain.onGameStart then
            gain:onGameStart()
        end
    end
end