---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/5/31 10:59
---

ResourcePointConfig = {}

local Config = {}
local ResourcePoint = {}

local function getProducePos(data, pointType)
    local rangePos = StringUtil.split(tostring(data), "#")
    if pointType == Define.ResourcePointType.Public then
        local posStr1 = StringUtil.split(tostring(rangePos[1]), ",")
        local pos1 = VectorUtil.newVector3(posStr1[1], posStr1[2], posStr1[3])
        return pos1
    elseif pointType == Define.ResourcePointType.Team then
        local posStr1 = StringUtil.split(tostring(rangePos[1]), ",")
        local posStr2 = StringUtil.split(tostring(rangePos[2]), ",")
        local pos1 = VectorUtil.newVector3(posStr1[1], posStr1[2], posStr1[3])
        local pos2 = VectorUtil.newVector3(posStr2[1], posStr2[2], posStr2[3])
        return pos1, pos2
    end
end

function ResourcePointConfig:init(config)
    for _, vConfig in pairs(config) do
        if tonumber(vConfig.mapId) == tonumber(GameConfig.mapId) then
            local data = {}
            data.id = tostring(vConfig.id)
            data.pointType = tonumber(vConfig.pointType)
            data.resourceList = StringUtil.split(tostring(vConfig.resourceList), "#")
            data.producePos1, data.producePos2 = getProducePos(vConfig.producePos, data.pointType)
            Config[data.id] = data

            if isClient and data.pointType == 1 then
                data.entityId = PublicResourceConfig:initNpcByConfig(data.id)
            end
        end
    end
end

function ResourcePointConfig:onGameStart()
    for _, data in pairs(Config) do
        if isClient and data.pointType == 1 then
            self:newPublicResourceTip(data, 1)
        end
    end
end

function ResourcePointConfig:UpgradeResource(pointId)
    if isClient and ResourcePoint[tostring(pointId)] == nil then
        local point = ClientTeamResource.new(pointId)
        ResourcePoint[tostring(pointId)] = point
    end
    ResourcePoint[tostring(pointId)]:onUpgrade()
end

function ResourcePointConfig:newPublicResourceTip(data, level)
    local typeConfig = ResourceTypeConfig:getConfigByType(data.resourceList[1])
    local tipTimes
    if typeConfig.levelUp[level + 1] == nil then
        tipTimes = 10000
    else
        tipTimes = math.ceil((typeConfig.levelUp[level + 1] - typeConfig.levelUp[level] )/ typeConfig.interval[level])
    end

    PublicResourceConfig:updateNpcHeadInfo(data.entityId, data.id, level, typeConfig.interval[level])
    LuaTimer:scheduleTimerWithEnd(function()
        PublicResourceConfig:updateNpcHeadInfo(data.entityId, data.id, level, typeConfig.interval[level])
    end, function()
        if typeConfig.levelUp[level + 1] ~= nil then
            self:newPublicResourceTip(data, level + 1)
        end
    end, 1000 * typeConfig.interval[level], tipTimes)
end

function ResourcePointConfig:getConfigById(id)
    return Config[tostring(id)]
end

function ResourcePointConfig:getAllConfig()
    return Config
end

function ResourcePointConfig:onPlayerIntoTeamResource(playerEntityId, pointId)
    if not ResourcePoint[tostring(pointId)] then
        return
    end
    ResourcePoint[tostring(pointId)]:onPlayerIntoResource(playerEntityId)
end

function ResourcePointConfig:onNotPlayerIntoResource(pointId)
    if not ResourcePoint[tostring(pointId)] then
        return
    end
    ResourcePoint[tostring(pointId)]:onNotPlayerIntoResource()
end

function ResourcePointConfig:setWatcherResource(data)
    for index, resourceData in pairs(data) do
        if ResourcePoint[tostring(index)] == nil then
            local point = ClientTeamResource.new(index)
            ResourcePoint[tostring(index)] = point
        end
        for item, level in pairs(resourceData.curLevel) do
            ResourcePoint[tostring(index)].curLevel[tostring(item)] = level
        end
        ResourcePoint[tostring(index)]:setSpawnLuaTimer()
    end
end

if GameConfig.mapId then
    ResourcePointConfig:init(FileUtil.getConfigFromCsv("setting/ResourcePoint.csv"))
end