---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangpq.
--- DateTime: 2019/9/17 10:32
---
local function hideEngineWindow(name)
    local window = GUIManager:getWindowByName(name)
    if not window then
        return
    end
    window:SetXPosition({ 100, 0 })
    window:SetVisible(false)
end

GameListener = {}

function GameListener:init()
    BaseListener.registerCallBack(GameReadyEvent, self.onGameReady)
    BaseListener.registerCallBack(SpawnEntityEvent, self.onSpawnEntity)
    BaseListener.registerCallBack(GameDestroyEvent, self.onGameDestroy)
    BaseListener.registerCallBack(GameInitEvent, self.onGameInit)

    Listener.registerCallBack(ClickSceneEvent, self.onClickScene)
    Listener.registerCallBack(ClickScenePlayActionEvent, self.onClickScenePlayAction)
    Listener.registerCallBack(LongTouchSceneEvent, self.onLongTouchScene)
    Listener.registerCallBack(CatchEntityEvent, self.onCatchEntity)
    Listener.registerCallBack(SyncBindEntityEvent, self.onSyncBindEntity)
    Listener.registerCallBack(SyncUnbindEntityEvent, self.onSyncUnbindEntity)
    Listener.registerCallBack(ClientCmdEvent, self.onClientCmd)
    Listener.registerCallBack(ClickSceneToControllerEvent, self.onClickSceneToController)
    Listener.registerCallBack(GamePauseEvent, self.onGamePause)
    Listener.registerCallBack(GameResumeEvent, self.onGameResume)
    Listener.registerCallBack(AddDiamondEvent, self.onAddDiamond)
    Listener.registerCallBack(DBDataReadyEvent, self.onDBDataReady)
end

function GameListener.onDBDataReady()
    LogUtil.log("LiftingSimulator GameListener.onDBDataReady")
    PlayerManager:getClientPlayer():setIgnoreFrustumCheck(true)
end

function GameListener.onGameReady()
    GameConfig:loadConfig()
    require "ui.GUIFactory"

    PlayerManager:getClientPlayer():setRenderDistanceWeight(CommonConfig.renderDistanceWeight)

    Blockman.Instance():switchPerspece()
    GameListener.initController()

    --默认使用摇杆
    GameClient.poleControlState = Blockman.Instance().m_gameSettings.usePole
    LogUtil.log("GameClient.poleControlState " .. GameClient.poleControlState)
    Utility.refreshPoleControlState(1)
    TextureAtlasRegister.Instance():addTextureAtlas("LSCountdown1.json", "")
    TextureAtlasRegister.Instance():addTextureAtlas("LSCountdown2.json", "")
    for i = 0, 5 do
        WorldImageRender.Instance():addImageRender("LSCountdown1.json", 6, tostring(i), string.format("number_6_%d", i))
    end
    for i = 6, 9 do
        WorldImageRender.Instance():addImageRender("LSCountdown2.json", 6, tostring(i), string.format("number_6_%d", i))
    end
    hideEngineWindow("Main-MoveState")
    hideEngineWindow("Main-ToggleInventoryButton")
    hideEngineWindow("PlayerInfo")
end

function GameListener.onGamePause()
    GameClient.gamePauseStartTime = os.time()
end

function GameListener.onGameResume()
    if GameClient.gamePauseStartTime ~= 0 then
        GameClient.gamePauseTime = os.time() - GameClient.gamePauseStartTime

        if nextAreaEventCd > 0 then
            nextAreaEventCd = nextAreaEventCd - GameClient.gamePauseTime
        end

        if areaEventCd > 0 then
            areaEventCd = areaEventCd - GameClient.gamePauseTime
        end

        GameClient.gamePauseTime = 0
    end
    LogUtil.log("GameListener.onGameResume " .. GameClient.gamePauseTime)
end

function GameListener.onClickScene()
    return MainControlController:onClickScene(false)
end

function GameListener.onClickScenePlayAction()
    return MainControlController:onClickScenePlayAction()
end

function GameListener.onLongTouchScene()
    return false
end

function GameListener.initController()
    MainControlController:init()
end

--return false会被过滤掉
function GameListener.onCatchEntity(entityPlayerSPMP, entity, entityType)
    if entityPlayerSPMP == nil then
        return false
    end

    entity = DynamicCast.dynamicCastEntity(entityType, entity)
    if not entity then
        return false
    end
    if entity:isEntityAlive() == false then
        --print("GameListener.onCatchEntity Dead")
        return false
    end
    if EntityDefine:isPlayer(entityType) then
        if entity:isGrab() or entity:getBoolProperty("Invincible") then
            return false
        else
            local muscleMassA = entityPlayerSPMP:getDoubleProperty("muscleMass")
            local muscleMassB = entity:getDoubleProperty("muscleMass")
            LogUtil.log(string.format("GameListener.onCatchEntity %f %f", muscleMassA, muscleMassB))
            return muscleMassA * GameConfig.grabCoe1 >= muscleMassB * GameConfig.grabCoe2
        end
    else
        if entityType ~= EntityType.ActorNpc then
            return
        end
        local player = PlayerManager:getClientPlayer()
        local weight = entity:getWeight()
        if weight == "-1" then
            return false
        end
        local result = BigNum.new(player.property.muscleMass) >= BigNum.new(string.format("%f", weight))
        --print("GameListener.onCatchEntity " .. tostring(result))
        return result
    end
end

function GameListener.onSyncBindEntity(parentEntity, childEntity)
    local player = PlayerManager:getClientPlayer()
    local isSelfGrab = (player:getEntityId() == parentEntity:hashCode())
    local isSelfBeGrab = (player:getEntityId() == childEntity:hashCode())
    --LogUtil.log(string.format("GameListener.onSyncBindEntity isSelfGrab:%s isSelfBeGrab:%s",
    --        tostring(isSelfGrab), tostring(isSelfBeGrab)))

    if isSelfGrab then
        if GUIMainControl.selectMode == Define.SelectMode.NotSelect then
            GUIMainControl:onButtonSelect(Define.SelectMode.Punch)
        end
    end

    if isSelfBeGrab then
        parentEntity = DynamicCastEntity.dynamicCastPlayer(parentEntity)
        ClientHelper.putFloatPrefs("CameraDistanceMax", parentEntity.m_isConcealPower and
                GameConfig.concealPowerCameraDistanceMax or (parentEntity:getScale() * GameConfig.CameraDistanceMaxCoe))
    end
end

function GameListener.onSyncUnbindEntity(childEntity)
    local player = PlayerManager:getClientPlayer()
    local isSelfBeGrab = (player:getEntityId() == childEntity:hashCode())
    --LogUtil.log(string.format("GameListener.onSyncUnbindEntity isSelfBeGrab:%s",
    --        tostring(isSelfBeGrab)))

    if isSelfBeGrab then
        ClientHelper.putFloatPrefs("CameraDistanceMax", player:isConcealPower() and
                GameConfig.concealPowerCameraDistanceMax or (player.Player:getScale() * GameConfig.CameraDistanceMaxCoe))
        MainControlController:doButtonSelect(GUIMainControl.selectMode)
    end
end

function GameListener.onClientCmd(cmd)
    GMHandler.onHandlerCmd(cmd)
    return true
end

function GameListener.onClickSceneToController()
    return false
end

function GameListener.onSpawnEntity(lEntity)
    if not lEntity then
        return
    end
    if lEntity.type == EntityType.ActorNpc and lEntity.entity then
        lEntity.entity:setRenderDistanceWeight(4)
    end
end

function GameListener.onGameInit()
    LogUtil.log("GameListener.onGameInit")

    --if Platform.isWindow() then
    --    HU.Init("base.hotupdate.hotupdatelist",
    --            { ".\\Media\\Scripts\\ClientGame\\g1031_g1060\\LiftingSimulator\\main" })
    --end
end

function GameListener.onGameDestroy()
    AutoAnimManager:destroy()
    Utility.refreshPoleControlState(GameClient.poleControlState)
end

function GameListener.onAddDiamond()
    local data = DataBuilder.new():addParam("AddDiamond", "nil"):getData()
    PacketSender:sendLuaCommonData("DoReport", data)
end

return GameListener