initPos: [97.5, 101, 865.5, 180]

#stand By Time
standByTime: 1800

#init exp
initExp : 0

#init deathLineY
deathLineY : 1

# unlock rune trough
unlockRuneTroughPrice: 50


#世界时间,维持时间点不变.
worldTime: 12000

# task giveup Time (x小时)
taskGiveUpCD: 0

#  task refresh Time （0~24小时）
taskRefreshTime: 0

# 符文映射表
RuneMapping:
    -
        temRuneId: 22503
        realRuneId: 12503
    -
        temRuneId: 22503
        realRuneId: 12503
    -
        temRuneId: 20101
        realRuneId: 10101
    -
        temRuneId: 20102
        realRuneId: 10102
    -
        temRuneId: 20103
        realRuneId: 10103
    -
        temRuneId: 20201
        realRuneId: 10201
    -
        temRuneId: 20202
        realRuneId: 10202
    -
        temRuneId: 20203
        realRuneId: 10203
    -
        temRuneId: 20301
        realRuneId: 10301
    -
        temRuneId: 20302
        realRuneId: 10302
    -
        temRuneId: 20303
        realRuneId: 10303
    -
        temRuneId: 20401
        realRuneId: 10401
    -
        temRuneId: 20402
        realRuneId: 10402
    -
        temRuneId: 20403
        realRuneId: 10403
    -
        temRuneId: 20501
        realRuneId: 10501
    -
        temRuneId: 20502
        realRuneId: 10502
    -
        temRuneId: 20503
        realRuneId: 10503
    -
        temRuneId: 20601
        realRuneId: 10601
    -
        temRuneId: 20602
        realRuneId: 10602
    -
        temRuneId: 20603
        realRuneId: 10603
    -
        temRuneId: 20701
        realRuneId: 10701
    -
        temRuneId: 20702
        realRuneId: 10702
    -
        temRuneId: 20703
        realRuneId: 10703
    -
        temRuneId: 20801
        realRuneId: 10801
    -
        temRuneId: 20802
        realRuneId: 10802
    -
        temRuneId: 20803
        realRuneId: 10803
    -
        temRuneId: 20901
        realRuneId: 10901
    -
        temRuneId: 20902
        realRuneId: 10902
    -
        temRuneId: 20903
        realRuneId: 10903
    -
        temRuneId: 21001
        realRuneId: 11001
    -
        temRuneId: 21002
        realRuneId: 11002
    -
        temRuneId: 21003
        realRuneId: 11003
    -
        temRuneId: 21101
        realRuneId: 11101
    -
        temRuneId: 21102
        realRuneId: 11102
    -
        temRuneId: 21103
        realRuneId: 11103
    -
        temRuneId: 21201
        realRuneId: 11201
    -
        temRuneId: 21202
        realRuneId: 11202
    -
        temRuneId: 21203
        realRuneId: 11203
    -
        temRuneId: 21301
        realRuneId: 11301
    -
        temRuneId: 21302
        realRuneId: 11302
    -
        temRuneId: 21303
        realRuneId: 11303
    -
        temRuneId: 21401
        realRuneId: 11401
    -
        temRuneId: 21402
        realRuneId: 11402
    -
        temRuneId: 21403
        realRuneId: 11403
    -
        temRuneId: 21501
        realRuneId: 11501
    -
        temRuneId: 21502
        realRuneId: 11502
    -
        temRuneId: 21503
        realRuneId: 11503
    -
        temRuneId: 21601
        realRuneId: 11601
    -
        temRuneId: 21602
        realRuneId: 11602
    -
        temRuneId: 21603
        realRuneId: 11603
    -
        temRuneId: 21701
        realRuneId: 11701
    -
        temRuneId: 21702
        realRuneId: 11702
    -
        temRuneId: 21703
        realRuneId: 11703
    -
        temRuneId: 21801
        realRuneId: 11801
    -
        temRuneId: 21802
        realRuneId: 11802
    -
        temRuneId: 21803
        realRuneId: 11803
    -
        temRuneId: 21901
        realRuneId: 11901
    -
        temRuneId: 21902
        realRuneId: 11902
    -
        temRuneId: 21903
        realRuneId: 11903
    -
        temRuneId: 22001
        realRuneId: 12001
    -
        temRuneId: 22002
        realRuneId: 12002
    -
        temRuneId: 22003
        realRuneId: 12003
    -
        temRuneId: 22101
        realRuneId: 12101
    -
        temRuneId: 22102
        realRuneId: 12102
    -
        temRuneId: 22103
        realRuneId: 12103
    -
        temRuneId: 22201
        realRuneId: 12201
    -
        temRuneId: 22202
        realRuneId: 12202
    -
        temRuneId: 22203
        realRuneId: 12203
    -
        temRuneId: 22301
        realRuneId: 12301
    -
        temRuneId: 22302
        realRuneId: 12302
    -
        temRuneId: 22303
        realRuneId: 12303
    -
        temRuneId: 22401
        realRuneId: 12401
    -
        temRuneId: 22402
        realRuneId: 12402
    -
        temRuneId: 22403
        realRuneId: 12403
    -
        temRuneId: 22501
        realRuneId: 12501
    -
        temRuneId: 22502
        realRuneId: 12502
    -
        temRuneId: 22503
        realRuneId: 12503


