---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by JY-032.
--- DateTime: 2019/12/17 17:29
---

require "ui.window.GUIGameResultItem"

local GUIGameResult = class("GUIGameResult", IGUILayout)

function GUIGameResult:onLoad()
    self.ivTitleBottomImage = self:getChildWindow("LuckySkyResult-Title-Bottom-Image", GUIType.StaticImage)
    self.ivTitleIcon = self:getChildWindow("LuckySkyResult-Title-Icon", GUIType.StaticImage)
    self.tvTitleText = self:getChildWindow("LuckySkyResult-Title-Text", GUIType.StaticText)
    self.ltLeftList = self:getChildWindow("LuckySkyResult-Left-List", GUIType.List)
    self.ltRightList = self:getChildWindow("LuckySkyResult-Right-List", GUIType.List)

    self.tvScoreNum = self:getChildWindow("LuckySkyResult-Self-Score-Num", GUIType.StaticText)
    self.tvGoldNum = self:getChildWindow("LuckySkyResult-Gold-Num", GUIType.StaticText)

    self.btnBack = self:getChildWindow("LuckySkyResult-Back-Button", GUIType.Button)
    self.btnAgain = self:getChildWindow("LuckySkyResult-Again-Button", GUIType.Button)

    self.btnBack:registerEvent(GUIEvent.ButtonClick, function()
        SoundUtil.clickUI()
        GamePacketSender:sendPlayerBackHallEvent()
    end)

    self.btnAgain:registerEvent(GUIEvent.ButtonClick, function()
        SoundUtil.clickUI()
        GamePacketSender:sendPlayerNextGameEvent()
    end)
    self:getChildWindow("LuckySkyResult-Back-Text", GUIType.StaticText):SetText(Lang:getString("lucky.sky.dead.summary.back"))
    self:getChildWindow("LuckySkyResult-Again-Text", GUIType.StaticText):SetText(Lang:getString("lucky.sky.dead.summary.again"))

    self:registerDataCallBack("GameSettlementData", function(data)
        self:onGameResultData(data)
    end, JsonBuilderProcessor)

end

function GUIGameResult:onGameResultData(data)
    self.gameData = data.players
    self.player_own_Data = data.own
    self:setTitleImage()
    self:show()
end

function GUIGameResult:onShow()
    GUIMain:hideAllLayout()
    self.ltLeftList:ClearAllItem()
    self.ltRightList:ClearAllItem()
    for _, value in pairs(self.gameData) do
        local Item = GUIGameResultItem.new("LuckySkyResultItem.json")
        if value.rank < 9 then
            self.ltLeftList:AddItem(Item.root)
        else
            self.ltRightList:AddItem(Item.root)
        end
        Item:initItem(value)
    end
end

function GUIGameResult:setTitleImage()
    if self.player_own_Data.isWin == 1 then
        self.ivTitleBottomImage:SetImage("set:lucky_sky_game_result_main.json image:win_bottom")
        self.ivTitleIcon:SetImage("set:lucky_sky_game_result_main.json image:win")
        self.tvTitleText:SetText(Lang:getString("lucky.sky.game.summary.win"))
    elseif self.player_own_Data.isWin == 0 then
        self.ivTitleBottomImage:SetImage("set:lucky_sky_game_result_main.json image:lose_bottom")
        self.ivTitleIcon:SetImage("set:lucky_sky_game_result_main.json image:lose")
        self.tvTitleText:SetText(Lang:getString("lucky.sky.game.summary.lose"))
    elseif self.player_own_Data.isWin == 2 then
        self.ivTitleBottomImage:SetImage("set:lucky_sky_game_result_main.json image:draw_bottom")
        self.ivTitleIcon:SetImage("set:lucky_sky_game_result_main.json image:draw")
        self.tvTitleText:SetText(Lang:getString("lucky.sky.game.summary.draw"))
    end

    local scoreText = "+" .. self.player_own_Data.result_add_integral
    if tonumber(self.player_own_Data.result_add_integral) < 0 then
        scoreText = self.player_own_Data.result_add_integral
    end

    self.tvScoreNum:SetText(scoreText)
    self.tvGoldNum:SetText(string.format("+%d", tostring(self.player_own_Data.gold)))
end

return GUIGameResult