---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by JY-032.
--- DateTime: 2019/11/7 16:07
---
local GUIToolBar = class("UIToolBar", IGUILayout)

function GUIToolBar:onLoad()
    self.contDownTimeText = ""
    self.contDownTime = 0

    self.tvContDownTime = self:getChildWindow("SkyWarLuckyToolBar-Count-Down", GUIType.StaticText)

    self.tvSurvivor = self:getChildWindow("SkyWarLuckyToolBar-Survivor-Text", GUIType.StaticText)
    self.tvSurviveTeam = self:getChildWindow("SkyWarLuckyToolBar-Survivor-Team-Text", GUIType.StaticText)

    self:registerDataCallBack("GameInfoData", function(data)
        self:updateGameInfo(data)
    end, DataBuilderProcessor)

    local window = GUIManager:getWindowByName("PlayerInventory-ArmorTab")
    window:SetXPosition({ 2, 0 })
end

function GUIToolBar:updateGameInfo(data)
    self.survivorNum = data:getNumberParam("survivorNum")
    self.surviveTeamNum = data:getNumberParam("surviveTeamNum")
    self:showGameInfo()
end

function GUIToolBar:showGameInfo()
    self.tvSurvivor:SetText(tostring(self.survivorNum))
    self.tvSurviveTeam:SetText(tostring(self.surviveTeamNum))
end

return GUIToolBar