---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 10184.
--- DateTime: 2020/5/25 18:26
---
local function hideEngineWindow(name)
    local window = GUIManager:getWindowByName(name)
    if not window then
        return
    end
    window:SetXPosition({ 0, 6000 })
    window:SetVisible(false)
end

local UIPlayerInventory = class("GUIPlayerInventory", IGUILayout)

function UIPlayerInventory:onLoad()
    local screenWidth = self:getChildWindow("PlayerInventory"):GetPixelSize().x
    screenWidth = math.min(math.max(screenWidth - 352, 900), screenWidth)
    local llInventory = self:getChildWindow("PlayerInventory-Inventory")
    llInventory:SetArea({ 0, 0 }, { 0, 53 }, { 0, screenWidth }, { 1, -167 })
    local ivTitle = self:getChildWindow("PlayerInventory-Page-Title-Bg", GUIType.StaticImage)
    ivTitle:SetArea({ 0, 0 }, { 0, 0 }, { 1, 0 }, { 0, 57 })
    ivTitle:SetProperty("StretchOffset", "20 20 20 20")
    ivTitle:SetImage("set:bed_war_player_inventory.json image:title")
    local ivClose = self:getChildWindow("PlayerInventory-CloseButton", GUIType.StaticImage)
    ivClose:SetArea({ 1, -57 }, { 0, 0 }, { 0, 40 }, { 0, 40 })
    ivClose:SetImage("set:bed_war_block_shop.json image:close")
    local tvTitle = self:getChildWindow("PlayerInventory-Title", GUIType.StaticText)
    tvTitle:SetArea({ 0, 0 }, { 0, 0 }, { 0, 400 }, { 0, 57 })
    local llPanel = self:getChildWindow("PlayerInventory-InventoryPanel", GUIType.Layout)
    llPanel:SetProperty("StretchOffset", "15 15 1 20")
    llPanel:SetBackImage("set:bed_war_player_inventory.json image:bg_base")
    hideEngineWindow("PlayerInventory-ArmorTab")
end

return UIPlayerInventory