---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by JY-032.
--- DateTime: 2019/10/15 12:14
---

require "config.JobConfig"
require "config.Define"
GUIJobChoiceItem = class("GUIJobChoiceItem", IGUIWindow)


--The selected status of the career selection screen
ItemsSelectStatus = {
    NotSelect = 1,
    Select = 2,
}

function GUIJobChoiceItem:onLoad()
    self.subAlpha = true
    self.borderAlpha = 1  --Checkbox transparency
    self.id = nil
    self.lastId = nil
    self.item = nil
    self.lastItemId = nil
    self.lastItem = {}
    self.status = JobStatus.NO_HAVE

    self.selectMode = ItemsSelectStatus.NotSelect

    self.selectJob = CurSelectJob.No_Select_Job
    self.content = self:getChildWindow(0, GUIType.Layout)
    self.ivImage = self:getChildWindow(0, GUIType.StaticImage, self.content)
    self.ivCount = self:getChildWindow(2, GUIType.StaticImage, self.ivImage)
    self.tvCount_text = self:getChildWindow(0, GUIType.StaticText, self.ivCount)

    self.ivName = self:getChildWindow(0, GUIType.StaticImage, self.ivImage)
    self.tvName_text = self:getChildWindow(0, GUIType.StaticText, self.ivName)

    self.ivSelect_image = self:getChildWindow(1, GUIType.StaticImage, self.ivImage)
    self.ivSelect_image:SetVisible(false)

    self.ivJobSelect_Icon = self:getChildWindow(1, GUIType.StaticImage)
    self.ivJobSelect_Icon:SetVisible(false)
    self.content:registerEvent(GUIEvent.TouchUp, function()
        self:onItemClick()
    end)
end

function GUIJobChoiceItem:onTick(frameTime)
    self:upJobSelectAlpha()
end

function GUIJobChoiceItem:upJobSelectAlpha()
    if not self.ivJobSelect_Icon:IsVisible() then
        return
    end
    if self.subAlpha then
        self.borderAlpha = self.borderAlpha - 0.01
        if self.borderAlpha <= 0.5 then
            self.subAlpha = false
        end
    else
        self.borderAlpha = self.borderAlpha + 0.01
        if self.borderAlpha >= 1 then
            self.subAlpha = true
        end
    end
    self.ivJobSelect_Icon:SetAlpha(self.borderAlpha)
end

--Current career choice
function GUIJobChoiceItem:changeCurSelectJob(selectJob)
    self.selectJob = selectJob
    if self.selectJob == CurSelectJob.No_Select_Job then
        self.ivSelect_image:SetVisible(false)
    elseif self.selectJob == CurSelectJob.Have_Select_Job then
        self.ivSelect_image:SetVisible(true)
    end
end

function GUIJobChoiceItem:setItemData(item)
    if not item then
        return
    end
    self.id = item.id
    self.item = item
    if item.type == Define.JobType.Card then
        self.ivName:SetVisible(false)
        self.ivCount:SetVisible(false)
    else
        self.tvName_text:SetText(Lang:getString(item.name))
        self:updateTime(item.times)
    end
    self.ivImage:SetImage(item.icon)
    self:setStatus(item.status)
end

--Update times display
function GUIJobChoiceItem:updateTime(times)
    if times > 0 then
        self.ivCount:SetVisible(true)
        self.tvCount_text:SetText(tostring(times))
    else
        self.ivCount:SetVisible(false)
    end
end

--Change the selected state
function GUIJobChoiceItem:changeSelectStatus(SelectMode)
    self.selectMode = SelectMode
    if self.selectMode == ItemsSelectStatus.NotSelect then
        self.ivJobSelect_Icon:SetVisible(false)
    elseif self.selectMode == ItemsSelectStatus.Select then
        self.ivJobSelect_Icon:SetVisible(true)
    end
end

function GUIJobChoiceItem:setStatus(status)
    self.status = status
    if self.status == JobStatus.HAVE then
        self.ivImage:SetEnabled(true)
    elseif self.status == JobStatus.NO_HAVE then
        self.ivImage:SetEnabled(false)
    end
end

function GUIJobChoiceItem:onItemClick()
    if self.item.type == Define.JobType.Card then
        GUIJobChoice:hide()
        GUIJobExtract:show(false)
    else
        GUIJobChoice:onJobsInfoUpdate(self.item.id)
    end
end
