---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 10184.
--- DateTime: 2020/5/19 12:13
---
local BattleInfoPlayerAdapter = class("BattleInfoPlayerAdapter", IDataAdapter)

function BattleInfoPlayerAdapter:setItemSize(width, height)
    self.width = width
    self.height = height
end

---必须重写，返回子UI的json文件名
function BattleInfoPlayerAdapter:getJsonName()
    return "BedWarBattlePlayerInfo.json"
end

---必须重写，返回子UI的class类创建对象
function BattleInfoPlayerAdapter:getWindowClass()
    return GUIBattlePlayerInfo
end

function BattleInfoPlayerAdapter:getItemWidth()
    return { 0, self.width }
end

function BattleInfoPlayerAdapter:getItemHeight()
    return { 0, self.height }
end

return BattleInfoPlayerAdapter
