---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jimmy.
--- DateTime: 2019/9/3 0003 15:09
---


OpenLotteryBoxEvent = IScriptEvent.new()
if GameType == "g1046" then
    UpdateActivityRedPointEvent = IScriptEvent.new()
    UpdateDailySignInRedPointEvent = IScriptEvent.new()
    UpdateBoxLotteryIntegralEvent = IScriptEvent.new()
    DressStoreTabChangeEvent = IScriptEvent.new()
    UIDressStorePanItemChangeEvent = IScriptEvent.new()
    TableNewNumChangeEvent = IScriptEvent.new()
    ShowUseDressEvent = IScriptEvent.new()
else
    HpChangeEvent = IScriptEvent.new()
    BedWarToolBarEvent = IScriptEvent.new()
end
