#pragma once

#ifndef __ENTITY_HEADER_H__
#define __ENTITY_HEADER_H__

#include "Entity/Attributes.h"
#include "Entity/CombatTracker.h"
#include "Entity/DamageSource.h"
#include "Entity/Enchantment.h"
#include "Entity/Entity.h"
#include "Entity/Explosion.h"
#include "Entity/PathFinder.h"
#include "Entity/PathNavigate.h"
#include "LuaRegister/Template/LuaRegister.h"
#include "World/RayTracyResult.h"
#include "Script/DynamicCastEntity.h"

using namespace BLOCKMAN;

using namespace LUA_REGISTER;

// Register Class Entity
#pragma region
_BEGIN_REGISTER_CLASS(Entity)
_CLASSREGISTER_AddBaseClass(ObjectAlloc)
_CLASSREGISTER_AddMember(HasProperty, Entity::HasProperty)
_CLASSREGISTER_AddMember(setBoolProperty, Entity::setBoolProperty)
_CLASSREGISTER_AddMember(getBoolProperty, Entity::getBoolProperty)
_CLASSREGISTER_AddMember(setIntProperty, Entity::setIntProperty)
_CLASSREGISTER_AddMember(getIntProperty, Entity::getIntProperty)
_CLASSREGISTER_AddMember(setFloatProperty, Entity::setFloatProperty)
_CLASSREGISTER_AddMember(getFloatProperty, Entity::getFloatProperty)
_CLASSREGISTER_AddMember(setDoubleProperty, Entity::setDoubleProperty)
_CLASSREGISTER_AddMember(getDoubleProperty, Entity::getDoubleProperty)
_CLASSREGISTER_AddMember(setStringProperty, Entity::setStringProperty)
_CLASSREGISTER_AddMember(getStringProperty, Entity::getStringProperty)
_CLASSREGISTER_AddMember(getFirstChildrenEntityId, Entity::getFirstChildrenEntityId)
_CLASSREGISTER_AddMember(unbindParentEntity, Entity::unbindParentEntity)
_CLASSREGISTER_AddMember(unbindAllEntity, Entity::unbindAllEntity)
_CLASSREGISTER_AddMember(getScale, Entity::getScale)
_CLASSREGISTER_AddMember(setScale, Entity::setScale)
_CLASSREGISTER_AddMember(addEntityID, Entity::addEntityID)
_CLASSREGISTER_AddMember(addNotRiddenEntityID, Entity::addNotRiddenEntityID)
_CLASSREGISTER_AddMember(addToPlayerScore, Entity::addToPlayerScore)
_CLASSREGISTER_AddMember(addVelocity, Entity::addVelocity)
_CLASSREGISTER_AddMember(applyEntityCollision, Entity::applyEntityCollision)
_CLASSREGISTER_AddMember(attackEntityFrom, Entity::attackEntityFrom)
_CLASSREGISTER_AddMember(canAttackWithItem, Entity::canAttackWithItem)
_CLASSREGISTER_AddMember(canBeCollidedWith, Entity::canBeCollidedWith)
_CLASSREGISTER_AddMember(canBePushed, Entity::canBePushed)
_CLASSREGISTER_AddMember(canRenderOnFire, Entity::canRenderOnFire)
_CLASSREGISTER_AddMember(doBlockCollisions, Entity::doBlockCollisions)
_CLASSREGISTER_AddMember(doesEntityNotTriggerPressurePlate, Entity::doesEntityNotTriggerPressurePlate)
_CLASSREGISTER_AddMember(dropItem, Entity::dropItem)
_CLASSREGISTER_AddMember(dropItemWithOffset, Entity::dropItemWithOffset)
_CLASSREGISTER_AddMember(entityDropItem, Entity::entityDropItem)
_CLASSREGISTER_AddMember(extinguish, Entity::extinguish)
_CLASSREGISTER_AddMember(getWidth, Entity::getWidth)
_CLASSREGISTER_AddMember(getHeight, Entity::getHeight)
_CLASSREGISTER_AddMember(getAir, Entity::getAir)
_CLASSREGISTER_AddMember(getBottomPos, Entity::getBottomPos)
_CLASSREGISTER_AddMember(getBoundingBox, Entity::getBoundingBox)
_CLASSREGISTER_AddMember(getBrightness, Entity::getBrightness)
_CLASSREGISTER_AddMember(getBrightnessForRender, Entity::getBrightnessForRender)
_CLASSREGISTER_AddMember(getCentorPos, Entity::getCentorPos)
_CLASSREGISTER_AddMember(getCollisionBorderSize, Entity::getCollisionBorderSize)
_CLASSREGISTER_AddMember(getCollisionBox, Entity::getCollisionBox)
_CLASSREGISTER_AddMember(getDistance, Entity::getDistance)
_CLASSREGISTER_AddMember(getDistanceSq, Entity::getDistanceSq)
_CLASSREGISTER_AddMember(getDistanceSqToEntity, Entity::getDistanceSqToEntity)
_CLASSREGISTER_AddMember(getDistanceToEntity, Entity::getDistanceToEntity)
_CLASSREGISTER_AddMember(getEntityName, Entity::getEntityName)
_CLASSREGISTER_AddMember(getExplosionResistance, Entity::getExplosionResistance)
_CLASSREGISTER_AddMember(getEyeHeight, Entity::getEyeHeight)
_CLASSREGISTER_AddMember(getLastActiveItems, Entity::getLastActiveItems)
_CLASSREGISTER_AddMember(getMaxFallHeight, Entity::getMaxFallHeight)
_CLASSREGISTER_AddMember(getMountedYOffset, Entity::getMountedYOffset)
_CLASSREGISTER_AddMember(getParts, Entity::getParts)
_CLASSREGISTER_AddMember(getPartsCount, Entity::getPartsCount)
_CLASSREGISTER_AddMember(getPortalCooldown, Entity::getPortalCooldown)
_CLASSREGISTER_AddMember(getRotationYawHead, Entity::getRotationYawHead)
_CLASSREGISTER_AddMember(getShadowSize, Entity::getShadowSize)
_CLASSREGISTER_AddStaticMember(getSuperClassID, Entity::getSuperClassID)
_CLASSREGISTER_AddMember(getTopperPos, Entity::getTopperPos)
_CLASSREGISTER_AddMember(getTranslatedEntityName, Entity::getTranslatedEntityName)
_CLASSREGISTER_AddMember(getUniqueID, Entity::getUniqueID)
_CLASSREGISTER_AddMember(getWidelyPos, Entity::getWidelyPos)
_CLASSREGISTER_AddMember(getYOffset, Entity::getYOffset)
_CLASSREGISTER_AddMember(getParentEntity, Entity::getParentEntity)
_CLASSREGISTER_AddMember(handleLavaMovement, Entity::handleLavaMovement)
_CLASSREGISTER_AddMember(handleWaterMovement, Entity::handleWaterMovement)
_CLASSREGISTER_AddMember(hashCode, Entity::hashCode)
_CLASSREGISTER_AddMember(hitByEntity, Entity::hitByEntity)
_CLASSREGISTER_AddMember(isBurning, Entity::isBurning)
_CLASSREGISTER_AddMember(isEating, Entity::isEating)
_CLASSREGISTER_AddMember(isEntityAlive, Entity::isEntityAlive)
_CLASSREGISTER_AddMember(isEntityEqual, Entity::isEntityEqual)
_CLASSREGISTER_AddMember(isEntityInsideOpaqueBlock, Entity::isEntityInsideOpaqueBlock)
_CLASSREGISTER_AddMember(isEntityInvulnerable, Entity::isEntityInvulnerable)
_CLASSREGISTER_AddMember(isImmuneToFire, Entity::isImmuneToFire)
_CLASSREGISTER_AddMember_Override(isInRangeToRenderDist, Entity::isInRangeToRenderDist, bool, float)
_CLASSREGISTER_AddMember_Override(isInRangeToRenderDist1, Entity::isInRangeToRenderDist, bool, const Vector3 &)
_CLASSREGISTER_AddMember(isInRangeToRenderVec3D, Entity::isInRangeToRenderVec3D)
_CLASSREGISTER_AddMember(isInWater, Entity::isInWater)
_CLASSREGISTER_AddMember(isInsideOfMaterial, Entity::isInsideOfMaterial)
_CLASSREGISTER_AddMember(isInvisible, Entity::isInvisible)
_CLASSREGISTER_AddMember(isInvisibleToPlayer, Entity::isInvisibleToPlayer)
_CLASSREGISTER_AddMember(isOffsetPositionInLiquid, Entity::isOffsetPositionInLiquid)
_CLASSREGISTER_AddMember(isPushedByWater, Entity::isPushedByWater)
_CLASSREGISTER_AddMember(isSneaking, Entity::isSneaking)
_CLASSREGISTER_AddMember(isSprinting, Entity::isSprinting)
_CLASSREGISTER_AddMember(isWet, Entity::isWet)
_CLASSREGISTER_AddMember(moveEntity, Entity::moveEntity)
_CLASSREGISTER_AddMember(moveFlying, Entity::moveFlying)
_CLASSREGISTER_AddMember(onCollideWithPlayer, Entity::onCollideWithPlayer)
_CLASSREGISTER_AddMember(onEntityUpdate, Entity::onEntityUpdate)
_CLASSREGISTER_AddMember(onKillEntity, Entity::onKillEntity)
_CLASSREGISTER_AddMember(onStruckByLightning, Entity::onStruckByLightning)
_CLASSREGISTER_AddMember(onUpdate, Entity::onUpdate)
_CLASSREGISTER_AddMember(performHurtAnimation, Entity::performHurtAnimation)
_CLASSREGISTER_AddMember(playSoundByType, Entity::playSoundByType)
_CLASSREGISTER_AddMember(processInitialInteract, Entity::processInitialInteract)
_CLASSREGISTER_AddMember(pushOutOfBlocks, Entity::pushOutOfBlocks)
_CLASSREGISTER_AddMember(readFromNBT, Entity::readFromNBT)
_CLASSREGISTER_AddMember(setAir, Entity::setAir)
_CLASSREGISTER_AddMember(setCurrentItemOrArmor, Entity::setCurrentItemOrArmor)
_CLASSREGISTER_AddMember(setDead, Entity::setDead)
_CLASSREGISTER_AddMember(setEating, Entity::setEating)
_CLASSREGISTER_AddMember(setFire, Entity::setFire)
_CLASSREGISTER_AddMember(setFireDurationTime, Entity::setFireDurationTime)
_CLASSREGISTER_AddMember(setInPortal, Entity::setInPortal)
_CLASSREGISTER_AddMember(setInWeb, Entity::setInWeb)
_CLASSREGISTER_AddMember(setInvisible, Entity::setInvisible)
_CLASSREGISTER_AddMember(setLocationAndAngles, Entity::setLocationAndAngles)
_CLASSREGISTER_AddMember(getPosition, Entity::getPosition)
_CLASSREGISTER_AddMember(setPosition, Entity::setPosition)
_CLASSREGISTER_AddMember(setPositionAndRotation, Entity::setPositionAndRotation)
_CLASSREGISTER_AddMember(setPositionAndRotation2, Entity::setPositionAndRotation2)
_CLASSREGISTER_AddMember(setRotationYawHead, Entity::setRotationYawHead)
_CLASSREGISTER_AddMember(setSneaking, Entity::setSneaking)
_CLASSREGISTER_AddMember(setSprinting, Entity::setSprinting)
_CLASSREGISTER_AddMember(setVelocity, Entity::setVelocity)
_CLASSREGISTER_AddMember(setWorld, Entity::setWorld)
_CLASSREGISTER_AddMember(toString, Entity::toString)
_CLASSREGISTER_AddMember(verifyExplosion, Entity::verifyExplosion)
_CLASSREGISTER_AddMember(writeToNBT, Entity::writeToNBT)
_CLASSREGISTER_AddMember(canFall, Entity::canFall)
_CLASSREGISTER_AddMember(canPlayerFallEx, Entity::canPlayerFallEx)
_CLASSREGISTER_AddMember(setOnSelected, Entity::setOnSelected)
_CLASSREGISTER_AddMember(setRenderDistanceWeight, Entity::setRenderDistanceWeight)
_CLASSREGISTER_AddMember(setIgnoreFrustumCheck, Entity::setIgnoreFrustumCheck)
_CLASSREGISTER_AddMember(isGrab, Entity::isGrab)
_CLASSREGISTER_AddMember(isBeGrab, Entity::isBeGrab)
_CLASSREGISTER_AddVar(position, Entity::position)
_CLASSREGISTER_AddVar(prevPos, Entity::prevPos)
_CLASSREGISTER_AddVar(motion, Entity::motion)
_CLASSREGISTER_AddVar(rotationYaw, Entity::rotationYaw)
_CLASSREGISTER_AddVar(rotationPitch, Entity::rotationPitch)
_CLASSREGISTER_AddVar(renderDistanceWeight, Entity::renderDistanceWeight)
_CLASSREGISTER_AddVar(onGround, Entity::onGround)
_CLASSREGISTER_AddVar(fallDistance, Entity::fallDistance)
_CLASSREGISTER_AddVar(m_flyingByPulled, Entity::m_flyingByPulled)
_CLASSREGISTER_AddVar(isDead, Entity::isDead)
_CLASSREGISTER_AddMember(getCustomProperties, Entity::getCustomProperties)
_CLASSREGISTER_AddMember(setCustomProperties, Entity::setCustomProperties)
_CLASSREGISTER_AddMember(setEnableTracker, Entity::setEnableTracker)
_CLASSREGISTER_AddMember(clearEntityFeature, Entity::clearEntityFeature)
_CLASSREGISTER_AddMember(hasEntityFeature, Entity::hasEntityFeature)
_CLASSREGISTER_AddMember(addCustomEffect, Entity::addCustomEffect)
_CLASSREGISTER_AddMember(clearCustomEffects, Entity::clearCustomEffects)
_CLASSREGISTER_AddMember(addCustomImage, Entity::addCustomImage)
_CLASSREGISTER_AddMember(clearCustomImages, Entity::clearCustomImages)
_CLASSREGISTER_AddMember(addCustomText, Entity::addCustomText)
_CLASSREGISTER_AddMember(clearCustomTexts, Entity::clearCustomTexts)
_CLASSREGISTER_AddMember(addCustomBodyPart, Entity::addCustomBodyPart)
_END_REGISTER_CLASS()
#pragma endregion

// Register Class EntityArrow
_BEGIN_REGISTER_CLASS(EntityArrow)
_CLASSREGISTER_AddBaseClass(Entity )
_CLASSREGISTER_AddBaseClass(IProjectile)
_CLASSREGISTER_AddCtor(World * )
_CLASSREGISTER_AddCtor(World * , const Vector3 & )
_CLASSREGISTER_AddCtor(World * , EntityLivingBase * , EntityLivingBase * , float , float )
_CLASSREGISTER_AddCtor(World * , EntityLivingBase * , float )
_CLASSREGISTER_AddCtor(World * , EntityLivingBase * , const Vector3 & , float , float , float )
_CLASSREGISTER_AddMember(canAttackWithItem, EntityArrow::canAttackWithItem)
_CLASSREGISTER_AddMember(getDamage, EntityArrow::getDamage)
_CLASSREGISTER_AddMember(getIsCritical, EntityArrow::getIsCritical)
_CLASSREGISTER_AddMember(getShadowSize, EntityArrow::getShadowSize)
_CLASSREGISTER_AddMember(onCollideWithPlayer, EntityArrow::onCollideWithPlayer)
_CLASSREGISTER_AddMember(onUpdate, EntityArrow::onUpdate)
_CLASSREGISTER_AddMember(readEntityFromNBT, EntityArrow::readEntityFromNBT)
_CLASSREGISTER_AddMember(setDamage, EntityArrow::setDamage)
_CLASSREGISTER_AddMember(setIsCritical, EntityArrow::setIsCritical)
_CLASSREGISTER_AddMember(setKnockbackStrength, EntityArrow::setKnockbackStrength)
_CLASSREGISTER_AddMember(setPositionAndRotation2, EntityArrow::setPositionAndRotation2)
_CLASSREGISTER_AddMember(setThrowableHeading, EntityArrow::setThrowableHeading)
_CLASSREGISTER_AddMember(setVelocity, EntityArrow::setVelocity)
_CLASSREGISTER_AddMember(writeEntityToNBT, EntityArrow::writeEntityToNBT)
_CLASSREGISTER_AddMember(getShootingEntity, EntityArrow::getShootingEntity)
_END_REGISTER_CLASS()

// Register Class EntityItem
_BEGIN_REGISTER_CLASS(EntityItem)
_CLASSREGISTER_AddBaseClass(Entity)
_CLASSREGISTER_AddCtor(World * , const Vector3 & )
_CLASSREGISTER_AddCtor(World * , const Vector3 & , ItemStackPtr )
_CLASSREGISTER_AddCtor(World * )
_CLASSREGISTER_AddMember(attackEntityFrom, EntityItem::attackEntityFrom)
_CLASSREGISTER_AddMember(canAttackWithItem, EntityItem::canAttackWithItem)
_CLASSREGISTER_AddMember(combineItems, EntityItem::combineItems)
_CLASSREGISTER_AddMember(getEntityItem, EntityItem::getEntityItem)
_CLASSREGISTER_AddMember(getEntityName, EntityItem::getEntityName)
_CLASSREGISTER_AddMember(handleWaterMovement, EntityItem::handleWaterMovement)
_CLASSREGISTER_AddMember(onCollideWithPlayer, EntityItem::onCollideWithPlayer)
_CLASSREGISTER_AddMember(onUpdate, EntityItem::onUpdate)
_CLASSREGISTER_AddMember(readEntityFromNBT, EntityItem::readEntityFromNBT)
_CLASSREGISTER_AddMember(setAgeToCreativeDespawnTime, EntityItem::setAgeToCreativeDespawnTime)
_CLASSREGISTER_AddMember(setEntityItemStack, EntityItem::setEntityItemStack)
_CLASSREGISTER_AddMember(writeEntityToNBT, EntityItem::writeEntityToNBT)
_CLASSREGISTER_AddVar(m_readyToDead, EntityItem::m_readyToDead)
_CLASSREGISTER_AddVar(m_isPickedUp, EntityItem::m_isPickedUp)
_CLASSREGISTER_AddVar(m_pickerId, EntityItem::m_pickerId)
_CLASSREGISTER_AddVar(m_pickerIsCurrClient, EntityItem::m_pickerIsCurrClient)
_END_REGISTER_CLASS()

// Register Class EntityLiving
_BEGIN_REGISTER_CLASS(EntityLiving)
_CLASSREGISTER_AddBaseClass(EntityLivingBase)
_CLASSREGISTER_AddCtor(World * )
_CLASSREGISTER_AddMember(canBeLeashedTo, EntityLiving::canBeLeashedTo)
_CLASSREGISTER_AddMember(canBeSteered, EntityLiving::canBeSteered)
_CLASSREGISTER_AddMember(canPickUpLoot, EntityLiving::canPickUpLoot)
_CLASSREGISTER_AddMember(clearLeashed, EntityLiving::clearLeashed)
_CLASSREGISTER_AddMember(eatGrassBonus, EntityLiving::eatGrassBonus)
_CLASSREGISTER_AddMember(enablePersistence, EntityLiving::enablePersistence)
_CLASSREGISTER_AddMember(faceEntity, EntityLiving::faceEntity)
_CLASSREGISTER_AddMember(getAlwaysRenderNameTagForRender, EntityLiving::getAlwaysRenderNameTagForRender)
_CLASSREGISTER_AddMember(getArmorFromSlot, EntityLiving::getArmorFromSlot)
_CLASSREGISTER_AddStaticMember(getArmorItemForSlot, EntityLiving::getArmorItemForSlot)
_CLASSREGISTER_AddStaticMember(getArmorPosition, EntityLiving::getArmorPosition)
_CLASSREGISTER_AddMember(getAttackTarget, EntityLiving::getAttackTarget)
_CLASSREGISTER_AddMember(getCanSpawnHere, EntityLiving::getCanSpawnHere)
_CLASSREGISTER_AddMember(getCurrentItemOrArmor, EntityLiving::getCurrentItemOrArmor)
_CLASSREGISTER_AddMember(getCustomNameTag, EntityLiving::getCustomNameTag)
_CLASSREGISTER_AddMember(getEntityName, EntityLiving::getEntityName)
_CLASSREGISTER_AddMember(getEntitySenses, EntityLiving::getEntitySenses)
_CLASSREGISTER_AddMember(getHeldItem, EntityLiving::getHeldItem)
_CLASSREGISTER_AddMember(getJumpHelper, EntityLiving::getJumpHelper)
_CLASSREGISTER_AddMember(getLastActiveItems, EntityLiving::getLastActiveItems)
_CLASSREGISTER_AddMember(getLeashed, EntityLiving::getLeashed)
_CLASSREGISTER_AddMember(getLeashedToEntity, EntityLiving::getLeashedToEntity)
_CLASSREGISTER_AddMember(getLookHelper, EntityLiving::getLookHelper)
_CLASSREGISTER_AddMember(getMaxFallHeight, EntityLiving::getMaxFallHeight)
_CLASSREGISTER_AddMember(getMaxSpawnedInChunk, EntityLiving::getMaxSpawnedInChunk)
_CLASSREGISTER_AddMember(getMoveHelper, EntityLiving::getMoveHelper)
_CLASSREGISTER_AddMember(getNavigator, EntityLiving::getNavigator)
_CLASSREGISTER_AddMember(getRenderSizeModifier, EntityLiving::getRenderSizeModifier)
_CLASSREGISTER_AddMember(getTalkInterval, EntityLiving::getTalkInterval)
_CLASSREGISTER_AddMember(getVerticalFaceSpeed, EntityLiving::getVerticalFaceSpeed)
_CLASSREGISTER_AddMember(hasCustomNameTag, EntityLiving::hasCustomNameTag)
_CLASSREGISTER_AddMember(isAIDisable, EntityLiving::isAIDisable)
_CLASSREGISTER_AddMember(isNoDespawnRequired, EntityLiving::isNoDespawnRequired)
_CLASSREGISTER_AddMember(onEntityUpdate, EntityLiving::onEntityUpdate)
_CLASSREGISTER_AddMember(onInitialSpawn, EntityLiving::onInitialSpawn)
_CLASSREGISTER_AddMember(onLivingUpdate, EntityLiving::onLivingUpdate)
_CLASSREGISTER_AddMember(onUpdate, EntityLiving::onUpdate)
_CLASSREGISTER_AddMember(playLivingSound, EntityLiving::playLivingSound)
_CLASSREGISTER_AddMember(processInitialInteract, EntityLiving::processInitialInteract)
_CLASSREGISTER_AddMember(readEntityFromNBT, EntityLiving::readEntityFromNBT)
_CLASSREGISTER_AddMember(setAIMoveSpeed, EntityLiving::setAIMoveSpeed)
_CLASSREGISTER_AddMember(setAttackTarget, EntityLiving::setAttackTarget)
_CLASSREGISTER_AddMember(setCanPickUpLoot, EntityLiving::setCanPickUpLoot)
_CLASSREGISTER_AddMember(setCurrentItemOrArmor, EntityLiving::setCurrentItemOrArmor)
_CLASSREGISTER_AddMember(setCustomNameTag, EntityLiving::setCustomNameTag)
_CLASSREGISTER_AddMember(setEquipmentDropChance, EntityLiving::setEquipmentDropChance)
_CLASSREGISTER_AddMember(setLeashedToEntity, EntityLiving::setLeashedToEntity)
_CLASSREGISTER_AddMember(setNoAI, EntityLiving::setNoAI)
_CLASSREGISTER_AddMember(spawnExplosionParticle, EntityLiving::spawnExplosionParticle)
_CLASSREGISTER_AddMember(writeEntityToNBT, EntityLiving::writeEntityToNBT)
_END_REGISTER_CLASS()

// Register Class EntityLivingBase
_BEGIN_REGISTER_CLASS(EntityLivingBase)
_CLASSREGISTER_AddBaseClass(Entity)
_CLASSREGISTER_AddMember(addPotionEffect, EntityLivingBase::addPotionEffect)
_CLASSREGISTER_AddMember(attackEntityAsMob, EntityLivingBase::attackEntityAsMob)
_CLASSREGISTER_AddMember(attackEntityFrom, EntityLivingBase::attackEntityFrom)
_CLASSREGISTER_AddMember(canBeCollidedWith, EntityLivingBase::canBeCollidedWith)
_CLASSREGISTER_AddMember(canBePushed, EntityLivingBase::canBePushed)
_CLASSREGISTER_AddMember(canBreatheUnderwater, EntityLivingBase::canBreatheUnderwater)
_CLASSREGISTER_AddMember(canEntityBeSeen, EntityLivingBase::canEntityBeSeen)
_CLASSREGISTER_AddMember(clearActivePotions, EntityLivingBase::clearActivePotions)
_CLASSREGISTER_AddMember(dismountEntity, EntityLivingBase::dismountEntity)
_CLASSREGISTER_AddMember(getAIMoveSpeed, EntityLivingBase::getAIMoveSpeed)
_CLASSREGISTER_AddMember(getAbsorptionAmount, EntityLivingBase::getAbsorptionAmount)
_CLASSREGISTER_AddMember(getActivePotionEffect, EntityLivingBase::getActivePotionEffect)
_CLASSREGISTER_AddMember(getActivePotionEffectById, EntityLivingBase::getActivePotionEffectById)
_CLASSREGISTER_AddMember(getActivePotionEffects, EntityLivingBase::getActivePotionEffects)
_CLASSREGISTER_AddMember(getAlwaysRenderNameTagForRender, EntityLivingBase::getAlwaysRenderNameTagForRender)
_CLASSREGISTER_AddMember(getArrowCountInEntity, EntityLivingBase::getArrowCountInEntity)
_CLASSREGISTER_AddMember(getAttackingEntity, EntityLivingBase::getAttackingEntity)
_CLASSREGISTER_AddMember(getAttributeMap, EntityLivingBase::getAttributeMap)
_CLASSREGISTER_AddMember(getCombatTracker, EntityLivingBase::getCombatTracker)
_CLASSREGISTER_AddMember(getCreatureAttribute, EntityLivingBase::getCreatureAttribute)
_CLASSREGISTER_AddMember(getEntityAttribute, EntityLivingBase::getEntityAttribute)
_CLASSREGISTER_AddMember(getEyeHeight, EntityLivingBase::getEyeHeight)
_CLASSREGISTER_AddMember(getHealth, EntityLivingBase::getHealth)
_CLASSREGISTER_AddMember(getLastActiveItems, EntityLivingBase::getLastActiveItems)
_CLASSREGISTER_AddMember(getLastActiveItemsCount, EntityLivingBase::getLastActiveItemsCount)
_CLASSREGISTER_AddMember(getLastAttacker, EntityLivingBase::getLastAttacker)
_CLASSREGISTER_AddMember(getLastAttackerTime, EntityLivingBase::getLastAttackerTime)
_CLASSREGISTER_AddMember(getLook, EntityLivingBase::getLook)
_CLASSREGISTER_AddMember(getLookVec, EntityLivingBase::getLookVec)
_CLASSREGISTER_AddMember(getMaxHealth, EntityLivingBase::getMaxHealth)
_CLASSREGISTER_AddMember(getPosition, EntityLivingBase::getPosition)
_CLASSREGISTER_AddMember(getRNG, EntityLivingBase::getRNG)
_CLASSREGISTER_AddMember(getRotationYawHead, EntityLivingBase::getRotationYawHead)
_CLASSREGISTER_AddMember(getSwingProgress, EntityLivingBase::getSwingProgress)
_CLASSREGISTER_AddMember(getTotalArmorValue, EntityLivingBase::getTotalArmorValue)
_CLASSREGISTER_AddMember(heal, EntityLivingBase::heal)
_CLASSREGISTER_AddMember(doHurt, EntityLivingBase::doHurt)
_CLASSREGISTER_AddStaticMember(initialize, EntityLivingBase::initialize)
_CLASSREGISTER_AddMember(isChild, EntityLivingBase::isChild)
_CLASSREGISTER_AddMember(isClientWorld, EntityLivingBase::isClientWorld)
_CLASSREGISTER_AddMember(isEntityAlive, EntityLivingBase::isEntityAlive)
_CLASSREGISTER_AddMember(isEntityUndead, EntityLivingBase::isEntityUndead)
_CLASSREGISTER_AddMember(isOnLadder, EntityLivingBase::isOnLadder)
_CLASSREGISTER_AddMember(isPlayerSleeping, EntityLivingBase::isPlayerSleeping)
_CLASSREGISTER_AddMember_Override(isPotionActive, EntityLivingBase::isPotionActive,bool ,int )
_CLASSREGISTER_AddMember_Override(isPotionActive1, EntityLivingBase::isPotionActive,bool ,Potion * )
_CLASSREGISTER_AddMember(isPotionApplicable, EntityLivingBase::isPotionApplicable)
_CLASSREGISTER_AddMember(knockBack, EntityLivingBase::knockBack)
_CLASSREGISTER_AddMember(moveEntityWithHeading, EntityLivingBase::moveEntityWithHeading)
_CLASSREGISTER_AddMember(onDeath, EntityLivingBase::onDeath)
_CLASSREGISTER_AddMember(onEntityUpdate, EntityLivingBase::onEntityUpdate)
_CLASSREGISTER_AddMember(onItemPickup, EntityLivingBase::onItemPickup)
_CLASSREGISTER_AddMember(onLivingUpdate, EntityLivingBase::onLivingUpdate)
_CLASSREGISTER_AddMember(onUpdate, EntityLivingBase::onUpdate)
_CLASSREGISTER_AddMember(performHurtAnimation, EntityLivingBase::performHurtAnimation)
_CLASSREGISTER_AddMember(rayTrace, EntityLivingBase::rayTrace)
_CLASSREGISTER_AddMember(readEntityFromNBT, EntityLivingBase::readEntityFromNBT)
_CLASSREGISTER_AddMember(removePotionEffect, EntityLivingBase::removePotionEffect)
_CLASSREGISTER_AddMember(removePotionEffectClient, EntityLivingBase::removePotionEffectClient)
_CLASSREGISTER_AddMember(renderBrokenItemStack, EntityLivingBase::renderBrokenItemStack)
_CLASSREGISTER_AddMember(setAIMoveSpeed, EntityLivingBase::setAIMoveSpeed)
_CLASSREGISTER_AddMember(setAbsorptionAmount, EntityLivingBase::setAbsorptionAmount)
_CLASSREGISTER_AddMember(setArrowCountInEntity, EntityLivingBase::setArrowCountInEntity)
_CLASSREGISTER_AddMember(setEntityHealth, EntityLivingBase::setEntityHealth)
_CLASSREGISTER_AddMember(setEntityMaxHealth, EntityLivingBase::setEntityMaxHealth)
_CLASSREGISTER_AddMember(setJumping, EntityLivingBase::setJumping)
_CLASSREGISTER_AddMember(setLastAttacker, EntityLivingBase::setLastAttacker)
_CLASSREGISTER_AddMember(setMoveForward, EntityLivingBase::setMoveForward)
_CLASSREGISTER_AddMember(setMoveStrafe, EntityLivingBase::setMoveStrafe)
_CLASSREGISTER_AddMember(setPositionAndRotation2, EntityLivingBase::setPositionAndRotation2)
_CLASSREGISTER_AddMember(setPositionAndUpdate, EntityLivingBase::setPositionAndUpdate)
_CLASSREGISTER_AddMember(setRotationYawHead, EntityLivingBase::setRotationYawHead)
_CLASSREGISTER_AddMember(setSprinting, EntityLivingBase::setSprinting)
_CLASSREGISTER_AddMember(swingItem, EntityLivingBase::swingItem)
_CLASSREGISTER_AddStaticMember(unInitialize, EntityLivingBase::unInitialize)
_CLASSREGISTER_AddMember(writeEntityToNBT, EntityLivingBase::writeEntityToNBT)
_CLASSREGISTER_AddVar(isSwingInProgress, EntityLivingBase::isSwingInProgress)
_CLASSREGISTER_AddVar(m_moving, EntityLivingBase::m_moving)
_END_REGISTER_CLASS()



/*
// Register Class EntityMob
_BEGIN_REGISTER_CLASS(EntityMob)
_CLASSREGISTER_AddBaseClass(EntityCreature /* implements IMob*///)
/*
_CLASSREGISTER_AddCtor(World * )
_CLASSREGISTER_AddMember(attackEntityAsMob, EntityMob::attackEntityAsMob)
_CLASSREGISTER_AddMember(attackEntityFrom, EntityMob::attackEntityFrom)
_CLASSREGISTER_AddMember(getBlockPathWeight, EntityMob::getBlockPathWeight)
_CLASSREGISTER_AddMember(getCanSpawnHere, EntityMob::getCanSpawnHere)
_CLASSREGISTER_AddMember(onLivingUpdate, EntityMob::onLivingUpdate)
_CLASSREGISTER_AddMember(onUpdate, EntityMob::onUpdate)
_END_REGISTER_CLASS()
*/




// Register Class EntityPlayer
_BEGIN_REGISTER_CLASS(EntityPlayer)
_CLASSREGISTER_AddBaseClass(EntityLivingBase)
_CLASSREGISTER_AddCtor(World * , const String & )
_CLASSREGISTER_AddMember(addChatMessage, EntityPlayer::addChatMessage)
_CLASSREGISTER_AddMember(setHoldItemActor, EntityPlayer::setHoldItemActor)
_CLASSREGISTER_AddMember(addExhaustion, EntityPlayer::addExhaustion)
_CLASSREGISTER_AddMember(addExperience, EntityPlayer::addExperience)
_CLASSREGISTER_AddMember(addExperienceLevel, EntityPlayer::addExperienceLevel)
_CLASSREGISTER_AddMember(addMovementStat, EntityPlayer::addMovementStat)
_CLASSREGISTER_AddMember(addScore, EntityPlayer::addScore)
_CLASSREGISTER_AddMember(addToPlayerScore, EntityPlayer::addToPlayerScore)
_CLASSREGISTER_AddMember(attackEntityFrom, EntityPlayer::attackEntityFrom)
_CLASSREGISTER_AddMember(attackTargetEntityWithCurrentItem, EntityPlayer::attackTargetEntityWithCurrentItem)
_CLASSREGISTER_AddMember(attckedByPlayer, EntityPlayer::attckedByPlayer)
_CLASSREGISTER_AddMember(canAttackPlayer, EntityPlayer::canAttackPlayer)
_CLASSREGISTER_AddMember(canEat, EntityPlayer::canEat)
_CLASSREGISTER_AddMember(canHarvestBlock, EntityPlayer::canHarvestBlock)
_CLASSREGISTER_AddMember(canPlayerEdit, EntityPlayer::canPlayerEdit)
_CLASSREGISTER_AddMember(clearItemInUse, EntityPlayer::clearItemInUse)
_CLASSREGISTER_AddMember(clonePlayer, EntityPlayer::clonePlayer)
_CLASSREGISTER_AddMember(closeScreen, EntityPlayer::closeScreen)
_CLASSREGISTER_AddMember(destroyCurrentEquippedItem, EntityPlayer::destroyCurrentEquippedItem)
_CLASSREGISTER_AddMember(dropOneItem, EntityPlayer::dropOneItem)
_CLASSREGISTER_AddMember(dropPlayerItem, EntityPlayer::dropPlayerItem)
_CLASSREGISTER_AddMember(dropPlayerItemWithRandomChoice, EntityPlayer::dropPlayerItemWithRandomChoice)
_CLASSREGISTER_AddMember(getAIMoveSpeed, EntityPlayer::getAIMoveSpeed)
_CLASSREGISTER_AddMember(getAbsorptionAmount, EntityPlayer::getAbsorptionAmount)
_CLASSREGISTER_AddMember(getActivatedBlock, EntityPlayer::getActivatedBlock)
_CLASSREGISTER_AddMember(getAlwaysRenderNameTagForRender, EntityPlayer::getAlwaysRenderNameTagForRender)
_CLASSREGISTER_AddMember(getArmorVisibility, EntityPlayer::getArmorVisibility)
_CLASSREGISTER_AddMember(getBedLocation, EntityPlayer::getBedLocation)
_CLASSREGISTER_AddMember(getBedOrientationInDegrees, EntityPlayer::getBedOrientationInDegrees)
_CLASSREGISTER_AddMember(getCommandSenderName, EntityPlayer::getCommandSenderName)
_CLASSREGISTER_AddMember(getCurrentArmor, EntityPlayer::getCurrentArmor)
_CLASSREGISTER_AddMember(getCurrentEquippedItem, EntityPlayer::getCurrentEquippedItem)
_CLASSREGISTER_AddMember(getCurrentItemOrArmor, EntityPlayer::getCurrentItemOrArmor)
_CLASSREGISTER_AddMember(getCurrentPlayerStrVsBlock, EntityPlayer::getCurrentPlayerStrVsBlock)
_CLASSREGISTER_AddMember(getEntityName, EntityPlayer::getEntityName)
_CLASSREGISTER_AddMember(setConcealPower, EntityPlayer::setConcealPower)
_CLASSREGISTER_AddMember(getEyeHeight, EntityPlayer::getEyeHeight)
_CLASSREGISTER_AddMember(getFoodStats, EntityPlayer::getFoodStats)
_CLASSREGISTER_AddMember(getHeldItem, EntityPlayer::getHeldItem)
_CLASSREGISTER_AddMember(getHeldItemId, EntityPlayer::getHeldItemId)
_CLASSREGISTER_AddMember_Override(getHideCape1, EntityPlayer::getHideCape,bool )
_CLASSREGISTER_AddMember(getInventoryEnderChest, EntityPlayer::getInventoryEnderChest)
_CLASSREGISTER_AddMember(getInventory, EntityPlayer::getInventory)
_CLASSREGISTER_AddMember(getItemInUse, EntityPlayer::getItemInUse)
_CLASSREGISTER_AddMember(getItemInUseCount, EntityPlayer::getItemInUseCount)
_CLASSREGISTER_AddMember(getItemInUseDuration, EntityPlayer::getItemInUseDuration)
_CLASSREGISTER_AddMember(getLastActiveItems, EntityPlayer::getLastActiveItems)
_CLASSREGISTER_AddMember(getScore, EntityPlayer::getScore)
_CLASSREGISTER_AddMember(getSleepTimer, EntityPlayer::getSleepTimer)
_CLASSREGISTER_AddMember(getTotalArmorValue, EntityPlayer::getTotalArmorValue)
_CLASSREGISTER_AddMember(getWorldPtr, EntityPlayer::getWorldPtr)
_CLASSREGISTER_AddMember(getYOffset, EntityPlayer::getYOffset)
_CLASSREGISTER_AddMember(interactWith, EntityPlayer::interactWith)
_CLASSREGISTER_AddMember(isBlocking, EntityPlayer::isBlocking)
_CLASSREGISTER_AddMember(isCurrentToolAdventureModeExempt, EntityPlayer::isCurrentToolAdventureModeExempt)
_CLASSREGISTER_AddMember(isEntityInsideOpaqueBlock, EntityPlayer::isEntityInsideOpaqueBlock)
_CLASSREGISTER_AddMember(isInvisibleToPlayer, EntityPlayer::isInvisibleToPlayer)
_CLASSREGISTER_AddMember(isPlayerFullyAsleep, EntityPlayer::isPlayerFullyAsleep)
_CLASSREGISTER_AddMember(isPlayerSleeping, EntityPlayer::isPlayerSleeping)
_CLASSREGISTER_AddMember(isPushedByWater, EntityPlayer::isPushedByWater)
_CLASSREGISTER_AddMember(isSpawnForced, EntityPlayer::isSpawnForced)
_CLASSREGISTER_AddMember(isUsingItem, EntityPlayer::isUsingItem)
_CLASSREGISTER_AddMember(moveEntityWithHeading, EntityPlayer::moveEntityWithHeading)
_CLASSREGISTER_AddMember(onCriticalHit, EntityPlayer::onCriticalHit)
_CLASSREGISTER_AddMember(onDeath, EntityPlayer::onDeath)
_CLASSREGISTER_AddMember(onEnchantmentCritical, EntityPlayer::onEnchantmentCritical)
_CLASSREGISTER_AddMember(onKillEntity, EntityPlayer::onKillEntity)
_CLASSREGISTER_AddMember(onLivingUpdate, EntityPlayer::onLivingUpdate)
_CLASSREGISTER_AddMember(onUpdate, EntityPlayer::onUpdate)
_CLASSREGISTER_AddMember(playSound, EntityPlayer::playSound)
_CLASSREGISTER_AddMember(preparePlayerToSpawn, EntityPlayer::preparePlayerToSpawn)
_CLASSREGISTER_AddMember(readEntityFromNBT, EntityPlayer::readEntityFromNBT)
_CLASSREGISTER_AddMember(respawnPlayer, EntityPlayer::respawnPlayer)
_CLASSREGISTER_AddMember(sendPlayerAbilities, EntityPlayer::sendPlayerAbilities)
_CLASSREGISTER_AddMember(setAbsorptionAmount, EntityPlayer::setAbsorptionAmount)
_CLASSREGISTER_AddMember(setActivatedBlock, EntityPlayer::setActivatedBlock)
_CLASSREGISTER_AddMember(setCurrentItemOrArmor, EntityPlayer::setCurrentItemOrArmor)
_CLASSREGISTER_AddMember(setDead, EntityPlayer::setDead)
_CLASSREGISTER_AddMember(setGameType, EntityPlayer::setGameType)
_CLASSREGISTER_AddMember(setInWeb, EntityPlayer::setInWeb)
_CLASSREGISTER_AddMember(setItemInUse, EntityPlayer::setItemInUse)
_CLASSREGISTER_AddMember(setOnFire, EntityPlayer::setOnFire)
_CLASSREGISTER_AddMember(setScore, EntityPlayer::setScore)
_CLASSREGISTER_AddMember(setSpawnChunk, EntityPlayer::setSpawnChunk)
_CLASSREGISTER_AddMember(shouldHeal, EntityPlayer::shouldHeal)
_CLASSREGISTER_AddMember(simpleAttackPlayerWithCurrentItem, EntityPlayer::simpleAttackPlayerWithCurrentItem)
_CLASSREGISTER_AddMember(sleepInBedAt, EntityPlayer::sleepInBedAt)
_CLASSREGISTER_AddMember(stopUsingItem, EntityPlayer::stopUsingItem)
_CLASSREGISTER_AddMember(syncPlayerMovement, EntityPlayer::syncPlayerMovement)
_CLASSREGISTER_AddStaticMember(verifyRespawnCoordinates, EntityPlayer::verifyRespawnCoordinates)
_CLASSREGISTER_AddMember(wakeUpPlayer, EntityPlayer::wakeUpPlayer)
_CLASSREGISTER_AddMember(writeEntityToNBT, EntityPlayer::writeEntityToNBT)
_CLASSREGISTER_AddMember(xpBarCap, EntityPlayer::xpBarCap)
_CLASSREGISTER_AddMember(setTeam, EntityPlayer::setTeamId)
_CLASSREGISTER_AddMember(setTeamId, EntityPlayer::setTeamId)
_CLASSREGISTER_AddMember(addOwnVehicle, EntityPlayer::addOwnVehicle)
_CLASSREGISTER_AddMember(getYaw, EntityPlayer::getYaw)
_CLASSREGISTER_AddMember(getPitch, EntityPlayer::getPitch)
_CLASSREGISTER_AddMember(getSex, EntityPlayer::getSex)
_CLASSREGISTER_AddMember(isWatchMode, EntityPlayer::isWatchMode)
_CLASSREGISTER_AddMember(getIsFlying, EntityPlayer::getIsFlying)
_CLASSREGISTER_AddMember(getWallet, EntityPlayer::getWallet)
_CLASSREGISTER_AddMember(isOnFlyingMount, EntityPlayer::isOnFlyingMount)
_CLASSREGISTER_AddMember(getFlyingMountId, EntityPlayer::getFlyingMountId)
_CLASSREGISTER_AddMember(getFlyingMount, EntityPlayer::getFlyingMount)
_CLASSREGISTER_AddMember(getOnFlyingMount, EntityPlayer::getOnFlyingMount)
_CLASSREGISTER_AddMember(getOffFlyingMount, EntityPlayer::getOffFlyingMount)
_CLASSREGISTER_AddMember(isOnFloatingMount, EntityPlayer::isOnFloatingMount)
_CLASSREGISTER_AddMember(getFloatingMountId, EntityPlayer::getFloatingMountId)
_CLASSREGISTER_AddMember(getFloatingMount, EntityPlayer::getFloatingMount)
_CLASSREGISTER_AddMember(getOnFloatingMount, EntityPlayer::getOnFloatingMount)
_CLASSREGISTER_AddMember(getOffFloatingMount, EntityPlayer::getOffFloatingMount)
_CLASSREGISTER_AddMember(setInsertUpperAction, EntityPlayer::setInsertUpperAction)
_CLASSREGISTER_AddMember(setInsertUpperAction1, EntityPlayer::setInsertUpperAction1)
_CLASSREGISTER_AddMember(stopInsertUpperAction, EntityPlayer::stopInsertUpperAction)
_CLASSREGISTER_AddMember(setUpperActionListenable, EntityPlayer::setUpperActionListenable)
_CLASSREGISTER_AddMember(getPrevBaseAction, EntityPlayer::getPrevBaseAction)
_CLASSREGISTER_AddMember(getPrevUpperAction, EntityPlayer::getPrevUpperAction)
_CLASSREGISTER_AddMember(getBaseAction, EntityPlayer::getBaseAction)
_CLASSREGISTER_AddMember(getUpperAction, EntityPlayer::getUpperAction)
_CLASSREGISTER_AddMember(setUpperAction1, EntityPlayer::setUpperAction1)
_CLASSREGISTER_AddMember(addCustomEffect, EntityPlayer::addCustomEffect)
_CLASSREGISTER_AddMember(getPlatformUserId, EntityPlayer::getPlatformUserId)
_CLASSREGISTER_AddMember(setActorInvisible, EntityPlayer::setActorInvisible)
_CLASSREGISTER_AddMember(isActorInvisible, EntityPlayer::isActorInvisible)
_CLASSREGISTER_AddMember(getTeamId, EntityPlayer::getTeamId)
_CLASSREGISTER_AddMember(enableXRay, EntityPlayer::enableXRay)
_CLASSREGISTER_AddMember(disableXRay, EntityPlayer::disableXRay)
_CLASSREGISTER_AddMember(isEnableXRay, EntityPlayer::isEnableXRay)
_CLASSREGISTER_AddMember(getXRayColor, EntityPlayer::getXRayColor)
_CLASSREGISTER_AddMember(getShowName, EntityPlayer::getShowName)
_CLASSREGISTER_AddMember(setShowName, EntityPlayer::setShowName)
_CLASSREGISTER_AddMember(setCameraLocked, EntityPlayer::setCameraLocked)
_CLASSREGISTER_AddVar(m_isConcealPower, EntityPlayer::m_isConcealPower)
_CLASSREGISTER_AddVar(m_holdItemId, EntityPlayer::m_holdItemId)
_CLASSREGISTER_AddVar(m_holdItemActor, EntityPlayer::m_holdItemActor)
_CLASSREGISTER_AddVar(m_holdItemChanged, EntityPlayer::m_holdItemChanged)
_CLASSREGISTER_AddVar(m_needUpdateUpperAction, EntityPlayer::m_needUpdateUpperAction)
_CLASSREGISTER_AddVar(m_playActionName, EntityPlayer::m_playActionName)
_CLASSREGISTER_AddVar(m_isPeopleActor, EntityPlayer::m_isPeopleActor)
_END_REGISTER_CLASS()


// Register Class FoodStats
_BEGIN_REGISTER_CLASS(FoodStats)
_CLASSREGISTER_AddBaseClass(ObjectAlloc)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddMember(addExhaustion, FoodStats::addExhaustion)
_CLASSREGISTER_AddMember_Override(addStats, FoodStats::addStats,void ,int ,float )
_CLASSREGISTER_AddMember_Override(addStats, FoodStats::addStats,void ,ItemFood * )
_CLASSREGISTER_AddMember(foodLevelListenable, FoodStats::foodLevelListenable)
_CLASSREGISTER_AddMember(waterlevelListenable, FoodStats::waterlevelListenable)
_CLASSREGISTER_AddMember(getFoodLevel, FoodStats::getFoodLevel)
_CLASSREGISTER_AddMember(getPrevFoodLevel, FoodStats::getPrevFoodLevel)
_CLASSREGISTER_AddMember(setmaxFoodLevel, FoodStats::setmaxFoodLevel)
_CLASSREGISTER_AddMember(getWaterLevel, FoodStats::getWaterLevel)
_CLASSREGISTER_AddMember(getmaxWaterLevel, FoodStats::getmaxWaterLevel)
_CLASSREGISTER_AddMember(setFoodHealValue, FoodStats::setFoodHealValue)
_CLASSREGISTER_AddMember(getSaturationLevel, FoodStats::getSaturationLevel)
_CLASSREGISTER_AddMember(needFood, FoodStats::needFood)
_CLASSREGISTER_AddMember(onUpdate, FoodStats::onUpdate)
_CLASSREGISTER_AddMember(readNBT, FoodStats::readNBT)
_CLASSREGISTER_AddMember(saturationLevelListenable, FoodStats::saturationLevelListenable)
_CLASSREGISTER_AddMember(setFoodLevel, FoodStats::setFoodLevel)
_CLASSREGISTER_AddMember(setWaterLevel, FoodStats::setWaterLevel)
_CLASSREGISTER_AddMember(setmaxWaterLevel, FoodStats::setmaxWaterLevel)
_CLASSREGISTER_AddMember(setFoodSaturationLevel, FoodStats::setFoodSaturationLevel)
_CLASSREGISTER_AddMember(writeNBT, FoodStats::writeNBT)
_END_REGISTER_CLASS()


// Register Class PlayerCapabilities
_BEGIN_REGISTER_CLASS(PlayerCapabilities)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddMember(getFlySpeed, PlayerCapabilities::getFlySpeed)
_CLASSREGISTER_AddMember(getWalkSpeed, PlayerCapabilities::getWalkSpeed)
_CLASSREGISTER_AddMember(readCapabilitiesFromNBT, PlayerCapabilities::readCapabilitiesFromNBT)
_CLASSREGISTER_AddMember(setFlySpeed, PlayerCapabilities::setFlySpeed)
_CLASSREGISTER_AddMember(setPlayerWalkSpeed, PlayerCapabilities::setPlayerWalkSpeed)
_CLASSREGISTER_AddMember(writeCapabilitiesToNBT, PlayerCapabilities::writeCapabilitiesToNBT)
_END_REGISTER_CLASS()


// Register Class EntityXPOrb
_BEGIN_REGISTER_CLASS(EntityXPOrb)
_CLASSREGISTER_AddBaseClass(Entity)
_CLASSREGISTER_AddCtor(World * , const Vector3 & , int )
_CLASSREGISTER_AddCtor(World * )
_CLASSREGISTER_AddMember(attackEntityFrom, EntityXPOrb::attackEntityFrom)
_CLASSREGISTER_AddMember(canAttackWithItem, EntityXPOrb::canAttackWithItem)
_CLASSREGISTER_AddMember(getBrightnessForRender, EntityXPOrb::getBrightnessForRender)
_CLASSREGISTER_AddMember(getTextureByXP, EntityXPOrb::getTextureByXP)
_CLASSREGISTER_AddStaticMember(getXPSplit, EntityXPOrb::getXPSplit)
_CLASSREGISTER_AddMember(getXpValue, EntityXPOrb::getXpValue)
_CLASSREGISTER_AddMember(handleWaterMovement, EntityXPOrb::handleWaterMovement)
_CLASSREGISTER_AddMember(onCollideWithPlayer, EntityXPOrb::onCollideWithPlayer)
_CLASSREGISTER_AddMember(onUpdate, EntityXPOrb::onUpdate)
_CLASSREGISTER_AddMember(readEntityFromNBT, EntityXPOrb::readEntityFromNBT)
_CLASSREGISTER_AddMember(writeEntityToNBT, EntityXPOrb::writeEntityToNBT)
_END_REGISTER_CLASS()


// Register Class Explosion
_BEGIN_REGISTER_CLASS(Explosion)
_CLASSREGISTER_AddBaseClass(ObjectAlloc)
_CLASSREGISTER_AddCtor(World * , Entity * , EntityLivingBase * , const Vector3 & , float )
_CLASSREGISTER_AddMember(doExplosionA, Explosion::doExplosionA)
_CLASSREGISTER_AddMember(doExplosionB, Explosion::doExplosionB)
_CLASSREGISTER_AddMember(getPlayerKnockbackMap, Explosion::getPlayerKnockbackMap)
_END_REGISTER_CLASS()


// Register Class EntityThrowable
_BEGIN_REGISTER_CLASS(EntityThrowable)
_CLASSREGISTER_AddBaseClass(Entity)
_CLASSREGISTER_AddMember(setHeadingFromThrower, EntityThrowable::setHeadingFromThrower)
_END_REGISTER_CLASS()


// Register Class EntitySkillThrowable
_BEGIN_REGISTER_CLASS(EntitySkillThrowable)
_CLASSREGISTER_AddBaseClass(EntityThrowable)
_CLASSREGISTER_AddMember(setItemSkillId, EntitySkillThrowable::setItemSkillId)
_CLASSREGISTER_AddMember(getItemSkillId, EntitySkillThrowable::getItemSkillId)
_CLASSREGISTER_AddMember(setReleaseDistance, EntitySkillThrowable::setReleaseDistance)
_CLASSREGISTER_AddMember(setMoveSpeed, EntitySkillThrowable::setMoveSpeed)
_CLASSREGISTER_AddMember(setCustomMoveSpeed, EntitySkillThrowable::setCustomMoveSpeed)
_CLASSREGISTER_AddMember(getMoveSpeed, EntitySkillThrowable::getMoveSpeed)
_CLASSREGISTER_AddMember(setDropSpeed, EntitySkillThrowable::setDropSpeed)
_CLASSREGISTER_AddMember(setCustomDropSpeed, EntitySkillThrowable::setCustomDropSpeed)
_CLASSREGISTER_AddMember(getDropSpeed, EntitySkillThrowable::getDropSpeed)
_CLASSREGISTER_AddMember(setAtlasName, EntitySkillThrowable::setAtlasName)
_CLASSREGISTER_AddMember(getAtlasName, EntitySkillThrowable::getAtlasName)
_CLASSREGISTER_AddMember(setItemIconName, EntitySkillThrowable::setItemIconName)
_CLASSREGISTER_AddMember(getItemIconName, EntitySkillThrowable::getItemIconName)
_CLASSREGISTER_AddMember(setIsParabola, EntitySkillThrowable::setIsParabola)
_CLASSREGISTER_AddMember(setSkillId, EntitySkillThrowable::setSkillId)
_CLASSREGISTER_AddMember(setEffectName, EntitySkillThrowable::setEffectName)
_CLASSREGISTER_AddMember(getEffectName, EntitySkillThrowable::getEffectName)
_CLASSREGISTER_AddMember(setNotCustomSpeed, EntitySkillThrowable::setNotCustomSpeed)
_CLASSREGISTER_AddMember(getNotCustomSpeed, EntitySkillThrowable::getNotCustomSpeed)
_CLASSREGISTER_AddMember(isRenderActor, EntitySkillThrowable::isRenderActor)
_CLASSREGISTER_AddMember(setRenderActor, EntitySkillThrowable::setRenderActor)
_CLASSREGISTER_AddMember(setSkillDuration, EntitySkillThrowable::setSkillDuration)
_END_REGISTER_CLASS()


// Register Class EntityActorCannon
_BEGIN_REGISTER_CLASS(EntityActorCannon)
_CLASSREGISTER_AddBaseClass(Entity)
_CLASSREGISTER_AddMember(setActorName, EntityActorCannon::setActorName)
_CLASSREGISTER_AddMember(getActorName, EntityActorCannon::getActorName)
_CLASSREGISTER_AddMember(setBodyId, EntityActorCannon::setBodyId)
_CLASSREGISTER_AddMember(getBodyId, EntityActorCannon::getBodyId)
_CLASSREGISTER_AddMember(setBody, EntityActorCannon::setBody)
_CLASSREGISTER_AddMember(getBody, EntityActorCannon::getBody)
_CLASSREGISTER_AddMember(isCanObstruct, EntityActorCannon::isCanObstruct)
_CLASSREGISTER_AddMember(setCanObstruct, EntityActorCannon::setCanObstruct)
_CLASSREGISTER_AddMember(setContent, EntityActorCannon::setContent)
_CLASSREGISTER_AddMember(getContent, EntityActorCannon::getContent)
_CLASSREGISTER_AddMember(isShowContent, EntityActorCannon::isShowContent)
_CLASSREGISTER_AddMember(setHaloEffectName, EntityActorCannon::setHaloEffectName)
_CLASSREGISTER_AddMember(getHaloEffectName, EntityActorCannon::getHaloEffectName)
_CLASSREGISTER_AddMember(setHeadName, EntityActorCannon::setHeadName)
_CLASSREGISTER_AddMember(getHeadName, EntityActorCannon::getHeadName)
_CLASSREGISTER_AddMember(setSkillName, EntityActorCannon::setSkillName)
_CLASSREGISTER_AddMember(getSkillName, EntityActorCannon::getSkillName)
_END_REGISTER_CLASS()


// Register Class EntityActorNpc
_BEGIN_REGISTER_CLASS(EntityActorNpc)
_CLASSREGISTER_AddBaseClass(Entity)
_CLASSREGISTER_AddMember(setActorName, EntityActorNpc::setActorName)
_CLASSREGISTER_AddMember(getActorName, EntityActorNpc::getActorName)
_CLASSREGISTER_AddMember(setHeadName, EntityActorNpc::setHeadName)
_CLASSREGISTER_AddMember(getHeadName, EntityActorNpc::getHeadName)
_CLASSREGISTER_AddMember(setSkillName, EntityActorNpc::setSkillName)
_CLASSREGISTER_AddMember(getSkillName, EntityActorNpc::getSkillName)
_CLASSREGISTER_AddMember(setHaloEffectName, EntityActorNpc::setHaloEffectName)
_CLASSREGISTER_AddMember(getHaloEffectName, EntityActorNpc::getHaloEffectName)
_CLASSREGISTER_AddMember(setContent, EntityActorNpc::setContent)
_CLASSREGISTER_AddMember(getContent, EntityActorNpc::getContent)
_CLASSREGISTER_AddMember(isShowContent, EntityActorNpc::isShowContent)
_CLASSREGISTER_AddMember(setSuspended, EntityActorNpc::setSuspended)
_CLASSREGISTER_AddMember(getSuspended, EntityActorNpc::getSuspended)
_CLASSREGISTER_AddMember(isCanObstruct, EntityActorNpc::isCanObstruct)
_CLASSREGISTER_AddMember(setCanObstruct, EntityActorNpc::setCanObstruct)
_CLASSREGISTER_AddMember(setCanCollided, EntityActorNpc::setCanCollided)
_CLASSREGISTER_AddMember(setWeight, EntityActorNpc::setWeight)
_CLASSREGISTER_AddMember(getWeight, EntityActorNpc::getWeight)
_CLASSREGISTER_AddMember(setHeight, EntityActorNpc::setHeight)
_CLASSREGISTER_AddMember(getHeight, EntityActorNpc::getHeight)
_CLASSREGISTER_AddMember(setFlying, EntityActorNpc::setFlying)
_CLASSREGISTER_AddMember(setNoClip, EntityActorNpc::setNoClip)
_END_REGISTER_CLASS()


// Register Class EntityAircraft
_BEGIN_REGISTER_CLASS(EntityAircraft)
_CLASSREGISTER_AddBaseClass(Entity)
_CLASSREGISTER_AddMember(getAircraftId, EntityAircraft::getAircraftId)
_CLASSREGISTER_AddMember(setAirLine, EntityAircraft::setAirLine)
_CLASSREGISTER_AddMember(getOffPassenger, EntityAircraft::getOffPassenger)
_CLASSREGISTER_AddMember(addPassenger, EntityAircraft::addPassenger)
_CLASSREGISTER_AddMember(getOffAllPassengers, EntityAircraft::getOffAllPassengers)
_CLASSREGISTER_AddMember(getAirLineStartPosition, EntityAircraft::getAirLineStartPosition)
_CLASSREGISTER_AddMember(getAirLineEndPosition, EntityAircraft::getAirLineEndPosition)
_CLASSREGISTER_AddMember(isAircraftFlying, EntityAircraft::isAircraftFlying)
_CLASSREGISTER_AddMember(getSpeed, EntityAircraft::getSpeed)
_CLASSREGISTER_AddMember(setFlying, EntityAircraft::setFlying)
_CLASSREGISTER_AddMember(canLeaveAircraft, EntityAircraft::canLeaveAircraft)
_END_REGISTER_CLASS()


// Register Class EntityBird
_BEGIN_REGISTER_CLASS(EntityBird)
_CLASSREGISTER_AddBaseClass(EntityLiving)
_CLASSREGISTER_AddMember(changeDress, EntityBird::changeDress)
_CLASSREGISTER_AddMember(setActorName, EntityBird::setActorName)
_CLASSREGISTER_AddMember(setActorBody, EntityBird::setActorBody)
_CLASSREGISTER_AddMember(setActorBodyId, EntityBird::setActorBodyId)
_CLASSREGISTER_AddMember(setDressGlasses, EntityBird::setDressGlasses)
_CLASSREGISTER_AddMember(setDressHat, EntityBird::setDressHat)
_CLASSREGISTER_AddMember(setDressBeak, EntityBird::setDressBeak)
_CLASSREGISTER_AddMember(setDressWing, EntityBird::setDressWing)
_CLASSREGISTER_AddMember(setDressTail, EntityBird::setDressTail)
_CLASSREGISTER_AddMember(setDressEffect, EntityBird::setDressEffect)
_CLASSREGISTER_AddMember(getActorName, EntityBird::getActorName)
_CLASSREGISTER_AddMember(getActorBody, EntityBird::getActorBody)
_CLASSREGISTER_AddMember(getActorBodyId, EntityBird::getActorBodyId)
_CLASSREGISTER_AddMember(getDressGlasses, EntityBird::getDressGlasses)
_CLASSREGISTER_AddMember(getDressHat, EntityBird::getDressHat)
_CLASSREGISTER_AddMember(getDressBeak, EntityBird::getDressBeak)
_CLASSREGISTER_AddMember(getDressWing, EntityBird::getDressWing)
_CLASSREGISTER_AddMember(getDressTail, EntityBird::getDressTail)
_CLASSREGISTER_AddMember(getActorBodyId, EntityBird::getActorBodyId)
_CLASSREGISTER_AddMember(getDressEffect, EntityBird::getDressEffect)
_CLASSREGISTER_AddMember(setNameLang, EntityBird::setNameLang)
_CLASSREGISTER_AddMember(getNameLang, EntityBird::getNameLang)
_CLASSREGISTER_AddMember(setCurrentTargetEntityId, EntityBird::setCurrentTargetEntityId)
_CLASSREGISTER_AddMember(getCurrentTargetEntityId, EntityBird::getCurrentTargetEntityId)
_CLASSREGISTER_AddMember(setSpeedAdditionLevel, EntityBird::setSpeedAdditionLevel)
_CLASSREGISTER_AddMember(destroyConvertEffects, EntityBird::destroyConvertEffects)
_END_REGISTER_CLASS()


// Register Class EntityBlockman
_BEGIN_REGISTER_CLASS(EntityBlockman)
_CLASSREGISTER_AddBaseClass(Entity)
_CLASSREGISTER_AddMember(setNameLang, EntityBlockman::setNameLang)
_CLASSREGISTER_AddMember(getNameLang, EntityBlockman::getNameLang)
_CLASSREGISTER_AddMember(setActorName, EntityBlockman::setActorName)
_CLASSREGISTER_AddMember(getActorName, EntityBlockman::getActorName)
_CLASSREGISTER_AddMember(setActorBody, EntityBlockman::setActorBody)
_CLASSREGISTER_AddMember(getActorBody, EntityBlockman::getActorBody)
_CLASSREGISTER_AddMember(setActorBodyId, EntityBlockman::setActorBodyId)
_CLASSREGISTER_AddMember(getActorBodyId, EntityBlockman::getActorBodyId)
_CLASSREGISTER_AddMember(setCurrentMaxSpeed, EntityBlockman::setCurrentMaxSpeed)
_CLASSREGISTER_AddMember(getCurrentMaxSpeed, EntityBlockman::getCurrentMaxSpeed)
_CLASSREGISTER_AddMember(setHealth, EntityBlockman::setHealth)
_CLASSREGISTER_AddMember(setMaxHealth, EntityBlockman::setMaxHealth)
_CLASSREGISTER_AddMember(getHealth, EntityBlockman::getHealth)
_CLASSREGISTER_AddMember(getMaxHealth, EntityBlockman::getMaxHealth)
_END_REGISTER_CLASS()


// Register Class EntityBlockmanEmpty
_BEGIN_REGISTER_CLASS(EntityBlockmanEmpty)
_CLASSREGISTER_AddBaseClass(EntityBlockman)
_CLASSREGISTER_AddMember(reverseDirection, EntityBlockmanEmpty::reverseDirection)
_CLASSREGISTER_AddMember(changeDirection, EntityBlockmanEmpty::changeDirection)
_CLASSREGISTER_AddMember(getLongHitTimes, EntityBlockmanEmpty::getLongHitTimes)
_CLASSREGISTER_AddMember(setLongHitTimes, EntityBlockmanEmpty::setLongHitTimes)
_CLASSREGISTER_AddMember(canLongHit, EntityBlockmanEmpty::canLongHit)
_CLASSREGISTER_AddMember(setNeedRecordRoute, EntityBlockmanEmpty::setNeedRecordRoute)
_CLASSREGISTER_AddMember(setCurSpeed, EntityBlockmanEmpty::setCurSpeed)
_CLASSREGISTER_AddMember(setSpeedAddtion, EntityBlockmanEmpty::setSpeedAddtion)
_CLASSREGISTER_AddMember(setNameLang, EntityBlockmanEmpty::setNameLang)
_CLASSREGISTER_AddMember(setActorName, EntityBlockmanEmpty::setActorName)
_CLASSREGISTER_AddMember(setActorBody, EntityBlockmanEmpty::setActorBody)
_CLASSREGISTER_AddMember(setActorBodyId, EntityBlockmanEmpty::setActorBodyId)
_CLASSREGISTER_AddMember(setCurrentMaxSpeed, EntityBlockmanEmpty::setCurrentMaxSpeed)
_CLASSREGISTER_AddMember(isNeedRecordRoute, EntityBlockmanEmpty::isNeedRecordRoute)
_CLASSREGISTER_AddMember(getCurSpeed, EntityBlockmanEmpty::getCurSpeed)
_CLASSREGISTER_AddMember(getSpeedAddtion, EntityBlockmanEmpty::getSpeedAddtion)
_CLASSREGISTER_AddMember(getMoveSpeed, EntityBlockmanEmpty::getMoveSpeed)
_CLASSREGISTER_AddMember(setOnFrozen, EntityBlockmanEmpty::setOnFrozen)
_CLASSREGISTER_AddMember(setNeedPlayedGuide, EntityBlockmanEmpty::setNeedPlayedGuide)
_CLASSREGISTER_AddMember(setYOffsetForBloodStrip, EntityBlockmanEmpty::setYOffsetForBloodStrip)
_CLASSREGISTER_AddMember(isFrozen, EntityBlockmanEmpty::isFrozen)
_CLASSREGISTER_AddMember(getFrozenTime, EntityBlockmanEmpty::getFrozenTime)
_CLASSREGISTER_AddMember(setHurting, EntityBlockmanEmpty::setHurting)
_CLASSREGISTER_AddMember(setSkillName, EntityBlockmanEmpty::setSkillName)
_END_REGISTER_CLASS()


// Register Class EntityBuildNpc
_BEGIN_REGISTER_CLASS(EntityBuildNpc)
_CLASSREGISTER_AddBaseClass(Entity)
_CLASSREGISTER_AddMember(setActorName, EntityBuildNpc::setActorName)
_CLASSREGISTER_AddMember(getActorName, EntityBuildNpc::getActorName)
_CLASSREGISTER_AddMember(setName, EntityBuildNpc::setName)
_CLASSREGISTER_AddMember(getName, EntityBuildNpc::getName)
_CLASSREGISTER_AddMember(setBuildType, EntityBuildNpc::setBuildType)
_CLASSREGISTER_AddMember(getBuildType, EntityBuildNpc::getBuildType)
_CLASSREGISTER_AddMember(setNameLang, EntityBuildNpc::setNameLang)
_CLASSREGISTER_AddMember(getNameLang, EntityBuildNpc::getNameLang)
_CLASSREGISTER_AddMember(setDesc, EntityBuildNpc::setDesc)
_CLASSREGISTER_AddMember(getDesc, EntityBuildNpc::getDesc)
_CLASSREGISTER_AddMember(setActorBody, EntityBuildNpc::setActorBody)
_CLASSREGISTER_AddMember(getActorBody, EntityBuildNpc::getActorBody)
_CLASSREGISTER_AddMember(setActorBodyId, EntityBuildNpc::setActorBodyId)
_CLASSREGISTER_AddMember(getActorBodyId, EntityBuildNpc::getActorBodyId)
_CLASSREGISTER_AddMember(setActorId, EntityBuildNpc::setActorId)
_END_REGISTER_CLASS()


// Register Class EntitySessionNpc
_BEGIN_REGISTER_CLASS(EntitySessionNpc)
_CLASSREGISTER_AddBaseClass(Entity)
_CLASSREGISTER_AddMember(setActorName, EntitySessionNpc::setActorName)
_CLASSREGISTER_AddMember(getActorName, EntitySessionNpc::getActorName)
_CLASSREGISTER_AddMember(setSessionType, EntitySessionNpc::setSessionType)
_CLASSREGISTER_AddMember(getSessionType, EntitySessionNpc::getSessionType)
_CLASSREGISTER_AddMember(setSessionContent, EntitySessionNpc::setSessionContent)
_CLASSREGISTER_AddMember(getSessionContent, EntitySessionNpc::getSessionContent)
_CLASSREGISTER_AddMember(setNameLang, EntitySessionNpc::setNameLang)
_CLASSREGISTER_AddMember(getNameLang, EntitySessionNpc::getNameLang)
_CLASSREGISTER_AddMember(setName, EntitySessionNpc::setName)
_CLASSREGISTER_AddMember(getName, EntitySessionNpc::getName)
_CLASSREGISTER_AddMember(setEffectName, EntitySessionNpc::setEffectName)
_CLASSREGISTER_AddMember(getEffectName, EntitySessionNpc::getEffectName)
_CLASSREGISTER_AddMember(setTimeLeft, EntitySessionNpc::setTimeLeft)
_CLASSREGISTER_AddMember(getTimeLeft, EntitySessionNpc::getTimeLeft)
_CLASSREGISTER_AddMember(setActorBody, EntitySessionNpc::setActorBody)
_CLASSREGISTER_AddMember(getActorBody, EntitySessionNpc::getActorBody)
_CLASSREGISTER_AddMember(setActorBodyId, EntitySessionNpc::setActorBodyId)
_CLASSREGISTER_AddMember(getActorBodyId, EntitySessionNpc::getActorBodyId)
_CLASSREGISTER_AddMember(setActorAction, EntitySessionNpc::setActorAction)
_CLASSREGISTER_AddMember(getActorAction, EntitySessionNpc::getActorAction)
_CLASSREGISTER_AddMember(setPerson, EntitySessionNpc::setPerson)
_CLASSREGISTER_AddMember(isPerson, EntitySessionNpc::isPerson)
_CLASSREGISTER_AddMember(setSuspended, EntitySessionNpc::setSuspended)
_CLASSREGISTER_AddMember(getSuspended, EntitySessionNpc::getSuspended)
_CLASSREGISTER_AddMember(setTimeLeftByUser, EntitySessionNpc::setTimeLeftByUser)
_CLASSREGISTER_AddMember(setNameLangByUser, EntitySessionNpc::setNameLangByUser)
_CLASSREGISTER_AddMember(setActorNameByUser, EntitySessionNpc::setActorNameByUser)
_CLASSREGISTER_AddMember(setActorBodyByUser, EntitySessionNpc::setActorBodyByUser)
_CLASSREGISTER_AddMember(setActorBodyIdByUser, EntitySessionNpc::setActorBodyIdByUser)
_CLASSREGISTER_AddMember(setEffectNameByUser, EntitySessionNpc::setEffectNameByUser)
_CLASSREGISTER_AddMember(setSessionContentByUser, EntitySessionNpc::setSessionContentByUser)
_CLASSREGISTER_AddMember(setActorActionByUser, EntitySessionNpc::setActorActionByUser)
_CLASSREGISTER_AddMember(setCanCollidedByUser, EntitySessionNpc::setCanCollidedByUser)
_CLASSREGISTER_AddMember(getTimeLeftByUser, EntitySessionNpc::getTimeLeftByUser)
_CLASSREGISTER_AddMember(getNameLangByUser, EntitySessionNpc::getNameLangByUser)
_CLASSREGISTER_AddMember(getActorNameByUser, EntitySessionNpc::getActorNameByUser)
_CLASSREGISTER_AddMember(getActorBodyByUser, EntitySessionNpc::getActorBodyByUser)
_CLASSREGISTER_AddMember(getActorBodyIdByUser, EntitySessionNpc::getActorBodyIdByUser)
_CLASSREGISTER_AddMember(getActorActionByUser, EntitySessionNpc::getActorActionByUser)
_CLASSREGISTER_AddMember(getEffectNameByUser, EntitySessionNpc::getEffectNameByUser)
_CLASSREGISTER_AddMember(getSessionContentByUser, EntitySessionNpc::getSessionContentByUser)
_CLASSREGISTER_AddMember(isCanCollidedByUser, EntitySessionNpc::isCanCollidedByUser)
_CLASSREGISTER_AddMember(setCanCollided, EntitySessionNpc::setCanCollided)
_CLASSREGISTER_AddMember(setHeadNameMulTickInfo, EntitySessionNpc::setHeadNameMulTickInfo)
_CLASSREGISTER_AddMember(getInfoTime, EntitySessionNpc::getInfoTime)
_CLASSREGISTER_AddMember(getInfoLv, EntitySessionNpc::getInfoLv)
_CLASSREGISTER_AddMember(getStringMsg, EntitySessionNpc::getStringMsg)
_END_REGISTER_CLASS()


// Register Class EntityBulletin
_BEGIN_REGISTER_CLASS(EntityBulletin)
_CLASSREGISTER_AddBaseClass(EntitySessionNpc)
_CLASSREGISTER_AddMember(setRank, EntityBulletin::setRank)
_CLASSREGISTER_AddMember(setRankByUserId, EntityBulletin::setRankByUserId)
_CLASSREGISTER_AddMember(setRanks, EntityBulletin::setRanks)
_CLASSREGISTER_AddMember(getRanks, EntityBulletin::getRanks)
_CLASSREGISTER_AddMember(getRankByUserId, EntityBulletin::getRankByUserId)
_CLASSREGISTER_AddMember(getRank, EntityBulletin::getRank)
_CLASSREGISTER_AddMember(setBulletinId, EntityBulletin::setBulletinId)
_CLASSREGISTER_AddMember(getBulletinId, EntityBulletin::getBulletinId)
_CLASSREGISTER_AddMember(setCanBeCollidedWith, EntityBulletin::setCanBeCollidedWith)
_END_REGISTER_CLASS()


// Register Class EntityCreature
_BEGIN_REGISTER_CLASS(EntityCreature)
_CLASSREGISTER_AddBaseClass(EntityLiving)
_CLASSREGISTER_AddMember(setUserId, EntityCreature::setUserId)
_CLASSREGISTER_AddMember(setActorName, EntityCreature::setActorName)
_CLASSREGISTER_AddMember(getActorName, EntityCreature::getActorName)
_CLASSREGISTER_AddMember(setCanFly, EntityCreature::setCanFly)
_CLASSREGISTER_AddMember(setNameLang, EntityCreature::setNameLang)
_CLASSREGISTER_AddMember(getNameLang, EntityCreature::getNameLang)
_CLASSREGISTER_AddMember(setTeamId, EntityCreature::setTeamId)
_CLASSREGISTER_AddMember(getTeamId, EntityCreature::getTeamId)
_CLASSREGISTER_AddMember(setSpeedAdditionLevel, EntityCreature::setSpeedAdditionLevel)
_CLASSREGISTER_AddMember(setCurrentTargetEntityId, EntityCreature::setCurrentTargetEntityId)
_CLASSREGISTER_AddMember(getCurrentTargetEntityId, EntityCreature::getCurrentTargetEntityId)
_CLASSREGISTER_AddMember(isBase, EntityCreature::isBase)
_CLASSREGISTER_AddMember(isBoss, EntityCreature::isBoss)
_CLASSREGISTER_AddMember(isMonster, EntityCreature::isMonster)
_CLASSREGISTER_AddMember(getMonsterId, EntityCreature::getMonsterId)
_CLASSREGISTER_AddMember(getAttackDistance, EntityCreature::getAttackDistance)
_CLASSREGISTER_AddMember(getSkillDistance, EntityCreature::getSkillDistance)
_CLASSREGISTER_AddMember(getPathToPos, EntityCreature::getPathToPos)
_CLASSREGISTER_AddMember(getPathToEntity, EntityCreature::getPathToEntity)
_END_REGISTER_CLASS()


// Register Class EntityCreatureBullet
_BEGIN_REGISTER_CLASS(EntityCreatureBullet)
_CLASSREGISTER_AddBaseClass(Entity)
_CLASSREGISTER_AddMember(getThrowerId, EntityCreatureBullet::getThrowerId)
_CLASSREGISTER_AddMember(getTargetId, EntityCreatureBullet::getTargetId)
_CLASSREGISTER_AddMember(setSprite, EntityCreatureBullet::setSprite)
_CLASSREGISTER_AddMember(setBombEffect, EntityCreatureBullet::setBombEffect)
_CLASSREGISTER_AddMember(setYawY, EntityCreatureBullet::setYawY)
_CLASSREGISTER_AddMember(setSpeedFactor, EntityCreatureBullet::setSpeedFactor)
_CLASSREGISTER_AddMember(setBox, EntityCreatureBullet::setBox)
_CLASSREGISTER_AddMember(setEffectScale, EntityCreatureBullet::setEffectScale)
_CLASSREGISTER_AddMember(setSpriteScale, EntityCreatureBullet::setSpriteScale)
_CLASSREGISTER_AddMember(getEffectScale, EntityCreatureBullet::getEffectScale)
_CLASSREGISTER_AddMember(getSpriteScale, EntityCreatureBullet::getSpriteScale)
_END_REGISTER_CLASS()


// Register Class EntityDecoration
_BEGIN_REGISTER_CLASS(EntityDecoration)
_CLASSREGISTER_AddBaseClass(Entity)
_CLASSREGISTER_AddMember(setDecorationId, EntityDecoration::setDecorationId)
_CLASSREGISTER_AddMember(getDecorationId, EntityDecoration::getDecorationId)
_CLASSREGISTER_AddMember(setActorName, EntityDecoration::setActorName)
_CLASSREGISTER_AddMember(getActorName, EntityDecoration::getActorName)
_CLASSREGISTER_AddMember(setNameLang, EntityDecoration::setNameLang)
_CLASSREGISTER_AddMember(getNameLang, EntityDecoration::getNameLang)
_CLASSREGISTER_AddMember(setName, EntityDecoration::setName)
_CLASSREGISTER_AddMember(getName, EntityDecoration::getName)
_CLASSREGISTER_AddMember(setEffectName, EntityDecoration::setEffectName)
_CLASSREGISTER_AddMember(getEffectName, EntityDecoration::getEffectName)
_CLASSREGISTER_AddMember(setActorBody, EntityDecoration::setActorBody)
_CLASSREGISTER_AddMember(getActorBody, EntityDecoration::getActorBody)
_CLASSREGISTER_AddMember(setActorBodyId, EntityDecoration::setActorBodyId)
_CLASSREGISTER_AddMember(getActorBodyId, EntityDecoration::getActorBodyId)
_CLASSREGISTER_AddMember(setActorAction, EntityDecoration::setActorAction)
_CLASSREGISTER_AddMember(getActorAction, EntityDecoration::getActorAction)
_CLASSREGISTER_AddMember(getActionId, EntityDecoration::getActionId)
_CLASSREGISTER_AddMember(setCanCollided, EntityDecoration::setCanCollided)
_CLASSREGISTER_AddMember(setSuspended, EntityDecoration::setSuspended)
_CLASSREGISTER_AddMember(getSuspended, EntityDecoration::getSuspended)
_CLASSREGISTER_AddMember(playerJoin, EntityDecoration::playerJoin)
_CLASSREGISTER_AddMember(playerLeave, EntityDecoration::playerLeave)
_CLASSREGISTER_AddMember(getNodes, EntityDecoration::getNodes)
_CLASSREGISTER_AddMember(changeNode, EntityDecoration::changeNode)
_CLASSREGISTER_AddMember(changeAction, EntityDecoration::changeAction)
_CLASSREGISTER_AddMember(setPlayAction, EntityDecoration::setPlayAction)
_CLASSREGISTER_AddMember(isPlayAction, EntityDecoration::isPlayAction)
_CLASSREGISTER_AddMember(isCanPlayAction, EntityDecoration::isCanPlayAction)
_CLASSREGISTER_AddMember(hasUser, EntityDecoration::hasUser)
_END_REGISTER_CLASS()


// Register Class EntityFireball
_BEGIN_REGISTER_CLASS(EntityFireball)
_CLASSREGISTER_AddBaseClass(EntityThrowable)
_END_REGISTER_CLASS()


// Register Class EntityGrenade
_BEGIN_REGISTER_CLASS(EntityGrenade)
_CLASSREGISTER_AddBaseClass(EntityThrowable)
_END_REGISTER_CLASS()


// Register Class EntityFishHook
_BEGIN_REGISTER_CLASS(EntityFishHook)
_CLASSREGISTER_AddBaseClass(Entity)
_CLASSREGISTER_AddMember(getAngler, EntityFishHook::getAngler)
_CLASSREGISTER_AddMember(getTarget, EntityFishHook::getTarget)
_CLASSREGISTER_AddMember(catchFish, EntityFishHook::catchFish)
_END_REGISTER_CLASS()


// Register Class EntityLandNpc
_BEGIN_REGISTER_CLASS(EntityLandNpc)
_CLASSREGISTER_AddBaseClass(Entity)
_CLASSREGISTER_AddMember(setActorName, EntityLandNpc::setActorName)
_CLASSREGISTER_AddMember(getActorName, EntityLandNpc::getActorName)
_CLASSREGISTER_AddMember(setNameLang, EntityLandNpc::setNameLang)
_CLASSREGISTER_AddMember(getNameLang, EntityLandNpc::getNameLang)
_CLASSREGISTER_AddMember(setName, EntityLandNpc::setName)
_CLASSREGISTER_AddMember(getName, EntityLandNpc::getName)
_CLASSREGISTER_AddMember(setActorName, EntityLandNpc::setActorName)
_CLASSREGISTER_AddMember(getActorName, EntityLandNpc::getActorName)
_CLASSREGISTER_AddMember(setActorBody, EntityLandNpc::setActorBody)
_CLASSREGISTER_AddMember(getActorBody, EntityLandNpc::getActorBody)
_CLASSREGISTER_AddMember(setActorBodyId, EntityLandNpc::setActorBodyId)
_CLASSREGISTER_AddMember(getActorBodyId, EntityLandNpc::getActorBodyId)
_CLASSREGISTER_AddMember(setStatus, EntityLandNpc::setStatus)
_CLASSREGISTER_AddMember(getStatus, EntityLandNpc::getStatus)
_CLASSREGISTER_AddMember(setUserId, EntityLandNpc::setUserId)
_CLASSREGISTER_AddMember(getUserId, EntityLandNpc::getUserId)
_CLASSREGISTER_AddMember(setLandCode, EntityLandNpc::setLandCode)
_CLASSREGISTER_AddMember(getLandCode, EntityLandNpc::getLandCode)
_CLASSREGISTER_AddMember(setTimeLeft, EntityLandNpc::setTimeLeft)
_CLASSREGISTER_AddMember(getTimeLeft, EntityLandNpc::getTimeLeft)
_CLASSREGISTER_AddMember(setPrice, EntityLandNpc::setPrice)
_CLASSREGISTER_AddMember(getPrice, EntityLandNpc::getPrice)
_CLASSREGISTER_AddMember(setTotalTime, EntityLandNpc::setTotalTime)
_CLASSREGISTER_AddMember(getTotalTime, EntityLandNpc::getTotalTime)
_END_REGISTER_CLASS()


// Register Class EntityMerchant
_BEGIN_REGISTER_CLASS(EntityMerchant)
_CLASSREGISTER_AddBaseClass(Entity)
_CLASSREGISTER_AddMember(setNameLang, EntityMerchant::setNameLang)
_CLASSREGISTER_AddMember(getNameLang, EntityMerchant::getNameLang)
_CLASSREGISTER_AddMember(setName, EntityMerchant::setName)
_CLASSREGISTER_AddMember(getName, EntityMerchant::getName)
_CLASSREGISTER_AddMember(getGroup, EntityMerchant::getGroup)
_CLASSREGISTER_AddMember(getCommodities, EntityMerchant::getCommodities)
_CLASSREGISTER_AddMember(resetCommodities, EntityMerchant::resetCommodities)
_CLASSREGISTER_AddMember(clearCommodities, EntityMerchant::clearCommodities)
_CLASSREGISTER_AddMember(setHasUpdated, EntityMerchant::setHasUpdated)
_CLASSREGISTER_AddMember(getHasUpdated, EntityMerchant::getHasUpdated)
_END_REGISTER_CLASS()


// Register Class EntityRankNpc
_BEGIN_REGISTER_CLASS(EntityRankNpc)
_CLASSREGISTER_AddBaseClass(Entity)
_CLASSREGISTER_AddMember(setNameLang, EntityRankNpc::setNameLang)
_CLASSREGISTER_AddMember(getNameLang, EntityRankNpc::getNameLang)
_CLASSREGISTER_AddMember(setName, EntityRankNpc::setName)
_CLASSREGISTER_AddMember(getName, EntityRankNpc::getName)
_CLASSREGISTER_AddMember(getRankInfo, EntityRankNpc::getRankInfo)
_CLASSREGISTER_AddMember(setRankInfo, EntityRankNpc::setRankInfo)
_END_REGISTER_CLASS()


// Register Class EntityRobot
_BEGIN_REGISTER_CLASS(EntityRobot)
_CLASSREGISTER_AddBaseClass(EntityCreature)
_END_REGISTER_CLASS()


// Register Class EntitySnowball
_BEGIN_REGISTER_CLASS(EntitySnowball)
_CLASSREGISTER_AddBaseClass(EntityThrowable)
_CLASSREGISTER_AddMember(handleStatusUpdate, EntitySnowball::handleStatusUpdate)
_CLASSREGISTER_AddMember(setMeta, EntitySnowball::setMeta)
_CLASSREGISTER_AddMember(getMeta, EntitySnowball::getMeta)
_END_REGISTER_CLASS()


// Register Class EntityTNTPrimed
_BEGIN_REGISTER_CLASS(EntityTNTPrimed)
_CLASSREGISTER_AddBaseClass(Entity)
_CLASSREGISTER_AddMember(setFuse, EntityTNTPrimed::setFuse)
_CLASSREGISTER_AddMember(getFuse, EntityTNTPrimed::getFuse)
_END_REGISTER_CLASS()


// Register Class EntityTNTThrowable
_BEGIN_REGISTER_CLASS(EntityTNTThrowable)
_CLASSREGISTER_AddBaseClass(EntityThrowable)
_END_REGISTER_CLASS()


// Register Class EntityVehicle
_BEGIN_REGISTER_CLASS(EntityVehicle)
_CLASSREGISTER_AddBaseClass(Entity)
_CLASSREGISTER_AddMember(setTurning, EntityVehicle::setTurning)
_CLASSREGISTER_AddMember(setBraking, EntityVehicle::setBraking)
_CLASSREGISTER_AddMember(getVehicleId, EntityVehicle::getVehicleId)
_CLASSREGISTER_AddMember(getDriverId, EntityVehicle::getDriverId)
_CLASSREGISTER_AddMember(isLocked, EntityVehicle::isLocked)
_CLASSREGISTER_AddMember(hasDriver, EntityVehicle::hasDriver)
_CLASSREGISTER_AddMember(getPassengersIds, EntityVehicle::getPassengersIds)
_CLASSREGISTER_AddMember(hasPlayer, EntityVehicle::hasPlayer)
_CLASSREGISTER_AddMember(getSetting, EntityVehicle::getSetting)
_CLASSREGISTER_AddMember(lockVehicle, EntityVehicle::lockVehicle)
_CLASSREGISTER_AddMember(canDrivedBy, EntityVehicle::canDrivedBy)
_CLASSREGISTER_AddMember(carryPassenger, EntityVehicle::carryPassenger)
_CLASSREGISTER_AddMember(getOffPassenger, EntityVehicle::getOffPassenger)
_CLASSREGISTER_AddMember(isDriver, EntityVehicle::isDriver)
_CLASSREGISTER_AddMember(getFreeSeatNum, EntityVehicle::getFreeSeatNum)
_END_REGISTER_CLASS()


// Register Class EntityFlyingMount
_BEGIN_REGISTER_CLASS(EntityFlyingMount)
_CLASSREGISTER_AddBaseClass(Entity)
_CLASSREGISTER_AddMember(setRider, EntityFlyingMount::setRider)
_CLASSREGISTER_AddMember(getRiderId, EntityFlyingMount::getRiderId)
_CLASSREGISTER_AddMember(getOrientation, EntityFlyingMount::getOrientation)
_CLASSREGISTER_AddMember(setHurting, EntityFlyingMount::setHurting)
_END_REGISTER_CLASS()


// Register Class EntityFloatingMount
_BEGIN_REGISTER_CLASS(EntityFloatingMount)
_CLASSREGISTER_AddBaseClass(Entity)
_CLASSREGISTER_AddMember(setRider, EntityFloatingMount::setRider)
_CLASSREGISTER_AddMember(getRiderId, EntityFloatingMount::getRiderId)
_CLASSREGISTER_AddMember(setHurting, EntityFloatingMount::setHurting)
_END_REGISTER_CLASS()


// Register Class DynamicCastEntity
_BEGIN_REGISTER_CLASS(DynamicCastEntity)
_CLASSREGISTER_AddStaticMember(dynamicCastActorCannon, DynamicCastEntity::dynamicCastActorCannon)
_CLASSREGISTER_AddStaticMember(dynamicCastActorNpc, DynamicCastEntity::dynamicCastActorNpc)
_CLASSREGISTER_AddStaticMember(dynamicCastAircraft, DynamicCastEntity::dynamicCastAircraft)
_CLASSREGISTER_AddStaticMember(dynamicCastArrow, DynamicCastEntity::dynamicCastArrow)
_CLASSREGISTER_AddStaticMember(dynamicCastBird, DynamicCastEntity::dynamicCastBird)
_CLASSREGISTER_AddStaticMember(dynamicCastBlockman, DynamicCastEntity::dynamicCastBlockman)
_CLASSREGISTER_AddStaticMember(dynamicCastBlockmanEmpty, DynamicCastEntity::dynamicCastBlockmanEmpty)
_CLASSREGISTER_AddStaticMember(dynamicCastBuildNpc, DynamicCastEntity::dynamicCastBuildNpc)
_CLASSREGISTER_AddStaticMember(dynamicCastBullet, DynamicCastEntity::dynamicCastBullet)
_CLASSREGISTER_AddStaticMember(dynamicCastBulletin, DynamicCastEntity::dynamicCastBulletin)
_CLASSREGISTER_AddStaticMember(dynamicCastCreature, DynamicCastEntity::dynamicCastCreature)
_CLASSREGISTER_AddStaticMember(dynamicCastCreatureBullet, DynamicCastEntity::dynamicCastCreatureBullet)
_CLASSREGISTER_AddStaticMember(dynamicCastDecoration, DynamicCastEntity::dynamicCastDecoration)
_CLASSREGISTER_AddStaticMember(dynamicCastFireball, DynamicCastEntity::dynamicCastFireball)
_CLASSREGISTER_AddStaticMember(dynamicCastFishHook, DynamicCastEntity::dynamicCastFishHook)
_CLASSREGISTER_AddStaticMember(dynamicCastFloatingMount, DynamicCastEntity::dynamicCastFloatingMount)
_CLASSREGISTER_AddStaticMember(dynamicCastFlyingMount, DynamicCastEntity::dynamicCastFlyingMount)
_CLASSREGISTER_AddStaticMember(dynamicCastGrenade, DynamicCastEntity::dynamicCastGrenade)
_CLASSREGISTER_AddStaticMember(dynamicCastItem, DynamicCastEntity::dynamicCastItem)
_CLASSREGISTER_AddStaticMember(dynamicCastLandNpc, DynamicCastEntity::dynamicCastLandNpc)
_CLASSREGISTER_AddStaticMember(dynamicCastLiving, DynamicCastEntity::dynamicCastLiving)
_CLASSREGISTER_AddStaticMember(dynamicCastLivingBase, DynamicCastEntity::dynamicCastLivingBase)
_CLASSREGISTER_AddStaticMember(dynamicCastMerchant, DynamicCastEntity::dynamicCastMerchant)
_CLASSREGISTER_AddStaticMember(dynamicCastPlayer, DynamicCastEntity::dynamicCastPlayer)
_CLASSREGISTER_AddStaticMember(dynamicCastPotion, DynamicCastEntity::dynamicCastPotion)
_CLASSREGISTER_AddStaticMember(dynamicCastRankNpc, DynamicCastEntity::dynamicCastRankNpc)
_CLASSREGISTER_AddStaticMember(dynamicCastRobot, DynamicCastEntity::dynamicCastRobot)
_CLASSREGISTER_AddStaticMember(dynamicCastSessionNpc, DynamicCastEntity::dynamicCastSessionNpc)
_CLASSREGISTER_AddStaticMember(dynamicCastSkillThrowable, DynamicCastEntity::dynamicCastSkillThrowable)
_CLASSREGISTER_AddStaticMember(dynamicCastThrowable, DynamicCastEntity::dynamicCastThrowable)
_CLASSREGISTER_AddStaticMember(dynamicCastTNTPrimed, DynamicCastEntity::dynamicCastTNTPrimed)
_CLASSREGISTER_AddStaticMember(dynamicCastTNTThrowable, DynamicCastEntity::dynamicCastTNTThrowable)
_CLASSREGISTER_AddStaticMember(dynamicCastVehicle, DynamicCastEntity::dynamicCastVehicle)
_CLASSREGISTER_AddStaticMember(dynamicCastXPOrb, DynamicCastEntity::dynamicCastXPOrb)
_END_REGISTER_CLASS()


#endif