#pragma once

#ifndef __WORLD_HEADER_H__
#define __WORLD_HEADER_H__

#include "World/World.h"
#include "World/WorldInfo.h"
#include "World/WorldSettings.h"
#include "World/Shop.h"
#include "World/RayTracyResult.h"
#include "Block/BM_Material.h"
#include "LuaRegister/Template/LuaRegister.h"

using namespace BLOCKMAN;

using namespace LUA_REGISTER;

// Register Class World
_BEGIN_REGISTER_CLASS(World)
_CLASSREGISTER_AddBaseClass(IBlockAccess)
_CLASSREGISTER_AddBaseClass(ObjectAlloc)
_CLASSREGISTER_AddMember(setTimeStopped, World::setTimeStopped)
_CLASSREGISTER_AddMember(addBlockEvent, World::addBlockEvent)
_CLASSREGISTER_AddMember(addWorldListener, World::addWorldListener)
_CLASSREGISTER_AddMember(blockExists, World::blockExists)
_CLASSREGISTER_AddMember(blockHasTileEntity, World::blockHasTileEntity)
_CLASSREGISTER_AddMember(calculateInitialSkylight, World::calculateInitialSkylight)
_CLASSREGISTER_AddMember(calculateSkylightSubtracted, World::calculateSkylightSubtracted)
_CLASSREGISTER_AddMember(canBlockFreeze, World::canBlockFreeze)
_CLASSREGISTER_AddMember(canBlockSeeTheSky, World::canBlockSeeTheSky)
_CLASSREGISTER_AddMember(canLightningStrikeAt, World::canLightningStrikeAt)
_CLASSREGISTER_AddMember(canMineBlock, World::canMineBlock)
_CLASSREGISTER_AddMember(canPlaceEntityOnSide, World::canPlaceEntityOnSide)
_CLASSREGISTER_AddMember(canSnowAt, World::canSnowAt)
_CLASSREGISTER_AddMember(checkBlockCollision, World::checkBlockCollision)
_CLASSREGISTER_AddMember(checkChunksExist, World::checkChunksExist)
_CLASSREGISTER_AddMember_Override(checkNoEntityCollision, World::checkNoEntityCollision,bool ,const Box & )
_CLASSREGISTER_AddMember_Override(checkNoEntityCollision1, World::checkNoEntityCollision,bool ,const Box & ,Entity * )
_CLASSREGISTER_AddMember(chunkExists, World::chunkExists)
_CLASSREGISTER_AddMember(createExplosion, World::createExplosion)
_CLASSREGISTER_AddMember(destroyBlock, World::destroyBlock)
_CLASSREGISTER_AddMember(destroyBlockInWorldPartially, World::destroyBlockInWorldPartially)
_CLASSREGISTER_AddMember(doChunksNearChunkExist, World::doChunksNearChunkExist)
_CLASSREGISTER_AddMember(doesBlockHaveSolidTopSurface, World::doesBlockHaveSolidTopSurface)
_CLASSREGISTER_AddMember(extendedLevelsInChunkCollection, World::extendedLevelsInChunkCollection)
_CLASSREGISTER_AddMember(extinguishFire, World::extinguishFire)
_CLASSREGISTER_AddMember(getActualHeight, World::getActualHeight)
_CLASSREGISTER_AddMember(getBlockDensity, World::getBlockDensity)
_CLASSREGISTER_AddMember(getBlockIDAndMeta, World::getBlockIDAndMeta)
_CLASSREGISTER_AddMember(getBlockId, World::getBlockId)
_CLASSREGISTER_AddMember(getBlockLightValue, World::getBlockLightValue)
_CLASSREGISTER_AddMember(getBlockMaterial, World::getBlockMaterial)
_CLASSREGISTER_AddMember(getBlockMeta, World::getBlockMeta)
_CLASSREGISTER_AddMember(getBlockPowerInput, World::getBlockPowerInput)
_CLASSREGISTER_AddMember(getBlockTileEntity, World::getBlockTileEntity)
_CLASSREGISTER_AddMember(getBrightness, World::getBrightness)
_CLASSREGISTER_AddMember(getCelestialAngle, World::getCelestialAngle)
_CLASSREGISTER_AddMember(getCelestialAngleRadians, World::getCelestialAngleRadians)
_CLASSREGISTER_AddMember(getChunkFromBlockCoords, World::getChunkFromBlockCoords)
_CLASSREGISTER_AddMember(getChunkFromChunkCoords, World::getChunkFromChunkCoords)
//_CLASSREGISTER_AddMember(getChunkService, World::getChunkService)
_CLASSREGISTER_AddMember(getClosestPlayer, World::getClosestPlayer)
_CLASSREGISTER_AddMember(getClosestPlayerToEntity, World::getClosestPlayerToEntity)
_CLASSREGISTER_AddMember(getClosestVulnerablePlayer, World::getClosestVulnerablePlayer)
_CLASSREGISTER_AddMember(getClosestVulnerablePlayerToEntity, World::getClosestVulnerablePlayerToEntity)
_CLASSREGISTER_AddMember(getCollidingBlockBounds, World::getCollidingBlockBounds)
_CLASSREGISTER_AddMember(getCollidingBoundingBoxes, World::getCollidingBoundingBoxes)
_CLASSREGISTER_AddMember(getEntitiesWithinAABB, World::getEntitiesWithinAABB)
_CLASSREGISTER_AddMember(getEntitiesWithinAABBExcludingEntity, World::getEntitiesWithinAABBExcludingEntity)
_CLASSREGISTER_AddMember(getEntity, World::getEntity)
//_CLASSREGISTER_AddMember(getEntityCreature, World::getEntityCreature)
_CLASSREGISTER_AddMember(getEntityPathToXYZ, World::getEntityPathToXYZ)
_CLASSREGISTER_AddMember(getFirstUncoveredBlock, World::getFirstUncoveredBlock)
_CLASSREGISTER_AddMember(getFullBlockLightValue, World::getFullBlockLightValue)
_CLASSREGISTER_AddMember(getHeight, World::getHeight)
_CLASSREGISTER_AddMember(getHeightValue, World::getHeightValue)
_CLASSREGISTER_AddMember(getHorizon, World::getHorizon)
_CLASSREGISTER_AddMember(getIndirectPowerLevelTo, World::getIndirectPowerLevelTo)
_CLASSREGISTER_AddMember(getIndirectPowerOutput, World::getIndirectPowerOutput)
_CLASSREGISTER_AddMember(getLightBrightness, World::getLightBrightness)
_CLASSREGISTER_AddMember(getLightBrightnessForSkyBlocks, World::getLightBrightnessForSkyBlocks)
_CLASSREGISTER_AddMember(getLoadedEntityMap, World::getLoadedEntityMap)
_CLASSREGISTER_AddMember(getPathEntityToEntity, World::getPathEntityToEntity)
_CLASSREGISTER_AddMember(getPlayerEntity, World::getPlayerEntity)
_CLASSREGISTER_AddMember(getPlayers, World::getPlayers)
_CLASSREGISTER_AddMember(getPrecipitationHeight, World::getPrecipitationHeight)
_CLASSREGISTER_AddMember(getSavedLightValue, World::getSavedLightValue)
_CLASSREGISTER_AddMember(getSeed, World::getSeed)
_CLASSREGISTER_AddMember(getSkyBlockTypeBrightness, World::getSkyBlockTypeBrightness)
_CLASSREGISTER_AddMember(getSpawnPoint, World::getSpawnPoint)
_CLASSREGISTER_AddMember(getStrongestIndirectPower, World::getStrongestIndirectPower)
_CLASSREGISTER_AddMember(getTopSolidOrLiquidBlock, World::getTopSolidOrLiquidBlock)
_CLASSREGISTER_AddMember(getTotalWorldTime, World::getTotalWorldTime)
_CLASSREGISTER_AddMember(getUniqueDataId, World::getUniqueDataId)
_CLASSREGISTER_AddMember(getWorldInfo, World::getWorldInfo)
_CLASSREGISTER_AddMember(getWorldTime, World::getWorldTime)
_CLASSREGISTER_AddMember(handleMaterialAcceleration, World::handleMaterialAcceleration)
_CLASSREGISTER_AddMember(init, World::init)
_CLASSREGISTER_AddMember(initialize, World::initialize)
_CLASSREGISTER_AddMember(isAirBlock, World::isAirBlock)
_CLASSREGISTER_AddMember(isAnyLiquid, World::isAnyLiquid)
_CLASSREGISTER_AddMember(isBlockFreezable, World::isBlockFreezable)
_CLASSREGISTER_AddMember(isBlockFullCube, World::isBlockFullCube)
_CLASSREGISTER_AddMember(isBlockHighHumidity, World::isBlockHighHumidity)
_CLASSREGISTER_AddMember(isBlockIndirectlyGettingPowered, World::isBlockIndirectlyGettingPowered)
_CLASSREGISTER_AddMember(isBlockNormalCube, World::isBlockNormalCube)
_CLASSREGISTER_AddMember(isBlockNormalCubeDefault, World::isBlockNormalCubeDefault)
_CLASSREGISTER_AddMember(isBlockOpaqueCube, World::isBlockOpaqueCube)
_CLASSREGISTER_AddMember(isBlockProvidingPowerTo, World::isBlockProvidingPowerTo)
_CLASSREGISTER_AddMember(isBlockTickScheduledThisTick, World::isBlockTickScheduledThisTick)
_CLASSREGISTER_AddMember(isBlockTopFacingSurfaceSolid, World::isBlockTopFacingSurfaceSolid)
_CLASSREGISTER_AddMember(isBoundingBoxBurning, World::isBoundingBoxBurning)
_CLASSREGISTER_AddMember(isDaytime, World::isDaytime)
_CLASSREGISTER_AddMember(isMaterialInBB, World::isMaterialInBB)
_CLASSREGISTER_AddMember(markBlockForRenderUpdate, World::markBlockForRenderUpdate)
_CLASSREGISTER_AddMember(markBlockForUpdate, World::markBlockForUpdate)
_CLASSREGISTER_AddMember(markSectionForUpdate, World::markSectionForUpdate)
_CLASSREGISTER_AddMember(markBlockRangeForRenderUpdate, World::markBlockRangeForRenderUpdate)
_CLASSREGISTER_AddMember(markTileEntityForDespawn, World::markTileEntityForDespawn)
_CLASSREGISTER_AddMember(newExplosion, World::newExplosion)
_CLASSREGISTER_AddMember(notifyBlockChange, World::notifyBlockChange)
_CLASSREGISTER_AddMember(notifyBlockOfNeighborChange, World::notifyBlockOfNeighborChange)
_CLASSREGISTER_AddMember_Override(notifyBlocksOfNeighborChange, World::notifyBlocksOfNeighborChange, void, const BlockPos &, int)
_CLASSREGISTER_AddMember_Override(notifyBlocksOfNeighborChange1, World::notifyBlocksOfNeighborChange, void, const BlockPos &, int, int)
_CLASSREGISTER_AddMember(playAuxSFX, World::playAuxSFX)
_CLASSREGISTER_AddMember(playAuxSFXAtEntity, World::playAuxSFXAtEntity)
_CLASSREGISTER_AddMember(playRecord, World::playRecord)
_CLASSREGISTER_AddMember(playSoundByType, World::playSoundByType)
_CLASSREGISTER_AddMember(playSoundAtEntityByType, World::playSoundAtEntityByType)
_CLASSREGISTER_AddMember(playSoundEffect, World::playSoundEffectByType)
_CLASSREGISTER_AddMember(playSoundOfPlaceBlock, World::playSoundOfPlaceBlock)
_CLASSREGISTER_AddMember(playSoundOfStepOnBlock, World::playSoundOfStepOnBlock)
_CLASSREGISTER_AddMember(playSoundToNearExceptByType, World::playSoundToNearExceptByType)
_CLASSREGISTER_AddMember_Override(rayTraceBlocks, World::rayTraceBlocks, RayTraceResult, Vector3, Vector3)
_CLASSREGISTER_AddMember_Override(rayTraceBlocks1, World::rayTraceBlocks, RayTraceResult, Vector3, Vector3, bool)
_CLASSREGISTER_AddMember_Override(rayTraceBlocks2, World::rayTraceBlocks, RayTraceResult, Vector3, Vector3, bool, bool)
_CLASSREGISTER_AddMember(removeBlockTileEntity, World::removeBlockTileEntity)
_CLASSREGISTER_AddMember_Override(removeEntity, World::removeEntity, void, Entity *)
_CLASSREGISTER_AddMember_Override(removeEntity1, World::removeEntity, void, int)
_CLASSREGISTER_AddMember(removePlayerEntityDangerously, World::removePlayerEntityDangerously)
_CLASSREGISTER_AddMember(removeWorldListener, World::removeWorldListener)
_CLASSREGISTER_AddMember(scheduleBlockUpdate, World::scheduleBlockUpdate)
_CLASSREGISTER_AddMember(scheduleBlockUpdateFromLoad, World::scheduleBlockUpdateFromLoad)
_CLASSREGISTER_AddMember(scheduleBlockUpdateWithPriority, World::scheduleBlockUpdateWithPriority)
_CLASSREGISTER_AddMember(sendQuittingDisconnectingPacket, World::sendQuittingDisconnectingPacket)
_CLASSREGISTER_AddMember_Override(setBlock, World::setBlock, bool, const BlockPos &, int, int, int, bool)
_CLASSREGISTER_AddMember(setBlockMetadataWithNotify, World::setBlockMetadataWithNotify)
_CLASSREGISTER_AddMember(setBlockTileEntity, World::setBlockTileEntity)
_CLASSREGISTER_AddMember(setBlockToAir, World::setBlockToAir)
_CLASSREGISTER_AddMember(setEntityState, World::setEntityState)
_CLASSREGISTER_AddMember(setRandomSeed, World::setRandomSeed)
_CLASSREGISTER_AddMember_Override(setSpawnLocation, World::setSpawnLocation, void)
_CLASSREGISTER_AddMember_Override(setSpawnLocation1, World::setSpawnLocation, void, const Vector3i &)
_CLASSREGISTER_AddMember(setWorldTime, World::setWorldTime)
_CLASSREGISTER_AddMember(setWorldWeather, World::setWorldWeather)
_CLASSREGISTER_AddMember(spawnEntityInWorld, World::spawnEntityInWorld)
_CLASSREGISTER_AddMember(spawnParticle, World::spawnParticle)
_CLASSREGISTER_AddMember(tick, World::tick)
_CLASSREGISTER_AddMember(tickUpdates, World::tickUpdates)
_CLASSREGISTER_AddMember(unloadEntities, World::unloadEntities)
_CLASSREGISTER_AddMember(updateAllPlayersSleepingFlag, World::updateAllPlayersSleepingFlag)
_CLASSREGISTER_AddMember(updateComparatorOutputLevel, World::updateComparatorOutputLevel)
_CLASSREGISTER_AddMember(updateEntities, World::updateEntities)
_CLASSREGISTER_AddMember(updateEntity, World::updateEntity)
_CLASSREGISTER_AddMember(updateEntityWithOptionalForce, World::updateEntityWithOptionalForce)
_CLASSREGISTER_AddMember(updateTileEntityChunkAndDoNothing, World::updateTileEntityChunkAndDoNothing)
_CLASSREGISTER_AddMember(spawnItemInWorld, World::spawnItemInWorld)
_CLASSREGISTER_AddMember(knockbackNoHarm, World::knockbackNoHarm)
_CLASSREGISTER_AddMember(setKnockbackNoHarm, World::setKnockbackNoHarm)
_CLASSREGISTER_AddMember(resetSignText, World::resetSignText)
_CLASSREGISTER_AddMember(addMerchant, World::addMerchant)
_CLASSREGISTER_AddMember(changePlayerActor, World::changePlayerActor)
_CLASSREGISTER_AddMember(restorePlayerActor, World::restorePlayerActor)
_CLASSREGISTER_AddMember(addGoodsGroupToShop, World::addGoodsGroupToShop)
_CLASSREGISTER_AddMember(addGoodsToShop, World::addGoodsToShop)
_CLASSREGISTER_AddMember(addRespawnGoodsToShop, World::addRespawnGoodsToShop)
_CLASSREGISTER_AddMember(addVehicle, World::addVehicle)
_CLASSREGISTER_AddMember(addRankNpc, World::addRankNpc)
_CLASSREGISTER_AddMember(resetVehiclePosition, World::resetVehiclePosition)
_CLASSREGISTER_AddMember(resetVehiclePositionAndYaw, World::resetVehiclePositionAndYaw)
_CLASSREGISTER_AddMember(hasPlayerByVehicle, World::hasPlayerByVehicle)
_CLASSREGISTER_AddMember(getPositionByEntityId, World::getPositionByEntityId)
_CLASSREGISTER_AddMember(addAircraft, World::addAircraft)
_CLASSREGISTER_AddMember(tryAllPlayerTakeAircraft, World::tryAllPlayerTakeAircraft)
_CLASSREGISTER_AddMember(tryAllPlayerOffAircraft, World::tryAllPlayerOffAircraft)
_CLASSREGISTER_AddMember(setPoisonCircleRange, World::setPoisonCircleRange)
_CLASSREGISTER_AddMember_Override(removeEntity, World::removeEntity, void, int)
_CLASSREGISTER_AddMember(addActorNpc, World::addActorNpc)
_CLASSREGISTER_AddMember(addSessionNpc, World::addSessionNpc)
_CLASSREGISTER_AddMember(addCreature, World::addCreature)
_CLASSREGISTER_AddMember(updateManorOwner, World::updateManorOwner)
_CLASSREGISTER_AddMember(addRailCar, World::addRailCar)
_CLASSREGISTER_AddMember(addActorCannon, World::addActorCannon)
_CLASSREGISTER_AddMember(addBuildNpc, World::addBuildNpc)
_CLASSREGISTER_AddMember(addLandNpc, World::addLandNpc)
_CLASSREGISTER_AddMember(addCreatureBullet, World::addCreatureBullet)
_CLASSREGISTER_AddMember(updateLandNpc, World::updateLandNpc)
_CLASSREGISTER_AddMember(rangeCheckBlock, World::rangeCheckBlock)
_CLASSREGISTER_AddMember(rangeCheckBlockByEntityId, World::rangeCheckBlockByEntityId)
_CLASSREGISTER_AddMember(getBlockRedStatusInThisWorld, World::getBlockRedStatusInThisWorld)
_CLASSREGISTER_AddMember(addRespawnGoodsToShopByUniqueId, World::addRespawnGoodsToShopByUniqueId)
_CLASSREGISTER_AddMember(addDecoration, World::addDecoration)
_CLASSREGISTER_AddMember(updateDecorationYaw, World::updateDecorationYaw)
_CLASSREGISTER_AddMember(setActorRotateSpeed, World::setActorRotateSpeed)
_CLASSREGISTER_AddMember(hasEntitiesInPos, World::hasEntitiesInPos)
_CLASSREGISTER_AddMember(addFlyingMount, World::addFlyingMount)
_CLASSREGISTER_AddMember(addFloatingMount, World::addFloatingMount)
_CLASSREGISTER_AddMember(addSkillThrowable, World::addSkillThrowable)
_CLASSREGISTER_AddMember(setBlockResistance, World::setBlockResistance)
_END_REGISTER_CLASS()




// Register Class WorldInfo
_BEGIN_REGISTER_CLASS(WorldInfo)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddCtor(const String , const WorldSettings & )
_CLASSREGISTER_AddCtor(const WorldInfo & )
_CLASSREGISTER_AddMember(areCommandsAllowed, WorldInfo::areCommandsAllowed)
_CLASSREGISTER_AddMember(getGameType, WorldInfo::getGameType)
_CLASSREGISTER_AddMember(getGeneratorOptions, WorldInfo::getGeneratorOptions)
_CLASSREGISTER_AddMember(getLastTimePlayed, WorldInfo::getLastTimePlayed)
_CLASSREGISTER_AddMember(getMapId, WorldInfo::getMapId)
_CLASSREGISTER_AddMember(getRainTime, WorldInfo::getRainTime)
_CLASSREGISTER_AddMember(getSaveVersion, WorldInfo::getSaveVersion)
_CLASSREGISTER_AddMember(getSeed, WorldInfo::getSeed)
_CLASSREGISTER_AddMember(getSizeOnDisk, WorldInfo::getSizeOnDisk)
_CLASSREGISTER_AddMember(getSpawnX, WorldInfo::getSpawnX)
_CLASSREGISTER_AddMember(getSpawnY, WorldInfo::getSpawnY)
_CLASSREGISTER_AddMember(getSpawnZ, WorldInfo::getSpawnZ)
_CLASSREGISTER_AddMember(getTerrainType, WorldInfo::getTerrainType)
_CLASSREGISTER_AddMember(getThunderTime, WorldInfo::getThunderTime)
_CLASSREGISTER_AddMember(getVanillaDimension, WorldInfo::getVanillaDimension)
_CLASSREGISTER_AddMember(getWorldName, WorldInfo::getWorldName)
_CLASSREGISTER_AddMember(getWorldTime, WorldInfo::getWorldTime)
_CLASSREGISTER_AddMember(getWorldTotalTime, WorldInfo::getWorldTotalTime)
_CLASSREGISTER_AddMember(incrementTotalWorldTime, WorldInfo::incrementTotalWorldTime)
_CLASSREGISTER_AddMember(isHardcoreModeEnabled, WorldInfo::isHardcoreModeEnabled)
_CLASSREGISTER_AddMember(isInitialized, WorldInfo::isInitialized)
_CLASSREGISTER_AddMember(isMapFeaturesEnabled, WorldInfo::isMapFeaturesEnabled)
_CLASSREGISTER_AddMember(isRaining, WorldInfo::isRaining)
_CLASSREGISTER_AddMember(isThundering, WorldInfo::isThundering)
_CLASSREGISTER_AddMember(setGameType, WorldInfo::setGameType)
_CLASSREGISTER_AddMember(setRainTime, WorldInfo::setRainTime)
_CLASSREGISTER_AddMember(setRaining, WorldInfo::setRaining)
_CLASSREGISTER_AddMember(setSaveVersion, WorldInfo::setSaveVersion)
_CLASSREGISTER_AddMember(setServerInitialized, WorldInfo::setServerInitialized)
_CLASSREGISTER_AddMember(setSpawnPosition, WorldInfo::setSpawnPosition)
_CLASSREGISTER_AddMember(setSpawnX, WorldInfo::setSpawnX)
_CLASSREGISTER_AddMember(setSpawnY, WorldInfo::setSpawnY)
_CLASSREGISTER_AddMember(setSpawnZ, WorldInfo::setSpawnZ)
_CLASSREGISTER_AddMember(setTerrainType, WorldInfo::setTerrainType)
_CLASSREGISTER_AddMember(setThunderTime, WorldInfo::setThunderTime)
_CLASSREGISTER_AddMember(setThundering, WorldInfo::setThundering)
_CLASSREGISTER_AddMember(setWorldName, WorldInfo::setWorldName)
_CLASSREGISTER_AddMember(setWorldTime, WorldInfo::setWorldTime)
_END_REGISTER_CLASS()



// Register Class WorldSettings
_BEGIN_REGISTER_CLASS(WorldSettings)
_CLASSREGISTER_AddBaseClass(ObjectAlloc)
_CLASSREGISTER_AddCtor(i64 , GAME_TYPE , bool , bool , TERRAIN_TYPE )
_CLASSREGISTER_AddCtor(const WorldInfo & )
_CLASSREGISTER_AddMember(areCommandsAllowed, WorldSettings::areCommandsAllowed)
_CLASSREGISTER_AddMember(enableBonusChest, WorldSettings::enableBonusChest)
_CLASSREGISTER_AddMember(enableCommands, WorldSettings::enableCommands)
_CLASSREGISTER_AddMember(func_82750_a, WorldSettings::func_82750_a)
_CLASSREGISTER_AddMember(getGameType, WorldSettings::getGameType)
_CLASSREGISTER_AddMember(getGenerateOptions, WorldSettings::getGenerateOptions)
_CLASSREGISTER_AddMember(getHardcoreEnabled, WorldSettings::getHardcoreEnabled)
_CLASSREGISTER_AddMember(getSeed, WorldSettings::getSeed)
_CLASSREGISTER_AddMember(getTerrainType, WorldSettings::getTerrainType)
_CLASSREGISTER_AddMember(isBonusChestEnabled, WorldSettings::isBonusChestEnabled)
_CLASSREGISTER_AddMember(isMapFeaturesEnabled, WorldSettings::isMapFeaturesEnabled)
_END_REGISTER_CLASS()

// Register Class RayTracyResult
_BEGIN_REGISTER_CLASS(RayTraceResult)
_CLASSREGISTER_AddBaseClass(ObjectAlloc)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(result, RayTraceResult::result)
_CLASSREGISTER_AddVar(typeOfHit, RayTraceResult::typeOfHit)
_CLASSREGISTER_AddVar(sideHit, RayTraceResult::sideHit)
_CLASSREGISTER_AddVar(blockPos, RayTraceResult::blockPos)
_CLASSREGISTER_AddVar(hitPointPos, RayTraceResult::hitPointPos)
_CLASSREGISTER_AddVar(entityHit, RayTraceResult::entityHit)
_END_REGISTER_CLASS()

#endif