---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 10184.
--- DateTime: 2020/11/16 11:09
---
local UICommonActivityMain = class("UICommonActivityMain", IGUILayout) ---@class UICommonActivityMain

function UICommonActivityMain:onLoad()
    self.btnEnterButton = self:getChildWindow("CommonActivityMain-Enter-Button", GUIType.Button)
    self.btnEnterButton:registerEvent(GUIEvent.ButtonClick, function()
        GUICommonActivityLayout:show()
    end)
    self.ivEnterEffect = self:getChildWindow("CommonActivityMain-Enter-Effect", GUIType.StaticImage)
    self.ivRedPoint = self:getChildWindow("CommonActivityMain-Red-Point", GUIType.StaticImage)
    self.ivRedPoint:SetVisible(false)
end

function UICommonActivityMain:checkRedPoint()
    local isShowRed = false
    local activities = CommonActivity:getCurrentActivityList()
    for _, activity in pairs(activities) do
        local chestGroup = CommonActivityChestConfig:getChestGroupById(activity.chestGroupId)
        local getChest = StringUtil.split(activity.getChest or "", ",", false, true)
        if chestGroup then
            for _, chest in pairs(chestGroup.chests) do
                if activity.lotteryTimes >= chest.times and not TableUtil.tableContain(getChest, chest.chestId) then
                    isShowRed = true
                    break
                end
            end
        end
        if isShowRed then
            break
        end
    end
    self.ivRedPoint:SetVisible(isShowRed)
end

return UICommonActivityMain
