---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/11/20 10:01
---
require "base.ui.window.GUICommonActivityRewardItem"
local dialog = nil

local GUICommonActivityShowReward = class("GUICommonActivityShowReward", IGUILayout)

function GUICommonActivityShowReward:onLoad()
    self.contents = {}
    self.contentView = nil
    self.customParams = nil
    self.leftClickListener = nil
    self.rightClickListener = nil
    self.closeClickListener = nil

    self.llRewardBox = self:getChildWindow("CommonActivityShowReward-Reward-Box", GUIType.Layout)

    self.tvTitleText = self:getChildWindow("CommonActivityShowReward-Title", GUIType.StaticText)

    self.btnLeftButton = self:getChildWindow("CommonActivityShowReward-Left", GUIType.Button)
    self.btnRightButton = self:getChildWindow("CommonActivityShowReward-Right", GUIType.Button)
    self.tvLeftBtnText = self:getChildWindow("CommonActivityShowReward-Left-Text", GUIType.StaticText)
    self.tvRightBtnText = self:getChildWindow("CommonActivityShowReward-Right-Text", GUIType.StaticText)

    self.ivLeftIcon = self:getChildWindow("CommonActivityShowReward-Left-Money-Icon", GUIType.StaticImage)
    self.ivRightIcon = self:getChildWindow("CommonActivityShowReward-Right-Money-Icon", GUIType.StaticImage)
    self.tvLeftBtnPrice = self:getChildWindow("CommonActivityShowReward-Left-Price", GUIType.StaticText)
    self.tvRightBtnPrice = self:getChildWindow("CommonActivityShowReward-Right-Price", GUIType.StaticText)

    self.btnLeftButton:registerEvent(GUIEvent.ButtonClick, function()
        if self.leftClickListener ~= nil then
            local close = self.leftClickListener() ---返回true拦截dialog不关闭
            if not close then
                self:hide()
            end
        else
            self:hide()
        end
        SoundUtil.playSound(SoundType.ClosePanel)
    end)
    self.btnRightButton:registerEvent(GUIEvent.ButtonClick, function()
        if self.rightClickListener ~= nil then
            local close = self.rightClickListener() ---返回true拦截dialog不关闭
            if not close then
                self:hide()
            end
        else
            self:hide()
        end
        SoundUtil.playSound(SoundType.ClosePanel)
    end)

    self.leftButtonPos = self.btnLeftButton:GetXPosition()
    self.rightButtonPos = self.btnRightButton:GetXPosition()

    self.gvRewardList = IGUIGridView.new("CommonActivityShowReward-Reward-List", self.llRewardBox, nil)
    self.gvRewardList.root:SetHorizontalAlignment(HorizontalAlignment.Center)
    self.gvRewardList.root:SetVerticalAlignment(VerticalAlignment.Center)
    self.gvRewardList.root:SetClipChild(false)
    self.gvRewardList:setArea({ 0, 0 }, { 0, 0 }, { 1, 0 }, { 0, 84 })
    self.gvRewardList:setConfig(22, 28, 6)
end

function GUICommonActivityShowReward:setDefault()
    self.customParams = nil
    self.leftClickListener = nil
    self.rightClickListener = nil
    self.closeClickListener = nil
    self.gvRewardList:clearItems()

    LuaTimer:cancel(self.showRewardKey)
    self.tvTitleText:SetText(Lang:getString("common.activity.showReward.title"))

    self:setLeftButton(Lang:getString("common.activity.tip.tryAgain"))
    self.ivLeftIcon:SetVisible(false)
    self.tvLeftBtnPrice:SetText("")

    self:setRightButton(Lang:getString("common.activity.sure"))
    self.ivRightIcon:SetVisible(false)
    self.tvRightBtnPrice:SetText("")
end

function GUICommonActivityShowReward:hide()
    if self:isShow() then
        self.root:SetVisible(false)
        self:onHide()
    end
end

function GUICommonActivityShowReward:onHide()
    self:setDefault()
end

function GUICommonActivityShowReward:builder()
    self:setDefault()
end

function GUICommonActivityShowReward:addRewardListItem(rewardList, size, isOneReward)
    LuaTimer:cancel(self.showRewardKey)
    size = size or math.min(84, (self.llRewardBox:GetPixelSize().x - (#rewardList - 1) * 22 - 20) / #rewardList)
    if isOneReward == nil then
        isOneReward = #rewardList == 1
    end

    local fun = function()
        local rewardInfo = table.remove(rewardList, 1)
        if rewardInfo then
            if rewardInfo.type and rewardInfo.type == "extra" then
                local rewardItem = GUICommonActivityRewardItem.new("CommonActivityRewardItem.json")
                rewardItem:setLotteryValue(rewardInfo)
                rewardItem:setWidth({ 0, size })
                rewardItem:setHeight({ 0, size })
                self.gvRewardList:addItem(rewardItem)
            else
                local reward = CommonActivityRewardConfig:getRewardById(rewardInfo.rewardId)
                if reward then
                    ---展示大奖
                    if rewardInfo.isGrandPrize == true then
                        LuaTimer:cancel(self.showRewardKey)
                        GUICommonActivityGrandPrize:init(reward, function()
                            self:addRewardListItem(rewardList, size, isOneReward)
                        end)
                        if isOneReward then
                            LuaTimer:schedule(function()
                                self:hide()
                            end, 1)
                        end
                    end
                    ---添加小图标
                    local rewardItem = GUICommonActivityRewardItem.new("CommonActivityRewardItem.json")
                    rewardItem:setLotteryResult(reward)
                    rewardItem:setWidth({ 0, size })
                    rewardItem:setHeight({ 0, size })
                    self.gvRewardList:addItem(rewardItem)
                end
            end
        end
    end

    if isOneReward then
        fun()
    else
        self.showRewardKey = LuaTimer:scheduleTimer(fun, 150, #rewardList)
    end
end

function GUICommonActivityShowReward:setRewardView(rewardList)
    GUICommonActivityGrandPrize:removeCallBack()
    local rewardNum = #rewardList
    local size = math.min(84, (self.llRewardBox:GetPixelSize().x - (rewardNum - 1) * 22) / math.min(6, rewardNum)) + 22
    local height = math.ceil(rewardNum / 6) * 84 + (math.ceil(rewardNum / 6) - 1) * 22
    self.gvRewardList:setArea({ 0, 0 }, { 0, 0 }, { 0, (size * math.min(6, rewardNum)) - 22 }, { 0, height })

    self.btnLeftButton:SetTouchable(false)
    self.btnRightButton:SetTouchable(false)
    LuaTimer:cancel(self.btnKey)
    self.btnKey = LuaTimer:schedule(function()
        self.btnLeftButton:SetTouchable(true)
        self.btnRightButton:SetTouchable(true)
    end, 150 * rewardNum)
    self:addRewardListItem(rewardList)
end

function GUICommonActivityShowReward:setUI()
    if self.btnLeftButton:IsVisible() and self.btnRightButton:IsVisible() then
        self.btnLeftButton:SetXPosition(self.leftButtonPos)
        self.btnRightButton:SetXPosition(self.rightButtonPos)
    elseif self.btnLeftButton:IsVisible() then
        self.btnLeftButton:SetXPosition({ 0, 0 })
    elseif self.btnRightButton:IsVisible() then
        self.btnRightButton:SetXPosition({ 0, 0 })
    end
end

function GUICommonActivityShowReward:setLeftButton(text, icon, price)
    if not text or #text == 0 then
        self.tvLeftBtnText:SetText("")
        self.btnLeftButton:SetVisible(false)
    else
        self.btnLeftButton:SetVisible(true)
        self.tvLeftBtnText:SetText(Lang:getString(text))
    end
    if not icon or #icon == 0 then
        self.ivLeftIcon:SetVisible(false)
        self.ivLeftIcon:SetImage("")
        self.tvLeftBtnPrice:SetText("")
    else
        self.ivLeftIcon:SetVisible(true)
        self.ivLeftIcon:SetImage(icon)
        self.tvLeftBtnPrice:SetText(price)
    end
end

function GUICommonActivityShowReward:setRightButton(text, icon, price)
    if not text or #text == 0 then
        self.tvRightBtnText:SetText("")
        self.btnRightButton:SetVisible(false)
    else
        self.btnRightButton:SetVisible(true)
        self.tvRightBtnText:SetText(Lang:getString(text))
    end
    if not icon or #icon == 0 then
        self.ivRightIcon:SetVisible(false)
        self.ivRightIcon:SetImage("")
        self.tvRightBtnPrice:SetText("")
    else
        self.ivRightIcon:SetVisible(true)
        self.ivRightIcon:SetImage(icon)
        self.tvRightBtnPrice:SetText(price)
    end
end

CommonActivityShowReward = {}

---构造一个初始化状态的自定义奖励界面
function CommonActivityShowReward.builder()
    dialog:builder()
    return CommonActivityShowReward
end

---设置奖励界面标题(默认是：提示)
---@text string 标题多语言或标题
function CommonActivityShowReward.setTitleText(title)
    dialog.tvTitleText:SetText(Lang:getString(title))
    return CommonActivityShowReward
end

---设置奖励界面奖励详情
---详情需要传入一个rewardId的列表
---@param rewardList table rewardId列表
function CommonActivityShowReward.setRewardView(rewardList)
    dialog:setRewardView(rewardList)
    return CommonActivityShowReward
end

---设置奖励界面奖励详情
---详情需要传入一个reward的列表
---@param groupId number groupId
function CommonActivityShowReward.setRewardGroup(groupId)
    local group = CommonActivityRewardConfig:getRewardGroupById(groupId)
    if not group then
        return CommonActivityShowReward
    end
    local result = {}
    for _, item in pairs(group) do
        table.insert(result, { rewardId = item.reward.rewardId, isGrandPrize = item.isGrandPrize })
    end
    dialog:setRewardView(result)
    return CommonActivityShowReward
end

---设置奖励界面右按钮信息
---@param text string 文字多语言或文字
---@param icon string 图片名称
---@param price string 价格
function CommonActivityShowReward.setRightButton(text, icon, price)
    dialog:setRightButton(text, icon, price)
    return CommonActivityShowReward
end

---设置奖励界面左按钮信息
---@param text string 文字多语言或文字
---@param icon string 图片名称
---@param price string 价格
function CommonActivityShowReward.setLeftButton(text, icon, price)
    dialog:setLeftButton(text, icon, price)
    return CommonActivityShowReward
end

---设置奖励界面左按钮点击监听
---@param listener function 监听回调函数
function CommonActivityShowReward.setLeftClickListener(listener)
    dialog.leftClickListener = listener
    return CommonActivityShowReward
end

---设置奖励界面右按钮点击监听
---@param listener function 监听回调函数
function CommonActivityShowReward.setRightClickListener(listener)
    dialog.rightClickListener = listener
    return CommonActivityShowReward
end

---显示奖励界面
function CommonActivityShowReward.show()
    dialog:setUI()
    dialog:show()
    SoundUtil.playSound(SoundType.OpenPanel)
end

---关闭奖励界面
function CommonActivityShowReward.hide()
    dialog:hide()
end

function CommonActivityShowReward.isShow()
    if not dialog then
        return false
    end
    return dialog:isShow()
end

---设置奖励界面(隐藏左按钮，右按钮且居中)
function CommonActivityShowReward.setHideLeftButton()
    dialog.btnLeftButton:SetVisible(false)
    dialog.btnRightButton:SetHorizontalAlignment(HorizontalAlignment.Center)
    dialog.btnRightButton:SetXPosition({ 0, 0 })
    return CommonActivityShowReward
end

---设置奖励界面(隐藏右按钮，左按钮且居中)
function CommonActivityShowReward.setHideRightButton()
    dialog.btnRightButton:SetVisible(false)
    dialog.btnLeftButton:SetHorizontalAlignment(HorizontalAlignment.Center)
    dialog.btnLeftButton:SetXPosition({ 0, 0 })
    return CommonActivityShowReward
end

---设置奖励界面是否显示在最前
function CommonActivityShowReward.setAlwaysOnTop(isTop)
    return dialog:setAlwaysOnTop(isTop)
end

---初始化奖励界面
function initCommonActivityShowReward()
    if dialog ~= nil then
        return
    end
    dialog = GUICommonActivityShowReward.new("CommonActivityShowReward.json")
end