---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 10184.
--- DateTime: 2020/6/16 10:07
---

local UIGMMain = class("GUIGMMain", IGUILayout)

function UIGMMain:onLoad()
    local btnOpen = self:getChildWindow("GMMain-Open", GUIType.Button)
    btnOpen:registerEvent(GUIEvent.ButtonClick, function()
        GUIGMControlPanel:show()
    end)
end

return UIGMMain