---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jimmy.
--- DateTime: 2019/12/16 0016 15:23
---
local function getChildWindow(window, name, type)
    local child = window:getChildWindow(name, type)
    if not child then
        error("SumRechargeResult must have" .. name .. " child window.")
    end
    return child
end

local UISumRechargeResult = class("UISumRechargeResult", IGUILayout)

function UISumRechargeResult:onLoad()
    local name = string.gsub(self.__name, ".json", "-")
    self.btnClose = getChildWindow(self, name .. "Close", GUIType.Button)
    self.ivImage = getChildWindow(self, name .. "Image", GUIType.StaticImage)
    self.awActor = getChildWindow(self, name .. "Actor", GUIType.ActorWindow)
    self.btnConfirm = getChildWindow(self, name .. "Confirm", GUIType.Button)

    self.btnClose:registerEvent(GUIEvent.ButtonClick, function()
        self:hide()
    end)

    self.btnConfirm:registerEvent(GUIEvent.ButtonClick, function()
        self:hide()
    end)
    self.btnConfirm:SetText(Lang:getString("sum.recharge.result.confirm"))
end

function UISumRechargeResult:onShow(id)
    GUISumRechargeLayout:hide()
    if not id then
        return
    end
    local config = SumRechargeConfig:getSumRecharge(id)
    if not config then
        return
    end
    SumRechargeResultEvent:invoke(id)
    if string.find(config.LayoutMainImage, ".actor")  ~= nil then
        self.ivImage:SetVisible(false)
        self.awActor:SetVisible(true)
        self.awActor:SetActor1(config.LayoutMainImage, "idle", 0)
    else
        self.ivImage:SetVisible(true)
        self.awActor:SetVisible(false)
        self.ivImage:SetImage(config.LayoutMainImage)
    end
end

function UISumRechargeResult:registerEvents()
    self:registerDataCallBack("SumRechargeResult", function(data)
        local id = data:getParam("Id")
        local config = SumRechargeConfig:getSumRecharge(id)
        if config then
            if self.__name ~= config.ResultUIName then
                self:reload(config.ResultUIName)
            end
            self:show(id)
        end
    end, DataBuilderProcessor)
end

function UISumRechargeResult:reload(name)
    GUIManager:removeLayout(self)
    GUIManager:destroyGUIWindow(self.root)
    for key, value in pairs(self) do
        if type(value) == "userdata" then
            self[key] = nil
        end
    end
    self.__name = name
    self:load()
end

return UISumRechargeResult