---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/1/17 14:39
---
--- DateTime: 2020/1/17 11:34
---
require "ui.window.GUIChangeItem"

local ShortCutBar = nil

local UITowerDefenseChangeTower = class("UITowerDefenseChangeTower", IGUILayout)

function UITowerDefenseChangeTower:onLoad()
    self.llClose = self:getChildWindow("TowerDefenseChangeTower-Close", GUIType.Layout)

    self:getChildWindow("TowerDefenseChangeTower-Title-Text", GUIType.StaticText):SetText(Lang:getString("gui_changetowertitle"))
    self:initRegister()
    self:initItemList()
end

function UITowerDefenseChangeTower:initRegister()
    self.llClose:registerEvent(GUIEvent.Click, function()
        self:close()
    end)

end

function UITowerDefenseChangeTower:close()
    self:hide()
end

function UITowerDefenseChangeTower:showPage(item)
    ShortCutBar = item
    self:show()
    self:updateItemList()
end

function UITowerDefenseChangeTower:initItemList()
    local llItemList = self:getChildWindow("TowerDefenseChangeTower-Content")
    self.itemList = IGUIGridView.new("TowerDefenseChangeTower-Items", llItemList)
    self.itemList:setArea({ 0, 0 }, { 0, 0 }, { 1, -26 }, { 1, -26 })
    self.itemList:setConfig(13, 13, 5)
    self.itemList.root:SetHorizontalAlignment(HorizontalAlignment.Center)
    self.itemList.root:SetVerticalAlignment(VerticalAlignment.Center)
    local ownTowers = GamePlayer:Instance():getOwnedTowerList()
    local allTowerConfig = TowerConfig:getShowSeq()
    if ownTowers ~= nil then
        for _, tower in pairs(allTowerConfig) do
            if ownTowers[tower.Id] ~= nil and not GUIMain:isInInitTowers(tower.Id) then
                local config = TowerConfig:getConfigById(tonumber(tower.Id))
                local towerItem = UIChangeItem.new("TowerDefenseChangeItem.json")
                towerItem:setWidth({ 0, 148 })
                towerItem:setHeight({ 0, 171 })
                towerItem:initInfo(config.Id)
                self.itemList:addItem(towerItem)
            end
        end
    end
end

function UITowerDefenseChangeTower:updateItemList()
    self.itemList:clearItems()
    local ownTowers = GamePlayer:Instance():getOwnedTowerList()
    local allTowerConfig = TowerConfig:getShowSeq()
    if ownTowers ~= nil then
        for _, tower in pairs(allTowerConfig) do
            if ownTowers[tower.Id] ~= nil and not GUIMain:isInInitTowers(tower.Id) then
                local config = TowerConfig:getConfigById(tonumber(tower.Id))
                if config.isShortCutPlace ~= 0 then
                    local towerItem = UIChangeItem.new("TowerDefenseChangeItem.json")
                    towerItem:setWidth({ 0, 148 })
                    towerItem:setHeight({ 0, 171 })
                    towerItem:initInfo(config.Id)
                    self.itemList:addItem(towerItem)
                end
            end
        end
    end
end

function UITowerDefenseChangeTower:onClickItem(towerId)
    if ShortCutBar.isBarLock then
        ShortCutBar:onClickUnlock(towerId)
    else
        ShortCutBar:onChoseTower(towerId)
        self:close()
    end
end

return UITowerDefenseChangeTower