---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 10184.
--- DateTime: 2020/7/21 16:15
---
local GMItemAdapter = class("GMItemAdapter", IDataAdapter)

function GMItemAdapter:setItemSize(width, height)
    self.width = width
    self.height = height
end

function GMItemAdapter:getWindowClass()
    return GUIGMItem
end

function GMItemAdapter:getJsonName()
    return "GMButton.json"
end

function GMItemAdapter:getItemWidth()
    return { 0, self.width }
end

function GMItemAdapter:getItemHeight()
    return { 0, self.height }
end

return GMItemAdapter