---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 10184.
--- DateTime: 2020/7/23 15:24
---
require "base.ui.window.GUIProbabilityItem"

local ProbabilityAdapter = class("ProbabilityAdapter", IDataAdapter)

function ProbabilityAdapter:setItemSize(width, height)
    self.width = width
    self.height = height
end

function ProbabilityAdapter:setJsonName(name)
    self.jsonName = name
end

function ProbabilityAdapter:getWindowClass()
    return GUIProbabilityItem
end

function ProbabilityAdapter:getJsonName()
    return self.jsonName or "ProbabilityItem.json"
end

function ProbabilityAdapter:getItemWidth()
    return { 0, self.width }
end

function ProbabilityAdapter:getItemHeight()
    return { 0, self.height }
end

return ProbabilityAdapter