---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 98632.
--- DateTime: 2019/10/17 17:54
---

local  Skills= MemoryPool.newTable()

SkillConfig = {}

function SkillConfig:loadConfig()

    local temp = FileUtil.getConfigFromCsv("setting/Skills.csv", 2)

    for _, Value in pairs(temp) do
        table.insert(Skills,{
            Id = tonumber(Value.n_id),
            Name = Value.s_name,
            Desc = Value.s_desc,
            Icon = Value.s_icon,
            Hurt  = tonumber(Value.n_hurt),
            Cd = tonumber(Value.n_cd),
            MoneyType = tonumber(Value.n_moneyType),
            Price = tonumber(Value.n_price),
            skillType = tonumber(Value.n_skillType) or 0, --技能类型
            Status = ItemBuyStatus.Lock, --购买状态
            holdItemId = tonumber(Value.n_holdItemId) or 0,
            skillTime = tonumber(Value.n_skillTime) or 0,
            delayTime = tonumber(Value.n_delayTime) or 0,
        })
    end

end

function SkillConfig:getSkills()
    return Skills
end

function SkillConfig:getSkillById(Id)

    for _, Value in pairs(Skills) do
        if Value.Id==Id then
            return Value
        end
    end
    return nil
end