---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 10184.
--- DateTime: 2020/7/16 20:14
---
require "hall.BaseHeader"
require "common.events.ClientEvents"
require "hall.listener.GameListener"
require "hall.listener.EntityListener"
require "hall.listener.PlayerListener"
require "hall.packet.GamePacketSender"
require "hall.entity.GameActorNpc"
require "hall.util.ReportUtil"
require "common.data.BuffInfo"

require "common.data.ClientTreasureChallenge"
require "common.entity.ClientPlayer"
require "common.pet.PetHeader"
require "common.manager.GameInfoManager"

BedWarClient = {}

function BedWarClient.onGameInit()
    GameListener:init()
    EntityListener:init()
    PlayerListener:init()
    registerMoneyIcon(4, "set:dress_shop.json image:chip")
    registerMoneyIcon(5, "set:app_shop.json image:bedwar_key")
    registerMoneyIcon(6, "set:icon_haojiao.json image:haojiao")
    registerMoneyIcon(7, "set:free_gift.json image:movie_ticket_icon")
    ClientHelper.putBoolPrefs("IsLoadSeason", true)
    ClientHelper.putBoolPrefs("IsRedAim", false)
end