---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jimmy.
--- DateTime: 2019/4/8 0008 10:34
---
local Sender
local CommonSender

PacketSender = {}

function PacketSender:init()
    Sender = ClientNetwork.Instance():getLuaSender()
    CommonSender = ClientNetwork.Instance():getLuaCommonSender()
end

function PacketSender:destroy()
    Sender = nil
    CommonSender = nil
end

function PacketSender:getSender()
    return Sender
end

function PacketSender:getCommonSender()
    return CommonSender
end

function PacketSender:sendPlayerDBReady(rakssid)
    if not Sender then
        return
    end
    Sender:sendPlayerDBDataReady(rakssid)
end

function PacketSender:sendCallOnManor(userId, from, isFriend, score)
    if not Sender then
        return
    end
    Sender:sendCallOnManor(userId, from, isFriend, score)
end

function PacketSender:sendClientCommonData(name, key, data)
    if not CommonSender then
        return
    end
    CommonSender:sendClientCommonData(name, key, data or "")
end

function PacketSender:sendLuaCommonData(key, data)
    if not CommonSender then
        return
    end
    CommonSender:sendLuaCommonData(key, data or "")
end

return PacketSender