#include "Blockman/Entity/EntityTrackerEntry.h"
#include "Blockman/Entity/EntityTracker.h"
#include "Blockman/Entity/EntityPlayerAI.h"
#include "Blockman/World/AnvilManagerServer.h"
#include "Blockman/World/AnvilServer.h"
#include "Blockman/World/BlockChangeRecorderServer.h"
#include "Blockman/Chunk/ChunkServer.h"
#include "Blockman/World/ServerWorld.h"
#include "Blockman/World/WorldServerListener.h"
#include "Inventory/InventoryPlayer.h"
#include "LuaRegister/Template/LuaRegister.h"
#include "Script/DynamicCastServerEntity.h"
#include "Script/ServerDynamicCast.h"
#include "RoomManager.h"
#include "Server.h"
#include "BtTreeController.h"

using namespace BLOCKMAN;
using namespace LUA_REGISTER;

// Register Class EntityPlayerMP
_BEGIN_REGISTER_CLASS(EntityPlayerMP)
_CLASSREGISTER_AddBaseClass(EntityPlayer)
_CLASSREGISTER_AddBaseClass(ICrafting)
_CLASSREGISTER_AddCtor(World *, const String &, const Vector3i &)
_CLASSREGISTER_AddMember(addMoveSpeedPotionEffect, EntityPlayerMP::addMoveSpeedPotionEffect)
_CLASSREGISTER_AddMember(addJumpPotionEffect, EntityPlayerMP::addJumpPotionEffect)
_CLASSREGISTER_AddMember(addNightVisionPotionEffect, EntityPlayerMP::addNightVisionPotionEffect)
_CLASSREGISTER_AddMember(addPoisonPotionEffect, EntityPlayerMP::addPoisonPotionEffect)
_CLASSREGISTER_AddMember(addEffect, EntityPlayerMP::addEffect)
_CLASSREGISTER_AddMember(removeEffect, EntityPlayerMP::removeEffect)
_CLASSREGISTER_AddMember(clearEffects, EntityPlayerMP::clearEffects)
_CLASSREGISTER_AddMember(changeMaxHealth, EntityPlayerMP::changeMaxHealth)
_CLASSREGISTER_AddMember(changeMaxHealthSingle, EntityPlayerMP::changeMaxHealthSingle)
_CLASSREGISTER_AddMember(addItem, EntityPlayerMP::addItem);
_CLASSREGISTER_AddMember(addGunItem, EntityPlayerMP::addGunItem);
_CLASSREGISTER_AddMember(replaceItem, EntityPlayerMP::replaceItem);
_CLASSREGISTER_AddMember(replaceArmorItemWithEnchant, EntityPlayerMP::replaceArmorItemWithEnchant)
_CLASSREGISTER_AddMember(addItemToEnderChest, EntityPlayerMP::addItemToEnderChest)
_CLASSREGISTER_AddMember(addGunItemToEnderChest, EntityPlayerMP::addGunItemToEnderChest)
_CLASSREGISTER_AddMember(equipArmor, EntityPlayerMP::equipArmor);
_CLASSREGISTER_AddMember(addChatMessage, EntityPlayerMP::addChatMessage)
_CLASSREGISTER_AddMember(addExperienceLevel, EntityPlayerMP::addExperienceLevel)
_CLASSREGISTER_AddMember(addSelfToInternalCraftingInventory, EntityPlayerMP::addSelfToInternalCraftingInventory)
_CLASSREGISTER_AddMember(attackEntityFrom, EntityPlayerMP::attackEntityFrom)
_CLASSREGISTER_AddMember(canAttackPlayer, EntityPlayerMP::canAttackPlayer)
_CLASSREGISTER_AddMember(canCommandSenderUseCommand, EntityPlayerMP::canCommandSenderUseCommand)
_CLASSREGISTER_AddMember(clonePlayer, EntityPlayerMP::clonePlayer)
_CLASSREGISTER_AddMember(closeContainer, EntityPlayerMP::closeContainer)
_CLASSREGISTER_AddMember(closeScreen, EntityPlayerMP::closeScreen)
_CLASSREGISTER_AddMember(getChatVisibility, EntityPlayerMP::getChatVisibility)
_CLASSREGISTER_AddMember(getEyeHeight, EntityPlayerMP::getEyeHeight)
_CLASSREGISTER_AddMember(getPlayerCoordinates, EntityPlayerMP::getPlayerCoordinates)
_CLASSREGISTER_AddMember(getPlayerIP, EntityPlayerMP::getPlayerIP)
_CLASSREGISTER_AddMember(getRaknetID, EntityPlayerMP::getRaknetID)
_CLASSREGISTER_AddMember(jump, EntityPlayerMP::jump)
_CLASSREGISTER_AddMember(specialJump, EntityPlayerMP::specialJump)
_CLASSREGISTER_AddMember(dropItemIntoChest, EntityPlayerMP::dropItemIntoChest)
_CLASSREGISTER_AddMember(knockBack, EntityPlayerMP::knockBack)
_CLASSREGISTER_AddMember(onCriticalHit, EntityPlayerMP::onCriticalHit)
_CLASSREGISTER_AddMember(onDeath, EntityPlayerMP::onDeath)
_CLASSREGISTER_AddMember(onEnchantmentCritical, EntityPlayerMP::onEnchantmentCritical)
_CLASSREGISTER_AddMember(onItemPickup, EntityPlayerMP::onItemPickup)
_CLASSREGISTER_AddMember(onUpdate, EntityPlayerMP::onUpdate)
_CLASSREGISTER_AddMember(readEntityFromNBT, EntityPlayerMP::readEntityFromNBT)
_CLASSREGISTER_AddMember(requestTexturePackLoad, EntityPlayerMP::requestTexturePackLoad)
_CLASSREGISTER_AddMember(sendChatToPlayer, EntityPlayerMP::sendChatToPlayer)
_CLASSREGISTER_AddMember(sendContainerAndContentsToPlayer, EntityPlayerMP::sendContainerAndContentsToPlayer)
_CLASSREGISTER_AddMember(sendContainerToPlayer, EntityPlayerMP::sendContainerToPlayer)
_CLASSREGISTER_AddMember(sendPlayerAbilities, EntityPlayerMP::sendPlayerAbilities)
_CLASSREGISTER_AddMember(sendProgressBarUpdate, EntityPlayerMP::sendProgressBarUpdate)
_CLASSREGISTER_AddMember(sendSlotContents, EntityPlayerMP::sendSlotContents)
_CLASSREGISTER_AddMember(setGameType, EntityPlayerMP::setGameType)
_CLASSREGISTER_AddMember(setItemInUse, EntityPlayerMP::setItemInUse)
_CLASSREGISTER_AddMember(setPositionAndUpdate, EntityPlayerMP::setPositionAndUpdate)
_CLASSREGISTER_AddMember(setRaknetID, EntityPlayerMP::setRaknetID)
_CLASSREGISTER_AddMember(sleepInBedAt, EntityPlayerMP::sleepInBedAt)
_CLASSREGISTER_AddMember(travelToDimension, EntityPlayerMP::travelToDimension)
_CLASSREGISTER_AddMember(triggerEntityUpdate, EntityPlayerMP::triggerEntityUpdate)
_CLASSREGISTER_AddMember(updateFlyingState, EntityPlayerMP::updateFlyingState)
_CLASSREGISTER_AddMember(updateHeldItem, EntityPlayerMP::updateHeldItem)
_CLASSREGISTER_AddMember(updatePotionMetadata, EntityPlayerMP::updatePotionMetadata)
_CLASSREGISTER_AddMember(useItem, EntityPlayerMP::useItem)
_CLASSREGISTER_AddMember(wakeUpPlayer, EntityPlayerMP::wakeUpPlayer)
_CLASSREGISTER_AddMember(writeEntityToNBT, EntityPlayerMP::writeEntityToNBT)
_CLASSREGISTER_AddMember(setExtraInventoryCount, EntityPlayerMP::setExtraInventoryCount)
_CLASSREGISTER_AddMember(setAllowFlying, EntityPlayerMP::setAllowFlying)
_CLASSREGISTER_AddMember(setHoldItemId, EntityPlayerMP::setHoldItemId)
_CLASSREGISTER_AddMember(setWatchMode, EntityPlayerMP::setWatchMode)
_CLASSREGISTER_AddMember(addEchantmentItem, EntityPlayerMP::addEchantmentItem)
_CLASSREGISTER_AddMember(addItemPotion, EntityPlayerMP::addItemPotion)
_CLASSREGISTER_AddMember(changeCurrentItem, EntityPlayerMP::changeCurrentItem)
_CLASSREGISTER_AddMember(setCurrency, EntityPlayerMP::setCurrency)
_CLASSREGISTER_AddMember(addCurrency, EntityPlayerMP::addCurrency)
_CLASSREGISTER_AddMember(subCurrency, EntityPlayerMP::subCurrency)
_CLASSREGISTER_AddMember(getCurrency, EntityPlayerMP::getCurrency)
_CLASSREGISTER_AddMember(changeClothes, EntityPlayerMP::changeClothes)
_CLASSREGISTER_AddMember(resetClothes, EntityPlayerMP::resetClothes)
_CLASSREGISTER_AddMember(addBackpackCapacity, EntityPlayerMP::addBackpackCapacity)
_CLASSREGISTER_AddMember(subBackpackCapacity, EntityPlayerMP::subBackpackCapacity)
_CLASSREGISTER_AddMember(resetBackpack, EntityPlayerMP::resetBackpack)
_CLASSREGISTER_AddMember(isParachute, EntityPlayerMP::isParachute)
_CLASSREGISTER_AddMember(setChangePlayerActor, EntityPlayerMP::setChangePlayerActor)
_CLASSREGISTER_AddMember(setCameraLocked, EntityPlayerMP::setCameraLocked)
_CLASSREGISTER_AddMember(changeInvisible, EntityPlayerMP::changeInvisible)
_CLASSREGISTER_AddMember(changeNamePerspective, EntityPlayerMP::changeNamePerspective)
_CLASSREGISTER_AddMember(changeHeart, EntityPlayerMP::changeHeart)
_CLASSREGISTER_AddMember(setScale, EntityPlayerMP::setScale)
_CLASSREGISTER_AddMember(showBossStripWithIcon, EntityPlayerMP::showBossStripWithIcon)
_CLASSREGISTER_AddMember(changeDefense, EntityPlayerMP::changeDefense)
_CLASSREGISTER_AddMember(changeAttack, EntityPlayerMP::changeAttack)
_CLASSREGISTER_AddMember(changeApple, EntityPlayerMP::changeApple)
_CLASSREGISTER_AddMember(appleFresh, EntityPlayerMP::appleFresh)
_CLASSREGISTER_AddMember(setPersonalShopArea, EntityPlayerMP::setPersonalShopArea)
_CLASSREGISTER_AddMember(changeSwitchableProps, EntityPlayerMP::changeSwitchableProps)
_CLASSREGISTER_AddMember(changeUpgradeProps, EntityPlayerMP::changeUpgradeProps)
_CLASSREGISTER_AddMember(changeEnchantmentProps, EntityPlayerMP::changeEnchantmentProps)
_CLASSREGISTER_AddMember(changeSuperProps, EntityPlayerMP::changeSuperProps)
_CLASSREGISTER_AddMember(setSpeedAdditionLevel, EntityPlayerMP::setSpeedAdditionLevel)
_CLASSREGISTER_AddMember(updateExp, EntityPlayerMP::updateExp)
_CLASSREGISTER_AddMember(playSkillEffect, EntityPlayerMP::playSkillEffect)
_CLASSREGISTER_AddMember(sendSkillEffect, EntityPlayerMP::sendSkillEffect)
_CLASSREGISTER_AddMember(setOccupation, EntityPlayerMP::setOccupation)
_CLASSREGISTER_AddMember(setUnlockedCommodities, EntityPlayerMP::setUnlockedCommodities)
_CLASSREGISTER_AddMember(setArmItem, EntityPlayerMP::setArmItem)
_CLASSREGISTER_AddMember(setFire, EntityPlayerMP::setFire)
_CLASSREGISTER_AddMember(addGunDamage, EntityPlayerMP::addGunDamage)
_CLASSREGISTER_AddMember(addGunBulletNum, EntityPlayerMP::addGunBulletNum)
_CLASSREGISTER_AddMember(subGunRecoil, EntityPlayerMP::subGunRecoil)
_CLASSREGISTER_AddMember(subGunFireCd, EntityPlayerMP::subGunFireCd)
_CLASSREGISTER_AddMember(changeCustomProps, EntityPlayerMP::changeCustomProps)
_CLASSREGISTER_AddMember(updateCustomProps, EntityPlayerMP::updateCustomProps)
_CLASSREGISTER_AddMember(setOnFrozen, EntityPlayerMP::setOnFrozen)
_CLASSREGISTER_AddMember(getRanch, EntityPlayerMP::getRanch)
_CLASSREGISTER_AddMember(setOnHurt, EntityPlayerMP::setOnHurt)
_CLASSREGISTER_AddMember(setOnColorful, EntityPlayerMP::setOnColorful)
_CLASSREGISTER_AddMember(setDisableMove, EntityPlayerMP::setDisableMove)
_CLASSREGISTER_AddMember(getDiamond, EntityPlayerMP::getDiamond)
_CLASSREGISTER_AddMember(getGold, EntityPlayerMP::getGold)
_CLASSREGISTER_AddMember(setOnFire, EntityPlayerMP::setOnFire)
_CLASSREGISTER_AddMember(getBirdSimulator, EntityPlayerMP::getBirdSimulator)
_CLASSREGISTER_AddMember(setBagInfo, EntityPlayerMP::setBagInfo)
_CLASSREGISTER_AddMember(setBirdConvert, EntityPlayerMP::setBirdConvert)
_CLASSREGISTER_AddMember(setGlide, EntityPlayerMP::setGlide)
_CLASSREGISTER_AddMember(setFlyWing, EntityPlayerMP::setFlyWing)
_CLASSREGISTER_AddMember(getClothesId, EntityPlayerMP::getClothesId)
_CLASSREGISTER_AddMember(getBlockCity, EntityPlayerMP::getBlockCity)
_CLASSREGISTER_AddMember(placeBlock, EntityPlayerMP::placeBlock)
_CLASSREGISTER_AddMember(getOffVehicle, EntityPlayerMP::getOffVehicle)
_CLASSREGISTER_AddMember(syncOwnVehicle, EntityPlayerMP::syncOwnVehicle)
_CLASSREGISTER_AddMember(getBulletNum, EntityPlayerMP::getBulletNum)
_CLASSREGISTER_AddMember(getBlockFort, EntityPlayerMP::getBlockFort)
_CLASSREGISTER_AddMember(getInventoryPlayer, EntityPlayerMP::getInventoryPlayer)
_CLASSREGISTER_AddMember(setElevator, EntityPlayerMP::setElevator)
_CLASSREGISTER_AddMember(setFlying, EntityPlayerMP::setFlying)
_CLASSREGISTER_AddMember(propertyChanged, EntityPlayerMP::propertyChanged)
_CLASSREGISTER_AddMember(markInventoryDirty, EntityPlayerMP::markInventoryDirty)
_CLASSREGISTER_AddMember(inventoryForceUpdate, EntityPlayerMP::inventoryForceUpdate)
_CLASSREGISTER_AddMember(getOnFlyingMount, EntityPlayerMP::getOnFlyingMount)
_CLASSREGISTER_AddMember(getOffFlyingMount, EntityPlayerMP::getOffFlyingMount)
_CLASSREGISTER_AddMember(getSpeedAddition, EntityPlayerMP::getSpeedAddition)
_CLASSREGISTER_AddMember(playAnimate, EntityPlayerMP::playAnimate)
_END_REGISTER_CLASS()

// Register Class EntityPlayerAI
_BEGIN_REGISTER_CLASS(EntityPlayerAI)
_CLASSREGISTER_AddBaseClass(EntityPlayerMP)
_CLASSREGISTER_AddMember(sendLogin, EntityPlayerAI::sendLogin)
_CLASSREGISTER_AddMember(sendLogout, EntityPlayerAI::sendLogout)
_CLASSREGISTER_AddMember(sendReady, EntityPlayerAI::sendReady)
_CLASSREGISTER_AddMember(sendAttack, EntityPlayerAI::sendAttack)
_CLASSREGISTER_AddMember(sendMovementInputChanged, EntityPlayerAI::sendMovementInputChanged)
_CLASSREGISTER_AddMember(stopMove, EntityPlayerAI::stopMove)
_CLASSREGISTER_AddMember(sendPlayerMovement, EntityPlayerAI::sendPlayerMovement)
_CLASSREGISTER_AddMember(sendPlayerRotationChanged, EntityPlayerAI::sendPlayerRotationChanged)
_CLASSREGISTER_AddMember(sendJumpChanged, EntityPlayerAI::sendJumpChanged)
_CLASSREGISTER_AddMember(moveToPos, EntityPlayerAI::moveToPos)
_CLASSREGISTER_AddMember(faceToPos, EntityPlayerAI::faceToPos)
_CLASSREGISTER_AddMember(faceToEntity, EntityPlayerAI::faceToEntity)
_CLASSREGISTER_AddMember(placeBlock, EntityPlayerAI::placeBlock)
_CLASSREGISTER_AddMember(breakBlock, EntityPlayerAI::breakBlock)
_CLASSREGISTER_AddMember(abortBreakBlock, EntityPlayerAI::abortBreakBlock)
_CLASSREGISTER_AddMember(attackEntity, EntityPlayerAI::attackEntity)
_CLASSREGISTER_AddMember(startShootArrow, EntityPlayerAI::startShootArrow)
_CLASSREGISTER_AddMember(setHandItemId, EntityPlayerAI::setHandItemId)
_CLASSREGISTER_AddMember(relaseItemSkill, EntityPlayerAI::relaseItemSkill)
_CLASSREGISTER_AddMember(startSneak, EntityPlayerAI::startSneak)
_END_REGISTER_CLASS()


// Register Class EntityTracker
_BEGIN_REGISTER_CLASS(EntityTracker)
_CLASSREGISTER_AddBaseClass(Singleton<EntityTracker>)
_CLASSREGISTER_AddBaseClass(ObjectAlloc)
_CLASSREGISTER_AddCtor(World *)
_CLASSREGISTER_AddMember_Override(addEntityToTracker, EntityTracker::addEntityToTracker, void, Entity *)
_CLASSREGISTER_AddMember(getTrackingPlayersOf, EntityTracker::getTrackingPlayersOf)
_CLASSREGISTER_AddMember(removeEntityFromAllTrackingPlayers, EntityTracker::removeEntityFromAllTrackingPlayers)
_CLASSREGISTER_AddMember(removePlayerFromTrackers, EntityTracker::removePlayerFromTrackers)
_CLASSREGISTER_AddMember(sendLeashedEntitiesInChunk, EntityTracker::sendLeashedEntitiesInChunk)
_CLASSREGISTER_AddMember(updateTrackedEntities, EntityTracker::updateTrackedEntities)
_END_REGISTER_CLASS()




// Register Class EntityTrackerEntry
_BEGIN_REGISTER_CLASS(EntityTrackerEntry)
_CLASSREGISTER_AddBaseClass(ObjectAlloc)
_CLASSREGISTER_AddCtor(Entity *, int, int, bool)
_CLASSREGISTER_AddMember(equals, EntityTrackerEntry::equals)
_CLASSREGISTER_AddMember(hashCode, EntityTrackerEntry::hashCode)
_CLASSREGISTER_AddMember(informAllAssociatedPlayersOfItemDestruction, EntityTrackerEntry::informAllAssociatedPlayersOfItemDestruction)
_CLASSREGISTER_AddMember(removeFromWatchingList, EntityTrackerEntry::removeFromWatchingList)
_CLASSREGISTER_AddMember(removePlayerFromTracker, EntityTrackerEntry::removePlayerFromTracker)
_CLASSREGISTER_AddMember(processWatchRemoveRelationTo, EntityTrackerEntry::spawnOrRemoveSelfEntityFor)
_CLASSREGISTER_AddMember(informMovementChangeToTrackingPlayers, EntityTrackerEntry::informMovementChangeToTrackingPlayers)
_CLASSREGISTER_AddMember(watchOrRemoveForEachOtherIfNeed, EntityTrackerEntry::spawnOrRemoveSelfEntityAtClientOf)
_END_REGISTER_CLASS()




// Register Class AnvilManagerServer
_BEGIN_REGISTER_CLASS(AnvilManagerServer)
_CLASSREGISTER_AddBaseClass(AnvilManager)
_END_REGISTER_CLASS()




// Register Class ChunkServerWithMeta
_BEGIN_REGISTER_CLASS(ChunkServerWithMeta)
_END_REGISTER_CLASS()


// Register Class BlockChangeRecorderServer
_BEGIN_REGISTER_CLASS(BlockChangeRecorderServer)
_CLASSREGISTER_AddBaseClass(Singleton<BlockChangeRecorderServer>)
_CLASSREGISTER_AddBaseClass(ObjectAlloc)
_CLASSREGISTER_AddMember(getChangedPositions, BlockChangeRecorderServer::getChangedPositions)
_CLASSREGISTER_AddMember_Override(record, BlockChangeRecorderServer::record, bool, int, int, int)
_CLASSREGISTER_AddMember_Override(record1, BlockChangeRecorderServer::record, bool, const BlockPos &)
_END_REGISTER_CLASS()

#pragma region // Register Class ServerWorld
_BEGIN_REGISTER_CLASS(ServerWorld)
_CLASSREGISTER_AddBaseClass(World)
_CLASSREGISTER_AddMember(fireTNT, ServerWorld::fireTNT)
_CLASSREGISTER_AddMember(addAirDrop, ServerWorld::addAirDrop)
_CLASSREGISTER_AddMember(addRobot, ServerWorld::addRobot)
_CLASSREGISTER_AddMember(addWalkingDead, ServerWorld::addWalkingDead)
_CLASSREGISTER_AddMember(addEntityPlayerAI, ServerWorld::addEntityPlayerAI)
_CLASSREGISTER_AddMember(addCreature, ServerWorld::addCreature)
_CLASSREGISTER_AddMember(killCreature, ServerWorld::killCreature)
_CLASSREGISTER_AddMember(fillAreaByBlockIdAndMate, ServerWorld::fillAreaByBlockIdAndMate)
_CLASSREGISTER_AddMember(setCropsBlock, ServerWorld::setCropsBlock)
_CLASSREGISTER_AddMember(changeCreatureAttackTarget, ServerWorld::changeCreatureAttackTarget)
_CLASSREGISTER_AddMember(addSkillEffect, ServerWorld::addSkillEffect)
_CLASSREGISTER_AddMember(isInChangeRecord, ServerWorld::isInChangeRecord)
_CLASSREGISTER_AddMember(updateActorNpcContent, ServerWorld::updateActorNpcContent)
_CLASSREGISTER_AddMember(updateActorNpcSuspended, ServerWorld::updateActorNpcSuspended)
_CLASSREGISTER_AddMember(updateSessionNpcHeadInfoMultiLang, ServerWorld::updateSessionNpcHeadInfoMultiLang)
_CLASSREGISTER_AddMember(addSimpleEffect, ServerWorld::addSimpleEffect)
_CLASSREGISTER_AddMember(removeSimpleEffect, ServerWorld::removeSimpleEffect)
_CLASSREGISTER_AddMember(setRailSpeedInfo, ServerWorld::setRailSpeedInfo)
_CLASSREGISTER_AddMember(setRailCarMaxSpeed, ServerWorld::setRailCarMaxSpeed)
_CLASSREGISTER_AddMember(setRailCarCurSpeed, ServerWorld::setRailCarCurSpeed)
_CLASSREGISTER_AddMember(setRailCarAddSpeed, ServerWorld::setRailCarAddSpeed)
_CLASSREGISTER_AddMember(setRailCarRecordRoute, ServerWorld::setRailCarRecordRoute)
_CLASSREGISTER_AddMember(setRailCarActor, ServerWorld::setRailCarActor)
_CLASSREGISTER_AddMember(setRailCarName, ServerWorld::setRailCarName)
_CLASSREGISTER_AddMember(startRailCarRun, ServerWorld::startRailCarRun)
_CLASSREGISTER_AddMember(changeRailCarDirection, ServerWorld::changeRailCarDirection)
_CLASSREGISTER_AddMember(setRailCarFrozen, ServerWorld::setRailCarFrozen)
_CLASSREGISTER_AddMember(updateBuildNpc, ServerWorld::updateBuildNpc)
_CLASSREGISTER_AddMember(playCloseup, ServerWorld::playCloseup)
_CLASSREGISTER_AddMember(setEntitySelected, ServerWorld::setEntitySelected)
_CLASSREGISTER_AddMember(addEntityBulletin, ServerWorld::addEntityBulletin)
_CLASSREGISTER_AddMember(updateEntityBulletin, ServerWorld::updateEntityBulletin)
_CLASSREGISTER_AddMember(updateEntityBulletinUserRank, ServerWorld::updateEntityBulletinUserRank)
_CLASSREGISTER_AddMember(addEntityBird, ServerWorld::addEntityBird)
_CLASSREGISTER_AddMember(setBirdDress, ServerWorld::setBirdDress)
_CLASSREGISTER_AddMember(updateBirdDress, ServerWorld::updateBirdDress)
_CLASSREGISTER_AddMember(updateSessionNpc, ServerWorld::updateSessionNpc)
_CLASSREGISTER_AddMember(setFruitsBlock, ServerWorld::setFruitsBlock)
_CLASSREGISTER_AddMember(forceCreatureToPos, ServerWorld::forceCreatureToPos)
_CLASSREGISTER_AddMember(setEntityHealth, ServerWorld::setEntityHealth)
_CLASSREGISTER_AddMember(setCreatureHome, ServerWorld::setCreatureHome)
_CLASSREGISTER_AddMember(getInventory, ServerWorld::getInventory)
_CLASSREGISTER_AddMember(setQuickWorldTime, ServerWorld::setQuickWorldTime)
_CLASSREGISTER_AddMember(updateSessionNpcHeadInfoTime, ServerWorld::updateSessionNpcHeadInfoTime)
_CLASSREGISTER_AddMember(createSchematic, ServerWorld::createSchematic)
_CLASSREGISTER_AddMember(destroySchematic, ServerWorld::destroySchematic)
_END_REGISTER_CLASS()
#pragma endregion




// Register Class ChunkServer
_BEGIN_REGISTER_CLASS(ChunkServer)
_CLASSREGISTER_AddBaseClass(Chunk)
_CLASSREGISTER_AddMember(setBlockIDAndMeta, ChunkServer::setBlockIDAndMeta)
_CLASSREGISTER_AddMember(setBlockMeta, ChunkServer::setBlockMeta)
_END_REGISTER_CLASS()




// Register Class BlockEventData
_BEGIN_REGISTER_CLASS(BlockEventData)
_CLASSREGISTER_AddCtor(const BlockPos &, int, int, int)
_END_REGISTER_CLASS()




// Register Class TickEntry
_BEGIN_REGISTER_CLASS(TickEntry)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddCtor(const BlockPos, int)
_END_REGISTER_CLASS()




// Register Class WorldServerListener
_BEGIN_REGISTER_CLASS(WorldServerListener)
_CLASSREGISTER_AddBaseClass(IWorldEventListener)
_CLASSREGISTER_AddBaseClass(ObjectAlloc)
_CLASSREGISTER_AddCtor(ServerWorld *)
_CLASSREGISTER_AddMember(broadcastSound, WorldServerListener::broadcastSound)
_CLASSREGISTER_AddMember(destroyBlockPartially, WorldServerListener::destroyBlockPartially)
_CLASSREGISTER_AddMember(markBlockForRenderUpdate, WorldServerListener::markBlockForRenderUpdate)
_CLASSREGISTER_AddMember(markBlockForUpdate, WorldServerListener::markBlockForUpdate)
_CLASSREGISTER_AddMember(markSectionForUpdate, WorldServerListener::markSectionForUpdate)
_CLASSREGISTER_AddMember(markBlockRangeForRenderUpdate, WorldServerListener::markBlockRangeForRenderUpdate)
_CLASSREGISTER_AddMember(onEntityCreate, WorldServerListener::onEntityCreate)
_CLASSREGISTER_AddMember(onEntityDestroy, WorldServerListener::onEntityDestroy)
_CLASSREGISTER_AddMember(playAuxSFX, WorldServerListener::playAuxSFX)
_CLASSREGISTER_AddMember(playRecord, WorldServerListener::playRecord)
_CLASSREGISTER_AddMember(playSound, WorldServerListener::playSound)
_CLASSREGISTER_AddMember(playSoundToNearExcept, WorldServerListener::playSoundToNearExcept)
_CLASSREGISTER_AddMember(spawnParticle, WorldServerListener::spawnParticle)
_END_REGISTER_CLASS()


// Register Class DynamicCastServerEntity
_BEGIN_REGISTER_CLASS(DynamicCastServerEntity)
_CLASSREGISTER_AddStaticMember(dynamicCastBirdAI, DynamicCastServerEntity::dynamicCastBirdAI)
_CLASSREGISTER_AddStaticMember(dynamicCastCreatureAI, DynamicCastServerEntity::dynamicCastCreatureAI)
_CLASSREGISTER_AddStaticMember(dynamicCastPlayerMP, DynamicCastServerEntity::dynamicCastPlayerMP)
_CLASSREGISTER_AddStaticMember(dynamicCastRobotAI, DynamicCastServerEntity::dynamicCastRobotAI)
_CLASSREGISTER_AddStaticMember(dynamicCastWalkingDeadAI, DynamicCastServerEntity::dynamicCastWalkingDeadAI)
_END_REGISTER_CLASS()


_BEGIN_REGISTER_CLASS(Server)
_CLASSREGISTER_AddStaticMember(Instance, Server::Instance)
_CLASSREGISTER_AddMember(getWorld, Server::getWorld)
_CLASSREGISTER_AddMember(getServerFramTime, Server::getServerFramTime)
_CLASSREGISTER_AddMember(getGameType, Server::getGameType)
_CLASSREGISTER_AddMember(getLuaRoomManager, Server::getLuaRoomManager)
_CLASSREGISTER_AddMember(startRedis, Server::startRedis)
_CLASSREGISTER_AddMember(getConfig, Server::getConfig)
_CLASSREGISTER_AddMember(setInitPos, Server::setInitPos)
_CLASSREGISTER_AddMember(getEnableRoom, Server::getEnableRoom)
_END_REGISTER_CLASS()


_BEGIN_REGISTER_CLASS(GamePartyParam)
_CLASSREGISTER_AddVar(userId, GamePartyParam::userId)
_CLASSREGISTER_AddVar(createAt, GamePartyParam::createAt)
_CLASSREGISTER_AddVar(expiredAt, GamePartyParam::expiredAt)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(UserAttrInfo)
_CLASSREGISTER_AddVar(requestId, UserAttrInfo::requestId)
_CLASSREGISTER_AddVar(country, UserAttrInfo::country)
_CLASSREGISTER_AddVar(picUrl, UserAttrInfo::picUrl)
_CLASSREGISTER_AddVar(lang, UserAttrInfo::lang)
_CLASSREGISTER_AddVar(userId, UserAttrInfo::userId)
_CLASSREGISTER_AddVar(targetUserId, UserAttrInfo::targetUserId)
_CLASSREGISTER_AddVar(manorId, UserAttrInfo::manorId)
_CLASSREGISTER_AddVar(classes, UserAttrInfo::classes)
_CLASSREGISTER_AddVar(team, UserAttrInfo::team)
_CLASSREGISTER_AddVar(regionId, UserAttrInfo::regionId)
_CLASSREGISTER_AddVar(vip, UserAttrInfo::vip)
_CLASSREGISTER_AddVar(sex, UserAttrInfo::sex)
_CLASSREGISTER_AddVar(faceId, UserAttrInfo::faceId)
_CLASSREGISTER_AddVar(hairId, UserAttrInfo::hairId)
_CLASSREGISTER_AddVar(topsId, UserAttrInfo::topsId)
_CLASSREGISTER_AddVar(pantsId, UserAttrInfo::pantsId)
_CLASSREGISTER_AddVar(shoesId, UserAttrInfo::shoesId)
_CLASSREGISTER_AddVar(glassesId, UserAttrInfo::glassesId)
_CLASSREGISTER_AddVar(scarfId, UserAttrInfo::scarfId)
_CLASSREGISTER_AddVar(wingId, UserAttrInfo::wingId)
_CLASSREGISTER_AddVar(hatId, UserAttrInfo::hatId)
_CLASSREGISTER_AddVar(decoratehatId, UserAttrInfo::decoratehatId)
_CLASSREGISTER_AddVar(armId, UserAttrInfo::armId)
_CLASSREGISTER_AddVar(tailId, UserAttrInfo::tailId)
_CLASSREGISTER_AddVar(extrawingId, UserAttrInfo::extrawingId)
_CLASSREGISTER_AddVar(footHaloId, UserAttrInfo::footHaloId)
_CLASSREGISTER_AddVar(backEffectId, UserAttrInfo::backEffectId)
_CLASSREGISTER_AddVar(headEffectId, UserAttrInfo::headEffectId)
_CLASSREGISTER_AddVar(crownId, UserAttrInfo::crownId)
_CLASSREGISTER_AddVar(bagId, UserAttrInfo::bagId)
_CLASSREGISTER_AddVar(skinColor, UserAttrInfo::skinColor)
_CLASSREGISTER_AddVar(updateTimestamp, UserAttrInfo::updateTimestamp)
_CLASSREGISTER_AddVar(defaultIdle, UserAttrInfo::defaultIdle)
_CLASSREGISTER_AddVar(scale, UserAttrInfo::scale)
_CLASSREGISTER_AddVar(gamePartyParam, UserAttrInfo::gamePartyParam)
_CLASSREGISTER_AddVar(privateParty, UserAttrInfo::privateParty)
_CLASSREGISTER_AddVar(isRobot, UserAttrInfo::isRobot)
_CLASSREGISTER_AddVar(robotId, UserAttrInfo::robotId)
_CLASSREGISTER_AddVar(followEnterType, UserAttrInfo::followEnterType)
_CLASSREGISTER_AddVar(name, UserAttrInfo::name)
_END_REGISTER_CLASS()


_BEGIN_REGISTER_CLASS(RoomManager)
_CLASSREGISTER_AddMember_Override(getUserAttrInfo, RoomManager::getUserAttrInfo, UserAttrInfo*, ui64)
_CLASSREGISTER_AddMember(isUserAttrExisted, RoomManager::isUserAttrExisted)
_CLASSREGISTER_AddMember(sendUserOut, RoomManager::sendUserOut)
_END_REGISTER_CLASS()


_BEGIN_REGISTER_CLASS(ServerDynamicCast)
_CLASSREGISTER_AddStaticMember(dynamicCastServerWorld, ServerDynamicCast::dynamicCastServerWorld)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(BtTreeController)
_CLASSREGISTER_AddStaticMember(Instance, BtTreeController::Instance)
_CLASSREGISTER_AddMember(addBtTree, BtTreeController::addBtTree)
_CLASSREGISTER_AddMember(removeBtTree, BtTreeController::removeBtTree)
_END_REGISTER_CLASS()