#include "LuaRegister/Template/LuaRegister.h"
#include "Game/Manor.h"
#include "Game/Ranch.h"
#include "Game/BirdSimulator.h"
#include "Game/BlockCity.h"
#include "Game/BlockFort.h"
#include "Setting/RanchSetting.h"
#include "Entity/EntityBuildNpc.h"
#include "Entity/EntityBulletin.h"
#include "Setting/SceneSetting.h"

using namespace BLOCKMAN;
using namespace LUA_REGISTER;

_BEGIN_REGISTER_CLASS(ManorInfo)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(id, ManorInfo::id)
_CLASSREGISTER_AddVar(manorId, ManorInfo::manorId)
_CLASSREGISTER_AddVar(rose, ManorInfo::rose)
_CLASSREGISTER_AddVar(level, ManorInfo::level)
_CLASSREGISTER_AddVar(price, ManorInfo::price)
_CLASSREGISTER_AddVar(value, ManorInfo::value)
_CLASSREGISTER_AddVar(houseId, ManorInfo::houseId)
_CLASSREGISTER_AddVar(charm, ManorInfo::charm)
_CLASSREGISTER_AddVar(maxLevel, ManorInfo::maxLevel)
_CLASSREGISTER_AddVar(seed, ManorInfo::seed)
_CLASSREGISTER_AddVar(ground, ManorInfo::ground)
_CLASSREGISTER_AddVar(icon, ManorInfo::icon)
_CLASSREGISTER_AddVar(currencyType, ManorInfo::currencyType)
_CLASSREGISTER_AddVar(isMaster, ManorInfo::isMaster)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(ManorHouse)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(id, ManorHouse::id)
_CLASSREGISTER_AddVar(price, ManorHouse::price)
_CLASSREGISTER_AddVar(charm, ManorHouse::charm)
_CLASSREGISTER_AddVar(unlockLevel, ManorHouse::unlockLevel)
_CLASSREGISTER_AddVar(cdTime, ManorHouse::cdTime)
_CLASSREGISTER_AddVar(icon, ManorHouse::icon)
_CLASSREGISTER_AddVar(name, ManorHouse::name)
_CLASSREGISTER_AddVar(isBuy, ManorHouse::isBuy)
_CLASSREGISTER_AddVar(currencyType, ManorHouse::currencyType)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(ManorFurniture)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(id, ManorFurniture::id)
_CLASSREGISTER_AddVar(price, ManorFurniture::price)
_CLASSREGISTER_AddVar(charm, ManorFurniture::charm)
_CLASSREGISTER_AddVar(icon, ManorFurniture::icon)
_CLASSREGISTER_AddVar(name, ManorFurniture::name)
_CLASSREGISTER_AddVar(operationType, ManorFurniture::operationType)
_CLASSREGISTER_AddVar(currencyType, ManorFurniture::currencyType)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(ManorMessage)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(id, ManorMessage::id)
_CLASSREGISTER_AddVar(userId, ManorMessage::userId)
_CLASSREGISTER_AddVar(messageType, ManorMessage::messageType)
_CLASSREGISTER_AddVar(content, ManorMessage::content)
_CLASSREGISTER_AddVar(userName, ManorMessage::userName)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(ManorOwner)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(index, ManorOwner::index)
_CLASSREGISTER_AddVar(ownerId, ManorOwner::ownerId)
_CLASSREGISTER_AddVar(origin, ManorOwner::origin)
_CLASSREGISTER_AddVar(termini, ManorOwner::termini)
_END_REGISTER_CLASS()

// Register Class Ranch
_BEGIN_REGISTER_CLASS(Ranch)
_CLASSREGISTER_AddBaseClass(ObjectAlloc)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddMember(setInfo, Ranch::setInfo)
_CLASSREGISTER_AddMember(setHouse, Ranch::setHouse)
_CLASSREGISTER_AddMember(setStorage, Ranch::setStorage)
_CLASSREGISTER_AddMember(updateStorageById, Ranch::updateStorageById)
_CLASSREGISTER_AddMember(setRankByType, Ranch::setRankByTypeFromLua)
_CLASSREGISTER_AddMember(setBuildByType, Ranch::setBuildByTypeFromLua)
_CLASSREGISTER_AddMember(setOrders, Ranch::setOrdersFromLua)
_CLASSREGISTER_AddMember(setAchievements, Ranch::setAchievementsFromLua)
_CLASSREGISTER_AddMember(setTimePrices, Ranch::setTimePricesFromLua)
_CLASSREGISTER_AddMember(setShortcutFreeTimes, Ranch::setShortcutFreeTimesFromLua)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(RanchCommon)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(itemId, RanchCommon::itemId)
_CLASSREGISTER_AddVar(num, RanchCommon::num)
_CLASSREGISTER_AddVar(price, RanchCommon::price)
_CLASSREGISTER_AddVar(userId, RanchCommon::userId)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(RanchInfo)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(index, RanchInfo::index)
_CLASSREGISTER_AddVar(level, RanchInfo::level)
_CLASSREGISTER_AddVar(exp, RanchInfo::exp)
_CLASSREGISTER_AddVar(giftNum, RanchInfo::giftNum)
_CLASSREGISTER_AddVar(sendGiftCount, RanchInfo::sendGiftCount)
_CLASSREGISTER_AddVar(achievementPoint, RanchInfo::achievementPoint)
_CLASSREGISTER_AddVar(nextExp, RanchInfo::nextExp)
_CLASSREGISTER_AddVar(prosperity, RanchInfo::prosperity)
_CLASSREGISTER_AddVar(taskStartLevel, RanchInfo::taskStartLevel)
_CLASSREGISTER_AddVar(exploreStartLevel, RanchInfo::exploreStartLevel)
_CLASSREGISTER_AddVar(prosperityRank, RanchInfo::prosperityRank)
_CLASSREGISTER_AddVar(achievementRank, RanchInfo::achievementRank)
_CLASSREGISTER_AddVar(clanRank, RanchInfo::clanRank)
_CLASSREGISTER_AddVar(isCanFlying, RanchInfo::isCanFlying)
_CLASSREGISTER_AddVar(isDestroyHouse, RanchInfo::isDestroyHouse)
_CLASSREGISTER_AddVar(isDestroyWarehouse, RanchInfo::isDestroyWarehouse)
_CLASSREGISTER_AddVar(startPos, RanchInfo::startPos)
_CLASSREGISTER_AddVar(endPos, RanchInfo::endPos)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(RanchStorage)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(level, RanchStorage::level)
_CLASSREGISTER_AddVar(maxLevel, RanchStorage::maxLevel)
_CLASSREGISTER_AddVar(capacity, RanchStorage::capacity)
_CLASSREGISTER_AddVar(nextCapacity, RanchStorage::nextCapacity)
_CLASSREGISTER_AddVar(upgradePrice, RanchStorage::upgradePrice)
_CLASSREGISTER_AddVar(needPlayerLevel, RanchStorage::needPlayerLevel)
_CLASSREGISTER_AddVar(items, RanchStorage::items)
_CLASSREGISTER_AddVar(upgradeRecipe, RanchStorage::upgradeRecipe)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(RanchHouse)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(id, RanchHouse::id)
_CLASSREGISTER_AddVar(level, RanchHouse::level)
_CLASSREGISTER_AddVar(maxLevel, RanchHouse::maxLevel)
_CLASSREGISTER_AddVar(nextLevel, RanchHouse::nextLevel)
_CLASSREGISTER_AddVar(upgradePrice, RanchHouse::upgradePrice)
_CLASSREGISTER_AddVar(needPlayerLevel, RanchHouse::needPlayerLevel)
_CLASSREGISTER_AddVar(icon, RanchHouse::icon)
_CLASSREGISTER_AddVar(name, RanchHouse::name)
_CLASSREGISTER_AddVar(nextIcon, RanchHouse::nextIcon)
_CLASSREGISTER_AddVar(nextName, RanchHouse::nextName)
_CLASSREGISTER_AddVar(upgradeRecipe, RanchHouse::upgradeRecipe)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(RanchRank)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(id, RanchRank::id)
_CLASSREGISTER_AddVar(level, RanchRank::level)
_CLASSREGISTER_AddVar(rank, RanchRank::rank)
_CLASSREGISTER_AddVar(value, RanchRank::value)
_CLASSREGISTER_AddVar(name, RanchRank::name)
_CLASSREGISTER_AddVar(userNum, RanchRank::userNum)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(RanchBuild)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(id, RanchBuild::id)
_CLASSREGISTER_AddVar(price, RanchBuild::price)
_CLASSREGISTER_AddVar(num, RanchBuild::num)
_CLASSREGISTER_AddVar(maxNum, RanchBuild::maxNum)
_CLASSREGISTER_AddVar(needLevel, RanchBuild::needLevel)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(ProductQueue)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(queueId, ProductQueue::queueId)
_CLASSREGISTER_AddVar(productId, ProductQueue::productId)
_CLASSREGISTER_AddVar(outputNum, ProductQueue::outputNum)
_CLASSREGISTER_AddVar(timeLeft, ProductQueue::timeLeft)
_CLASSREGISTER_AddVar(needTime, ProductQueue::needTime)
_CLASSREGISTER_AddVar(unlockPrice, ProductQueue::unlockPrice)
_CLASSREGISTER_AddVar(currencyType, ProductQueue::currencyType)
_CLASSREGISTER_AddVar(state, ProductQueue::state)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(ProductRecipe)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(productId, ProductRecipe::productId)
_CLASSREGISTER_AddVar(needLevel, ProductRecipe::needLevel)
_CLASSREGISTER_AddVar(needTime, ProductRecipe::needTime)
_CLASSREGISTER_AddVar(items, ProductRecipe::items)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(RanchOrderInfo)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(index, RanchOrderInfo::index)
_CLASSREGISTER_AddVar(itemId, RanchOrderInfo::itemId)
_CLASSREGISTER_AddVar(needNum, RanchOrderInfo::needNum)
_CLASSREGISTER_AddVar(helperId, RanchOrderInfo::helperId)
_CLASSREGISTER_AddVar(isDone, RanchOrderInfo::isDone)
_CLASSREGISTER_AddVar(isHelp, RanchOrderInfo::isHelp)
_CLASSREGISTER_AddVar(isHot, RanchOrderInfo::isHot)
_CLASSREGISTER_AddVar(helperSex, RanchOrderInfo::helperSex)
_CLASSREGISTER_AddVar(fullBoxNum, RanchOrderInfo::fullBoxNum)
_CLASSREGISTER_AddVar(boxAmount, RanchOrderInfo::boxAmount)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(RanchOrder)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(id, RanchOrder::id)
_CLASSREGISTER_AddVar(price, RanchOrder::price)
_CLASSREGISTER_AddVar(status, RanchOrder::status)
_CLASSREGISTER_AddVar(timeLeft, RanchOrder::timeLeft)
_CLASSREGISTER_AddVar(refreshTimeLeft, RanchOrder::refreshTimeLeft)
_CLASSREGISTER_AddVar(msg, RanchOrder::msg)
_CLASSREGISTER_AddVar(guestIcon, RanchOrder::guestIcon)
_CLASSREGISTER_AddVar(isHot, RanchOrder::isHot)
_CLASSREGISTER_AddVar(infos, RanchOrder::infos)
_CLASSREGISTER_AddVar(rewards, RanchOrder::rewards)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(RanchAchievement)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(id, RanchAchievement::id)
_CLASSREGISTER_AddVar(exp, RanchAchievement::exp)
_CLASSREGISTER_AddVar(level, RanchAchievement::level)
_CLASSREGISTER_AddVar(nextExp, RanchAchievement::nextExp)
_CLASSREGISTER_AddVar(maxLevel, RanchAchievement::maxLevel)
_CLASSREGISTER_AddVar(playerExp, RanchAchievement::playerExp)
_CLASSREGISTER_AddVar(achievement, RanchAchievement::achievement)
_CLASSREGISTER_AddVar(icon, RanchAchievement::icon)
_CLASSREGISTER_AddVar(desc, RanchAchievement::desc)
_CLASSREGISTER_AddVar(name, RanchAchievement::name)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(RanchTimePrice)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(id, RanchTimePrice::id)
_CLASSREGISTER_AddVar(price, RanchTimePrice::price)
_CLASSREGISTER_AddVar(timeLeft, RanchTimePrice::timeLeft)
_END_REGISTER_CLASS()


// Register Class BirdSimulator
_BEGIN_REGISTER_CLASS(BirdSimulator)
_CLASSREGISTER_AddBaseClass(ObjectAlloc)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddMember(setBag, BirdSimulator::setBag)
_CLASSREGISTER_AddMember(setActivity, BirdSimulator::setActivity)
_CLASSREGISTER_AddMember(setPlayerInfo, BirdSimulator::setPlayerInfo)
_CLASSREGISTER_AddMember(setAtlas, BirdSimulator::setAtlasFromLua)
_CLASSREGISTER_AddMember(setTasks, BirdSimulator::setTasksFromLua)
_CLASSREGISTER_AddMember(setDress, BirdSimulator::setDressFromLua)
_CLASSREGISTER_AddMember(setFoods, BirdSimulator::setFoodsFromLua)
_CLASSREGISTER_AddMember(setStores, BirdSimulator::setStoresFromLua)
_CLASSREGISTER_AddMember(setPersonalStore, BirdSimulator::setPersonalStoreFromLua)
_CLASSREGISTER_AddMember(setScopes, BirdSimulator::setScopesFromLua)
_CLASSREGISTER_AddMember(setTimePrices, BirdSimulator::setTimePricesFromLua)
_CLASSREGISTER_AddMember(setBuffs, BirdSimulator::setBuffsFromLua)
_END_REGISTER_CLASS()


_BEGIN_REGISTER_CLASS(BirdStore)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(id, BirdStore::id)
_CLASSREGISTER_AddVar(startPos, BirdStore::startPos)
_CLASSREGISTER_AddVar(endPos, BirdStore::endPos)
_CLASSREGISTER_AddVar(items, BirdStore::items)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(BirdStoreItem)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(id, BirdStoreItem::id)
_CLASSREGISTER_AddVar(storeId, BirdStoreItem::storeId)
_CLASSREGISTER_AddVar(price, BirdStoreItem::price)
_CLASSREGISTER_AddVar(currencyType, BirdStoreItem::currencyType)
_CLASSREGISTER_AddVar(status, BirdStoreItem::status)
_CLASSREGISTER_AddVar(type, BirdStoreItem::type)
_CLASSREGISTER_AddVar(name, BirdStoreItem::name)
_CLASSREGISTER_AddVar(desc, BirdStoreItem::desc)
_CLASSREGISTER_AddVar(icon, BirdStoreItem::icon)
_CLASSREGISTER_AddVar(iconNew, BirdStoreItem::iconNew)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(BirdGiftBagItem)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(id, BirdGiftBagItem::id)
_CLASSREGISTER_AddVar(num, BirdGiftBagItem::num)
_CLASSREGISTER_AddVar(type, BirdGiftBagItem::type)
_CLASSREGISTER_AddVar(icon, BirdGiftBagItem::icon)
_CLASSREGISTER_AddVar(giftBagId, BirdGiftBagItem::giftBagId)
_CLASSREGISTER_AddVar(isAutoUse, BirdGiftBagItem::isAutoUse)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(BirdGiftBag)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(id, BirdGiftBag::id)
_CLASSREGISTER_AddVar(price, BirdGiftBag::price)
_CLASSREGISTER_AddVar(limit, BirdGiftBag::limit)
_CLASSREGISTER_AddVar(timeLeft, BirdGiftBag::timeLeft)
_CLASSREGISTER_AddVar(discount, BirdGiftBag::discount)
_CLASSREGISTER_AddVar(currencyType, BirdGiftBag::currencyType)
_CLASSREGISTER_AddVar(icon, BirdGiftBag::icon)
_CLASSREGISTER_AddVar(desc, BirdGiftBag::desc)
_CLASSREGISTER_AddVar(name, BirdGiftBag::name)
_CLASSREGISTER_AddVar(topLeftIcon, BirdGiftBag::topLeftIcon)
_CLASSREGISTER_AddVar(topLeftName, BirdGiftBag::topLeftName)
_CLASSREGISTER_AddVar(topRightIcon, BirdGiftBag::topRightIcon)
_CLASSREGISTER_AddVar(topRightName, BirdGiftBag::topRightName)
_CLASSREGISTER_AddVar(items, BirdGiftBag::items)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(BirdPersonalStoreTab)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(tabId, BirdPersonalStoreTab::tabId)
_CLASSREGISTER_AddVar(tabName, BirdPersonalStoreTab::tabName)
_CLASSREGISTER_AddVar(tabIcon, BirdPersonalStoreTab::tabIcon)
_CLASSREGISTER_AddVar(items, BirdPersonalStoreTab::items)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(BirdDress)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(id, BirdDress::id)
_CLASSREGISTER_AddVar(num, BirdDress::num)
_CLASSREGISTER_AddVar(type, BirdDress::type)
_CLASSREGISTER_AddVar(isUse, BirdDress::isUse)
_CLASSREGISTER_AddVar(bodyId, BirdDress::bodyId)
_CLASSREGISTER_AddVar(bodyName, BirdDress::bodyName)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(BirdInfo)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(id, BirdInfo::id)
_CLASSREGISTER_AddVar(level, BirdInfo::level)
_CLASSREGISTER_AddVar(maxLevel, BirdInfo::maxLevel)
_CLASSREGISTER_AddVar(exp, BirdInfo::exp)
_CLASSREGISTER_AddVar(nextExp, BirdInfo::nextExp)
_CLASSREGISTER_AddVar(quality, BirdInfo::quality)
_CLASSREGISTER_AddVar(speed, BirdInfo::speed)
_CLASSREGISTER_AddVar(gather, BirdInfo::gather)
_CLASSREGISTER_AddVar(conver, BirdInfo::conver)
_CLASSREGISTER_AddVar(attack, BirdInfo::attack)
_CLASSREGISTER_AddVar(isCarry, BirdInfo::isCarry)
_CLASSREGISTER_AddVar(name, BirdInfo::name)
_CLASSREGISTER_AddVar(icon, BirdInfo::icon)
_CLASSREGISTER_AddVar(skill, BirdInfo::skill)
_CLASSREGISTER_AddVar(talent, BirdInfo::talent)
_CLASSREGISTER_AddVar(glassesId, BirdInfo::glassesId)
_CLASSREGISTER_AddVar(hatId, BirdInfo::hatId)
_CLASSREGISTER_AddVar(beakId, BirdInfo::beakId)
_CLASSREGISTER_AddVar(wingId, BirdInfo::wingId)
_CLASSREGISTER_AddVar(tailId, BirdInfo::tailId)
_CLASSREGISTER_AddVar(effectId, BirdInfo::effectId)
_CLASSREGISTER_AddVar(bodyId, BirdInfo::bodyId)
_CLASSREGISTER_AddVar(convertTime, BirdInfo::convertTime)
_CLASSREGISTER_AddVar(gatherTime, BirdInfo::gatherTime)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(BirdBag)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(curCarry, BirdBag::curCarry)
_CLASSREGISTER_AddVar(maxCarry, BirdBag::maxCarry)
_CLASSREGISTER_AddVar(curCapacity, BirdBag::curCapacity)
_CLASSREGISTER_AddVar(maxCapacity, BirdBag::maxCapacity)
_CLASSREGISTER_AddVar(maxCarryLevel, BirdBag::maxCarryLevel)
_CLASSREGISTER_AddVar(maxCapacityLevel, BirdBag::maxCapacityLevel)
_CLASSREGISTER_AddVar(expandCarryPrice, BirdBag::expandCarryPrice)
_CLASSREGISTER_AddVar(expandCapacityPrice, BirdBag::expandCapacityPrice)
_CLASSREGISTER_AddVar(expandCurrencyType, BirdBag::expandCurrencyType)
_CLASSREGISTER_AddVar(birds, BirdBag::birds)
_END_REGISTER_CLASS()


_BEGIN_REGISTER_CLASS(BirdPlayerInfo)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(score, BirdPlayerInfo::score)
_CLASSREGISTER_AddVar(eggTicket, BirdPlayerInfo::eggTicket)
_CLASSREGISTER_AddVar(isConvert, BirdPlayerInfo::isConvert)
_END_REGISTER_CLASS()


_BEGIN_REGISTER_CLASS(BirdFood)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(id, BirdFood::id)
_CLASSREGISTER_AddVar(num, BirdFood::num)
_CLASSREGISTER_AddVar(name, BirdFood::name)
_CLASSREGISTER_AddVar(icon, BirdFood::icon)
_CLASSREGISTER_AddVar(desc, BirdFood::desc)
_END_REGISTER_CLASS()


_BEGIN_REGISTER_CLASS(BirdTaskItem)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(id, BirdTaskItem::id)
_CLASSREGISTER_AddVar(curValue, BirdTaskItem::curValue)
_CLASSREGISTER_AddVar(needValue, BirdTaskItem::needValue)
_CLASSREGISTER_AddVar(desc, BirdTaskItem::desc)
_CLASSREGISTER_AddVar(name, BirdTaskItem::name)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(BirdTask)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(taskId, BirdTask::taskId)
_CLASSREGISTER_AddVar(curValue, BirdTask::entityId)
_CLASSREGISTER_AddVar(taskName, BirdTask::taskName)
_CLASSREGISTER_AddVar(contents, BirdTask::contents)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(BirdEgg)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(id, BirdEgg::id)
_CLASSREGISTER_AddVar(quality, BirdEgg::quality)
_CLASSREGISTER_AddVar(icon, BirdEgg::icon)
_CLASSREGISTER_AddVar(isHave, BirdEgg::isHave)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(BirdAtlas)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(id, BirdAtlas::id)
_CLASSREGISTER_AddVar(eggIcon, BirdAtlas::eggIcon)
_CLASSREGISTER_AddVar(items, BirdAtlas::items)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(BirdGain)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(itemId, BirdGain::itemId)
_CLASSREGISTER_AddVar(icon, BirdGain::icon)
_CLASSREGISTER_AddVar(num, BirdGain::num)
_CLASSREGISTER_AddVar(name, BirdGain::name)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(BirdScope)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(id, BirdScope::id)
_CLASSREGISTER_AddVar(type, BirdScope::type)
_CLASSREGISTER_AddVar(startPos, BirdScope::startPos)
_CLASSREGISTER_AddVar(endPos, BirdScope::endPos)
_END_REGISTER_CLASS()


_BEGIN_REGISTER_CLASS(BirdTimePrice)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(id, BirdTimePrice::id)
_CLASSREGISTER_AddVar(price, BirdTimePrice::price)
_CLASSREGISTER_AddVar(timeLeft, BirdTimePrice::timeLeft)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(BirdBuff)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(id, BirdBuff::id)
_CLASSREGISTER_AddVar(level, BirdBuff::level)
_CLASSREGISTER_AddVar(icon, BirdBuff::icon)
_CLASSREGISTER_AddVar(timeLeft, BirdBuff::timeLeft)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(BulletinRank)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(rank, BulletinRank::rank)
_CLASSREGISTER_AddVar(userId, BulletinRank::userId)
_CLASSREGISTER_AddVar(score, BulletinRank::score)
_CLASSREGISTER_AddVar(name, BulletinRank::name)
_END_REGISTER_CLASS()



// Register Class BlockCity
_BEGIN_REGISTER_CLASS(BlockCity)
_CLASSREGISTER_AddBaseClass(ObjectAlloc)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddMember(setManorManager, BlockCity::setManorManager)
_CLASSREGISTER_AddMember(setPlayerInfo, BlockCity::setPlayerInfo)
_CLASSREGISTER_AddMember(setStores, BlockCity::setStoresFromLua)
_CLASSREGISTER_AddMember(setManorInfo, BlockCity::setManorInfo)
_CLASSREGISTER_AddMember(setBuyLackItems, BlockCity::setBuyLackItems)
_CLASSREGISTER_AddMember(setHouseShop, BlockCity::setHouseShopFromLua)
_CLASSREGISTER_AddMember(setManorArea, BlockCity::setManorAreaFromLua)
_CLASSREGISTER_AddMember(setElevatorArea, BlockCity::setElevatorAreaFromLua)
_CLASSREGISTER_AddMember(setWeekReward, BlockCity::setWeekRewardFromLua)
_CLASSREGISTER_AddMember(setArchive, BlockCity::setArchive)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(BlockCityManor)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(level, BlockCityManor::level)
_CLASSREGISTER_AddVar(area, BlockCityManor::area)
_CLASSREGISTER_AddVar(score, BlockCityManor::score)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(BlockCityManorManager)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(blockScore, BlockCityManorManager::blockScore)
_CLASSREGISTER_AddVar(decorateScore, BlockCityManorManager::decorateScore)
_CLASSREGISTER_AddVar(allScore, BlockCityManorManager::allScore)
_CLASSREGISTER_AddVar(openStatus, BlockCityManorManager::openStatus)
_CLASSREGISTER_AddVar(upgradeMoney, BlockCityManorManager::upgradeMoney)
_CLASSREGISTER_AddVar(upgradeMoneyType, BlockCityManorManager::upgradeMoneyType)
_CLASSREGISTER_AddVar(deleteMoney, BlockCityManorManager::deleteMoney)
_CLASSREGISTER_AddVar(deleteMoneyType, BlockCityManorManager::deleteMoneyType)
_CLASSREGISTER_AddVar(curManor, BlockCityManorManager::curManor)
_CLASSREGISTER_AddVar(nextManor, BlockCityManorManager::nextManor)
_CLASSREGISTER_AddVar(maxLevel, BlockCityManorManager::maxLevel)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(BlockCityPlayerInfo)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(score, BlockCityPlayerInfo::score)
_CLASSREGISTER_AddVar(isEditMode, BlockCityPlayerInfo::isEditMode)
_CLASSREGISTER_AddVar(isCanFlying, BlockCityPlayerInfo::isCanFlying)
_CLASSREGISTER_AddVar(flyingRemainTime, BlockCityPlayerInfo::flyingRemainTime)
_CLASSREGISTER_AddVar(isGotFreeFly, BlockCityPlayerInfo::isGotFreeFly)
_CLASSREGISTER_AddVar(lastWeekRank, BlockCityPlayerInfo::lastWeekRank)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(BlockCityFlyingInfo)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(id, BlockCityFlyingInfo::id)
_CLASSREGISTER_AddVar(day, BlockCityFlyingInfo::day)
_CLASSREGISTER_AddVar(moneyType, BlockCityFlyingInfo::moneyType)
_CLASSREGISTER_AddVar(price, BlockCityFlyingInfo::price)
_CLASSREGISTER_AddVar(flyMsg, BlockCityFlyingInfo::flyMsg)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(BlockCityManorInfo)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(startPos, BlockCityManorInfo::startPos)
_CLASSREGISTER_AddVar(endPos, BlockCityManorInfo::endPos)
_CLASSREGISTER_AddVar(canPlaceStartPos, BlockCityManorInfo::canPlaceStartPos)
_CLASSREGISTER_AddVar(canPlaceEndPos, BlockCityManorInfo::canPlaceEndPos)
_CLASSREGISTER_AddVar(flyingInfo, BlockCityManorInfo::flyingInfo)
//_CLASSREGISTER_AddVar(flyMoneyType, BlockCityManorInfo::flyMoneyType)
//_CLASSREGISTER_AddVar(flyPrice, BlockCityManorInfo::flyPrice)
//_CLASSREGISTER_AddVar(flyMsg, BlockCityManorInfo::flyMsg)
_END_REGISTER_CLASS()


_BEGIN_REGISTER_CLASS(BlockCityPayment)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(num, BlockCityPayment::num)
_CLASSREGISTER_AddVar(moneyType, BlockCityPayment::moneyType)
_CLASSREGISTER_AddVar(price, BlockCityPayment::price)
_CLASSREGISTER_AddVar(tabId, BlockCityPayment::tabId)
_CLASSREGISTER_AddVar(itemId, BlockCityPayment::itemId)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(BlockCityMaterial)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(id, BlockCityMaterial::id)
_CLASSREGISTER_AddVar(itemId, BlockCityMaterial::itemId)
_CLASSREGISTER_AddVar(itemMate, BlockCityMaterial::itemMate)
_CLASSREGISTER_AddVar(needNum, BlockCityMaterial::needNum)
_CLASSREGISTER_AddVar(haveNum, BlockCityMaterial::haveNum)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(BlockCityStoreItem)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(id, BlockCityStoreItem::id)
_CLASSREGISTER_AddVar(groupId, BlockCityStoreItem::groupId)
_CLASSREGISTER_AddVar(itemId, BlockCityStoreItem::itemId)
_CLASSREGISTER_AddVar(itemMate, BlockCityStoreItem::itemMate)
_CLASSREGISTER_AddVar(num, BlockCityStoreItem::num)
_CLASSREGISTER_AddVar(limit, BlockCityStoreItem::limit)
_CLASSREGISTER_AddVar(volume, BlockCityStoreItem::volume)
_CLASSREGISTER_AddVar(score, BlockCityStoreItem::score)
_CLASSREGISTER_AddVar(onePriceCube, BlockCityStoreItem::onePriceCube)
_CLASSREGISTER_AddVar(onePrice, BlockCityStoreItem::onePrice)
_CLASSREGISTER_AddVar(groupPriceCube, BlockCityStoreItem::groupPriceCube)
_CLASSREGISTER_AddVar(groupPrice, BlockCityStoreItem::groupPrice)
_CLASSREGISTER_AddVar(materials, BlockCityStoreItem::materials)
_CLASSREGISTER_AddVar(weight, BlockCityStoreItem::weight)
_CLASSREGISTER_AddVar(isNew, BlockCityStoreItem::isNew)
_CLASSREGISTER_AddVar(isHot, BlockCityStoreItem::isHot)
_CLASSREGISTER_AddVar(moneyType, BlockCityStoreItem::moneyType)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(BlockCityStoreGroup)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(groupId, BlockCityStoreGroup::groupId)
_CLASSREGISTER_AddVar(groupName, BlockCityStoreGroup::groupName)
_CLASSREGISTER_AddVar(groupIcon, BlockCityStoreGroup::groupIcon)
_CLASSREGISTER_AddVar(isNew, BlockCityStoreGroup::isNew)

_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(BlockCityStoreTab)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(tabId, BlockCityStoreTab::tabId)
_CLASSREGISTER_AddVar(items, BlockCityStoreTab::items)
_CLASSREGISTER_AddVar(groups, BlockCityStoreTab::groups)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(BlockCityLackItem)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(id, BlockCityLackItem::id)
_CLASSREGISTER_AddVar(itemId, BlockCityLackItem::itemId)
_CLASSREGISTER_AddVar(itemMeta, BlockCityLackItem::itemMeta)
_CLASSREGISTER_AddVar(haveNum, BlockCityLackItem::haveNum)
_CLASSREGISTER_AddVar(needNum, BlockCityLackItem::needNum)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(BlockCityBuyLackItems)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(items, BlockCityBuyLackItems::items)
_CLASSREGISTER_AddVar(price, BlockCityBuyLackItems::price)
_CLASSREGISTER_AddVar(priceCube, BlockCityBuyLackItems::priceCube)
_CLASSREGISTER_AddVar(type, BlockCityBuyLackItems::type)
_END_REGISTER_CLASS()

// Register Class BlockFort
_BEGIN_REGISTER_CLASS(BlockFort)
_CLASSREGISTER_AddBaseClass(ObjectAlloc)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddMember(setManorInfo, BlockFort::setManorInfo)
_CLASSREGISTER_AddMember(setManorManager, BlockFort::setManorManager)
_CLASSREGISTER_AddMember(setPlayerInfo, BlockFort::setPlayerInfo)
_CLASSREGISTER_AddMember(setStores, BlockFort::setStoresFromLua)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(BlockFortManorInfo)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(startPos, BlockFortManorInfo::startPos)
_CLASSREGISTER_AddVar(endPos, BlockFortManorInfo::endPos)
_CLASSREGISTER_AddVar(canPlaceStartPos, BlockFortManorInfo::canPlaceStartPos)
_CLASSREGISTER_AddVar(canPlaceEndPos, BlockFortManorInfo::canPlaceEndPos)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(BlockFortManor)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(level, BlockFortManor::level)
_CLASSREGISTER_AddVar(area, BlockFortManor::area)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(BlockFortManorManager)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(curManor, BlockFortManorManager::curManor)
_CLASSREGISTER_AddVar(nextManor, BlockFortManorManager::nextManor)
_CLASSREGISTER_AddVar(maxLevel, BlockFortManorManager::maxLevel)
_CLASSREGISTER_AddVar(upgradeMoney, BlockFortManorManager::upgradeMoney)
_CLASSREGISTER_AddVar(upgradeMoneyType, BlockFortManorManager::upgradeMoneyType)
_CLASSREGISTER_AddVar(unlockIds, BlockFortManorManager::unlockIds)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(BlockFortPlayerInfo)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(exp, BlockFortPlayerInfo::exp)
_CLASSREGISTER_AddVar(level, BlockFortPlayerInfo::level)
_CLASSREGISTER_AddVar(totalExp, BlockFortPlayerInfo::totalExp)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(BlockFortStoreItem)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(id, BlockFortStoreItem::id)
_CLASSREGISTER_AddVar(groupId, BlockFortStoreItem::groupId)
_CLASSREGISTER_AddVar(itemId, BlockFortStoreItem::itemId)
_CLASSREGISTER_AddVar(itemMate, BlockFortStoreItem::itemMate)
_CLASSREGISTER_AddVar(itemNum, BlockFortStoreItem::itemNum)
_CLASSREGISTER_AddVar(limit, BlockFortStoreItem::limit)
_CLASSREGISTER_AddVar(weight, BlockFortStoreItem::weight)
_CLASSREGISTER_AddVar(moneyType, BlockFortStoreItem::moneyType)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(BlockFortStoreGroup)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(groupId, BlockFortStoreGroup::groupId)
_CLASSREGISTER_AddVar(groupName, BlockFortStoreGroup::groupName)
_CLASSREGISTER_AddVar(groupIcon, BlockFortStoreGroup::groupIcon)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(BlockFortStoreTab)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(tabId, BlockFortStoreTab::tabId)
_CLASSREGISTER_AddVar(items, BlockFortStoreTab::items)
_CLASSREGISTER_AddVar(groups, BlockFortStoreTab::groups)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(BlockCityHouseShopClassify)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(shopClassifyId, BlockCityHouseShopClassify::shopClassifyId)
_CLASSREGISTER_AddVar(shopClassifyName, BlockCityHouseShopClassify::shopClassifyName)
_CLASSREGISTER_AddVar(shopClassifyImage, BlockCityHouseShopClassify::shopClassifyImage)
_CLASSREGISTER_AddVar(shops, BlockCityHouseShopClassify::shops)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(BlockCityHouseShop)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(items, BlockCityHouseShop::items)
_CLASSREGISTER_AddVar(areaIds, BlockCityHouseShop::areaIds)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(BlockCityHouseShopItem)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(itemId, BlockCityHouseShopItem::itemId)
_CLASSREGISTER_AddVar(itemStatus, BlockCityHouseShopItem::itemStatus)
_CLASSREGISTER_AddVar(itemActorName, BlockCityHouseShopItem::itemActorName)
_CLASSREGISTER_AddVar(itemScale, BlockCityHouseShopItem::itemScale)
_CLASSREGISTER_AddVar(isCanBuy, BlockCityHouseShopItem::isCanBuy)
_CLASSREGISTER_AddVar(moneyType, BlockCityHouseShopItem::moneyType)
_CLASSREGISTER_AddVar(limit, BlockCityHouseShopItem::limit)
_CLASSREGISTER_AddVar(haveNum, BlockCityHouseShopItem::haveNum)
_CLASSREGISTER_AddVar(limitTime, BlockCityHouseShopItem::limitTime)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(BlockCityManorArea)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(userId, BlockCityManorArea::userId)
_CLASSREGISTER_AddVar(startPos, BlockCityManorArea::startPos)
_CLASSREGISTER_AddVar(endPos, BlockCityManorArea::endPos)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(BlockCityElevatorArea)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(id, BlockCityElevatorArea::id)
_CLASSREGISTER_AddVar(floor, BlockCityElevatorArea::floor)
_CLASSREGISTER_AddVar(startPos, BlockCityElevatorArea::startPos)
_CLASSREGISTER_AddVar(endPos, BlockCityElevatorArea::endPos)
_CLASSREGISTER_AddVar(floorIcon, BlockCityElevatorArea::floorIcon)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(BlockCityWeekRewardItem)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(id, BlockCityWeekRewardItem::id)
_CLASSREGISTER_AddVar(meta, BlockCityWeekRewardItem::meta)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(BlockCityWeekReward)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(rank, BlockCityWeekReward::rank)
_CLASSREGISTER_AddVar(items, BlockCityWeekReward::items)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(BlockCityArchiveItem)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(name, BlockCityArchiveItem::name)
_CLASSREGISTER_AddVar(updateAt, BlockCityArchiveItem::updateAt)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(BlockCityArchive)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(items, BlockCityArchive::items)
_CLASSREGISTER_AddVar(nextPrice, BlockCityArchive::nextPrice)
_CLASSREGISTER_AddVar(maxNum, BlockCityArchive::maxNum)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(SkyInfo)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(skyboxId, SkyInfo::skyboxId)
_CLASSREGISTER_AddVar(skyboxName, SkyInfo::skyboxName)
_CLASSREGISTER_AddVar(startFadeIn, SkyInfo::startFadeIn)
_CLASSREGISTER_AddVar(endFadeIn, SkyInfo::endFadeIn)
_CLASSREGISTER_AddVar(startFadeOut, SkyInfo::startFadeOut)
_CLASSREGISTER_AddVar(endFadeOut, SkyInfo::endFadeOut)
_CLASSREGISTER_AddVar(blendMode, SkyInfo::blendMode)
_CLASSREGISTER_AddVar(rotateAngle, SkyInfo::rotateAngle)
_CLASSREGISTER_AddVar(rotateAxisX, SkyInfo::rotateAxisX)
_CLASSREGISTER_AddVar(rotateAxisY, SkyInfo::rotateAxisY)
_CLASSREGISTER_AddVar(rotateAxisZ, SkyInfo::rotateAxisZ)
_CLASSREGISTER_AddVar(isTwinkle, SkyInfo::isTwinkle)
_CLASSREGISTER_AddVar(twinkleBrightMax, SkyInfo::twinkleBrightMax)
_CLASSREGISTER_AddVar(twinkleDarkMax, SkyInfo::twinkleDarkMax)
_CLASSREGISTER_AddVar(twinkleAlphaMin, SkyInfo::twinkleAlphaMin)
_END_REGISTER_CLASS()
