#include "Network/ClientPeer.h"
#include "Network/HttpRequest.h"
#include "Network/ServerPacketSender.h"
#include "Network/ServerCommonDataSender.h"
#include "Network/ServerNetwork.h"
#include "LuaRegister/Template/LuaRegister.h"
#include "GameAnalytics/GameAnalyticsRequest.h"
#include "Object/Singleton.h"

_BEGIN_REGISTER_CLASS(ClientPeer)
_CLASSREGISTER_AddMember(getEntityRuntimeID, ClientPeer::getEntityRuntimeID)
_CLASSREGISTER_AddMember(getRakssid, ClientPeer::getRakssid)
_CLASSREGISTER_AddMember(setModuleBlockData, ClientPeer::setModuleBlockData)
_CLASSREGISTER_AddMember(getPlatformUserId, ClientPeer::getPlatformUserId)
_CLASSREGISTER_AddMember(getEntityPlayer, ClientPeer::getEntityPlayer)
_CLASSREGISTER_AddMember(getName, ClientPeer::getName)
_CLASSREGISTER_AddMember(sendLoginResult, ClientPeer::sendLoginResult)
_CLASSREGISTER_AddMember(setShowName, ClientPeer::setShowName)
_CLASSREGISTER_AddMember(buyChangeActor, ClientPeer::buyChangeActor)
_CLASSREGISTER_AddMember(pickupItemPay, ClientPeer::pickupItemPay)
_CLASSREGISTER_AddMember(consumeDiamonds, ClientPeer::consumeDiamonds)
_CLASSREGISTER_AddMember(consumeGolds, ClientPeer::consumeGolds)
_CLASSREGISTER_AddMember(isVisitor, ClientPeer::isVisitor)
_CLASSREGISTER_AddMember(setRespawnPos, ClientPeer::setRespawnPos)
_CLASSREGISTER_AddMember(getLanguage, ClientPeer::getLanguage)
_CLASSREGISTER_AddMember(tryAskVehicle, ClientPeer::tryAskVehicle)
_CLASSREGISTER_AddMember(checkDiamondBlues, ClientPeer::checkDiamondBlues)
_CLASSREGISTER_AddMember(rebirth, ClientPeer::rebirth)
_CLASSREGISTER_AddMember(login, ClientPeer::login)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(HttpRequest)
_CLASSREGISTER_AddStaticMember(asyncGet, HttpRequest::asyncLuaGet)
_CLASSREGISTER_AddStaticMember(asyncPost, HttpRequest::asyncLuaPost)
_CLASSREGISTER_AddStaticMember(asyncPut, HttpRequest::asyncLuaPut)
_CLASSREGISTER_AddStaticMember(asyncDelete, HttpRequest::asyncLuaDelete)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(RoomGameConfig)
_CLASSREGISTER_AddVar(gameId, RoomGameConfig::gameId)
_CLASSREGISTER_AddVar(gameName, RoomGameConfig::gameName)
_CLASSREGISTER_AddVar(gameIp, RoomGameConfig::gameIp)
_CLASSREGISTER_AddVar(serverPort, RoomGameConfig::serverPort)
_CLASSREGISTER_AddVar(monitorAddr, RoomGameConfig::monitorAddr)
_CLASSREGISTER_AddVar(gameType, RoomGameConfig::gameType)
_CLASSREGISTER_AddVar(maxPlayers, RoomGameConfig::maxPlayers)
_CLASSREGISTER_AddVar(userConfig, RoomGameConfig::userConfig)
_CLASSREGISTER_AddVar(propAddr, RoomGameConfig::propAddr)
_CLASSREGISTER_AddVar(rankAddr, RoomGameConfig::rankAddr)
_CLASSREGISTER_AddVar(rewardAddr, RoomGameConfig::rewardAddr)
_CLASSREGISTER_AddVar(isChina, RoomGameConfig::isChina)
_CLASSREGISTER_AddVar(blockymodsRewardAddr, RoomGameConfig::blockymodsRewardAddr)
_CLASSREGISTER_AddVar(dbHttpServiceUrl, RoomGameConfig::dbHttpServiceUrl)
_CLASSREGISTER_AddVar(isGameParty, RoomGameConfig::isGameParty)
_CLASSREGISTER_AddVar(dbHttpServiceRetryUrl, RoomGameConfig::dbHttpServiceRetryUrl)
_CLASSREGISTER_AddVar(scriptDir, RoomGameConfig::scriptDir)
_CLASSREGISTER_AddVar(isPrivateParty, RoomGameConfig::isPrivateParty)
_CLASSREGISTER_AddVar(maxWatch, RoomGameConfig::maxWatch)
_CLASSREGISTER_AddVar(watchMode, RoomGameConfig::watchMode)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(GameAnalyticsRequest)
_CLASSREGISTER_AddStaticMember(asyncInit, GameAnalyticsRequest::asyncInit)
_CLASSREGISTER_AddStaticMember(asyncEvents, GameAnalyticsRequest::asyncEvents)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(ServerNetwork)
_CLASSREGISTER_AddStaticMember(Instance, ServerNetwork::Instance)
_CLASSREGISTER_AddMember(getLuaSender, ServerNetwork::getLuaSender)
_CLASSREGISTER_AddMember(getLuaCommonSender, ServerNetwork::getLuaCommonSender)
_CLASSREGISTER_AddMember(getSendTotalPacketInfo, ServerNetwork::getSendTotalPacketInfo)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(ServerPacketSender)
_CLASSREGISTER_AddMember(sendCommonTip, ServerPacketSender::sendCommonTip)
_CLASSREGISTER_AddMember(updateBlockFortItem, ServerPacketSender::updateBlockFortItem)
_CLASSREGISTER_AddMember(showBlockFortBuildingInfo, ServerPacketSender::showBlockFortBuildingInfo)
_CLASSREGISTER_AddMember(sendPlayerDBDataReady, ServerPacketSender::sendPlayerDBDataReady)
_CLASSREGISTER_AddMember(sendInitMoney, ServerPacketSender::sendInitMoney)
_CLASSREGISTER_AddMember(sendChangeQuicklyBuildBlockStatus, ServerPacketSender::sendChangeQuicklyBuildBlockStatus)
_CLASSREGISTER_AddMember(sendEntityAnimateToTackingPlayers, ServerPacketSender::sendEntityAnimateToTackingPlayers)
_CLASSREGISTER_AddMember(sendPlayerChangeActor, ServerPacketSender::sendPlayerChangeActor)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(ServerCommonDataSender)
_CLASSREGISTER_AddMember(sendServerCommonData, ServerCommonDataSender::sendServerCommonData)
_CLASSREGISTER_AddMember(broadCastServerCommonData, ServerCommonDataSender::broadCastServerCommonData)
_CLASSREGISTER_AddMember(sendServerCommonDataToTrackingPlayers, ServerCommonDataSender::sendServerCommonDataToTrackingPlayers)
_END_REGISTER_CLASS()
