#include "Core.h"
#include "Math/IntMath.h"
#include "LuaRegister/Template/LuaRegister.h"
#include "World/Shop.h"
#include "Item/ItemStack.h"
#include "Util/AboutShopping.h"
#include "Setting/GunSetting.h"
#include "Setting/MonsterSetting.h"
#include "Setting/SkillSetting.h"
#include "Setting/SceneSetting.h"
#include "Setting/ActionAreaManager.h"

using namespace LORD;
using namespace BLOCKMAN;
using namespace LUA_REGISTER;

_BEGIN_REGISTER_CLASS(Goods)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(uniqueId, Goods::uniqueId)
_CLASSREGISTER_AddVar(itemId, Goods::itemId)
_CLASSREGISTER_AddVar(itemMeta, Goods::itemMeta)
_CLASSREGISTER_AddVar(itemNum, Goods::itemNum)
_CLASSREGISTER_AddVar(coinId, Goods::coinId)
_CLASSREGISTER_AddVar(blockymodsPrice, Goods::blockymodsPrice)
_CLASSREGISTER_AddVar(blockmanPrice, Goods::blockmanPrice)
_CLASSREGISTER_AddVar(limit, Goods::limit)
_CLASSREGISTER_AddVar(desc, Goods::desc)
_CLASSREGISTER_AddVar(icon, Goods::icon)
_CLASSREGISTER_AddVar(detail, Goods::detail)
_CLASSREGISTER_AddVar(rewardId, Goods::rewardId)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(RespawnGoods)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(time, RespawnGoods::time)
_CLASSREGISTER_AddVar(coinId, RespawnGoods::coinId)
_CLASSREGISTER_AddVar(blockymodsPrice, RespawnGoods::blockymodsPrice)
_CLASSREGISTER_AddVar(blockmanPrice, RespawnGoods::blockmanPrice)
_CLASSREGISTER_AddVar(times, RespawnGoods::times)
_CLASSREGISTER_AddVar(uniqueId, RespawnGoods::uniqueId)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(Commodity)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(itemId, Commodity::itemId)
_CLASSREGISTER_AddVar(itemMeta, Commodity::itemMeta)
_CLASSREGISTER_AddVar(itemNum, Commodity::itemNum)
_CLASSREGISTER_AddVar(coinId, Commodity::coinId)
_CLASSREGISTER_AddVar(price, Commodity::price)
_CLASSREGISTER_AddVar(desc, Commodity::desc)
_CLASSREGISTER_AddVar(image, Commodity::image)
_CLASSREGISTER_AddVar(notify, Commodity::notify)
_CLASSREGISTER_AddVar(tipDesc, Commodity::tipDesc)
_CLASSREGISTER_AddVar(videoAd, Commodity::videoAd)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(GunPluginSetting)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(gunId, GunPluginSetting::gunId)
_CLASSREGISTER_AddVar(gunType, GunPluginSetting::gunType)
_CLASSREGISTER_AddVar(maxBulletNum, GunPluginSetting::maxBulletNum)
_CLASSREGISTER_AddVar(damage, GunPluginSetting::damage)
_CLASSREGISTER_AddVar(knockback, GunPluginSetting::knockback)
_CLASSREGISTER_AddVar(bulletId, GunPluginSetting::bulletId)
_CLASSREGISTER_AddVar(shootRange, GunPluginSetting::shootRange)
_CLASSREGISTER_AddVar(cdTime, GunPluginSetting::cdTime)
_CLASSREGISTER_AddVar(sniperDistance, GunPluginSetting::sniperDistance)
_CLASSREGISTER_AddVar(mouseSensitivity, GunPluginSetting::mouseSensitivity)
_CLASSREGISTER_AddVar(bulletPerShoot, GunPluginSetting::bulletPerShoot)
_CLASSREGISTER_AddVar(bulletOffset, GunPluginSetting::bulletOffset)
_CLASSREGISTER_AddVar(headshotDamage, GunPluginSetting::headshotDamage)
_CLASSREGISTER_AddVar(recoil, GunPluginSetting::recoil)
_CLASSREGISTER_AddVar(bulletEffect, GunPluginSetting::bulletEffect)
_CLASSREGISTER_AddVar(flameEffect, GunPluginSetting::flameEffect)
_CLASSREGISTER_AddVar(isPiercing, GunPluginSetting::isPiercing)
_CLASSREGISTER_AddVar(explosionRange, GunPluginSetting::explosionRange)
_CLASSREGISTER_AddVar(gravityVelocity, GunPluginSetting::gravityVelocity)
_CLASSREGISTER_AddVar(bounceTimes, GunPluginSetting::bounceTimes)
_CLASSREGISTER_AddVar(isAutoShoot, GunPluginSetting::isAutoShoot)
_CLASSREGISTER_AddVar(bulletSpeed, GunPluginSetting::bulletSpeed)
_CLASSREGISTER_AddVar(isFireworks, GunPluginSetting::isFireworks)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(MonsterSetting)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(monsterId, MonsterSetting::monsterId)
_CLASSREGISTER_AddVar(monsterBtTree, MonsterSetting::monsterBtTree)
_CLASSREGISTER_AddVar(actorName, MonsterSetting::actorName)
_CLASSREGISTER_AddVar(monsterType, MonsterSetting::monsterType)
_CLASSREGISTER_AddVar(isAutoAttack, MonsterSetting::isAutoAttack)
_CLASSREGISTER_AddVar(attackDistance, MonsterSetting::attackDistance)
_CLASSREGISTER_AddVar(attackCd, MonsterSetting::attackCd)
_CLASSREGISTER_AddVar(attackCount, MonsterSetting::attackCount)
_CLASSREGISTER_AddVar(moveSpeed, MonsterSetting::moveSpeed)
_CLASSREGISTER_AddVar(attackType, MonsterSetting::attackType)
_CLASSREGISTER_AddVar(patrolDistance, MonsterSetting::patrolDistance)
_CLASSREGISTER_AddVar(skillId, MonsterSetting::skillId)
_CLASSREGISTER_AddVar(viewRange, MonsterSetting::viewRange)
_CLASSREGISTER_AddVar(viewDegree, MonsterSetting::viewDegree)
_CLASSREGISTER_AddVar(moveSpeedAddition, MonsterSetting::moveSpeedAddition)
_CLASSREGISTER_AddVar(canFly, MonsterSetting::canFly)
_CLASSREGISTER_AddVar(patrolType, MonsterSetting::patrolType)
_CLASSREGISTER_AddVar(canTogether, MonsterSetting::canTogether)
_CLASSREGISTER_AddVar(togetherRange, MonsterSetting::togetherRange)
_CLASSREGISTER_AddVar(patrolDistanceOnce, MonsterSetting::patrolDistanceOnce)
_CLASSREGISTER_AddVar(patrolCD, MonsterSetting::patrolCD)
_CLASSREGISTER_AddVar(alertTime, MonsterSetting::alertTime)
_CLASSREGISTER_AddVar(pursueDistance, MonsterSetting::pursueDistance)
_CLASSREGISTER_AddVar(deathEffectName, MonsterSetting::deathEffectName)
_CLASSREGISTER_AddVar(skillCd, MonsterSetting::skillCd)
_CLASSREGISTER_AddVar(chaseRange, MonsterSetting::chaseRange)
_CLASSREGISTER_AddVar(bombEffect, MonsterSetting::bombEffect)
_CLASSREGISTER_AddVar(remoteSpeedFactor, MonsterSetting::remoteSpeedFactor)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(SkillEffect)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(id, SkillEffect::id)
_CLASSREGISTER_AddVar(name, SkillEffect::name)
_CLASSREGISTER_AddVar(duration, SkillEffect::duration)
_CLASSREGISTER_AddVar(width, SkillEffect::width)
_CLASSREGISTER_AddVar(height, SkillEffect::height)
_CLASSREGISTER_AddVar(density, SkillEffect::density)
_CLASSREGISTER_AddVar(color, SkillEffect::color)
_CLASSREGISTER_AddVar(effectType, SkillEffect::effectType)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(SkillItem)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(SkillId, SkillItem::SkillId)
_CLASSREGISTER_AddVar(Occupation, SkillItem::Occupation)
_CLASSREGISTER_AddVar(ItemId, SkillItem::ItemId)
_CLASSREGISTER_AddVar(ItemSkillCd, SkillItem::ItemSkillCd)
_CLASSREGISTER_AddVar(ItemSkillDistace, SkillItem::ItemSkillDistace)
_CLASSREGISTER_AddVar(MoveSpeed, SkillItem::MoveSpeed)
_CLASSREGISTER_AddVar(DropSpeed, SkillItem::DropSpeed)
_CLASSREGISTER_AddVar(AtlasName, SkillItem::AtlasName)
_CLASSREGISTER_AddVar(ItemIconName, SkillItem::ItemIconName)
_CLASSREGISTER_AddVar(AutoCast, SkillItem::AutoCast)
_CLASSREGISTER_AddVar(IsCrossHair, SkillItem::IsCrossHair)
_CLASSREGISTER_AddVar(Parabola, SkillItem::Parabola)
_CLASSREGISTER_AddVar(EffectName, SkillItem::EffectName)
_CLASSREGISTER_AddVar(CanFallNoUse, SkillItem::CanFallNoUse)
_CLASSREGISTER_AddVar(CanFallNoUseTip, SkillItem::CanFallNoUseTip)
_CLASSREGISTER_AddVar(IsActor, SkillItem::IsActor)
_CLASSREGISTER_AddVar(SkillDuration, SkillItem::SkillDuration)
_CLASSREGISTER_AddVar(IsLongTouch, SkillItem::IsLongTouch)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(ActionArea)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(id, ActionArea::id)
_CLASSREGISTER_AddVar(type, ActionArea::type)
_CLASSREGISTER_AddVar(titleNor, ActionArea::titleNor)
_CLASSREGISTER_AddVar(titlePre, ActionArea::titlePre)
_CLASSREGISTER_AddVar(isVisible, ActionArea::isVisible)
_CLASSREGISTER_AddVar(backNor, ActionArea::backNor)
_CLASSREGISTER_AddVar(backPre, ActionArea::backPre)
_CLASSREGISTER_AddVar(startPos, ActionArea::startPos)
_CLASSREGISTER_AddVar(endPos, ActionArea::endPos)
_END_REGISTER_CLASS()
