---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/5/28 11:48
---

local ActionAdapter = class("ActionAdapter", IDataAdapter)

function ActionAdapter:setItemSize(width, height)
    self.width = width
    self.height = height
end

function ActionAdapter:getWindowClass()
    return GUIActionItem
end

function ActionAdapter:getJsonName()
    return "ActionItem.json"
end

function ActionAdapter:getItemWidth()
    return { 0, self.width }
end

function ActionAdapter:getItemHeight()
    return { 0, self.height }
end

return ActionAdapter