---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/12/12 20:13
---

local UIChristmasTip = class("UIChristmasTip", IGUILayout)

function UIChristmasTip:onLoad()
    print("UIChristmasTip:onLoad()")

    self.title = self:getChildWindow("SkyBlockChristmasReward-Title")
    self.title:SetText(Lang:getString("gui_dialog_tip_title_tip"))
    self.imgBg1 = self:getChildWindow("SkyBlockChristmasReward-Icon1-Bg")
    self.imgBg2 = self:getChildWindow("SkyBlockChristmasReward-Icon2-Bg")
    self.icon1 = self:getChildWindow("SkyBlockChristmasReward-Icon1")
    self.icon2 = self:getChildWindow("SkyBlockChristmasReward-Icon2")

    self.sureBtn = self:getChildWindow("SkyBlockChristmasReward-Sure-Btn", GUIType.Button)
    self.sureBtn:SetText(Lang:getString("gui_dialog_tip_btn_sure"))
    self.sureBtn:registerEvent(GUIEvent.ButtonClick, function()
        self:onClickSure()
    end)

    self.closeBtn = self:getChildWindow("SkyBlockChristmasReward-Close", GUIType.Button)
    self.closeBtn:registerEvent(GUIEvent.ButtonClick, function()
        self:onClickClose()
    end)

    self:registerDataCallBack("ChristmasReward", function(data)
        self:onShowChristmasDialog(data)
    end, JsonBuilderProcessor)

end

function UIChristmasTip:onClickClose()
    self:hide()
end

function UIChristmasTip:onClickSure()
    self:hide()
    local data =
    {
      entityId = self.entityId,
      headInfo = self.headInfo,
    }
    GamePacketSender:sendGetChristmasReward(json.encode(data))
end

function UIChristmasTip:onShowChristmasDialog(data)
    self.entityId = data.entityId
    self.headInfo = data.headInfo
    self:show()
    GuiItemStack.showItemIcon(self.icon1, tonumber(2802), 0, "")
    GuiItemStack.showItemIcon(self.icon2, tonumber(2803), 0, "")
end


GUIChristmasTip = UIChristmasTip.new("SkyBlockChristmasReward.json")
GUIChristmasTip:hide()