---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 10184.
--- DateTime: 2020/6/4 12:26
---
local BlockShopTabs = {}

local BlockShopMaps = {}

local function init()
    local config = FileUtil.getConfigFromCsv("setting/BlockShopTabs.csv")
    for _, item in pairs(config) do
        BlockShopTabs[item.TabId] = {
            TabId = tonumber(item.TabId),
            LeftLang = item.LeftLang,
            RightLang = item.RightLang,
            Image = item.Image,
            GoodsList = {},
            SkinList = {},
            WallList = {},
            Weight = tonumber(item.Weight) or 1,
        }

    end
    config = FileUtil.getConfigFromCsv("setting/BlockShopGoods.csv")
    for _, item in pairs(config) do
        local tab = BlockShopTabs[item.TabId]
        if tab then
            local goods = {
                Id = tonumber(item.Id),
                Type = tonumber(item.Type),
                TabId = tonumber(item.TabId),
                Price = tonumber(item.Price),
                Name = item.Name,
                ActorName = item.ActorName or "",
                ActorScale = tonumber(item.ActorScale or 1),
                ActorPos = StringUtil.split(item.ActorPos or "0,0", ","),
                EffectName = item.EffectName or "",
                EffectScale = tonumber(item.EffectScale or 1),
                EffectPos = StringUtil.split(item.EffectPos or "0,0", ","),
                Image = item.Image,
                Time = tonumber(item.Time) or -1,
                SettingId = item.SettingId,
                Default = item.Default == "1",
                Weight = tonumber(item.Weight) or 1,
                Order = tonumber(item.Order) or 1,
            }
            if isClient then
                goods.Time = 0
            end
            if goods.Type == BlockShopConfig.Type.Skin then
                table.insert(tab.SkinList, goods)
            end
            if goods.Type == BlockShopConfig.Type.Wall then
                table.insert(tab.WallList, goods)
            end
            table.insert(tab.GoodsList, goods)
        end
    end
    for _, tab in pairs(BlockShopTabs) do
        table.sort(tab.GoodsList, function(a, b)
            return a.Weight < b.Weight
        end)
        table.sort(tab.WallList, function(a, b)
            return a.Weight < b.Weight
        end)
    end

    ----
    config = FileUtil.getConfigFromCsv("setting/BlockShopMap.csv")
    for _, item in pairs(config) do
        local map = {
            Id = tonumber(item.Id),
            TabId = tonumber(item.TabId),
            SkinOrder = tonumber(item.SkinOrder),
            WallOrder = tonumber(item.WallOrder),
            BlockId = tonumber(item.BlockId),
            DressBlockId = tonumber(item.DressBlockId),
        }
        local tab = BlockShopTabs[item.TabId]
        if tab then
            tab.oldBlockId = map.BlockId
        end
        table.insert(BlockShopMaps, map)
    end
end

BlockShopConfig = {}
BlockShopConfig.Type = {
    Skin = 1,
    Wall = 2,
}
init()

function BlockShopConfig:getBlockShop()
    local items = {}
    for _, tab in pairs(BlockShopTabs) do
        table.insert(items, tab)
    end
    table.sort(items, function(a, b)
        return a.Weight < b.Weight
    end)
    return items
end

function BlockShopConfig:getGoodsList(tabId, type)
    for _, tab in pairs(BlockShopTabs) do
        if tab.TabId == tabId then
            if type == BlockShopConfig.Type.Skin then
                return tab.SkinList
            end
            if type == BlockShopConfig.Type.Wall then
                return tab.WallList
            end
        end
    end
    return {}
end

function BlockShopConfig:getGoodsConfig(goodsId)
    goodsId = tonumber(goodsId)
    for _, tab in pairs(BlockShopTabs) do
        for _, goods in pairs(tab.GoodsList) do
            if goods.Id == goodsId then
                return goods
            end
        end
    end
end

function BlockShopConfig:getEquipCount(tabId)
    for _, tab in pairs(BlockShopTabs) do
        if tab.TabId == tabId then
            return tab.EquipCount or 1
        end
    end
    return 1
end

function BlockShopConfig:getBlockMap(tabId, skinOrder, wallOrder)
    for _, map in pairs(BlockShopMaps) do
        if map.TabId == tabId and map.SkinOrder == skinOrder and map.WallOrder == wallOrder then
            return map
        end
    end
    local tab = BlockShopTabs[tostring(tabId)]
    if tab then
        return {
            TabId = tabId,
            SkinOrder = 0,
            WallOrder = 0,
            BlockId = tab.oldBlockId,
        }
    end
end