---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 10184.
--- DateTime: 2020/5/28 14:13
---
StoreId = { GoodsStore = 1, UpgradeStore = 2, CubeStore = 3 }

GoodsType = { Item = 0, Armor = 1, Upgrade = 2, Privilege = 3, Key = 4, Horn = 5, Ticket = 6 }

StoreNpcType = { Goods = 1, Upgrade = 2 }

local Stores = {
    [StoreId.GoodsStore] = { CurrencyList = {}, Tabs = {} },
    [StoreId.UpgradeStore] = { CurrencyList = {}, Tabs = {} },
    [StoreId.CubeStore] = { CurrencyList = {}, Tabs = {} }
}

local UpgradeGoodsFlag = {}

local UpgradeGoods = {}

local OtherGoods = {}

StoreConfig = {}

local function init()
    local config = FileUtil.getConfigFromCsv("setting/StoreTabs.csv")
    local tabs = {}
    for _, item in pairs(config) do
        tabs[item.Id] = {
            Id = tonumber(item.Id),
            StoreId = tonumber(item.StoreId),
            Lang = item.Lang,
            Icon = item.Icon,
            GoodsList = {}
        }
    end
    config = FileUtil.getConfigFromCsv("setting/StoreCurrency.csv")
    for _, item in pairs(config) do
        local storeIds = StringUtil.split(item.StoreId, "#")
        for _, storeId in pairs(storeIds) do
            local store = Stores[tonumber(storeId)]
            if store then
                table.insert(store.CurrencyList, {
                    Id = tonumber(item.Id),
                    ItemId = tonumber(item.ItemId),
                    RealId = tonumber(item.RealId)
                })
            end
        end
    end
    --- [ItemId] = TabId
    local blockShopMap = {}
    local blockShopTab = BlockShopConfig:getBlockShop()
    for _, tab in pairs(blockShopTab) do
        blockShopMap[tostring(tab.oldBlockId)] = tab.TabId
    end
    config = FileUtil.getConfigFromCsv("setting/StoreGoods.csv")
    for _, item in pairs(config) do
        local goods = {
            Id = tonumber(item.Id),
            TabId = tonumber(item.TabId),
            Type = tonumber(item.Type),
            ItemId = tonumber(item.ItemId),
            Level = tonumber(item.Level),
            LevelGroup = item.LevelGroup,
            Count = tonumber(item.Count),
            CountText = item.CountText or "#",
            CurrencyId = tonumber(item.CurrencyId),
            Price = tonumber(item.Price),
            SkipLevel = tonumber(item.SkipLevel) == 1,
            LimitCount = tonumber(item.LimitCount),
            LimitMax = tonumber(item.LimitCount),
            Name = item.Name,
            Desc = item.Desc,
            Image = item.Image,
            GetWay = tonumber(item.GetWay),
            EnchantList = {}
        }
        goods.BlockShopTabId = blockShopMap[tostring(goods.ItemId)]
        if item.EnchantIds ~= "#" then
            goods.EnchantList = ItemEnchantment:getEnchantmentList(StringUtil.split(item.EnchantIds, "#"))
        end
        if goods.LevelGroup ~= "#" then
            local group = UpgradeGoods[goods.LevelGroup]
            if group == nil then
                group = {}
            end
            table.insert(group, goods)
            UpgradeGoods[goods.LevelGroup] = group
            if goods.Type == GoodsType.Item or goods.Type == GoodsType.Armor then
                local mappings = ItemMapping:getNewItemIds(goods.ItemId)
                UpgradeGoodsFlag[tostring(goods.ItemId)] = true
                for _, itemId in pairs(mappings) do
                    UpgradeGoodsFlag[tostring(itemId)] = true
                end
            end
        end
        local tab = tabs[item.TabId]
        if tab then
            if goods.Level <= 1 or goods.SkipLevel then
                table.insert(tab.GoodsList, goods)
            else
                table.insert(OtherGoods, goods)
            end
        else
            table.insert(OtherGoods, goods)
        end
    end
    for _, tab in pairs(tabs) do
        local store = Stores[tab.StoreId]
        if store then
            table.insert(store.Tabs, tab)
        end
    end
    for _, store in pairs(Stores) do
        table.sort(store.CurrencyList, function(a, b)
            return a.Id < b.Id
        end)
        table.sort(store.Tabs, function(a, b)
            return a.Id < b.Id
        end)
        for _, tab in pairs(store.Tabs) do
            table.sort(tab.GoodsList, function(a, b)
                return a.Id < b.Id
            end)
        end
    end
    tabs = {}
    if isClient then
        config = FileUtil.getConfigFromCsv("setting/StoreNpc.csv", 2, true)
        for _, item in pairs(config) do
            if tonumber(GameConfig.mapId) == tonumber(item.mapId) then
                local position = VectorUtil.newVector3(item.X, item.Y, item.Z)
                EngineWorld:addActorNpc(position, tonumber(item.Yaw), item.Actor, function(entity)
                    entity:setHeadName(item.Name)
                    entity:setIntProperty("Type", tonumber(item.Type))
                end)
            end
        end
    end
end

init()

function StoreConfig:getStoreConfig(storeId)
    return Stores[tonumber(storeId)]
end

local function getGoodsByKey(key, value)
    for _, goods in pairs(OtherGoods) do
        if goods[key] == value then
            return goods
        end
    end
    for _, group in pairs(UpgradeGoods) do
        for _, goods in pairs(group) do
            if goods[key] == value then
                return goods
            end
        end
    end
    for _, store in pairs(Stores) do
        for _, tab in pairs(store.Tabs) do
            for _, goods in pairs(tab.GoodsList) do
                if goods[key] == value then
                    return goods
                end
            end
        end
    end
    return nil
end

local function getCurrencyByKey(key, value)
    for _, store in pairs(Stores) do
        for _, currency in pairs(store.CurrencyList) do
            if currency[key] == value then
                return currency
            end
        end
    end
    return nil
end

local function getMinUpgradeGoods(LevelGroup)
    local group = UpgradeGoods[LevelGroup]
    local goods
    if group then
        for _, item in pairs(group) do
            if not goods then
                goods = item
            end
            if item.Level < goods.Level then
                goods = item
            end
        end
    end
    return goods
end

---根据itemId查找商品信息
function StoreConfig:getGoodsByItemId(itemId)
    if itemId == 0 then
        return nil
    end
    return getGoodsByKey("ItemId", itemId)
end

---根据goodsId查找商品信息
function StoreConfig:getGoodsById(goodsId)
    return getGoodsByKey("Id", tonumber(goodsId))
end

---获取下一个等级的商品信息
function StoreConfig:getNextUpgradeGoods(itemId)
    local goods = self:getGoodsByItemId(itemId)
    if not goods then
        return
    end
    local group = UpgradeGoods[goods.LevelGroup]
    local upgradeGoods
    if group then
        for _, item in pairs(group) do
            if item.Level == goods.Level + 1 then
                upgradeGoods = item
                break
            end
        end
    end
    return upgradeGoods or goods
end

---根据itemId查找商品组
function StoreConfig:getUpgradeGoodsGroup(itemId)
    local goods = self:getGoodsByItemId(itemId)
    if not goods then
        return
    end
    return UpgradeGoods[goods.LevelGroup]
end

---根据itemId和level查找商品
function StoreConfig:getUpgradeGoods(itemId, level)
    local goods = self:getGoodsByItemId(itemId)
    if not goods then
        return
    end
    local group = UpgradeGoods[goods.LevelGroup] or {}
    for _, _goods in pairs(group) do
        if _goods.Level == level then
            return _goods
        end
    end
    return goods
end

---根据商品组，自动过滤无效商品
function StoreConfig:getGoodsGroup(levelGroup)
    local group = UpgradeGoods[levelGroup] or {}
    local result = TableUtil.copyTable(group)
    for pos, goods in pairs(result) do
        if goods.Price < 0 then
            table.remove(result, pos)
        end
    end
    table.sort(result, function(a, b)
        return a.Level < b.Level
    end)
    return result
end

---获取货币信息
function StoreConfig:getCurrencyConfig(currencyId)
    local currency = getCurrencyByKey("Id", currencyId)
    if not currency then
        return nil
    end
    return currency
end

---检查某商品是否可以升级
function StoreConfig:needCheckUpgrade(itemId)
    return UpgradeGoodsFlag[tostring(itemId)] or false
end

---重置整个道具商店
function StoreConfig:resetGoodsStore()
    local store = Stores[StoreId.GoodsStore]
    for _, tab in pairs(store.Tabs) do
        for pos, goods in pairs(tab.GoodsList) do
            if goods.LevelGroup ~= "#" and not goods.SkipLevel then
                local minLvGoods = getMinUpgradeGoods(goods.LevelGroup)
                if minLvGoods then
                    table.remove(tab.GoodsList, pos)
                    table.insert(tab.GoodsList, pos, minLvGoods)
                end
            end
        end
    end
end

---替换商店中相同类型的商品
function StoreConfig:replaceUpgradeGoods(newGoods)
    if not newGoods then
        return
    end
    if newGoods.SkipLevel then
        return
    end
    for _, store in pairs(Stores) do
        for _, tab in pairs(store.Tabs) do
            for pos, goods in pairs(tab.GoodsList) do
                if goods.LevelGroup == newGoods.LevelGroup then
                    table.remove(tab.GoodsList, pos)
                    table.insert(tab.GoodsList, pos, newGoods)
                    break
                end
            end
        end
    end
end

---获取玩家当前所有装备的ItemId
local function getEquipArmorItemIds(player)
    local inv = player:getInventory()
    local itemIds = {}
    for index = 101, 103 do
        local info = inv:getItemStackInfo(index)
        if info.id > 0 then
            table.insert(itemIds, info.id)
        end
    end
    return itemIds
end

---获取玩家当前装备的商品
function StoreConfig:getEquipArmorGoods(player, levelGroup)
    local itemIds = getEquipArmorItemIds(player)
    for _, itemId in pairs(itemIds) do
        local _goods = self:getGoodsByItemId(itemId)
        if _goods and _goods.LevelGroup == levelGroup then
            return _goods
        end
    end
    return nil
end

---获取玩家当前装备的商品等级
function StoreConfig:getEquipArmorLevel(player, levelGroup)
    local goods = self:getEquipArmorGoods(player, levelGroup)
    if not goods then
        return 0
    end
    return goods.Level
end

---判断某商品是否在道具商店内
function StoreConfig:isInGoodsStore(goods)
    local store = Stores[StoreId.GoodsStore]
    for _, tab in pairs(store.Tabs) do
        if tab.Id == goods.TabId then
            return true
        end
    end
    return false
end

---获取商品所在的商店Id
function StoreConfig:getGoodsStoreId(goods)
    for storeId, store in pairs(Stores) do
        for _, tab in pairs(store.Tabs) do
            if tab.Id == goods.TabId then
                return storeId
            end
        end
    end
    return StoreId.GoodsStore
end