---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by JY-032.
--- DateTime: 2019/10/18 16:55
---

local GUIMain = class("", IGUILayout)

function GUIMain:onLoad()

    self.windowPosRecord = {}
    self.killMostPlayer = ""
    self.survivorNum = 0
    self.surviveTeamNum = 0
    self.killNum = 0
    self.mountTime = 0
    self.isShowInfo = true
    self.isFishing = false
    self.isUseSkill = false
    self.isUseGun = false
    self.contDownTimeText = ""
    self.contDownTime = 0
    self.preView = -1
    self.isFirst = true
    self.ropeTime = 0
    self.ropeLeftTime = 0

    self.llMount = self:getChildWindow("SkyWarLuckyMain-Mount", GUIType.Layout)
    self.llMount:SetVisible(false)
    self.llPlayerInfo = self:getChildWindow("SkyWarLuckyMain-Player-Info", GUIType.Layout)
    self.llPlayerInfo:SetVisible(false)
    self.llPlayerInfo:registerEvent(GUIEvent.Click, function()
        SoundUtil.clickUI()
        self:showInfoPanel()
    end)

    self.llKnight = self:getChildWindow("SkyWarLuckyMain-Kill-Most", GUIType.Layout)
    self.llKills = self:getChildWindow("SkyWarLuckyMain-Kills", GUIType.Layout)
    self.llEvent = self:getChildWindow("SkyWarLuckyMain-Event", GUIType.Layout)

    self.tvKillMost = self:getChildWindow("SkyWarLuckyMain-Kill-Most-Name", GUIType.StaticText)
    self.tvKills = self:getChildWindow("SkyWarLuckyMain-Kills-Num", GUIType.StaticText)
    self.tvMount = self:getChildWindow("SkyWarLuckyMain-Mount-Time", GUIType.StaticText)

    self.tvContDownTime = self:getChildWindow("SkyWarLuckyMain-Event-Time", GUIType.StaticText)
    self.tvEventName = self:getChildWindow("SkyWarLuckyMain-Event-Name", GUIType.StaticText)

    self.llRope = self:getChildWindow("SkyWarLuckyMain-Rope", GUIType.Layout)
    self.pbRopeValue = self:getChildWindow("SkyWarLuckyMain-Rope-Value", GUIType.ProgressBar)
    self.ivRopeFireEffect = self:getChildWindow("SkyWarLuckyMain-Rope-Fire-Effect", GUIType.StaticImage)
    self.ivRopeExplodeEffect = self:getChildWindow("SkyWarLuckyMain-Rope-Explode", GUIType.StaticImage)
    self.llRope:SetVisible(false)
    self.ivRopeExplodeEffect:SetVisible(false)

    self.ivCrossHair = self:getChildWindow("SkyWarLuckyMain-Cross-Hair", GUIType.StaticImage)
    self.ivCrossHair:SetVisible(false)

    self.ivUsePropBg = self:getChildWindow("SkyWarLuckyMain-Use_Prop_Bg", GUIType.StaticImage)
    self.ivUsePropBg:SetVisible(false)
    self.ivUsePropIcon = self:getChildWindow("SkyWarLuckyMain-Prop_Icon", GUIType.StaticImage)
    self.tvUsePropName = self:getChildWindow("SkyWarLuckyMain-Prop_Name", GUIType.StaticText)
    self.tvUsePropTip = self:getChildWindow("SkyWarLuckyMain-Prop_Tip", GUIType.StaticText)
    self.tvUsePropTip:SetText(Lang:getString("lucky.sky.use.prop.next.game"))
    self.tvUsePropNum = self:getChildWindow("SkyWarLuckyMain-Prop_Num", GUIType.StaticText)

    self:getChildWindow("SkyWarLuckyMain-Kill-Most-Title", GUIType.StaticText):SetText(Lang:getString("lucky.sky.kill.most.title"))
    self:getChildWindow("SkyWarLuckyMain-Kills-Text", GUIType.StaticText):SetText(Lang:getString("lucky.sky.kills.text"))
    self:getChildWindow("SkyWarLuckyMain-Mount-Text", GUIType.StaticText):SetText(Lang:getString("lucky.sky.mount.text"))
    self:getChildWindow("SkyWarLuckyMain-Event-Title", GUIType.StaticText):SetText(Lang:getString("lucky.sky.event.title"))
    self.btnEnter = self:getChildWindow("SkyWarLuckyMain-Enter-Button", GUIType.Button)
    self.btnEnter:SetVisible(true)
    self.btnEnter:registerEvent(GUIEvent.ButtonClick, function()
        SoundUtil.clickUI()
        GUIJobChoice:show(false)
    end)
    self.btnProp = self:getChildWindow("SkyWarLuckyMain-Prop-Button", GUIType.Button)
    self.btnProp:registerEvent(GUIEvent.ButtonClick, function()
        SoundUtil.clickUI()
        GUIIllustration:show()
    end)

    self:hideEngineWindow("PlayerInfo-FoodSaturation")

    self:registerDataCallBack("hideJobButton", function(data)
        self:onHideJobButton(data)
    end, DataBuilderProcessor)

    self:registerDataCallBack("ToolBarData", function(data)
        self:onToolBarData(data)
    end, DataBuilderProcessor)

    self:registerDataCallBack("PlayerInfoData", function(data)
        self:updatePlayerInfo(data)
    end, DataBuilderProcessor)

    self:registerDataCallBack("MountInfoData", function(data)
        self:updateMountInfo(data)
    end, DataBuilderProcessor)

    self:registerDataCallBack("CountDownData", function(data)
        self:onCountDownData(data)
    end, DataBuilderProcessor)

    self:registerDataCallBack("SendRopeData", function(data)
        self:onReceiveRopeData(data)
    end, DataBuilderProcessor)

    self:registerDataCallBack("SetView", function()
        self:onCancelAim()
        if self.preView == -1 then
            self.preView = RootGuiLayout.Instance():getViewNum()
        end
    end, DataBuilderProcessor)

    LuaTimer:schedule(function(userId)
        self:upContDownTimeTextTick()
    end, 1000, 1000)

    self:registerDataCallBack("sendUsePropData", function(data)
        self:onUsePropData(data)
    end, DataBuilderProcessor)

    local llArmor = GUIManager:getWindowByName("PlayerInfo-Armor")
    llArmor:SetArea({ 0, 0 }, { 0, -155 }, { 0, 600 }, { 0, 28 })
end

function GUIMain:onUsePropData(data)
    self.ivUsePropBg:SetVisible(true)
    local itemId = data:getNumberParam("propId")
    local number = data:getNumberParam("num")
    local name = ItemConfig:getItemNameById(itemId)
    if itemId == nil then
        self.ivUsePropBg:SetVisible(false)
        return
    end
    GuiItemStack.showItemIcon(self.ivUsePropIcon, tonumber(itemId), 0, "")
    self.tvUsePropName:SetText(string.format(Lang:getString(name) .. "  x%s", tostring(number)))
end

function GUIMain:onCountDownData(data)
    self.contDownTimeText = data:getParam("ContDownTimeText")
    self.contDownTime = data:getNumberParam("ContDownTime")
end

function GUIMain:upContDownTimeTextTick()
    if self.contDownTime > 0 then
        self.contDownTime = self.contDownTime - 1
        self:upTimeText()
    else
        self.contDownTime = 0
    end
end

function GUIMain:upTimeText()
    self.tvEventName:SetText(Lang:getString(self.contDownTimeText))
    self.tvContDownTime:SetText(Lang:getString(self.contDownTime))
end

function GUIMain:onToolBarData(data)
    local isShow = data:getBoolParam("isShow")
    if not isShow then
        GUIIllustration:hide()
        GUIIllustrationDescription:hide()
        GUIManager:hideWindowByName("ToolBar.json")
    else
        GUIManager:showWindowByName("ToolBar.json")
    end
end

function GUIMain:onTick(nTimeElapse)
    if not Game:getPlayer() or not self:isShow() then
        return
    end
    self:updateMountTime(nTimeElapse)
    self:updateRopeTime(nTimeElapse)
    --local isOnMount = Blockman.Instance():getPlayer():isOnFlyingMount() or Blockman.Instance():getPlayer():isOnFloatingMount()
    --GUIManager:getWindowByName("ToolBar-Perspece"):SetEnabled(not isOnMount)
end

function GUIMain:updateMountTime(nTimeElapse)
    if self.mountTime <= 0 and not self.llMount:IsVisible() then
        return
    end
    if self.mountTime > 0 then
        if self.isShowInfo and not self.llMount:IsVisible() then
            self.llMount:SetVisible(true)
        end
        self.mountTime = self.mountTime - nTimeElapse
        self.tvMount:SetText(tostring(math.ceil(self.mountTime / 1000)))
        if Game:getPlayer():isOnFlyingMount() then
            self.ivCrossHair:SetVisible(true)
        end
    else
        self:resetLayout()
        if self.preView ~= -1 then
            Blockman.Instance():setPersonView(self.preView)
            self.preView = -1
        end
    end
end

function GUIMain:updateRopeTime(nTimeElapse)
    if self.ropeTime <= 0 then
        return
    end
    if not self.llRope:IsVisible() then
        self.llRope:SetVisible(true)
        self.ivRopeExplodeEffect:SetVisible(false)
    end
    self.ropeLeftTime = self.ropeLeftTime - nTimeElapse
    if self.ropeLeftTime > 0 then
        self.pbRopeValue:SetProgress(self.ropeLeftTime / self.ropeTime)
        self.ivRopeFireEffect:SetXPosition({ self.ropeLeftTime / self.ropeTime, -15 })
        if self.ropeLeftTime < 2000 and not self.ivRopeExplodeEffect:IsVisible() then
            self.ivRopeExplodeEffect:SetVisible(true)
        end
    else
        self.ropeLeftTime = 0
        self.ropeTime = 0
        self.llRope:SetVisible(false)
        self.ivRopeExplodeEffect:SetVisible(false)
    end
end

function GUIMain:onHideJobButton(data)
    local isHide = data:getBoolParam("isHide")
    if isHide then
        self.btnEnter:SetVisible(false)
        self.ivUsePropBg:SetVisible(false)
        GUIJobChoice:hide()
        GUIJobExtract:hide()
        GUIIllustration:hide()
        GUIIllustrationDescription:hide()
        self.llPlayerInfo:SetVisible(true)
    end
    if self.isFirst then
        self.isFirst = false
        self:changeChattingPosition()
    end
end

function GUIMain:changeChattingPosition()
    GUIManager:getWindowByName("Main-Chat-Message"):SetYPosition({ 0, 300 })
    GUIManager:getWindowByName("Main-Center-System-Notification"):SetFont(GUIFontManager:Instance():GetFont("HT12"))
end

function GUIMain:updatePlayerInfo(data)
    if not self.llPlayerInfo:IsVisible() or not self:isShow() then
        self:show()
        self.llPlayerInfo:SetVisible(true)
    end
    self.killMostPlayer = data:getParam("killMost") or ""
    self.killNum = data:getNumberParam("killNum")
    self:showPlayerInfo()
end

function GUIMain:updateMountInfo(data)
    self.mountTime = data:getNumberParam("Time") * 1000
    if self.mountTime > 0 then
        self:resetLayout()
        RootGuiLayout.Instance():showMainControl()
        GUIManager:getWindowByName("ToolBar-Perspece"):SetEnabled(false)
        self:hideEngineWindow("Main-Control")
        self:hideEngineWindow("Main-MoveState")
        self:hideEngineWindow("Main-Jump-Controls")
        self:hideEngineWindow("Main-ItemBarBg")
        self:hideEngineWindow("Main-VisibleBar")
        self:hideEngineWindow("Main-Player-Exp")
        self:hideEngineWindow("Main-PoleControl")
        self:hideEngineWindow("Main-Gun-CrossHairs")
        self.isFishing = false
        self.isUseSkill = false
        self.isUseGun = false
        if GUIManager:getWindowByName("Main-Fishing"):IsVisible() then
            self.isFishing = true
            self:hideEngineWindow("Main-Fishing")
        end
        if GUIManager:getWindowByName("Main-Skill-Release-btn"):IsVisible() then
            self.isUseSkill = true
            self:hideEngineWindow("Main-Skill-Release-btn")
        end
        if GUIManager:getWindowByName("Main-Gun-Operate"):IsVisible() then
            self.isUseGun = true
            self:hideEngineWindow("Main-Gun-Operate")
        end
    end
end

function GUIMain:hideEngineWindow(name)
    local window = GUIManager:getWindowByName(name)
    if not window then
        return
    end
    self.windowPosRecord[name] = window:GetXPosition()
    window:SetXPosition({ 200, 0 })
end

function GUIMain:showEngineWindow(name)
    local oldPos = self.windowPosRecord[name]
    if not oldPos then
        return
    end
    local window = GUIManager:getWindowByName(name)
    window:SetXPosition(oldPos)
end

function GUIMain:showPlayerInfo()
    self.tvKillMost:SetText(tostring("▢FFFF0000" .. self.killMostPlayer))
    self.tvKills:SetText(tostring(self.killNum))
end

function GUIMain:showInfoPanel()
    self.isShowInfo = not self.isShowInfo
    self.llEvent:SetVisible(self.isShowInfo)
    self.llKills:SetVisible(self.isShowInfo)
    self.llMount:SetVisible(self.isShowInfo and self.mountTime > 0)
    if self.isShowInfo == true then
        self.llPlayerInfo:SetHeight({ 0.3, 0 })
        self.llKnight:SetYPosition({ 0.03, 0 })
        self.llKnight:SetHeight({ 0.28, 0 })
    else
        self.llPlayerInfo:SetHeight({ 0.1, 0 })
        self.llKnight:SetYPosition({ 0.083, 0 })
        self.llKnight:SetHeight({ 0.83, 0 })
    end
end

function GUIMain:onCancelAim()
    local gui_mainControl = DynamicCastHelper.dynamicCastGuiMainControl(RootGuiLayout.Instance():getLayout(0))
    if gui_mainControl then
        gui_mainControl:onCancelAim()
    end
end

function GUIMain:resetLayout()
    self.llMount:SetVisible(false)
    self.ivCrossHair:SetVisible(false)
    GUIManager:getWindowByName("ToolBar-Perspece"):SetEnabled(true)
    self:showEngineWindow("Main-Control")
    self:showEngineWindow("Main-MoveState")
    self:showEngineWindow("Main-Jump-Controls")
    self:showEngineWindow("Main-ItemBarBg")
    self:showEngineWindow("Main-VisibleBar")
    self:showEngineWindow("Main-Player-Exp")
    self:showEngineWindow("Main-PoleControl")
    self:showEngineWindow("Main-Gun-CrossHairs")
    if self.isFishing then
        self:showEngineWindow("Main-Fishing")
    end
    if self.isUseSkill then
        self:showEngineWindow("Main-Skill-Release-btn")
    end
    if self.isUseGun then
        self:showEngineWindow("Main-Gun-Operate")
    end
end

function GUIMain:onReceiveRopeData(data)
    self.ropeLeftTime = data:getNumberParam("Time") * 1000
    self.ropeTime = self.ropeLeftTime
    if self.ropeTime <= 0 and self.llRope:IsVisible() then
        self.llRope:SetVisible(false)
        self.ivRopeExplodeEffect:SetVisible(false)
    end
end

function GUIMain:hideAllLayout()
    GUIIllustration:hide()
    GUIIllustrationDescription:hide()
    GUIManager:hideWindowByName("ToolBar.json")
    GUIManager:hideWindowByName("TipDialog.json")
end

return GUIMain