---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Yanzhuolin.
--- DateTime: 2019/10/25 18:02
---

GameWallet = class("GameWallet", BaseWallet)

CommonDataEvents:registerCallBack("UpdateWallet", function(data)
    PlayerManager:getClientPlayer().Wallet:updateWallet(data:getNumberParam("coinId"), data:getNumberParam("count"))
end, DataBuilderProcessor)

function GameWallet:updateWallet(coinId, count)
    self:setMoneyCount(coinId, count)
    UpdateMoneyEvent:invoke()
end

