---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 10184.
--- DateTime: 2020/6/4 15:14
---

function BlockShop:init()
    EventObservable:registerDataCallBack("BlockShopData", function(data)
        self:updateData(data)
    end, JsonBuilderProcessor)
    EventObservable:registerDataCallBack("BuyBlockGoodsSuccess", function(goodsId)
        GUIBlockShop:showBuyGoodsSuccess(goodsId)
    end)
    EventObservable:registerDataCallBack("BlockShopRedPoint", function()
        GUIMain.ivBlockShopPoint:SetVisible(true)
    end)
end

BlockShop:init()

function BlockShop:onBuyGoods(goods)
    CommonPacketSender:sendBuyBlockGoods(goods.Id)
end

function BlockShop:onEquipGoods(goods)
    CommonPacketSender:sendEquipBlockGoods(goods.Id)
    ReportUtil.reportBlockShopEquip(goods.Id)
end

function BlockShop:onUnloadGoods(goods)
    CommonPacketSender:sendUnloadBlockGoods(goods.Id)
    ReportUtil.reportBlockShopUnload(goods.Id)
end

function BlockShop:updateData(data)
    local TabIds = {}
    for _, item in pairs(data) do
        local goods = BlockShopConfig:getGoodsConfig(item[BlockGoodsIndex.Id])
        if goods then
            goods.Status = item[BlockGoodsIndex.Status]
            goods.Time = item[BlockGoodsIndex.Time]
            TabIds[tostring(goods.TabId)] = true
        end
    end
    for tabId, _ in pairs(TabIds) do
        local goodsList = BlockShopConfig:getGoodsList(tonumber(tabId), BlockShopConfig.Type.Skin)
        table.sort(goodsList, function(a, b)
            if a.Time ~= b.Time then
                return a.Time < b.Time
            end
            return a.Weight < b.Weight
        end)
        goodsList = BlockShopConfig:getGoodsList(tonumber(tabId), BlockShopConfig.Type.Wall)
        table.sort(goodsList, function(a, b)
            if a.Time ~= b.Time then
                return a.Time < b.Time
            end
            return a.Weight < b.Weight
        end)
    end
    if GUIBlockShop then
        GUIBlockShop:updateListUI()
    end
end