---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lai.
--- DateTime: 2019/4/15 10:32
---

HonourConfig = {}

local honour = {}

local function init()
    local config = FileUtil.getConfigFromCsv("HonourConfig.csv")
    for i, v in pairs(config) do
        local data = {}
        data.id = tonumber(v.id)
        data.rank = tonumber(v.rank)
        data.integral = tonumber(v.integral)
        data.yaoshi = tonumber(v.yaoshi)
        data.exp = tonumber(v.exp) or 0
        honour[i] = data
    end
end

init()

function HonourConfig:getHonourByRank(rank)
    for _, config in pairs(honour) do
        if config.rank == rank then
            return config.integral
        end
    end
    return 0
end

function HonourConfig:getYaoShiByRank(rank)
    for _, config in pairs(honour) do
        if config.rank == rank then
            return config.yaoshi or 0
        end
    end
    return 0
end

function HonourConfig:getRewardExp(rank, isWin, hasPrivilege)
    local timeExp = 0
    for _, config in pairs(honour) do
        if config.rank == rank then
            timeExp = config.exp
            break
        end
    end

    local exp = 0
    if isWin then
        exp = math.floor(GameConfig.playerWin * GameConfig.isGameOver * timeExp)
    else
        exp = math.floor(GameConfig.playerLos * GameConfig.isGameOver * timeExp)
    end

    if hasPrivilege then
        exp = exp * 2
    end

    return exp
end