---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Heshenghuan.
--- DateTime: 2020/1/11 20:57
---

LevelHelper = {}

function LevelHelper:checkUpgrade(target)
    if target.entityType ~= Define.EntityType.Tower then
        return ---塔才能升级
    end
    local upgradeInfo = LevelConfig:getConfigByGroupId(target.config.levelGroup)
    if not upgradeInfo then
        return ---找不到塔的升级组
    end
    local curLevelInfo = upgradeInfo[target.properties["curLevel"] + 1]
    if not curLevelInfo then
       return ---找不到升级的信息，达到最高级
    end
    if target.properties["curExp"] > curLevelInfo.expLimit then
        ---经验够了，可以升级
        local redundantExp = target.properties["curExp"] - curLevelInfo.expLimit
        target.properties["curExp"] = redundantExp
        target.properties["curLevel"] = target.properties["curLevel"] + 1
        AdditionHelper:additionEject(target, curLevelInfo.upgradeAdditionIds)
    end
end