---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Yanzhuolin.
--- DateTime: 2019/10/29 12:08
---

GameTower = class("GameTower", BaseTower)

function GameTower:ctor(serverId, pos, configId, userId, seed)
    self.serverId = serverId
    self.processId = GamePlayer:Instance().processId
    self.config = TowerConfig:getConfigById(tonumber(configId))
    self.userId = userId
    self:setRandom(seed)
    self:onCreate(pos, self.config, userId, Game:getPlayer():getPosition())
    SoundUtil.playSound3D(self.config.AppearSound, self.pos.x, self.pos.y, self.pos.z)

    self.effectPosition = VectorUtil.newVector3(pos.x, pos.y + 0.1, pos.z)
    self.OwnEffectPosition = VectorUtil.newVector3(pos.x, pos.y + 0.01, pos.z)
    self.auraEffectName = nil
    self.attackEffectName = nil
    self.ownEffectName = nil
    self:addOwnEffect()

    if self.config.StarLevel == 1 then
        self:showEffect(Define.TowerStatus.Build)
    else
        self:showEffect(Define.TowerStatus.Formula)
    end

    if userId == tostring(GamePlayer:Instance().userId) then
        if GamePlayer:Instance().formulaList["Start" .. self.config.StarLevel] == nil then
            GamePlayer:Instance().formulaList["Start" .. self.config.StarLevel] = {}
        end
        table.insert(GamePlayer:Instance().formulaList["Start" .. self.config.StarLevel], self)
        GamePlayer:Instance():checkTowerFormulaByStarLevel()
        LuaTimer:schedule(function ()
            GamePlayer:Instance():checkAllTowerItem()
        end,4500)
    end
end

function GameTower:synAttack(targetIds)
    local targets = {}
    for _, id in pairs(targetIds) do
        local monster = LuaEntityManager:getMonster(LuaEntityManager:getClientId(tonumber(id)))
        if monster then
            table.insert(targets, monster)
        end
    end
    self:attack(targets)
end

function GameTower:synEjections(target, preTarget, ejectionsCount)
    self:ejectionsAttack(target, preTarget, ejectionsCount)
end

function GameTower:onClickLock()
    if self.userId ~= tostring(GamePlayer:Instance().userId) then
        return
    end

    self.isLock = not self.isLock
    GamePacketSender:sendLockTower(self.serverId, self.isLock)

    if self.isLock then
        EngineWorld:removeSimpleEffect(self.ownEffectName)
        local effect = EngineWorld:addSimpleEffect("165_tower_biaoshita_red.effect", self.OwnEffectPosition, 0, -1)
        self.ownEffectName = effect.mEffectName

        for i, v in pairs(GamePlayer:Instance().formulaList["Start" .. self.config.StarLevel]) do
            if self.serverId == v.serverId then
                table.remove(GamePlayer:Instance().formulaList["Start" .. self.config.StarLevel], i)
                break
            end
        end
        GamePlayer:Instance():checkAllTowerItem()
    else
        EngineWorld:removeSimpleEffect(self.ownEffectName)
        local effect = EngineWorld:addSimpleEffect("165_tower_biaoshita.effect", self.OwnEffectPosition, 0, -1)
        self.ownEffectName = effect.mEffectName

        if GamePlayer:Instance().formulaList["Start" .. self.config.StarLevel] == nil then
            GamePlayer:Instance().formulaList["Start" .. self.config.StarLevel] = {}
        end
        table.insert(GamePlayer:Instance().formulaList["Start" .. self.config.StarLevel], self)
        GamePlayer:Instance():checkTowerFormulaByStarLevel()
        LuaTimer:schedule(function ()
            GamePlayer:Instance():checkAllTowerItem()
        end,4500)
    end
end

function GameTower:checkPropertyChange()
    self.super.checkPropertyChange(self)
    GUITowerDetail:updateDetail(self)

end

function GameTower:addOwnEffect()
    if self.userId == tostring(GamePlayer:Instance().userId) then
        local effect = EngineWorld:addSimpleEffect("165_tower_biaoshita.effect", self.OwnEffectPosition, 0, -1)
        self.ownEffectName = effect.mEffectName
    end
end

function GameTower:removeOwnEffect()
    EngineWorld:removeSimpleEffect(self.ownEffectName)
    self.ownEffectName = nil
end

function GameTower:removeAttackRangeEffect()
    EngineWorld:removeSimpleEffect(self.attackEffectName)
    self.attackEffectName = nil
end

function GameTower:showAttackRangeEffect()
    self:removeAttackRangeEffect()
    local effect = EngineWorld:addSimpleEffect(self.config.AttackRangeEffect, self.effectPosition, 0, -1, self.config.AttackRange - 0.2, 1, self.config.AttackRange)
    self.attackEffectName = effect.mEffectName
end

function GameTower:hideAttackRangeEffect()
    self:removeAttackRangeEffect()
    local effect = EngineWorld:addSimpleEffect(self.config.AttackRangeEffect, self.effectPosition, 0, 3000, self.config.AttackRange, 1, self.config.AttackRange)
    self.attackEffectName = effect.mEffectName
end

function GameTower:onDie()
    if self.userId == tostring(GamePlayer:Instance().userId) then
        for key, v in pairs(GamePlayer:Instance().formulaList["Start" .. self.config.StarLevel]) do
            if self.serverId == v.serverId then
                table.remove(GamePlayer:Instance().formulaList["Start" .. self.config.StarLevel], key)
                GamePlayer:Instance():checkTowerFormulaByStarLevel()
                GamePlayer:Instance():checkAllTowerItem()
                break
            end
        end
    end

    self:showEffect(Define.TowerStatus.Destroy)
    GUITowerDetail:onTowerDestroy(self)
    self:removeAttackRangeEffect()
    self:removeOwnEffect()
    self.super.onDie(self)
end

function GameTower:showEffect(status)
    local effectConfig = TowerEffectConfig:getConfigById(1)
    if status == Define.TowerStatus.Build then
        EngineWorld:addSimpleEffect(effectConfig.buildEffect, self.pos, 0, 1000)
    elseif status == Define.TowerStatus.Formula then
        EngineWorld:addSimpleEffect(effectConfig.formulaEffect, self.pos, 0, 1000)
    elseif status == Define.TowerStatus.Destroy then
        EngineWorld:addSimpleEffect(effectConfig.destroyEffect, self.pos, 0, 1000)
        SoundUtil.playSound3D(902, self.pos.x, self.pos.y, self.pos.z)
    end
end

