---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jimmy.
--- DateTime: 2019/9/4 0004 15:07
---

IGUIListView = class("IGUIListView", IGUIDataView) ---@class IGUIListView : IGUIDataView

function IGUIListView:ctor(name, parent, root, orientation)
    if not parent then
        return
    end
    if not root then
        orientation = orientation or Orientation.Vertical
        if orientation == Orientation.Vertical then
            root = GUIManager:createGUIWindow(GUIType.List, name)
        else
            root = GUIManager:createGUIWindow(GUIType.ListHorizontal, name)
        end
        root:SetArea({ 0, 0 }, { 0, 0 }, { 1, 0 }, { 1, 0 })
    end
    self:init(root)
    self.orientation = orientation
    parent:AddChildWindow(self.root)
    MemoryPool.pushTable(self)
end

function IGUIListView:setItemSpace(itemSpace)
    if not self.root then
        return
    end
    self.root:SetInterval(itemSpace)
end

function IGUIListView:getHorizontalSpace()
    if not self.root then
        return 0
    end
    if self.orientation == Orientation.Vertical then
        return 0
    else
        return self.root:GetInterval()
    end
end

function IGUIListView:getVerticalSpace()
    if not self.root then
        return 0
    end
    if self.orientation == Orientation.Vertical then
        return self.root:GetInterval()
    else
        return 0
    end
end

function IGUIListView:clearItems()
    if self.adapter then
        self.adapter:clearItems()
        return
    end
    for pos, item in pairs(self.items) do
        item:destroy()
    end
    self.items = {}
    if not self.root then
        return
    end
    self.root:ClearAllItem()
end