---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Yanzhuolin.
--- DateTime: 2019/11/7 15:56
---

LuaEntityManager = {}

local EntityList = {}
local DataCache = {}

function LuaEntityManager:getClientId(serverId)
    return DataCache[tostring(serverId)]
end

function LuaEntityManager:addEntity(entity)
    EntityList[tostring(entity.entityId)] = entity
    if isClient then
        DataCache[tostring(entity.serverId)] = entity.entityId
    end
end

function LuaEntityManager:subEntity(entityId)
    EntityList[tostring(entityId)] = nil
end

function LuaEntityManager:getTowers()
    local towers = {}
    for _, entity in pairs(EntityList) do
        if entity.__cname == "GameTower" then
            table.insert(towers, entity)
        end
    end
    return towers
end

function LuaEntityManager:getTower(entityId)
    local entity = nil
    entity = EntityList[tostring(entityId)]
    if not entity or entity.__cname ~= "GameTower" then
        return
    end
    return entity
end

function LuaEntityManager:getMonster(entityId)
    local entity = nil
    entity = EntityList[tostring(entityId)]
    if not entity or entity.__cname ~= "GameMonster" then
        return
    end
    return entity
end

function LuaEntityManager:getMonstersByManager(mapManager, userId)
    local monsters = {}
    if userId then
        local path = mapManager:getPathByUserId(userId) or {}
        for _, monster in pairs(path.monsters or {}) do
            table.insert(monsters, monster)
        end
    else
        for _, path in pairs(mapManager.pathList) do
            for _, monster in pairs(path.monsters) do
                table.insert(monsters, monster)
            end
        end
    end
    return monsters
end

function LuaEntityManager:getTowersByManager(mapManager, userId)
    local towers = {}
    if userId then
        for _, entity in pairs(EntityList) do
            if entity.__cname == "GameTower" then
                if tostring(entity.userId) == tostring(userId) then
                    table.insert(towers, entity)
                end
            end
        end
    else
        local userIds = {}
        for _, path in pairs(mapManager.pathList) do
            for _, userId in pairs(path.protectUserId) do
                userIds[tostring(userId)] = 1
            end
        end

        for _, entity in pairs(EntityList) do
            if entity.__cname == "GameTower" then
                if userIds[tostring(entity.userId)] or isClient then
                    table.insert(towers, entity)
                end
            end
        end
    end
    return towers
end

function LuaEntityManager:clearEntity(mapManager)
    if isClient then
        for key, entity in pairs(EntityList) do
            if entity.__cname == "GameMonster" then
                entity.clientDead = true
                entity.serverDead = true
            end
            entity:onDie()
            EntityList[key] = nil
        end
    else
        local resetUserIds = {}
        for _, path in pairs(mapManager.pathList) do
            local monsterIds = {}
            for _, monster in pairs(path.monsters) do
                table.insert(monsterIds, monster.entityId)
            end
            for _, id in pairs(monsterIds) do
                local monster = EntityList[tostring(id)]
                EntityList[tostring(id)] = nil
                monster.super.onDie(monster)
            end

            for _, userId in pairs(path.protectUserId) do
                resetUserIds[tostring(userId)] = 1
            end

        end

        for key, entity in pairs(EntityList) do
            if entity.__cname == "GameTower" then
                if resetUserIds[tostring(entity.userId)] then
                    entity.super.onDie(entity)
                    EntityList[key] = nil
                end
            end
        end
    end
end