---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangpq.
--- DateTime: 2019/10/9 17:51
---
Utility = {}

function Utility.trimTailZero(str)
    local loopCount = 1
    while str:sub(str:len(), str:len()) == "0" do
        if loopCount >= 10 then
            break
        end

        str = str:sub(1, str:len() - 1)

        loopCount = loopCount + 1
    end
    return str
end

function Utility.addWallText(text, index)
    local setting = WallTextConfig:getWallTextConfig(index)
    if not setting then
        return
    end

    local globalRender = Blockman.Instance().m_globalRender
    if not globalRender then
        return
    end

    --text = Utility.toAbbreviateString(tostring(text))

    local pos = VectorUtil.newVector3(setting.pos[1], setting.pos[2], setting.pos[3])
    globalRender:luaAddWallText(setting.type, setting.timeLeft, text, pos, setting.scale, setting.yaw, setting.pitch,
            {setting.color[1], setting.color[2], setting.color[3], setting.color[4]})
end

function Utility.kmbStrToNumber(str)
    local len = string.len(str)
    local number = string.sub(str, 1, len - 1)
    local abbreviation = string.sub(str, len, len)

    LogUtil.log(string.format("kmbStrToNumber %s %s %s", str, number, abbreviation))

    for _, setting in pairs(UnitConfig.settings) do
        if setting.abbreviation == abbreviation then
            local value = tonumber(number) * (10 ^ tonumber(setting.digitNum))
            --LogUtil.log(string.format("kmbStrToNumber result %s %f %f %f",
            --        str, value, tonumber(number), tonumber(setting.digitNum)))
            return value
        else
            --LogUtil.log(string.format("setting.abbreviation ~= abbreviation %s %s",
            --        setting.abbreviation, abbreviation))
        end
    end

    return tonumber(str)
end

--数字转为“K”、“M”、“B”格式
function Utility.toKMBString(str, precision)
    str = string.format("%f", str)
    str = tostring(BigNum.new(str))
    precision = precision or 0
    local len = string.len(str)

    if str == "inf" or str == "Inf" then
        return "∞"
    end

    for _, setting in pairs(UnitConfig.settings) do
        if len > setting.digitNum then
            if len <= 12 then
                precision = 2
            end

            local integer = string.sub(str, 1, len - setting.digitNum) --整数部分
            local decimal = string.sub(str, len - setting.digitNum + 1, len - setting.digitNum + precision) --小数部分
            decimal = Utility.trimTailZero(decimal)
            if precision ~= 0 then
                if decimal ~= "" then
                    str = integer .. "." .. decimal .. setting.abbreviation
                else
                    str = integer .. setting.abbreviation
                end
            else
                str = integer .. setting.abbreviation
            end
            return str
        end
    end

    return str
end

--function Utility.toInfinity(str, precision)
--    if str == "inf" then
--        return "∞"
--    else
--        return Utility.toKMBString(str, precision)
--    end
--end

--将超过11个字符的字符串表示成8个字符的缩写形式，如:“123456789123”,表示成“12345678...”
function Utility.toAbbreviateString(str)
    --print(str)
    if string.len(str) >= 11 then
        str = string.sub(str, 1, 8).."..."
    end
    --print("省略")
    --print(str)
    return str
end

--function Utility.tableToString(tb)
--    if type(tb) ~= "table" then
--        return ""
--    end
--
--    local str = ""
--    for i, v in pairs(tb) do
--        str = str .. i .. "," .. v .. "#"
--    end
--
--    str = string.sub(str, 1, string.len(str) - 1)
--
--    --print(string.format("Utility.tableToString %s %s", inspect.inspect(tb), str))
--
--    return str
--end

function Utility.stringToTable(str)
    local result = {}

    for _, pair in pairs(StringUtil.split(str, "#")) do
        local kv = StringUtil.split(pair, ",")
        result[kv[1]] = tonumber(kv[2])
    end

    --print(string.format("Utility.stringToTable %s %s", str, inspect.inspect(result)))

    return result
end

local function showFloatNumber_inner(pEntity, damage, color, scaleCoe)
    if not pEntity then
        --LogUtil.log("Utility.showFloatNumber not pEntity")
        return
    end

    local entityRenderManager = EntityRenderManager.Instance()
    if not entityRenderManager then
        --LogUtil.log("Utility.showFloatNumber not entityRenderManager")
        return
    end

    local actor = entityRenderManager:getEntityActor(pEntity)
    if not actor then
        --LogUtil.log("Utility.showFloatNumber not actor")
        return
    end

    local pos = pEntity:getBottomPos()
    local scale = actor:GetTotalScale().y
    pos.y = pos.y + (pEntity:getHeight() * GameConfig.showFloatNumberPosCoe * scale)

    --随机位置
    --local offset = 1
    --pos.x = math.random(pos.x - offset, pos.x + offset)
    --pos.y = math.random(pos.y - offset, pos.y + offset)
    --pos.z = math.random(pos.z - offset, pos.z + offset)

    local pullDistance = 0
    WorldImageRender.Instance():addFloatNumber(Utility.toKMBString(tostring(damage), 2),
            pos, (1 + scale) * scaleCoe, color or 1, pullDistance)
end

function Utility.showFloatNumber(pEntity, pAttacker, damage, color)
    showFloatNumber_inner(pEntity, damage, color, GameConfig.showFloatNumberScaleCoeHurter)
    showFloatNumber_inner(pAttacker, damage, color, GameConfig.showFloatNumberScaleCoeAttacker)
end

function Utility.refreshPoleControlState(state)
    if Platform.isWindow() then
        return
    end

    local gui_menu = DynamicCastHelper.dynamicCastGuiMenu(RootGuiLayout.Instance():getLayout(7))
    if not gui_menu then
        return
    end

    local gui_gameSetting = DynamicCastHelper.dynamicCastGuiGameSetting(gui_menu:getRadioPanel(3))
    if not gui_gameSetting then
        return
    end

    gui_gameSetting:refreshPoleControlState(state)

    LogUtil.log(string.format("Utility.refreshPoleControlState %d", state))
end

function Utility.updateCameraDistance(bForce)
    local gui_mainControl = DynamicCastHelper.dynamicCastGuiMainControl(RootGuiLayout.Instance():getLayout(0))
    if gui_mainControl then
        LogUtil.log("gui_mainControl:updateCameraDistance " .. tostring(bForce))
        gui_mainControl:updateCameraDistance(bForce)
    end
end

return Utility