---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by JY-032.
--- DateTime: 2019/10/15 15:27
---
require "config.GameConfig"

local function hideEngineWindow(name)
    local window = GUIManager:getWindowByName(name)
    if not window then
        return
    end
    window:SetXPosition({ 0, 6000 })
    window:SetVisible(false)
end

GameListener = {}

function GameListener:init()
    BaseListener.registerCallBack(GameReadyEvent, self.onGameReady)
end

function GameListener.onGameReady()
    GameConfig.loadConfig()
    require "ui.GUIFactory"
    hideEngineWindow("PlayerInfo-Effect-Layout")
    hideEngineWindow("PlayerInfo-Buff")


    local edit = GUIManager:getWindowByName("Chat-Input-Box", GUIType.Edit)
    edit:EnableSmallKeyboard()

end

return GameListener
