---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by JY-032.
--- DateTime: 2019/10/15 16:04
---
require "config.JobConfig"
require "packet.GamePacketSender"
require "ui.window.GUIJobExtractItem"
require "ui.window.GUIJobExtractSmallItem"

local GUIJobExtract = class("UIJobExtract", IGUILayout)

function GUIJobExtract:onLoad()
    self.jobsPond = {}

    self.isCardOpen = true
    self.isRefresh = true
    self.times = 1    --记录次数：第几次抽取，
    self.refreshPrice = 0
    self.cur_prices = 0
    self.prices = ""

    self.have_index = {}    --存着已经点过牌的index
    self.index = 0
    self.cur_jobId = 0     --接收服务器抽取到的职业id
    self:getChildWindow("SkyWarLuckyJobExtract-Title"):SetText(Lang:getString("lucky.sky.jobExtract.tile"))
    self.btnClose = self:getChildWindow("SkyWarLuckyJobExtract-Close-Button", GUIType.Button)
    self.btnClose:registerEvent(GUIEvent.ButtonClick, function()
        SoundUtil.clickUI()
        self:hide()
        GUIJobChoice:show(true)
    end)

    self.btnRefresh = self:getChildWindow("SkyWarLuckyJobExtract-Refresh-Button", GUIType.Button)
    self.btnRefresh:registerEvent(GUIEvent.ButtonClick, function()
        self:onRefreshClick()
    end)

    self.tvRefresh_price = self:getChildWindow("SkyWarLuckyJobExtract-Refresh-Price", GUIType.StaticText)
    self:getChildWindow("SkyWarLuckyJobExtract-Tip-Text"):SetText(Lang:getString("lucky.sky.click.card.to.draw.job"))
    self:getChildWindow("SkyWarLuckyJobExtract-Price-Text"):SetText(Lang:getString("lucky.sky.job.price"))
    self:getChildWindow("SkyWarLuckyJobExtract-Job-Text"):SetText(Lang:getString("lucky.sky.remain.job"))
    self.tvPrice = self:getChildWindow("SkyWarLuckyJobExtract-Price", GUIType.StaticText)

    self.llJobInfo = self:getChildWindow("SkyWarLuckyJobExtract-Info-Job", GUIType.Layout)  --本轮可抽取的职业
    self.jobInfo_GridView = IGUIGridView.new("SkyWarLuckyJobExtract-Info-Job-JobsList", self.llJobInfo)
    self.jobInfo_GridView:setArea({ 0, 0 }, { 0, 0 }, { 1, 0 }, { 1, 0 })
    self.jobInfo_GridView:setConfig(0.012 * self.jobInfo_GridView:getWidth(), 0, 5)

    self.llJob_panels = self:getChildWindow("SkyWarLuckyJobExtract-Job-Panels", GUIType.Layout)
    self.card_GridView = IGUIGridView.new("SkyWarLuckyJobExtract-Job-Panels-Card", self.llJob_panels)
    self.card_GridView:setArea({ 0, 0 }, { 0, 0 }, { 1, 0 }, { 1, 0 })
    self.card_GridView:setConfig(0, 0, 5)

    self:registerDataCallBack("jobListUpdate", function(data)
        self:onUpdateJobData(data)
    end, JsonBuilderProcessor)

    self:registerDataCallBack("synJobId", function(data)
        self:onSynJobId(data)
    end, DataBuilderProcessor)

    self.btnProbability = self:getChildWindow("SkyWarLuckyJobExtract-Probability", GUIType.Button)
    if Game:isChina() then
        self.btnProbability:SetVisible(true)
        self.btnProbability:registerEvent(GUIEvent.ButtonClick, function()
            ProbabilityDialog.show("g1054_1")
        end)
    else
        self.btnProbability:SetVisible(false)
    end

end

function GUIJobExtract:upRefreshPriceText()
    self.tvRefresh_price:SetText(self.refreshPrice)
end

function GUIJobExtract:changeIndex(index)
    self.index = index
end

function GUIJobExtract:onSynJobId(data)
    self.cur_jobId = data:getNumberParam("id")
    local item = JobConfig:getJobById(self.cur_jobId)
    local Item = self.card_GridView:getItem("index", self.index)
    Item:setItemData(item)
    self.times = self.times + 1
    if self.times > 5 then
        self.times = 5
    end
    self:getPrice()
    self.tvPrice:SetText(tostring(self.cur_prices))
    self.isCardOpen = true
    table.insert(self.have_index, self.index)
end

function GUIJobExtract:isHaveIndex(index)
    for _, v in pairs(self.have_index) do
        if v == index then
            return true
        end
    end
    return false
end

function GUIJobExtract:onShow(needLoad)
    if needLoad == nil then
        needLoad = true
    end
    if not needLoad and self.card_GridView:getItemCount() > 0 then
        return
    end
    self.card_GridView:clearItems()
    local contentWidth = self.card_GridView:getWidth()
    local itemWidth = (contentWidth - 20) / 5
    local itemHeight = itemWidth * 1.4756
    for i = 1, 5 do
        local Item = GUIJobExtractItem.new("SkyWarLuckyCard.json")
        Item:setWidth({ 0, itemWidth })
        Item:setHeight({ 0, itemHeight })
        Item:initItem(i)
        self.card_GridView:addItem(Item)
    end
    HostApi.log("****#self.jobsPond" .. #self.jobsPond)
    if self.jobsPond == nil then
        self:RefreshJobList()
    end
    self:updateJobInfoUI()
end

function GUIJobExtract:updateJobInfoUI()
    self:getPrice()
    self.tvPrice:SetText(tostring(self.cur_prices))
    self.jobInfo_GridView:clearItems()
    local contentWidth = self.jobInfo_GridView:getWidth()
    local contentHeight = self.jobInfo_GridView:getHeight()
    local itemWidth = math.min(contentWidth * 0.18632, contentHeight)
    local itemHeight = itemWidth
    for _, card in pairs(self.jobsPond) do
        local Item = GUIJobExtractSmallItem.new("SkyWarLuckySmallItem.json")
        Item:setWidth({ 0, itemWidth })
        Item:setHeight({ 0, itemHeight })
        Item:setItemData(card)
        self.jobInfo_GridView:addItem(Item)
    end
end

function GUIJobExtract:changeSmallItemStatus(id)
    for _, item in pairs(self.jobsPond) do
        if item.id == id then
            JobConfig:changeJobIsOpen(id, true)
        end
    end
    self:updateJobInfoUI()
end

function GUIJobExtract:onRefreshClick()
    if self.isRefresh == false then
        return
    end
    PayHelper.checkMoney(MoneyType.Diamonds, self.refreshPrice, function(isSuccess)
        if isSuccess then
            self.isRefresh = false
            self:RefreshJobList()
        else
            self.isRefresh = true
        end
    end)
end

function GUIJobExtract:RefreshJobList()
    self.jobsPond = {}
    self.have_index = {}
    self.times = 1
    GamePacketSender:sendRefreshJobList(self.refreshPrice)
end

function GUIJobExtract:onUpdateJobData(data)
    HostApi.log("onUpdateJobListData!!!!!!!!!!!!!!!!!!")
    self.isRefresh = true
    self.refreshPrice = tonumber(data.refreshPrice)
    self.prices = data.price
    local jobs = data.allJobs

    for _, v in pairs(jobs) do
        table.insert(self.jobsPond, JobConfig:changeJobIsOpen(v.id, v.isOpen))
    end
    self:onShow(true)
    self:upRefreshPriceText()
end

function GUIJobExtract:getPrice()
    local price = StringUtil.split(self.prices, "#")
    self.cur_prices = tonumber(price[self.times])
end

function GUIJobExtract:extractRandomJob()
    PayHelper.checkMoney(MoneyType.Diamonds, self.cur_prices, function(isSuccess)
        if isSuccess then
            GamePacketSender:sendExtractRandomJobId(self.cur_prices)
        else
            self.isCardOpen = true
        end
    end)
end

return GUIJobExtract


