---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by JY-032.
--- DateTime: 2019/10/14 22:04
---
require "ui.window.GUIJobChoiceItem"
require "ui.window.GUIJobGoods"
require "packet.GamePacketSender"
require "config.JobConfig"
require "config.Define"

local GUIJobChoice = class("UIJobChoice", IGUILayout)

function GUIJobChoice:onLoad()
    self.id = nil       --当前点中职业的id
    self.last_id = 0    --记录上一次选中的id
    self.cur_select_id = 0       --当前选择的职业
    self.last_select_id = 0      --上一次选择的职业id

    self.gridViewItems = {}
    self.goods = {}
    self:getChildWindow("SkyWarLuckyBlock-Title-Text"):SetText(Lang:getString("lucky.sky.jobChoice.tile"))

    self.btnExit = self:getChildWindow("SkyWarLuckyBlock-Exit-Button", GUIType.Button)
    self.btnExit:registerEvent(GUIEvent.ButtonClick, function()
        SoundUtil.clickUI()
        self:hide()
    end)
    self.icon = self:getChildWindow("SkyWarLuckyBlock-Job-Icon", GUIType.StaticImage)
    self.tvName = self:getChildWindow("SkyWarLuckyBlock-Job-Name", GUIType.StaticText)
    self.desc = self:getChildWindow("SkyWarLuckyBlock-Job-Desc", GUIType.StaticText)

    self.goods_panels = self:getChildWindow("SkyWarLuckyBlock-Job-Goods", GUIType.Layout)
    self.goods_GridView = IGUIGridView.new("SkyWarLuckyJobExtract-Job-GoodsList", self.goods_panels)
    self.goods_GridView:setArea({ 0, 0 }, { 0, 0 }, { 1, 0 }, { 1, 0 })
    self.goods_GridView:setConfig(0, 0, 3)

    self.job_times = self:getChildWindow("SkyWarLuckyBlock-Job-Times", GUIType.StaticText)

    self.btnSelect = self:getChildWindow("SkyWarLuckyBlock-Select-Button", GUIType.Button)
    self.btnHasSelect = self:getChildWindow("SkyWarLuckyBlock-Has-Select-Button", GUIType.Button)
    self.btnHasSelect:SetText(Lang:getString("lucky.sky.has.Choice.button"))
    self.btnHasSelect:SetVisible(false)
    self.btnSelect:SetText(Lang:getString("lucky.sky.Choice.button"))
    local jobs_panels = self:getChildWindow("SkyWarLuckyBlock-Panels")
    self.job_GridView = IGUIGridView.new("SkyWarLuckyBlock-Panels-Items", jobs_panels)
    self.job_GridView:setArea({ 0, 0 }, { 0, 0 }, { 1, 0 }, { 1, 0 })
    self.job_GridView:setConfig(0, 0, 4)

    self.btnSelect:registerEvent(GUIEvent.ButtonClick, function()
        self:onSelectJobClick()
    end)

    self:registerDataCallBack("UpdateJobs", function(data)
        self:onJobUpdate(data)
    end, JsonBuilderProcessor)

    self:registerDataCallBack("CurJobId", function(data)
        self:onCurJobId(data)
    end, DataBuilderProcessor)

    self:registerDataCallBack("OpenUIData", function(data)
        self:openUIData(data)
    end, DataBuilderProcessor)
end

function GUIJobChoice:openUIData(data)
    local type = data:getNumberParam("type")
    if type == Define.UIType.Job_Store then
        self:show()
    end
end

function GUIJobChoice:onTick(frameTime)
    local items = self.job_GridView.items
    for _, item in pairs(items) do
        item:onTick(frameTime)
    end
end

function GUIJobChoice:onShow(needLoad)
    if needLoad == nil then
        needLoad = true
    end
    if not needLoad and self.job_GridView:getItemCount() > 0 then
        return
    end
    --local items = JobConfig.getJobLists()
    local items = JobConfig:getAllJobList()
    if not items then
        return
    end
    self.job_GridView:clearItems()
    local contentWidth = self.job_GridView:getWidth()
    local contentHeight = self.job_GridView:getHeight()
    local itemWidth = contentWidth / 4
    local itemHeight = itemWidth * 1.4756
    local i = 1
    for _, item in pairs(items) do
        local Item = GUIJobChoiceItem.new("SkyWarLuckySelectItem.json")
        self.gridViewItems[i] = Item
        Item:setWidth({ 0, itemWidth })
        Item:setHeight({ 0, itemHeight })
        Item:setItemData(item)
        self.job_GridView:addItem(Item)
        i = i + 1
    end
    self:changeSelectJob()
    self:onJobsInfoUpdate(self.cur_select_id)
    self:updateGoods()
end

--Update the right class information
function GUIJobChoice:onJobsInfoUpdate(id)
    self:changeSelectItem(id)

    self.id = id
    local item = JobConfig:getJobById(id)
    if item == nil then
        item = JobConfig:getDefaultJob()
        self.goods = JobConfig:getGoodsIdByJobId(item.id)
    else
        self.goods = JobConfig:getGoodsIdByJobId(id)
    end
    if item.type == Define.JobType.DefaultJob then
        self.btnSelect:SetEnabled(true)
        self.job_times:SetText(Lang:getString("lucky.sky.job.free"))
    else
        self.job_times:SetText(string.format(Lang:getString("lucky.sky.remain.times"), item.times))
        if item.times > 0 then
            self.btnSelect:SetEnabled(true)
        else
            self.btnSelect:SetEnabled(false)
        end
    end
    self.icon:SetImage(item.icon)
    self.tvName:SetText(Lang:getString(item.name))
    self.desc:SetText(Lang:getString(item.describe))
    self:changeSelectButton()
    self:updateGoods()
end

--Current career choice
function GUIJobChoice:onCurJobId(data)
    self.cur_select_id = data:getNumberParam("id")
    self:changeSelectJob()
    self:onJobsInfoUpdate(self.cur_select_id)
end

--Select career button
function GUIJobChoice:onSelectJobClick()
    self.cur_select_id = self.id
    GamePacketSender:sendSelectJobId(self.id)
    self:changeSelectJob()
    self:changeSelectButton()
end

function GUIJobChoice:onJobUpdate(data)
    for i, v in pairs(data) do
        JobConfig:updateStatus(v.id, v.times)
    end
end

--Selected button
function GUIJobChoice:changeSelectButton()
    if self.cur_select_id == self.id then
        self.btnSelect:SetVisible(false)
        self.btnHasSelect:SetVisible(true)
    else
        self.btnHasSelect:SetVisible(false)
        self.btnSelect:SetVisible(true)
    end
end

function GUIJobChoice:changeSelectItem(id)
    for _, item in pairs(self.gridViewItems) do
        if item.id == self.last_id then
            item:changeSelectStatus(ItemsSelectStatus.NotSelect)
        end

        if item.id == id then
            item:changeSelectStatus(ItemsSelectStatus.Select)
        end
    end
    self.last_id = id
end

--The currently selected occupation is highlighted in a frame diagram
function GUIJobChoice:changeSelectJob()
    for _, item in pairs(self.gridViewItems) do
        if item.id == self.last_select_id then
            item:changeCurSelectJob(CurSelectJob.No_Select_Job)
        end

        if item.id == self.cur_select_id then
            item:changeCurSelectJob(CurSelectJob.Have_Select_Job)
        end
    end
    self.last_select_id = self.cur_select_id
end

function GUIJobChoice:updateGoods()
    self.goods_GridView:clearItems()
    local contentWidth = self.goods_GridView:getWidth()
    local contentHeight = self.goods_GridView:getHeight()
    local itemWidth = (contentWidth) / 3
    local itemHeight = contentHeight / 3
    for i = 1, 9 do
        local Item = GUIJobGoods.new("GoodsSlot.json")
        Item:setWidth({ 0, itemWidth })
        Item:setHeight({ 0, itemHeight })
        Item:setItemData(self.goods[i] or 0)
        self.goods_GridView:addItem(Item)
    end
end

return GUIJobChoice