---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/12/21 15:16
---

require "ui.window.GUIRankItem"
require "config.Define"

local GUISeasonRank = class("", IGUILayout)

function GUISeasonRank:onLoad()
    self.curRank = 0
    self.seasonTime = 0

    --List
    self.ltUpgradeList = self:getChildWindow("LuckySkyHallSeasonRank-Upgrade-List", GUIType.List)
    self.ltUpgradeList:SetInterval(5)
    self.ltStriveList = self:getChildWindow("LuckySkyHallSeasonRank-Strive-List", GUIType.List)
    self.ltStriveList:SetInterval(5)

    --StaticImage
    self.ivNextRankIcon = self:getChildWindow("LuckySkyHallSeasonRank-Rank-Icon", GUIType.StaticImage)
    self.ivNextRankFlag = self:getChildWindow("LuckySkyHallSeasonRank-Rank-Flag", GUIType.StaticImage)

    --StaticText
    self.tvNextRankName = self:getChildWindow("LuckySkyHallSeasonRank-Rank-Name", GUIType.StaticText)
    self.tvSeasonTime = self:getChildWindow("LuckySkyHallSeasonRank-Season-Time-Text", GUIType.StaticText)
    self.tvUpgradeScore = self:getChildWindow("LuckySkyHallSeasonRank-Upgrade-Score", GUIType.StaticText)
    self.tvStriveScore = self:getChildWindow("LuckySkyHallSeasonRank-Strive-Score", GUIType.StaticText)

    --Button
    self:getChildWindow("LuckySkyHallSeasonRank-Close", GUIType.Button):registerEvent(GUIEvent.ButtonClick, function()
        self:hide()
    end)

    self:getChildWindow("LuckySkyHallSeasonRank-Rule-Icon", GUIType.StaticImage):registerEvent(GUIEvent.Click, function()
        GUIRankRule:show()
    end)

    self:getChildWindow("LuckySkyHallSeasonRank-Title-Text", GUIType.StaticText):SetText(Lang:getString("lucky.sky.rank.title.text"))
    self:getChildWindow("LuckySkyHallSeasonRank-Upgrade-Title-Text", GUIType.StaticText):SetText(Lang:getString("lucky.sky.rank.upgrade.title.text"))
    self:getChildWindow("LuckySkyHallSeasonRank-Strive-Title-Text", GUIType.StaticText):SetText(Lang:getString("lucky.sky.rank.strive.title.text"))
    self:getChildWindow("LuckySkyHallSeasonRank-Upgrade-Tip-Text", GUIType.StaticText):SetText(Lang:getString("lucky.sky.rank.upgrade.tip.text"))
    self:getChildWindow("LuckySkyHallSeasonRank-Strive-Tip-Text", GUIType.StaticText):SetText(Lang:getString("lucky.sky.rank.strive.tip.text"))

    self:registerDataCallBack("CurrentSeasonInfo", function(data)
        self:initSeasonRank(data)
    end, DataBuilderProcessor)

    self:registerDataCallBack("OpenUIData", function(data)
        self:openUIData(data)
    end, DataBuilderProcessor)
end

function GUISeasonRank:openUIData(data)
    local type = data:getNumberParam("type")
    if type == Define.UIType.Rank then
        self:show()
    end
end

function GUISeasonRank:initSeasonRank(data)
    local honorId = data:getNumberParam("honorId")
    local rank = data:getNumberParam("rank")
    local days = data:getNumberParam("days")

    local curSeason = SeasonConfig:getSeasonByHonorId(honorId)
    if not curSeason then
        return
    end
    self.curRank = rank
    local nextSeason = SeasonConfig:getSeasonByHonorId(honorId + 1) or curSeason

    local pageSize = 50
    local pageNo = math.floor(rank / pageSize)

    if honorId == nextSeason.honorId and pageNo == 0 then
        pageNo = 1
    end

    self:getSeasonRank(Define.RankType.STRIVE, pageNo, pageSize, function(info, code)
        self:updateSeasonRank(Define.RankType.STRIVE, info, code)
    end)

    self:getSeasonRank(Define.RankType.UPGRADE, 0, pageSize, function(info, code)
        self:updateSeasonRank(Define.RankType.UPGRADE, info, code)
    end)

    self.ivNextRankIcon:SetImage(curSeason.icon)
    self.ivNextRankFlag:SetImage(curSeason.flag)
    self.tvNextRankName:SetText(Lang:getString(curSeason.honorName))
    self.tvUpgradeScore:SetText(nextSeason.defaultScore .. "+")
    self.tvStriveScore:SetText(curSeason.defaultScore .. "+")
    self:setTime(days)
end

function GUISeasonRank:setTime(days)
    self.tvSeasonTime:SetText(string.format(Lang:getString("lucky.sky.rank.time.text"), days))
end

function GUISeasonRank:getSeasonRank(highRank, pageNo, pageSize, callback)
    local params = {
        { "userId", tostring(CGame.Instance():getPlatformUserId()) },
        { "gameId", BaseMain:getGameType() },
        { "highRank", highRank },
        { "pageNo", pageNo },
        { "pageSize", pageSize }
    }
    WebService.asyncGet("/gameaide/api/v1/segment/integral/rank", params, callback)
end

function GUISeasonRank:updateSeasonRank(type, info, code)
    if code == 1 then
        if info then
            if type == Define.RankType.UPGRADE then
                self:initRankList(self.ltUpgradeList, info, false)
            else
                self:initRankList(self.ltStriveList, info, true)
            end
        end
    end
end

function GUISeasonRank:initRankList(list, data, isStrive)
    list:ClearAllItem()
    for _, item in pairs(data) do
        local llItem = GUIRankItem.new("LuckySkyHallRankItem.json")
        list:AddItem(llItem.root)
        llItem:initItem(item, item.rank == self.curRank)
    end
end

return GUISeasonRank