---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Yanzhuolin.
--- DateTime: 2019/11/1 16:34
---

MapManagerCreateEvent = IScriptEvent.new()
CommonDataEvents:registerEvent("MapManagerCreate", MapManagerCreateEvent)

MonsterCreateEvent = IScriptEvent.new()
CommonDataEvents:registerEvent("MonsterCreate", MonsterCreateEvent)

MonsterDeadEvent = IScriptEvent.new()
CommonDataEvents:registerEvent("MonsterDead", MonsterDeadEvent)

TowerCreateEvent = IScriptEvent.new()
CommonDataEvents:registerEvent("TowerCreate", TowerCreateEvent)

TowerDeadEvent = IScriptEvent.new()
CommonDataEvents:registerEvent("TowerDead", TowerDeadEvent)

MapManagerDestroyEvent = IScriptEvent.new()
CommonDataEvents:registerEvent("MapManagerDestroy", MapManagerDestroyEvent)

SetProcessIdEvent = IScriptEvent.new()
CommonDataEvents:registerEvent("ProcessId", SetProcessIdEvent)

SetCanPlaceBlockIdEvent = IScriptEvent.new()
CommonDataEvents:registerEvent("CanPlaceBlockId", SetCanPlaceBlockIdEvent)

UsePropsEvent = IScriptEvent.new()
CommonDataEvents:registerEvent("UseProps", UsePropsEvent)

CreateBoxEvent = IScriptEvent.new()
CommonDataEvents:registerEvent("CreateBox", CreateBoxEvent, DataBuilderProcessor)

TowerAttackEvent = IScriptEvent.new()
CommonDataEvents:registerEvent("TowerAttack", TowerAttackEvent, DataBuilderProcessor)

TowerEjectionsEvent = IScriptEvent.new()
CommonDataEvents:registerEvent("TowerEjections", TowerEjectionsEvent, DataBuilderProcessor)

SynHpEvent = IScriptEvent.new()
CommonDataEvents:registerEvent("SynHp", SynHpEvent, DataBuilderProcessor)