#多少级可以点赞
giveLoveNumLevel: 5

#一次金魔方数量
onceBuyMoneyCost: 60

#最大数量：
maxBuyMoneyCost: 600

#一次购买的金币数量
onceMoneyNum: 100000

#圣诞活动结束时间戳
christmasFinishTime: 4102470000

#圣诞活动结束时间是否显示1显示 0不显示
isShowChristmasTime: 0

#辉光设置[阈值,饱和度,强度]
lightConfig: [0, 0.6, 2]

#辉光使用的高斯模糊的方差。影响辉光亮度与广度
bloomBlurDeviation: 7

#辉光使用的高斯模糊核的总和。影响辉光亮度
bloomBlurMultiplier: 0.8

#增强带颜色方块光的幅度
blockLightEnhancement: 1