---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jimmy.
--- DateTime: 2018/10/23 0023 11:32
---
MonsterConfig = {}
MonsterConfig.Config = {}

function MonsterConfig:init(config)
    for _, car in pairs(config) do
        local item = {}
        item.Id = tonumber(car.Id)
        item.Actor = car.Actor
        item.Name = car.Name
        item.Speed = tonumber(car.Speed)
        item.AddSpeed = tonumber(car.AddSpeed)
        item.Des = car.Des
        item.Hp = tonumber(car.Hp)
        item.Defense = tonumber(car.Defense)
        item.immunityBuffClasses = StringUtil.split(car.immunityBuffClasses,"#")
        item.isTaunt = tonumber(car.IsTaunt) or 0
        item.skills = StringUtil.split(car.skills,"#")
        item.IconIds = StringUtil.split(car.IconIds or "","#")
        self.Config[item.Id] = item
    end
end

function MonsterConfig:getConfigById(id)
    return self.Config[id]
end

MonsterConfig:init(FileUtil.getConfigFromCsv("setting/Monster.csv"))