---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangpq.
--- DateTime: 2019/11/26 17:50
---
LogUtil = {}

LogUtil.LogLevel =
{
    ["Debug"] = 100,
    ["Info"] = 300,
    ["Warning"] = 500,
    ["Error"] = 800,
    ["Fatal"] = 1000,
}

LogUtil.disableList = {}
for k, v in pairs(LogUtil.LogLevel) do
    LogUtil.disableList[v] = false
end

LogUtil.isDebug = false
LogUtil.highestLevel = LogUtil.LogLevel.Debug

local function getPrefix(level)
    if level == LogUtil.LogLevel.Debug then
        return "Debug"
    elseif level == LogUtil.LogLevel.Info then
        return "Info"
    elseif level == LogUtil.LogLevel.Warning then
        return "Warning"
    elseif level == LogUtil.LogLevel.Error then
        return "Error"
    elseif level == LogUtil.LogLevel.Fatal then
        return "Fatal"
    end
end

function LogUtil.log(msg, level)
    level = level or LogUtil.LogLevel.Debug

    if level <= LogUtil.LogLevel.Debug and not LogUtil.isDebug then
        return
    end

    if level < LogUtil.highestLevel then
        return
    end

    if LogUtil.disableList[level] then
        return
    end

    HostApi.log(string.format("[%s] %s", getPrefix(level), msg))
end

function LogUtil.setHighest(level)
    LogUtil.highestLevel = level
end

function LogUtil.setDebug(debug)
    LogUtil.isDebug = debug
end

function LogUtil.disable(level)
    LogUtil.disableList[level] = true
end

function LogUtil.enable(level)
    LogUtil.disableList[level] = false
end

function LogUtil.disableAll()
    for k, v in pairs(LogUtil.disableList) do
        LogUtil.disableList[k] = true
    end
    HostApi.log("LogUtil.disableAll " .. inspect.inspect(LogUtil.disableList))
end

function LogUtil.enableAll()
    for k, v in pairs(LogUtil.disableList) do
        LogUtil.disableList[k] = false
    end
    HostApi.log("LogUtil.enableAll " .. inspect.inspect(LogUtil.disableList))
end

return LogUtil