---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangpq.
--- DateTime: 2019/6/10 20:16
---
MathUtil = {}
MathUtil.DEG2RAD = 0.01745329
MathUtil.RAD2DEG = 57.29577

--随机n个[low,high]范围的整数
function MathUtil:randomIntRepeat(low, high, n)
    local result = {}
    for i = 1, n do
        table.insert(result, math.random(low, high))
    end
    return result
end

function MathUtil:createTable(low, high)
    local result = {}
    for i = low, high do
        table.insert(result, i)
    end
    return result
end

--随机n个[low,high]范围的不重复的整数
function MathUtil:randomIntNoRepeat(low, high, n)
    local size = high - low + 1
    if n > size then
        return nil
    end

    local tb = MathUtil:createTable(low, high)

    local result = {}
    for i = 1, n do
        local index = math.random(#tb)
        tb[index], tb[#tb] = tb[#tb], tb[index]
        table.insert(result, tb[#tb])
        table.remove(tb)
    end
    return result
end

--在矩形范围内随机count个不重复的点
function MathUtil:randomInRect(minX, maxX, minZ, maxZ, count)
    local result = {}

    if (maxX - minX + 1) * (maxZ - minZ + 1) < count then
        return result
    end

    local index = 1
    while(index <= count)
    do
        local randomX = math.random(minX, maxX)
        local randomZ = math.random(minZ, maxZ)
        local pt = PointUtil:newPoint(randomX, randomZ)
        if PointUtil:isTableHavePoint(result, pt) == false then
            table.insert(result, pt)
            index = index + 1
        end
    end

    return result
end

--在矩形范围内随机count个不重复的可站立点
function MathUtil:randomInRectCanStand(pos, radius, count)
    --
end

--在圆内随机一个点
function MathUtil:randomInCircle(pos, radius)
    local resultX = math.random(-radius, radius)
    local resultY = math.sqrt(math.pow(radius, 2) - math.pow(resultX, 2))
    resultY = math.random(-resultY, resultY)
    return VectorUtil.newVector3(resultX + pos.x, pos.y, resultY + pos.z)
end

--3d点距离的平方
function MathUtil:distanceSquare3d(pos1, pos2)
    local result = math.pow((pos1.x - pos2.x), 2) + math.pow((pos1.y - pos2.y), 2) + math.pow((pos1.z - pos2.z), 2)
    return result
end

--检测是否在距离内
function MathUtil:checkDisLessThan(pos1, pos2, dis)
    return MathUtil:distanceSquare3d(pos1, pos2) < math.pow(dis, 2)
end

return MathUtil