---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangpq.
--- DateTime: 2019/10/10 11:58
---
local UIWorkout = class("UIWorkout", IGUILayout)

local totalShowTime = 1200
UIWorkout.WorkoutTip = { {}, {}, {}, {}, {} }
UIWorkout.GoldTip = { {}, {} }
function UIWorkout:onLoad()

    self:initUI()

    MuscleMassChangeEvent:registerCallBack(function(muscleMass, maxMuscleMass, inc)
        self:onMuscleMassChange(muscleMass, maxMuscleMass, inc)
    end)

    self.isFirstChange = true
    self.beforeGoldNum = 0
    self:initGoldUI()

    GoldChangeEvent:registerCallBack(function (bigNum)
        --print("++++++++++++++++++++")
        self:onGoldChange(bigNum)
    end)

end

function UIWorkout:initUI()
    for i = 1, 5 do
        self.WorkoutTip[i].Region = self:getChildWindow("LiftingSimulatorWorkout-IconRegion_" .. i, GUIType.Layout)
        self.WorkoutTip[i].Icon = self:getChildWindow("LiftingSimulatorWorkout-Icon_" .. i, GUIType.Layout)
        self.WorkoutTip[i].Value = self:getChildWindow("LiftingSimulatorWorkout-Value_" .. i, GUIType.StaticText)
        self.WorkoutTip[i].Image = self:getChildWindow("LiftingSimulatorWorkout-Image_" .. i, GUIType.StaticImage)
    end

    self:initQueue()
end

function UIWorkout:initGoldUI()

    self.GoldTip[1].Region = self:getChildWindow("LiftingSimulatorWorkout-IconRegion_30", GUIType.Layout)
    self.GoldTip[1].Icon = self:getChildWindow("LiftingSimulatorWorkout-Icon_30", GUIType.Layout)
    self.GoldTip[1].Value = self:getChildWindow("LiftingSimulatorWorkout-Value_30", GUIType.StaticText)

    self.GoldTip[2].Region = self:getChildWindow("LiftingSimulatorWorkout-IconRegion_40", GUIType.Layout)
    self.GoldTip[2].Icon = self:getChildWindow("LiftingSimulatorWorkout-Icon_40", GUIType.Layout)
    self.GoldTip[2].Value = self:getChildWindow("LiftingSimulatorWorkout-Value_40", GUIType.StaticText)

    for i, tip in pairs(self.GoldTip) do
        tip.showTime  = 0
        tip.isShowing = false
        tip.scaleX = 0
        tip.scaleY = 0
        tip.Icon:SetVisible(false)
    end

end

function UIWorkout:onTick(frameTime)
    self:updateTipQueue(frameTime)
    self:updateGoldTipQueue(frameTime)
end

function UIWorkout:updateGoldTipQueue(frameTime)
    for i, tip in pairs(self.GoldTip) do

        if tip.isShowing == true and tip.showTime + frameTime > totalShowTime  then
            tip.isShowing = false
            tip.showTime = 0
            tip.Icon:SetVisible(false)
        elseif tip.isShowing == true then
            tip.showTime = tip.showTime + frameTime
            if tip.showTime < 200 then
                self:updateWorkoutIcon(tip)
            elseif tip.showTime > 270 then
                self:stressWorkoutIcon(tip)
            end
        end

    end
end

function UIWorkout:addNewGoldTip(gold , isPositive)


    for i, tip in pairs(self.GoldTip) do
        if tip.isShowing == false then
            self:showGoldIcon(tip,gold,isPositive)
            return
        end
    end
    if self.GoldTip[1].showTime > self.GoldTip[2].showTime then
        self:showGoldIcon(self.GoldTip[1], gold, isPositive)
    else
        self:showGoldIcon(self.GoldTip[2], gold, isPositive)
    end

end

function UIWorkout:showGoldIcon(tip,gold,isPositive)

    tip.isShowing = true
    tip.showTime = 0
    if Game:isChina() then
        if isPositive then
            tip.Value:SetText("+" .. Utility.toKMBString(tostring(gold), 2) .. " 金币")
        else
            tip.Value:SetText("-" .. Utility.toKMBString(tostring(gold), 2) .. " 金币")
        end
    else
        if isPositive then
            tip.Value:SetText("+" .. Utility.toKMBString(tostring(gold), 2) .. " Gold")
        else
            tip.Value:SetText("-" .. Utility.toKMBString(tostring(gold), 2) .. " Gold")
        end
    end

    local width = 100 + string.len(Utility.toKMBString(tostring(gold),2))*10
    tip.Value:SetWidth({0, width})
    tip.Value:SetBackgroundColor({ 0, 0, 0, 0 })
    tip.Value:SetTextBoader({ 0.278, 0.145, 0.078, 1 })
    tip.Value:SetTextColor({ 0.965, 0.992, 0.204, 1 })

    local area = tip.Region:GetArea()
    local minX = tonumber(area.min.x[1])
    local maxX = tonumber(area.max.x[1])
    local minY = tonumber(area.min.y[1])
    local maxY = tonumber(area.max.y[1])
    local scale = 10000

    tip.scaleX = math.random(math.floor(minX * scale), math.floor(maxX * scale)) / scale + 0.05
    tip.scaleY = math.random(math.floor(minY * scale), math.floor(maxY * scale)) / scale + 0.6

    tip.Icon:SetXPosition({ tip.scaleX, 0 })
    tip.Icon:SetYPosition({ tip.scaleY, 0 })
    tip.Icon:SetVisible(true)

end

function UIWorkout:showWorkoutIcon(tip, index, visible)
    if visible then
        local area = self.WorkoutTip[index].Region:GetArea()
        local minX = tonumber(area.min.x[1])
        local maxX = tonumber(area.max.x[1])
        local minY = tonumber(area.min.y[1])
        local maxY = tonumber(area.max.y[1])
        local scale = 10000

        tip.scaleX = math.random(math.floor(minX * scale), math.floor(maxX * scale)) / scale + 0.05
        tip.scaleY = math.random(math.floor(minY * scale), math.floor(maxY * scale)) / scale + 0.6

        tip.Icon:SetXPosition({ tip.scaleX, 0 })
        tip.Icon:SetYPosition({ tip.scaleY, 0 })

    end
    tip.Icon:SetVisible(visible)
end

function UIWorkout:updateWorkoutIcon(tip)
    tip.scaleX = tip.scaleX - 0.0025
    tip.scaleY = tip.scaleY - 0.03
    tip.Icon:SetXPosition({ tip.scaleX, 0 })
    tip.Icon:SetYPosition({ tip.scaleY, 0 })
end

function UIWorkout:stressWorkoutIcon(tip)
    tip.Icon:SetXPosition({ tip.scaleX + 0.05, 0 })
    tip.Icon:SetYPosition({ tip.scaleY + 0.05, 0 })
end

function UIWorkout:onMuscleMassChange(muscleMass, maxMuscleMass, inc)
    if not self:isLoad() then
        return
    end

    --HostApi.log(string.format("UIWorkout:onMuscleMassChange %f %f %f", muscleMass, maxMuscleMass, inc))

    if inc > 0 then
        self:addNewTip(inc)
    end
end

function UIWorkout:onGoldChange(bigNum)

    if self.isFirstChange then
        self.isFirstChange = false
        self.beforeGoldNum = bigNum
        return
    end

    --print("///////////////////////////")
    if self.beforeGoldNum > bigNum then
        local gold = self.beforeGoldNum - bigNum
        self.beforeGoldNum = bigNum
        --self:addNewGoldTip(tostring(gold) , false)
    elseif self.beforeGoldNum < bigNum then
        local gold = bigNum - self.beforeGoldNum
        self.beforeGoldNum = bigNum
        self:addNewGoldTip(tostring(gold) , true)
    end



end

function UIWorkout:initQueue()
    for i, tip in pairs(self.WorkoutTip) do
        tip.showTime = 0
        tip.isShowing = false
        tip.scaleX = 0
        tip.scaleY = 0
        self:showWorkoutIcon(tip, i, false)
    end
end

function UIWorkout:updateTipQueue(frameTime)
    for i, tip in pairs(self.WorkoutTip) do
        if tip.isShowing == true and tip.showTime + frameTime > totalShowTime then
            tip.isShowing = false
            self:showWorkoutIcon(tip, i, false)
        elseif tip.isShowing == true then
            tip.showTime = tip.showTime + frameTime
            if tip.showTime < 200 then
                self:updateWorkoutIcon(tip)
            elseif tip.showTime > 270 then
                self:stressWorkoutIcon(tip)
            end
        end
    end
end

function UIWorkout:addNewTip(inc)
    local busyCount = 0
    for _, tip in pairs(self.WorkoutTip) do
        if tip.isShowing then
            busyCount = busyCount + 1
        end
    end

    for i, tip in pairs(self.WorkoutTip) do
        if tip.isShowing == false then
            self:initTip(tip, i, inc, busyCount >= 2)
            return
        end
    end

    local showTimeMax = 0
    local index = 1
    for i, tip in pairs(self.WorkoutTip) do
        if tip.showTime > showTimeMax then
            showTimeMax = tip.showTime
            index = i
        end
    end

    self:initTip(self.WorkoutTip[index], index, inc, busyCount >= 2)
end

function UIWorkout:initTip(tip, index, inc, hot)
    hot = hot or false
    tip.isShowing = true
    tip.showTime = 0
    if Game:isChina() then
        tip.Value:SetText("+" .. Utility.toKMBString(tostring(inc), 2) .. " 肌肉值")
    else
        tip.Value:SetText("+" .. Utility.toKMBString(tostring(inc), 2) .. " Muscle")
    end
    local width = 100 + string.len(Utility.toKMBString(tostring(inc),2))*10
    tip.Value:SetWidth({0, width})
    tip.Value:SetBackgroundColor({ 0, 0, 0, 0 })
    tip.Value:SetTextBoader({ 0.278, 0.145, 0.078, 1 })
    tip.Value:SetTextColor({ 0.965, 0.992, 0.204, 1 })
    if hot then
        tip.Image:SetArea({ 0, 0 }, { 0, 0 }, { 0, 121 }, { 0, 117 })
        tip.Image:SetImage("set:LiftingSimulatorMainControl1.json image:workout5")
    else
        tip.Image:SetArea({ 0, 0 }, { 0, 0 }, { 0, 80 }, { 0, 68 })
        tip.Image:SetImage("set:LiftingSimulatorMainControl1.json image:workout")
    end
    self:showWorkoutIcon(tip, index, true)
end

return UIWorkout