---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jimmy.
--- DateTime: 2019/9/3 0003 10:01
---
require "listener.GameListener"

PluginMain = {}

function PluginMain:init()
    GameListener:init()
    ClientHelper.putBoolPrefs("IsGunAction", false)
    ClientHelper.putBoolPrefs("IsGunNorAttack", false)
    ClientHelper.putBoolPrefs("IsLoadSeason", true)
    ClientHelper.putBoolPrefs("IsShowGetGoodsBg", false)
    ClientHelper.putBoolPrefs("IsShowTeamUI", false)
    ClientHelper.putBoolPrefs("IsRedAimBlock", false)
    ClientHelper.putBoolPrefs("IsRedAim", false)
end

PluginMain:init()

return PluginMain