---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jimmy.
--- DateTime: 2019/10/9 0009 9:50
---

require "common.ui.RadioBoxGroup"
require "game.ui.window.GUINumberItem"
require "game.ui.window.GUIHeadIcon"
require "common.ui.layout.GUIWatchADTip"

GUIImagesetManager.Instance():CreateFromFile("bed_war_player_inventory.json")
if GameConfig.useNewLottery == 1 then
    local UILottery = require "game.ui.layout.GUIBedWarLottery"
    GUILottery = UILottery.new("BedWarLottery.json")
    GUILottery:hide()
else
    local UILottery = require "game.ui.layout.GUIBedWarLottery2"
    GUILottery = UILottery.new("BedWarLottery2.json")
    GUILottery:hide()
end

local UILotteryDetailWindow = require "game.ui.layout.GUILotteryDetail"
GUILotteryDetailWindow = UILotteryDetailWindow.new("LotteryDetailWindow.json")
GUILotteryDetailWindow:hide()

local UIMain = require "game.ui.layout.GUIMain"
GUIMain = UIMain.new("BedWarGameMain.json", GUIManager:getMainControl())
GUIMain:show()

local UISettlementSingle = require "game.ui.layout.GUISettlementSingle"
GUISettlementSingle = UISettlementSingle.new("SettlementSingle.json")
GUISettlementSingle:hide()

local UIBedWarToolBar = require "common.ui.layout.GUIBedWarToolBar"
GUIBedWarToolBar = UIBedWarToolBar.new("BedWarToolBar.json", GUIManager:getMainControl())
GUIBedWarToolBar:show()

local UIBedWarMenu = require "game.ui.layout.GUIBedWarMenu"
GUIBedWarMenu = UIBedWarMenu.new("Menu")

local UIAction = require "common.ui.layout.GUIAction"
GUIAction = UIAction.new("BedWarActionList.json")
GUIAction:hide()

--local UIBattleInfo = require "game.ui.layout.GUIBattleInfo"
--GUIBattleInfo = UIBattleInfo.new("BedWarBattleInfo.json")
--GUIBattleInfo:hide()

local UIResult = require "game.ui.layout.GUIResult"
GUIResult = UIResult.new("Result.json")
GUIResult:hide()

local UIResult8P = require "game.ui.layout.GUIResult8P"
GUIResult8P = UIResult8P.new("Result8P.json")
GUIResult8P:hide()

local UIPlayerInfo = require "common.ui.layout.GUIPlayerInfo"
GUIPlayerInfo = UIPlayerInfo.new("BedWarPlayerInfo.json", GUIManager:getPlayerInfo())
GUIPlayerInfo:show()

local UICommandList = require "game.ui.layout.GUICommandList"
GUICommandList = UICommandList.new("BedWarCommandList.json")
GUICommandList:hide()

local UICommandBuy = require "game.ui.layout.GUICommandBuy"
GUICommandBuy = UICommandBuy.new("BedWarCommandBuy.json")
GUICommandBuy:hide()

local UIBoxLottery = require "common.ui.layout.GUIBoxLottery"
GUIBoxLottery = UIBoxLottery.new("BoxLottery.json")
GUIBoxLottery:hide()

local UIBoxDetail = require "common.ui.layout.GUIBoxDetail"
GUIBoxDetail = UIBoxDetail.new("LotteryBoxDetail.json")
GUIBoxDetail:hide()

local UIBoxRewardResult = require "common.ui.layout.GUIBoxRewardResult"
GUIBoxRewardResult = UIBoxRewardResult.new("BoxRewardResult.json")
GUIBoxRewardResult:hide()

local UIBoxRewardDetail = require "common.ui.layout.GUIBoxRewardDetail"
GUIBoxRewardDetail = UIBoxRewardDetail.new("BoxRewardDetail.json")
GUIBoxRewardDetail:hide()

local UITreasureChallenge = require "common.ui.layout.GUITreasureChallenge"
GUITreasureChallenge = UITreasureChallenge.new("TreasureChallenge.json")
GUITreasureChallenge:hide()

local UIChallengeTask = require "common.ui.layout.GUIChallengeTask"
GUIChallengeTask = UIChallengeTask.new("ChallengeTask.json")
GUIChallengeTask:hide()

local UIGameTips = require "common.ui.layout.GUIBedWarGameTip"
GUIBedWarGameTips = UIGameTips.new("BedWarGameTips.json", GUIManager:getMainControl())
GUIBedWarGameTips:show()

local UIBedWarSetting = require "common.ui.layout.GUIBedWarSetting"
GUIBedWarSetting = UIBedWarSetting.new("BedWarSetting.json")
GUIBedWarSetting:hide()

local UIPlayerInventory = require "common.ui.layout.GUIPlayerInventory"
GUIPlayerInventory = UIPlayerInventory.new("PlayerInventory")

local UIArmorPanel = require "common.ui.layout.GUIArmorPanel"
GUIArmorPanel = UIArmorPanel.new("ArmorPanel")

local UIChest = require "game.ui.layout.GUIChest"
GUIChest = UIChest.new("Chest")

local UIChatInput = require "game.ui.layout.GUIChatInput"
GUIChatInput = UIChatInput.new("BedWarChatInput.json")
GUIChatInput:hide()

local UIUpgradeStore = require "game.ui.layout.GUIUpgradeStore"
GUIUpgradeStore = UIUpgradeStore.new("BedWarUpgradeStore.json")
GUIUpgradeStore:hide()

local UICustomShop = require "common.ui.layout.GUICustomShop"
GUICustomShop = UICustomShop.new("BedWarCustomShop.json")
GUICustomShop:hide()

local UIBlockShop = require "common.ui.layout.GUIBlockShop"
GUIBlockShop = UIBlockShop.new("BedWarBlockShop.json")
GUIBlockShop:hide()

local UILevelUp = require "game.ui.layout.GUILevelUp"
GUILevelUp = UILevelUp.new("BedWarLevelUp.json")
GUILevelUp:hide()

local UILicense = require "common.ui.layout.GUILicense"
GUILicense = UILicense.new("BedWarLicense.json")
GUILicense:hide()

local UILicenseGrandPriceDisplay = require "common.ui.layout.GUILicenseGrandPriceDisplay"
GUILicenseGrandPriceDisplay = UILicenseGrandPriceDisplay.new("BedWarLicenseGrandPrice.json")
GUILicenseGrandPriceDisplay:hide()

local UILicenseRewardBuy = require "common.ui.layout.GUILicenseRewardBuy"
GUILicenseRewardBuy = UILicenseRewardBuy.new("BedWarLicenseBuy.json")
GUILicenseRewardBuy:hide()

local UILicenseExchangeNum = require "common.ui.layout.GUILicenseExchangeNum"
GUILicenseExchangeNum = UILicenseExchangeNum.new("BedWarLicenseExchangeNum.json")
GUILicenseExchangeNum:hide()

local UILicenseSeasonTask = require "common.ui.layout.GUILicenseSeasonTask"
GUILicenseSeasonTask = UILicenseSeasonTask.new("BedWarLicenseSeasonTask.json")
GUILicenseSeasonTask:hide()

local UILicenseBuyLevelTip = require "common.ui.layout.GUILicenseBuyLevelTip"
GUILicenseBuyLevelTip = UILicenseBuyLevelTip.new("BedWarLicenseBuyLeveyTip.json")
GUILicenseBuyLevelTip:hide()

local UILicenseGetAllTip = require "common.ui.layout.GUILicenseGetAllTip"
GUILicenseGetAllTip = UILicenseGetAllTip.new("BedWarLicenseGetAllTip.json")
GUILicenseGetAllTip:hide()

local UILicenseTip = require "common.ui.layout.GUILicenseTip"
GUILicenseTip = UILicenseTip.new("BedWarLicenseTip.json")
GUILicenseTip:hide()

local UILicenseBigPrice = require "common.ui.layout.GUILicenseBigPrice"
GUILicenseBigPrice = UILicenseBigPrice.new("BedWarLicenseBigPrice.json")
GUILicenseBigPrice:hide()

local UIStore = require "common.ui.layout.GUIStore"
GUIStore = UIStore.new("BedWarStore.json")
GUIStore:hide()

local UIRewardResult = require "common.ui.layout.GUIRewardResult"
GUIRewardResult = UIRewardResult.new("BedWarRewardResult.json")
GUIRewardResult:setAlwaysOnTop(true)
GUIRewardResult:hide()

--local UIWatchADTip = require "common.ui.layout.GUIWatchADTip"
--GUIWatchADTip = UIWatchADTip.new("BedWarWatchADTip.json")
--GUIWatchADTip:hide()

local UIChallengeRewardReceive = require "common.ui.layout.ChallengeRewardReceive"
GUIChallengeRewardReceive = UIChallengeRewardReceive.new("ChallengeRewardReceive.json")
GUIChallengeRewardReceive:setAlwaysOnTop(true)
GUIChallengeRewardReceive:hide()

initCustomDialog("BedWarCustomDialog.json")
initWatchAdTip("BedWarWatchADTip.json")
require "common.ui.layout.GUIGoodsDetailContent"
require "common.ui.layout.GUIBlockDetailContent"
require "game.ui.layout.GUILotteryReplaceContent"
require "common.ui.layout.GUIChallengeRewardIntroduce"
require "common.ui.layout.GUIFreeGiftWatchADTipContent"

