
# 是否使用新版抽奖界面
useNewLottery: 1

# 是否开启特殊第三视角镜头  1 开启,0 关闭
useTransparentCamera: 1

# 特殊第三视角镜头 透视透明度
specialTransparentAlpha: 0.5
# 拉弓时灵敏度倍率
bowSensitiveMultiplier: 0.6
# 拉弓速度倍率
bowSpeedMultiplier: 1.5
# 拉弓聚焦倍率
bowFOVMultiplier: 1.5
# 快捷建造最大发散范围
placeBlockMaxDepth: 2
# 快捷建造最大建造距离
placeBlockMaxBuildDistance: 4
#搭路模式建造距离
buildRoadModeMaxDistance: 4

