---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xiaolai.
--- DateTime: 2019/9/27 16:28
---

UIFriendInvitationItem = class("UIFriendInvitationItem", IGUIWindow)

function UIFriendInvitationItem:onLoad()
    print("UIFriendItem:onLoad()")
    self.icon = self:getChildWindow(0 , GUIType.UrlImage)
    self.icon:setDefaultImage("set:userItem.json image:icon")
    self.name = self:getChildWindow(1)
    self.sex = self:getChildWindow(2, GUIType.StaticImage)
    self.status = self:getChildWindow(3)

    self.invitationBtn = self:getChildWindow(4):GetChildByIndex(0)
    self.invitationBtn:registerEvent(GUIEvent.ButtonClick, function()
        self:onInvitationButtonEvent()
    end)

    self.data = {}
end

function UIFriendInvitationItem:onInvitationButtonEvent()
    print("onInvitationButton")
    

    MultiBuildData:postInvitationOther(GameData.userId, self.data.userId)
end

function UIFriendInvitationItem:getStatusText()
    if self.data.status == 20 then
        if self.data.gameId == BaseMain:getGameType() then
            return Lang:getString("online")
        end
    end
    return Lang:getString("offline")
end

function UIFriendInvitationItem:getSexIcon()
    if self.data.sex == 2 then
        return "set:skyblock_friend.json image:sex_girl"
    end
    return "set:skyblock_friend.json image:sex_boy"
end


function UIFriendInvitationItem:setItemData(data)
    self.data = data
    self:setDataUpdate()
end

function UIFriendInvitationItem:setDataUpdate()
    if self.data.picUrl then
        self.icon:setUrl(self.data.picUrl)
    end
    self.name:SetText(self.data.nickName)
    self.status:SetText(self:getStatusText())
    self.sex:SetImage(self:getSexIcon())
end