---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xiaolai.
--- DateTime: 2019/9/19 16:50
---

local function getChildWindow(window, name, type)
    local child = window:getChildWindow(name, type)
    if not child then
        error("SumRechargeLayout must have" .. name .. " child window.")
    end
    return child
end

local UIMain = class("UIMain", IGUILayout)

function UIMain:onLoad()
    self.btnBackHall = self:getChildWindow("SkyBlockMainLua-BackHall-Btn", GUIType.Button)
    self.stBackHall = self:getChildWindow("SkyBlockMainLua-BackHall-Text", GUIType.StaticText)
    self.stBackHall:SetText(Lang:getString("gui_skyblock_backHall"))
    self.welcomeTip = self:getChildWindow("SkyBlockMainLua-Welcome-Tip", GUIType.StaticText)
    self.welcomeTip:SetVisible(false)

    self.timeText = GUIManager:createGUIWindow(GUIType.StaticText, "SkyBlockMainLua-FlyTime-Text")
    self.timeText:SetTouchable(false)
    self.flyRemainingTime = 0
    self:initFlyColdDownText()

    self.btnBackHall:registerEvent(GUIEvent.ButtonClick, function()
    	SoundUtil.clickUI()
    	self:onClickBackHall()
    end)
    self:registerDataCallBack("WelcomeTip", function(data)
        self:onWelcomeVisitorTip(data)
    end, JsonBuilderProcessor)

    self:registerEvent(SumRechargeCreateItemsEvent, function ()
        self:refreshSkyBlockUI()
    end)

    self:registerDataCallBack("FlyRemainingTime", function(data)
        data = json.decode(data)
        self.timeText:SetVisible(true)
        self.flyRemainingTime = tonumber(data.remainingTime or 0)
        local isForever = data.isForever
        if isForever then
            self.timeText:SetVisible(false)
            return
        end
        if self.timerKey then
            return
        end

        self.timerKey = LuaTimer:schedule(function()
            self:upTimeTextTick()
        end, 1000, 1000)
    end)
end

function UIMain:initFlyColdDownText()
    self.timeText:SetVisible(false)
    self.timeText:SetText("00:00")
    self.timeText:SetArea({ 0, 0 }, { 0, -30 }, { 0, 60 }, { 0, 20 })
    self.timeText:SetTextColor({0, 1, 0, 1})
    self.timeText:SetBackgroundColor({ 0, 0, 0, 0.5 })
    self.timeText:SetHorizontalAlignment(HorizontalAlignment.Center)
    self.timeText:SetTextHorzAlign(HorizontalAlignment.Center)
    self.timeText:SetTextVertAlign(VerticalAlignment.Center)
    local flyBtn = GUIManager:getWindowByName("Main-Fly", GUIType.Button)
    flyBtn:AddChildWindow(self.timeText)
end

function UIMain:refreshSkyBlockUI()
    GUISumRechargeLayout.gvRewards.root:SetVisible(false)
    local config = SumRechargeConfig:getSumRecharge(GUISumRechargeLayout.currentId)
    if not config then
        return
    end
    local rewardCount = #config.Rewards
    local name = string.gsub(GUISumRechargeLayout.__name, ".json", "-")
    local llThreeItem = getChildWindow(GUISumRechargeLayout, name .. "Reward-Three-Panel", GUIType.Layout)
    local llSixItem = getChildWindow(GUISumRechargeLayout, name .. "Reward-Six-Panel", GUIType.Layout)
    llThreeItem:SetVisible(false)
    llSixItem:SetVisible(false)

    local llRewardItems = {}
    local nameStr = ""
    if rewardCount > 3 then
        nameStr = "Six-Item-Reward-"
        llSixItem:SetVisible(true)
    else
        nameStr = "Three-Item-Reward-"
        llThreeItem:SetVisible(true)
    end

    for i = 1, #config.Rewards do
        local skReward = getChildWindow(GUISumRechargeLayout, name .. nameStr .. tostring(i), GUIType.Layout)
        if skReward then
            llRewardItems[i] = skReward
        end
    end

    local rewards = config.Rewards
    for index, reward in ipairs(rewards) do
        local item = GUISumRechargeReward.new(config.RewardUIName)
        if rewardCount > 3 then
            item.ivIcon:SetArea({ 0, 0 }, { 0, 0 }, { 0, 60 }, { 0, 60 })
        else
            item.ivIcon:SetArea({ 0, 0 }, { 0, 0 }, { 0, 85 }, { 0, 85 })
        end
        item:setRewardItem(reward)
        item:setWidth({ 1, 0 })
        item:setHeight({ 1, 0 })
        llRewardItems[index]:CleanupChildren()
        llRewardItems[index]:AddChildWindow(item.root)
    end
end

function UIMain:onClickBackHall()
	GamePacketSender:sendGotoHall()
end

function UIMain:onWelcomeVisitorTip(data)
    self.welcomeTip:SetVisible(data.show)
    local message = string.format(Lang:getString("welcome_visitor_tip"), tostring(data.targetName))
    self.welcomeTip:SetText(message)
end

function UIMain:upTimeTextTick()
    if self.flyRemainingTime <= 0 then
        LuaTimer:cancel(self.timerKey)
        self.timerKey = nil
    end

    if self.flyRemainingTime > 0 then
        self.flyRemainingTime = self.flyRemainingTime - 1
        self:upTimeText()
    end
end

function UIMain:upTimeText()
    local minute = math.floor(self.flyRemainingTime % 3600 / 60)
    local hour = math.floor(self.flyRemainingTime / 3600)
    if minute >= 0 or hour >= 0 then
        local time_text = string.format("%s:%s",
            hour < 10 and string.format("0%d", hour) or tostring(hour),
            minute < 10 and string.format("0%d", minute) or tostring(minute))
        self.timeText:SetText(time_text)
    end
end

GUIMain = UIMain.new("SkyBlockMainLua.json", GUIManager:getMainControl())
GUIMain:show()