---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xiaolai.
--- DateTime: 2019/9/27 14:59
---

UINearFriendItem = class("UINearFriendItem", IGUIWindow)

function UINearFriendItem:onLoad()
    print("UINearFriendItem:onLoad")
    self.icon = self:getChildWindow(0 , GUIType.UrlImage)
    self.icon:setDefaultImage("set:userItem.json image:icon")
    self.name = self:getChildWindow(1)
    self.sex = self:getChildWindow(2, GUIType.StaticImage)

    self.visitBtn = self:getChildWindow(3):GetChildByIndex(0)
    self.visitBtn:registerEvent(GUIEvent.ButtonClick, function()
        self:onVisitButtonEvent()
    end)
    self.addBtn = self:getChildWindow(3):GetChildByIndex(1)
    self.addBtn:registerEvent(GUIEvent.ButtonClick, function()
        self:onAddButtonEvent()
    end)
    self.addBtn:SetVisible(false)
    self.data = {}
end

function UINearFriendItem:onVisitButtonEvent()
    PacketSender:sendCallOnManor(self.data.userId, 3, true, 0)
end

function UINearFriendItem:onAddButtonEvent()
    print("onAddButton")
    MultiBuildData:addNearFriend(self.data.userId)
    self.addBtn:SetEnabled(false)
    MultiBuildData:postAddFriend(self.data.userId)
end

function UINearFriendItem:getSexIcon()
    if self.data.sex == 2 then
        return "set:skyblock_friend.json image:sex_girl"
    end
    return "set:skyblock_friend.json image:sex_boy"
end

function UINearFriendItem:setItemData(data)
    self.data = data
    self:setDataUpdate()
end

function UINearFriendItem:setDataUpdate()
    self.addBtn:SetEnabled(MultiBuildData:checkCanAddFriend(self.data.userId))
    if self.data.picUrl then
        self.icon:setUrl(self.data.picUrl)
    end
    self.name:SetText(self.data.nickName)
    self.sex:SetImage(self:getSexIcon())
    if MultiBuildData:checkIsMyFriend(self.data.userId) then
        self.addBtn:SetVisible(false)
    else
        self.addBtn:SetVisible(true)
    end
end