---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/10/14 20:07
---
local dialog
local GUISkyBlockCommonDialog = class("GUISkyBlockCommonDialog", IGUILayout)

function GUISkyBlockCommonDialog:onLoad()
    print("SkyBlockCommonDialog")
    self.tvTitleText = self:getChildWindow("SkyBlockCommonDialog-Title-Text")
    self.tvContentText = self:getChildWindow("SkyBlockCommonDialog-Content-Text")
    self.btnClose = self:getChildWindow("SkyBlockCommonDialog-Close-Btn")
    self.btnLeftButton = self:getChildWindow("SkyBlockCommonDialog-Left-Button", GUIType.Button)
    self.btnRightButton = self:getChildWindow("SkyBlockCommonDialog-Right-Button", GUIType.Button)
    
    self.btnClose:registerEvent(GUIEvent.ButtonClick, function()
        self:hide()
        SoundUtil.playSound(SoundType.ClosePanel)
    end)
    self.btnLeftButton:registerEvent(GUIEvent.ButtonClick, function()
        if self.leftClickListener ~= nil then
            local close = self.leftClickListener() ---返回true拦截dialog不关闭
            if not close then
                self:hide()
            end
        else
            self:hide()
        end
        SoundUtil.playSound(SoundType.ClosePanel)
    end)
    self.btnRightButton:registerEvent(GUIEvent.ButtonClick, function()
        if self.rightClickListener ~= nil then
            local close = self.rightClickListener() ---返回true拦截dialog不关闭
            if not close then
                self:hide()
            end
        else
            self:hide()
        end
        SoundUtil.playSound(SoundType.ClosePanel)
    end)

end

function GUISkyBlockCommonDialog:setDefault()
    self.leftClickListener = nil
    self.rightClickListener = nil
    self.tvTitleText:SetText(Lang:getString("gui_dialog_tip_title_tip"))
    self.btnClose:SetVisible(true)
    self.tvContentText:SetText("")
    --self.ivExtraIcon:SetVisible(false)
    --self.ivLeftIcon:SetVisible(false)
    --self.ivRightIcon:SetVisible(false)
    self.btnLeftButton:SetText(Lang:getString("gui_dialog_tip_btn_cancel"))
    self.btnRightButton:SetText(Lang:getString("gui_dialog_tip_btn_sure"))
    --if self.contentView ~= nil then
    --    self.contentView:hide()
    --    self.contentView = nil
    --end
end

function GUISkyBlockCommonDialog:onHide()
    self:setDefault()
end

function GUISkyBlockCommonDialog:builder()
    self:setDefault()
end

local function setButtonUI(button, icon, iconPos)
    if not button:IsVisible() then
        return
    end
    if icon:IsVisible() then
        local offset = icon:GetPixelSize().x / 2
        button:SetRenderOffset({ x = offset, y = 0 })
        if #button:GetText() == 0 then
            icon:SetHorizontalAlignment(HorizontalAlignment.Center)
            icon:SetXPosition({ 0, 0 })
        else
            icon:SetHorizontalAlignment(HorizontalAlignment.Left)
            icon:SetXPosition(iconPos)
        end
    else
        button:SetRenderOffset({ x = 0, y = 0 })
    end
end

function GUISkyBlockCommonDialog:setUI()
    if self.btnLeftButton:IsVisible() and self.btnRightButton:IsVisible() then
        self.btnLeftButton:SetHorizontalAlignment(HorizontalAlignment.Left)
        self.btnLeftButton:SetXPosition(self.leftButtonPos)
        self.btnRightButton:SetHorizontalAlignment(HorizontalAlignment.Right)
        self.btnRightButton:SetXPosition(self.rightButtonPos)
    elseif self.btnLeftButton:IsVisible() then
        self.btnLeftButton:SetHorizontalAlignment(HorizontalAlignment.Center)
        self.btnLeftButton:SetXPosition({ 0, 0 })
    elseif self.btnRightButton:IsVisible() then
        self.btnRightButton:SetHorizontalAlignment(HorizontalAlignment.Center)
        self.btnRightButton:SetXPosition({ 0, 0 })
    end
    setButtonUI(self.btnLeftButton, self.ivLeftIcon, self.leftIconPos)
    setButtonUI(self.btnRightButton, self.ivRightIcon, self.rightIconPos)
    if self.contentView ~= nil then
        self.tvContentText:SetText("")
        self.ivExtraIcon:SetVisible(false)
    end
end

SkyBlockCommonDialog = {}

function SkyBlockCommonDialog.builder()
    dialog:builder()
    return SkyBlockCommonDialog
end

function SkyBlockCommonDialog.setContentText(text)
    dialog.tvContentText:SetText(text)
    return SkyBlockCommonDialog
end

function SkyBlockCommonDialog.setLeftText(text)
    if not text or #text == 0 then
        dialog.btnLeftButton:SetText("")
        dialog.btnLeftButton:SetVisible(dialog.ivLeftIcon:IsVisible())
    else
        dialog.btnLeftButton:SetVisible(true)
        dialog.btnLeftButton:SetText(Lang:getString(text))
    end
    return SkyBlockCommonDialog
end

function SkyBlockCommonDialog.setRightText(text)
    if not text or #text == 0 then
        dialog.btnRightButton:SetText("")
        dialog.btnRightButton:SetVisible(dialog.ivRightIcon:IsVisible())
    else
        dialog.btnRightButton:SetVisible(true)
        dialog.btnRightButton:SetText(Lang:getString(text))
    end
    return SkyBlockCommonDialog
end

function SkyBlockCommonDialog.setLeftClickListener(listener)
    dialog.leftClickListener = listener
    return SkyBlockCommonDialog
end

function SkyBlockCommonDialog.setRightClickListener(listener)
    dialog.rightClickListener = listener
    return SkyBlockCommonDialog
end

function SkyBlockCommonDialog.show()
    --dialog:setUI()
    dialog:show()
    SoundUtil.playSound(SoundType.OpenPanel)
end

function SkyBlockCommonDialog.hide()
    dialog:hide()
end

function initSkyBlockCommonDialog(name)
    if dialog ~= nil then
        return
    end
    dialog = GUISkyBlockCommonDialog.new(name)
end