---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by bell.
--- DateTime: 2020/2/4 14:55
---
EntityRankManager = class("EntityRankManager", EventObservable)

local entityRankNum = 4
local titleText = { "rank", "userName", "killNum", "integral", "stage" }
local col_num = 10

function EntityRankManager:init()
    self:registerDataCallBack("EntityRankCountdown", self.onEntityRankCountdown, DataBuilderProcessor)
    self:registerDataCallBack("CreateEntityRankTitle", self.onCreateEntityRankTitle, DataBuilderProcessor)
    self:registerDataCallBack("AddRowWallText", self.onAddRowWallText)
    self:registerDataCallBack("DeleteAllWallText", self.onDeleteAllWallText)
end

function EntityRankManager.onEntityRankCountdown(data)
    local time = data:getNumberParam("time")
    for rankId = 1, entityRankNum do
        Utility.addWallText("UpdateCountdown", tonumber(rankId .. "9901"))
        Utility.addWallText(tostring(time), tonumber(rankId .. "9902"))
    end
end

function EntityRankManager.onCreateEntityRankTitle(data)
    for rankId = 1, entityRankNum do
        Utility.addWallText("rank_title" .. rankId, tonumber(rankId .. "9991"))

        local start = tonumber(rankId .. "9001")
        for i = start, start + #titleText do
            Utility.addWallText(titleText[i - start + 1], i)
        end
    end
end

function EntityRankManager.onAddRowWallText(data)
    LogUtil.log("EntityRankManager.onAddRowWallText " .. data)

    local result = StringUtil.split(data, "&")
    for i = 1, #result do
        local value = StringUtil.split(result[i], ",")
        Utility.addWallText(tostring(value[1]), tonumber(value[2]))
    end
end

function EntityRankManager.onDeleteAllWallText(data)
    for rankId = 1, entityRankNum do
        local first = tonumber(rankId .. "0001")
        local last = tonumber(rankId .. "0050")
        for i = first, last do
            Utility.addWallText("", i)
        end
    end
end

return EntityRankManager