---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/12/23 10:55
---

GUIRankItem = class("GUIRankItem", IGUIWindow)

function GUIRankItem:onLoad()
    --StaticImage
    self.ivBg = self:getChildWindow(0, GUIType.StaticImage)
    self.ivRankBg = self:getChildWindow(1, GUIType.StaticImage)
    self.ivScoreBg = self:getChildWindow(2, GUIType.StaticImage)

    --StaticText
    self.tvPlayerName = self:getChildWindow(0, GUIType.StaticText, self.ivRankBg)
    self.tvRankNum = self:getChildWindow(1, GUIType.StaticText, self.ivRankBg)
    self.tvScoreNum = self:getChildWindow(1, GUIType.StaticText, self.ivScoreBg)
end

function GUIRankItem:initItem(item, isSelf)
    local rank = item.rank
    local nickName = item.nickName
    local integral = item.integral
    local bgImg = "set:lucky_sky_season_rank.json image:bg_rank"
    local bgIcon = "set:lucky_sky_season_rank.json image:ic_rank"
    local bgScore = "set:lucky_sky_season_rank.json image:ic_rank"
    local rankColor = Define.RankColor.Rank_Nor
    local scoreRank = Define.ScoreColor.Rank_Nor

    if rank < 4 then
        bgIcon = "set:lucky_sky_season_rank.json image:ic_rank_" .. rank
        rankColor = Define.RankColor["Rank_" .. rank]
    end

    if isSelf then
        bgImg = "set:lucky_sky_season_rank.json image:bg_mine"
        bgIcon = "set:lucky_sky_season_rank.json image:ic_mine"
        bgScore = "set:lucky_sky_season_rank.json image:ic_mine"
        rankColor = Define.RankColor.Rank_Self
        scoreRank = Define.ScoreColor.Rank_Self
        self.tvPlayerName:SetTextColor({240 / 255, 1, 196 / 255, 1})
        self.tvRankNum:SetTextColor({240 / 255, 1, 196 / 255, 1})
        self.tvScoreNum:SetTextColor({240 / 255, 1, 196 / 255, 1})
    end

    self.ivBg:SetImage(bgImg)
    self.ivRankBg:SetImage(bgIcon)
    self.ivScoreBg:SetImage(bgScore)

    self.tvRankNum:SetTextColor(rankColor)
    self.tvScoreNum:SetTextColor(scoreRank)

    self.tvRankNum:SetText(rank)
    self.tvPlayerName:SetText(nickName)
    self.tvScoreNum:SetText(integral)
end

return GUIRankItem