---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 10184.
--- DateTime: 2020/6/4 21:29
---
CustomShopSwordLight.curSwordLight = nil
CustomShopSwordLight.curTimerKey = nil

function CustomShopSwordLight:onTabChange(isSelect)
    LuaTimer:cancel(self.curTimerKey)
    if isSelect then
        return
    end
    if CustomShopSwordLight.curSwordLight then
        GUICustomShop:unloadBodyPart(CustomShopSwordLight.curSwordLight.PartName)
        GUICustomShop:playSkill("idle")
        CustomShopSwordLight.curSwordLight = nil
    end
end

function CustomShopSwordLight:onSelectGoods(goods)
    local setting = self.Settings[goods.SettingId]
    if not setting then
        return
    end
    CustomShopSwordLight.curSwordLight = setting
    GUICustomShop:useBodyPart(setting.PartName, setting.MeshName)
    GUICustomShop:playSkill(setting.Action)
    LuaTimer:cancel(self.curTimerKey)
    self:playAction()
end

function CustomShopSwordLight:playIdle()
    if CustomShopSwordLight.curSwordLight then
        GUICustomShop:playSkill("idle")
        self.curTimerKey = LuaTimer:schedule(function()
            self:playAction()
        end, CustomShopSwordLight.curSwordLight.IdleTime)
    end
end

function CustomShopSwordLight:playAction()
    if CustomShopSwordLight.curSwordLight then
        GUICustomShop:playSkill(CustomShopSwordLight.curSwordLight.Action)
        self.curTimerKey = LuaTimer:schedule(function()
            self:playIdle()
        end, GUICustomShop.awPlayer1:GetActor():GetSkillTimeLength(CustomShopSwordLight.curSwordLight.Action))
    end
end

function CustomShopSwordLight:getSettingByAction(action)
    for _, setting in pairs(self.Settings) do
        if setting.Action == action then
            return setting
        end
    end
end

function CustomShopSwordLight:getSettingBySceneAction(action)
    for _, setting in pairs(self.Settings) do
        if setting.SceneAction == action then
            return setting
        end
    end
end