---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 98632.
--- DateTime: 2019/9/29 21:19
---

local UIResultRank = class("UIResultRank", IGUILayout)

function UIResultRank:onLoad()
    self:onInitData()
    self:initUI()
    self:initEvent()
end

function UIResultRank:onInitData()
    self.isStart = false
    self.alphaTime = 2000
    self.setAlphaTime = self.alphaTime
end

function UIResultRank:initUI()
    self.siContentBox = self:getChildWindow("LSChampionShipResultRand-Content", GUIType.StaticImage)
    self.siContentBox:SetAlpha(0)
    self.stTitleRank = {}
    self.stTitleID = {}
    self.stTitleKill = {}
    self.stTitleScore = {}
    self.stTitleLv = {}
    for i=1,2 do
        self.stTitleRank[i] = self:getChildWindow("LSChampionShipResultRand-Rank"..i, GUIType.StaticText)
        self.stTitleRank[i]:SetText(Lang:getString("Rank"))
        self.stTitleID[i] = self:getChildWindow("LSChampionShipResultRand-Name"..i, GUIType.StaticText)
        self.stTitleID[i]:SetText(Lang:getString("Name"))
        self.stTitleKill[i] = self:getChildWindow("LSChampionShipResultRand-Kill"..i, GUIType.StaticText)
        self.stTitleKill[i]:SetText(Lang:getString("Kill"))
        self.stTitleScore[i] = self:getChildWindow("LSChampionShipResultRand-Score"..i, GUIType.StaticText)
        self.stTitleScore[i]:SetText(Lang:getString("Score"))
        self.stTitleLv[i] = self:getChildWindow("LSChampionShipResultRand-Lv"..i, GUIType.StaticText)
        self.stTitleLv[i]:SetText(Lang:getString("Stage"))
    end
    self.siRankBox = {}
    self.siRankBox[1] = self:getChildWindow("LSChampionShipResultRand-RankBox1", GUIType.StaticImage)
    self.siRankBox[2]= self:getChildWindow("LSChampionShipResultRand-RankBox2", GUIType.StaticImage)

    self.ivIconItem = {}
    self.siLineItem = {}
    self.tvRankItem = {}
    self.tvNameItem = {}
    self.tvKillItem = {}
    self.tvScoreItem = {}
    self.tvStageItem = {}
    local row = 8
    local col = 5
    local serial = 0
    for j=1,#self.siRankBox do
        for i=1,row do
            local value = {}
            serial = serial + 1
            local strIcon = string.format("LSChampionShipResultRand-Item-Icon%d", serial)
            self.ivIconItem[serial] = GUIManager:createGUIWindow(GUIType.StaticImage, strIcon)
            self.siRankBox[j]:AddChildWindow(self.ivIconItem[serial])
            self.ivIconItem[serial]:SetArea({ 0, 0 }, { 1/row*(i-1) + 0.005, 0 }, { 1, 0 }, { 0.12, 0 })

            if serial == 1 or serial == 2 or serial == 3 then
                self.ivIconItem[serial]:SetImage("set:LSChampionShip_ResultRank.json image:rank"..serial)
                self.ivIconItem[serial]:SetProperty("StretchType","NineGrid")
                self.ivIconItem[serial]:SetProperty( "StretchOffset", "20 20 20 20")
            end
            local strIconLine = string.format("LSChampionShipResultRand-Item-Line%d", serial)
            self.siLineItem[serial] = GUIManager:createGUIWindow(GUIType.StaticImage, strIconLine)
            self.ivIconItem[serial]:AddChildWindow(self.siLineItem[serial])
            self.siLineItem[serial]:SetImage("set:LSChampionShip_ResultRank.json image:line")
            self.siLineItem[serial]:SetArea({ 0, 0 }, { 0, 0 }, { 1, 0 }, { 0.05, 0 })
            self.siLineItem[serial]:SetHorizontalAlignment(HorizontalAlignment.Center)
            self.siLineItem[serial]:SetVerticalAlignment(VerticalAlignment.Bottom)
            local u_x = 0
            local strRank = string.format("LSChampionShipResultRand-Item-Rank%d", serial)
            self.tvRankItem[serial] = GUIManager:createGUIWindow(GUIType.StaticText, strRank)
            self.tvRankItem[serial]:SetArea({ 0, 0 }, { 0, 0 }, { 1/col, 0 }, { 1, 0 })
            self.tvRankItem[serial]:SetFont(GUIFontManager:Instance():GetFont("HT18"))
            -- self.tvRankItem[serial]:SetText(tostring(value.rank or i))
            self:SetTextColorByRank(self.tvRankItem[serial], serial, false, true)
            self.tvRankItem[serial]:SetTextHorzAlign(HorizontalAlignment.Center)
            self.tvRankItem[serial]:SetTextVertAlign(VerticalAlignment.Center)
            self.ivIconItem[serial]:AddChildWindow(self.tvRankItem[serial])
            u_x = u_x + 1
            local strName = string.format("LSChampionShipResultRand-Item-Name%d", serial)
            self.tvNameItem[serial] = GUIManager:createGUIWindow(GUIType.StaticText, strName)
            self.tvNameItem[serial]:SetArea({ 1/col*u_x, 0 }, { 0, 0 }, { 1/col, 0 }, { 1, 0 })
            self.tvNameItem[serial]:SetFont(GUIFontManager:Instance():GetFont("HT18"))
            -- self.tvNameItem[serial]:SetText(Utility.toAbbreviateString(tostring(value.name or i)))
            self:SetTextColorByRank(self.tvNameItem[serial], serial, false, false)
            self.tvNameItem[serial]:SetTextHorzAlign(HorizontalAlignment.Center)
            self.tvNameItem[serial]:SetTextVertAlign(VerticalAlignment.Center)
            self.ivIconItem[serial]:AddChildWindow(self.tvNameItem[serial])
            u_x = u_x + 1
            local strKill = string.format("LSChampionShipResultRand-Item-Kill%d", serial)
            self.tvKillItem[serial] = GUIManager:createGUIWindow(GUIType.StaticText, strKill)
            self.tvKillItem[serial]:SetArea({ 1/col*u_x, 0 }, { 0, 0 }, { 1/col, 0 }, { 1, 0 })
            self.tvKillItem[serial]:SetFont(GUIFontManager:Instance():GetFont("HT18"))
            -- self.tvKillItem[serial]:SetText(Utility.toKMBString(tostring(value.kill or i), 2))
            self:SetTextColorByRank(self.tvKillItem[serial], serial, false, false)
            self.tvKillItem[serial]:SetTextHorzAlign(HorizontalAlignment.Center)
            self.tvKillItem[serial]:SetTextVertAlign(VerticalAlignment.Center)
            self.ivIconItem[serial]:AddChildWindow(self.tvKillItem[serial])
            u_x = u_x + 1
            local strStage = string.format("LSChampionShipResultRand-Item-Stage%d", serial)
            self.tvStageItem[serial] = GUIManager:createGUIWindow(GUIType.StaticText, strStage)
            self.tvStageItem[serial]:SetArea({ 1/col*u_x, 0 }, { 0, 0 }, { 1/col, 0 }, { 1, 0 })
            self.tvStageItem[serial]:SetFont(GUIFontManager:Instance():GetFont("HT18"))
            -- self.tvStageItem[serial]:SetText(Lang:getString(tostring(value.stage or i), 2))
            self:SetTextColorByRank(self.tvStageItem[serial], serial, false, false)
            self.tvStageItem[serial]:SetTextHorzAlign(HorizontalAlignment.Center)
            self.tvStageItem[serial]:SetTextVertAlign(VerticalAlignment.Center)
            self.ivIconItem[serial]:AddChildWindow(self.tvStageItem[serial])
            u_x = u_x + 1
            local strScore = string.format("LSChampionShipResultRand-Item-Score%d", serial)
            self.tvScoreItem[serial] = GUIManager:createGUIWindow(GUIType.StaticText, strScore)
            self.tvScoreItem[serial]:SetArea({ 1/col*u_x, 0 }, { 0, 0 }, { 1/col, 0 }, { 1, 0 })
            self.tvScoreItem[serial]:SetFont(GUIFontManager:Instance():GetFont("HT18"))
            -- self.tvScoreItem[serial]:SetText(Utility.toKMBString(tostring(value.score or i), 2))
            self:SetTextColorByRank(self.tvScoreItem[serial], serial, false, false)
            self.tvScoreItem[serial]:SetTextHorzAlign(HorizontalAlignment.Center)
            self.tvScoreItem[serial]:SetTextVertAlign(VerticalAlignment.Center)
            self.ivIconItem[serial]:AddChildWindow(self.tvScoreItem[serial])
        end
    end

    self.btnBack = self:getChildWindow("LSChampionShipResultRand-Back" ,GUIType.Button)
    self.btnBack_text = self:getChildWindow("LSChampionShipResultRand-BackTxt", GUIType.StaticText)
    self.btnBack_text:SetText(Lang:getString("gui_back_hall"))
    self.btnNext = self:getChildWindow("LSChampionShipResultRand-Next" ,GUIType.Button)
    self.btnNext_text = self:getChildWindow("LSChampionShipResultRand-NextTxt", GUIType.StaticText)
    self.btnNext_text:SetText(Lang:getString("gui_next_game"))
end

function UIResultRank:initEvent()
    self.btnBack:registerEvent(GUIEvent.ButtonClick, function ()
        self:onClickBack()
    end)
    self.btnNext:registerEvent(GUIEvent.ButtonClick, function ()
        self:onClickNext()
    end)
end

function UIResultRank:SetTextColorByRank(textUI, rankNum, isMe, isRank)
    rankNum = rankNum or 0
    isMe = isMe or false
    if isMe then
        textUI:SetTextColor({254/255, 253/255, 252/255, 1})
    elseif rankNum == 1 then
        textUI:SetTextColor({252/255, 1, 7/255, 1})
    elseif rankNum == 2 then
        textUI:SetTextColor({230/255, 230/255, 230/255, 1})
    elseif rankNum == 3 then
        textUI:SetTextColor({237/255, 148/255, 68/255, 1})
    elseif isRank then
        textUI:SetTextColor({214/255, 96/255, 85/255, 1})
    else
        textUI:SetTextColor({123/255, 78/255, 41/255, 1})
    end
end

function UIResultRank:ShowResultRank(data)
    if not data or not self:isLoad() then
        return
    end
    self:setResultRankData(data[1], data[2])
    self:show()
    self.isStart = true
end

function UIResultRank:setResultRankData(meRank, rankData)
    if meRank == nil or rankData == nil then
        return
    end
    local row = 8
    if meRank > #self.siRankBox*row then
        return
    end
    -- LogUtil.log("meRank: "..meRank)
    for i=1,#self.siRankBox*row do
        if rankData[i] then
            if i == meRank and meRank > 3 then
                self.ivIconItem[i]:SetImage("set:LSChampionShip_ResultRank.json image:rankMe")
                self.ivIconItem[i]:SetProperty("StretchType","NineGrid")
                self.ivIconItem[i]:SetProperty( "StretchOffset", "20 20 20 20")
                self:SetTextColorByRank(self.tvRankItem[i], i, true, true)
                self:SetTextColorByRank(self.tvNameItem[i], i, true, false)
                self:SetTextColorByRank(self.tvKillItem[i], i, true, false)
                self:SetTextColorByRank(self.tvScoreItem[i], i, true, false)
                self:SetTextColorByRank(self.tvStageItem[i], i, true, false)
            end
            self.tvRankItem[i]:SetText(tostring(rankData[i].rank or i))
            self.tvNameItem[i]:SetText(Utility.toAbbreviateString(tostring(rankData[i].name or i)))
            self.tvKillItem[i]:SetText(Utility.toKMBString(tostring(rankData[i].kill or i), 2))
            self.tvScoreItem[i]:SetText(Utility.toKMBString(tostring(rankData[i].score or i), 2))
            self.tvStageItem[i]:SetText(Lang:getString(tostring(rankData[i].stage or i), 2))
        else
            self.ivIconItem[i]:SetVisible(false)
        end
    end
end

function UIResultRank:onClickBack()
    -- LogUtil.log("--- onClickBack ---")
    self:hide()
    local data = DataBuilder.new():addParam("backOrAgain", "back"):getData()
    PacketSender:sendLuaCommonData("BackOrAgainClick", data)
end

function UIResultRank:onClickNext()
    -- LogUtil.log("--- onClickNext ---")
    self:hide()
    local data = DataBuilder.new():addParam("backOrAgain", "again"):getData()
    PacketSender:sendLuaCommonData("BackOrAgainClick", data)
end

function UIResultRank:onTick(frameTime)
    if self:isShow() and self.isStart then
        self:onUpdate(frameTime)
    end
end

function UIResultRank:onUpdate(frameTime)
    if self.setAlphaTime > 0 then
        self.setAlphaTime = self.setAlphaTime - frameTime
        if self.setAlphaTime > 0 then
            local progress = 1 - self.setAlphaTime / self.alphaTime
            if progress >= 0.95 then
                progress = 1
            end
            self.siContentBox:SetAlpha(progress)
        else
            return
        end
    end
end

return UIResultRank
