= BlockyMods说明文档
:toc: left

== 地图格式 [[map-format]]

地图文件夹中++plugins++文件夹。这个文件夹里面有很多子文件夹，每个子文件夹就是一个<<plugin, 插件>>。子文件夹的名字决定了这个插件的名字。

在地图文件夹中还有有++id_mappings.ini++文件。这个文件决定了哪个ID代表了哪个方块或道具。这个文件可以有两个不同的节（Section），++[Block]++节记录了哪个ID对应到哪个方块。++[Item]++节记录了哪个ID对应到哪个道具。

NOTE: 方块的名字和道具的名字必须要使用他们的全称，也就是应该遵守++<插件名>:<方块名或道具名>++的格式，关于插件请看<<plugin, 这里>>。

更多说明，请看++地图模块说明.docx++

== 插件（Plugin） [[plugin]]

**插件（Plugin）**是共享的基本单位，以后的计划中，玩家可以把自己写的方块，物品，合成配方等等都打包到一个插件中，上传到服务器，让其他玩家下载使用。所以说插件是共享的基本单位。

NOTE: 命名规则：我们在命名一个插件的时候应该遵守这样的规则：插件的名字由小写字母，下划线，以及数字组成，不同单词之间可以用下划线分割。

NOTE: “插件是共享的基本单位”这句话仅就程序的实现而言的，也就是说玩家实际操作的时候可能会意识不到插件的存在。至于玩家到底要不要知道插件这个概念，则由产品确定，这些都是后话了。

插件不仅仅是共享的基本单位，它的名字还是许多内容的命名空间。例如插件++addon++里面有自定义方块++aluminum++，那么这个自定方块的全称为++addon:aluminum++。插件内的东西引用这个方块可以不带命名空间，但是从插件外，或者从其他插件引用这个方块就需要使用它的全称了。关于自定义方块，请看<<block, 这里>>。

== 方块（Block） [[block]]

**自定义方块（Custom Block）**是一类使用配置文件定义的方块。自定义方块的属性与逻辑都通过配置文件来定义。自定义方块的配置文件都放在++<插件名>/blocks/<方块名>/++中。

自定义方块的名字由文件夹名字决定。

NOTE: 命名规则：方块的命名规则与插件相同，由小写字母，下划线，以及数字组成，不同单词之间可以用下划线分割。

目录结构为

----
<方块名字>
|-- block.json
|-- texture.json
|-- texture.png
`-- texts
    |-- en.lang
    |-- zh.lang
    |-- ...
----

=== block.json的格式 [[block.json]]

++block.json++示例如下：

[source, json]
--
{
    "texture": "blockymods:iron_block",
    "state": "SOLID",
    "color": "FF2100",
    "transparent": false,
    "collisionBox": {
        "min": { "x": -0.5, "y": 0, "z": -0.5},
        "max": { "x": 1.5, "y": 1, "z": 1.5}
    },
    "resistance": 100,
    "flammable": true,
    "triggers": [
        {
            "type": "CLICK",
            "actions": [
                {
                    "type": "SHOW_MESSAGE",
                    "textId": "message.intro"
                }
            ]
        },
        {
            "type": "CLICK",
            "itemIds": [50, 76],
            "actions": [
                {
                    "type": "EXPLODE",
                    "power": 20,
                    "range": 5
                },
                {
                    "type": "SHOW_MESSAGE",
                    "textId": "message.explode"
                }
            ]
        }
    ]
}
--

==== texture [[block.json-texture]]

* 类型为字符串或对象
* 必需

方块的贴图，可以是一个指向贴图的字符串，或者是一个对象。如果是一个对象，则必须有++top++，++bottom++，++left++，++right++，++front++，++back++，这六个字段，每个字段都是一个指向贴图的字符串。

指向贴图的字符串必须是以下格式：

* ++"plugin:<插件名>:block:<方块名>:<贴图名>"++ 或者
* ++"blockymods:<贴图名>"++

程序会去寻找名为++<贴图名>++的贴图，作为这个方块的贴图。如果前缀是++blockymods:++，则会在BlockyMods自带的贴图资源中寻找，否则就在++<插件名>:<方块名>++方块提供的贴图中寻找。

++plugin:<插件名>++前缀与++:block:<方块名>:++前缀都可以省略，++<插件名>++默认是所属的插件的名字，++<方块名>++默认是所属的方块的名字。

IMPORTANT: 如果每一个面都使用不同的贴图的话，每一个面的贴图都必须来自同一个贴图文件。

==== state [[block.json-state]]

* 类型为字符串
* 必须是++"SOLID"++或者++"GAS"++
* 可选，默认值：++"SOLID"++

++"SOLID"++表示这个方块是固态方块，++"GAS"++表示这个方块是气态。气态方块不能被选中，必须半透明，没有碰撞盒，可以被其他方块替换。颜色可以通过<<block.json-color, color>>设置。

==== color [[block.json-color]]

* 类型为字符串
* 必须是16进制的6位数字符串
* 可选，默认值：++"FFFFFF"++

可以影响方块的颜色。一般情况下是颜色相乘，具体由shader决定。

==== transparent [[block.json-transparent]]

* 类型为布尔值
* 可选，默认值：++false++

是否半透明。这个值会影响到渲染。

IMPORTANT: 如果这个方块是半透明方块，则不仅需要transparent的值是true，还需要贴图也是半透明的。

==== collisionBox [[block.json-collisionBox]]

* 类型为对象或++null++
* 可选，默认值：++{"min": {0,0,0}, "max": {1,1,1}}++

可以是对象或++null++。如果值为++null++，则这个方块没有碰撞盒，如果是对象，必须有++min++和++max++这两个字段。++min++和++max++都是对象，都必须有++x++，++y++，++z++这三个字段。

所有自定义方块的都是1m x 1m x 1m的正方体，但是碰撞盒大小可以和方块的大小不同。程序判断其他物体与这个方块是否接触（碰撞）是通过判断那个物体的碰撞盒与这个方块的碰撞盒是否接触（碰撞），而不会去考虑物体或者方块的具体形状大小。

碰撞盒的形状是一个立方体。BlockyMods使用右手坐标系。如果面朝z轴负方向看向一个方块，把方块的左下后方的角看作原点的话，++min++的坐标就是碰撞盒的左下后方的角的坐标，++max++的坐标就是碰撞盒的右上前方的角的坐标。

==== resistance [[block.json-resistance]]

* 类型为整数
* 值的可取范围是0-10000（包括两端）
* 可选，默认值：++15++

方块的爆炸抗性。数字越大，越能抵抗更大威力的爆炸。

==== flammable [[block.json-flammable]]

* 类型为布尔值
* 可选，默认值：++false++

方块是否可以燃烧。

==== triggers [[block.json-triggers]]

* 类型为数组
* 可选，默认值：++[]++

<<trigger, 触发器>>列表。

*TODO*

=== texture.json的格式

*TODO*

=== 如何创建一个新的自定义方块

== 触发器（Trigger） [[trigger]]

我们创建新的方块不仅是想要自定义他的外貌和属性，我们有时候也会希望能有特殊的逻辑。这个特殊的逻辑也可以通过配置来实现，这个机制就是触发器机制。

=== 触发器基本概念 [[trigger-concept]]

每个自定义方块都可以带有若干个**触发器（Trigger)**。一个触发器带有一个或多个**触发器动作（Trigger Action）**。一个触发器动作定义了一个游戏逻辑，可以被执行，例如产生爆炸。除此之外，触发器还有**条件（Condition）**，不同的触发器有不同的条件，例如用户点击方块。在条件被满足时，触发器能够被**激活（Activate）**。触发器被激活意味着按顺序执行这个触发器带有的所有触发器动作。这个顺序由++block.json++决定。不同类型的触发器有不同的**激活点（Activation Point）**，激活点是指代码中的一个位置，检查触发器条件，以及执行触发器动作，都是在激活点进行的。

触发器可以按照它的条件分为不同的类型。例如，玩家空手点击一个方块就会被激活的触发器，和玩家拿着火炬时点击就会被激活的触发器，都是在点击时被激活的，只是手上持有的物品不一样，所以这两个触发器都是++CLICK++类型的触发器。而“手上的物品”是++CLICK++触发器的参数，不同的参数会产生不同的触发器。

同理，触发器动作也可以按照它的逻辑分为不同的类型。例如，产生威力为100的爆炸和产生威力为200的爆炸是两个不同的动作，但是属于同一个类型++EXPLODE++。只是“威力”这个参数不一样而已。

NOTE: 触发器相关代码中有些地方可以看到++Remote++，++Local++等单词，例如++RemoteActivatedTrigger++。这里做一下解释：对于服务端，客户端是remote端，服务端是local端；对于客户端，服务端是remote端，客户端是local端。

=== 触发器的网络同步机制 [[trigger-network]]

有些触发器动作是必须要在客户端进行的，例如在画面中显示某个UI。有些触发器动作是必须在服务端进行的，例如产生爆炸（爆炸效果要在服务端进行计算，并下发计算结果给客户端，详见相关代码）。同样的，有些触发器是只在客户端有激活点，例如点击方块。如果激活点和动作的执行位置不在同一台机器上，程序必须要通过某种方法通知另一台机器去执行动作。为此，我们需要引入触发器的网络同步机制。

刚刚提到，有些触发器动作一定要在客户端执行，而有些一定要在服务器执行。实际上，我们规定，所有触发器动作都必须要么在客户端执行，要么在服务器执行（这个规定的原因请看<<trigger-network-design, 这里>>）。而某一个触发器的激活点可以只在客户端或服务端，也可以在两边都有激活点，但是为了防止混乱，减少同步次数，实际运行的时候，由一套规则来确定是要使用客户端的激活点还是服务端的激活点。规则详见server项目的++CustomBlockServer::checkTriggers++函数与client项目的++CustomBlockClient::checkTriggers++函数

==== 网络同步机制的设计考量 [[trigger-network-design]]

*TODO*

=== 如何创建一个新的触发器

. ++TriggerTypeDef.h++文件中增加新的++TriggerType++枚举值，并在它下面的++triggerTypeNames++数组中添加对应的枚举值字符串。
. 确定它在客户端和服务端有没有激活点。如果只在客户端有激活点，那么触发器代码写在++TriggersClient.h/cpp++中。如果只在服务端有代码，那么触发器代码写在++TriggersServer.h/cpp++中。如果两边都有代码，那么触发器代码写在++Triggers.h/cpp++中。
. 在上面确定的文件中新建一个Trigger的子类。请参考其他现有的类

NOTE: 如果触发器在两边都有激活点，子类要继承自++BothSideActivatedTrigger++，否则继承自++SingleSideActivatedTrigger++

=== 如何创建一个新的触发器动作

. ++TriggerTypeDef.h++文件中增加新的++TriggerActionType++枚举值，并在它下面的++triggerActionTypeNames++数组中添加对应的枚举值字符串。
. 确定它在客户端执行还是在服务端执行。如果在客户端执行，那么触发器动作代码写在++TriggerActionsClient.h/cpp++中。如果在服务端执行，那么触发器动作代码写在++TriggerActionsServer.h/cpp++中。
. 在上面确定的文件中新建一个TriggerAction的子类。请参考其他现有的类

