#include "Core.h"
#include "EffectIElement.h"

namespace LORD
{

	const String IElement::token[250] = 
	{
		"effect",
		"effect_scale",
		"effect_timescale",
		"effect_lod1",
		"effect_lod2",
		"effect_fallowpair",
		"effect_2d",
		"effect_positionx",
		"effect_positiony",
		"effect_fadetime",

		"layer",
		"layer_name",
		"layer_lod",
		"layer_ispuppet",
		"layer_spacewarp",
		"layer_rendergroup",
		"layer_repeatcount",
		"layer_repeattime",
		"layer_restate",

		"layer_bb_width",
		"layer_bb_height",
		"layer_bb_perpendicular",
		"layer_bb_noscalewidth",
		"layer_bb_noscaleheight",
		"layer_bb_centrewidth",
		"layer_bb_centreheight",
		"layer_bb_offsetviewport",
		"layer_3bb_usegroundnormal",
		"layer_3bb_needupdate",
		"layer_3bb_useterrainheight",

		"layer_co_radiusbottom",
		"layer_co_radiustop",
		"layer_co_height",
		"layer_co_segment",
		"layer_co_noscalewidth",
		"layer_co_noscaleheight",
		"layer_co_keepcenter",
		"layer_co_texclamp",

		"layer_pb_param",
		"layer_pb_height",

		"layer_tr_position1",
		"layer_tr_position2",
		"layer_tr_durationtime",
		"layer_tr_fallowparent",

		"layer_ln_beginpos",
		"layer_ln_endpos",
		"layer_ln_segment",
		"layer_ln_num",
		"layer_ln_wavelen",
		"layer_ln_timespin",
		"layer_ln_startwidth",
		"layer_ln_endwidth",
		"layer_ln_midderwidth",
		"layer_ln_startalpha",
		"layer_ln_endalpha",
		"layer_ln_midderalpha",
		"layer_ln_usenormal",
		"layer_ln_normal",
		"layer_ln_curvedlen",
		"layer_ln_deviation",
		"layer_ln_filter",
		"layer_ln_extenal",

		"layer_rp_beginpos",
		"layer_rp_endpos",
		"layer_rp_segment",
		"layer_rp_startwidth",
		"layer_rp_endwidth",
		"layer_rp_startalpha",
		"layer_rp_endalpha",
		"layer_rp_midderalpha",
		"layer_rp_curvedlen",
		"layer_rp_flytime",
		"layer_rp_uvscale",

		"layer_cp_area",

		"layer_sp_area",

		"layer_lp_area",

		"layer_es_rows",
		"layer_es_columns",
		"layer_es_interval",
		"layer_es_offviewport",
		"layer_es_vectors",
		"layer_es_colors",

		"layer_smd_transparent",
		"layer_smd_name",
		"layer_dmd_transparent",
		"layer_dmd_skeleton",
		"layer_dmd_skin",
		"layer_dmd_animation",
		"layer_dmd_attachmodel",
		"layer_dmd_attachbone",
		"layer_dmd_arepeatcount",

		"layer_sa_useg",
		"layer_sa_vseg",
		"layer_sa_width",
		"layer_sa_height",
		"layer_sa_speed",

		"layer_ce_name",
		"layer_ce_loop",
		"layer_ce_speed",

		"layer_pt_quota",
		"layer_pt_width",
		"layer_pt_height",
		"layer_pt_3dbillboard",
		"layer_pt_prependicular",
		"layer_pt_3dtrans",
		"layer_pt_notransscale",
		"layer_pt_noscalewidth",
		"layer_pt_noscaleweight",
		"layer_pt_centerwidth",
		"layer_pt_centerheight",
		"layer_pt_emitterrate",
		"layer_pt_emitterangle",
		"layer_pt_speed",
		"layer_pt_maxspeed",
		"layer_pt_addspeed",
		"layer_pt_leavetime",
		"layer_pt_maxleavetime",
		"layer_pt_mincolor",
		"layer_pt_maxcolor",
		"layer_pt_minscale",
		"layer_pt_maxscale",
		"layer_pt_min2dangle",
		"layer_pt_max2dangle",
		"layer_pt_fallowparent",
		"layer_pt_emitterinsurface",

		"e_material",
		"e_material_alphamode",
		"e_material_zwritting",
		"e_material_texture",
		"e_material_uvswap",
		"e_material_flipu",
		"e_material_flipv",
		"e_material_uspeed",
		"e_material_vspeed",
		"e_material_clampmode",
		"e_material_scriptrows",
		"e_material_scriptcolumn",
		"e_material_scripttime",
		"e_material_uvvalue",

		"distortion_enable",
		"distortion_texture",
		"distortion_uvvalue",
		"distortion_alpha_threshold",
		"distortion_tc_offsetu",
		"distortion_tc_offsetv",
		"distortion_tc_sacleu",
		"distortion_saclev",
		"distortion_blend_weight",
		"distortion_only",

		"keyframe",
		"keyframe_position",
		"keyframe_oritation",
		"keyframe_pitch",
		"keyframe_yaw",
		"keyframe_roll",
		"keyframe_selfrotate",
		"keyframe_scale",
		"keyframe_color",
		"keyframe_begintime",
		"keyframe_affecttime",
		"keyframe_slerpmode",
		"keyframe_simplespline",
		"keyframe_autooritation",

		"particlecontrollerset",

		"controller",
		"controller_begintime",
		"controller_endtime",

		"controller_ts_direction",
		"controller_ts_speed",
		"controller_ts_addspeed",

		"controller_rs_speed",
		"controller_rs_addspeed",

		"controller_ra_axispos",
		"controller_ra_axisdir",
		"controller_ra_speed",
		"controller_ra_addspeed",

		"controller_rr_axispos",
		"controller_rr_axisdir",
		"controller_rr_speed",
		"controller_rr_addspeed",

		"controller_oc_center",
		"controller_oc_speed",
		"controller_oc_addspeed",

		"controller_cc_r",
		"controller_cc_g",
		"controller_cc_b",
		"controller_cc_a",

		"controller_cn_swing",
		"controller_cn_wavelen",
		"controller_cn_basecolor",

		"controller_cs_begincolor",
		"controller_cs_setNum",
		"controller_cs_targetcolor1",
		"controller_cs_time1",
		"controller_cs_targetcolor2",
		"controller_cs_time2",
		"controller_cs_targetcolor3",
		"controller_cs_time3",
		"controller_cs_targetcolor4",
		"controller_cs_time4",

		"controller_ss_beginscale",
		"controller_ss_setNum",
		"controller_ss_targetscale1",
		"controller_ss_time1",
		"controller_ss_targetscale2",
		"controller_ss_time2",
		"controller_ss_targetscale3",
		"controller_ss_time3",
		"controller_ss_targetscale4",
		"controller_ss_time4",

		"controller_sc_scale",
		"controller_sc_minscale",
		"controller_sc_maxscale",

		"controller_sn_swing",
		"controller_sn_wavelen",
	};
}
