---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jimmy.
--- DateTime: 2019/10/14 0014 15:29
---
EntityType = {
    Invalid = -1,
    Entity = 0,
    LivingBase = 1,
    Living = 2,
    Creature = 3,
    Player = 4,
    PlayerOtherMp = 5,
    PlayerMp = 6,
    PlayerSp = 7,
    PlayerSpMp = 8,
    Arrow = 9,
    Bullet = 10,
    XPOrb = 11,
    Mob = 12,
    Item = 13,
    Zombie = 14,
    Hanging = 15,
    Boat = 16,
    Squid = 17,
    Wither = 18,
    Bat = 19,
    Blockman = 20,
    Pid = 21,
    ItemFrame = 22,
    Animals = 23,
    Dragon = 24,
    Fishhook = 25,
    FishhookClient = 26,
    Potion = 27,
    ExpBottle = 28,
    EnderPearl = 29,
    EnderEye = 30,
    FireworkRocket = 31,
    SmallFireBall = 32,
    FireBall = 33,
    Egg = 34,
    TNTPrimed = 35,
    TNTThrowable = 36,
    EnderCrystal = 37,
    FallingSand = 38,
    Painting = 39,
    LeashKnot = 40,
    Container = 41,
    Snowball = 42,
    Throwable = 43,
    Merchant = 44,
    Grenade = 45,
    Vehicle = 46,
    VehicleClient = 47,
    RankNpc = 48,
    Aircraft = 49,
    ActorNpc = 50,
    SessionNpc = 51,
    CreatureAI = 52,
    CreatureBullet = 53,
    ItemSkill = 54,
    BlockmanEmpty = 55,
    ActorCannon = 56,
    ActorCannonClient = 57,
    BuildNpc = 58,
    LandNpc = 59,
    GunFlame = 60,
    Bulletin = 61,
    Bird = 62,
    BirdAI = 63,
    Decoration = 64,
    Robot = 65,
    FlyingMount = 66,
    FloatingMount = 67,
    BulletClient = 68,
    WalkingDeadAI = 69,
}

local Creators = {}

EntityDefine = {}

function EntityDefine:isPlayer(entityType)
    return entityType == EntityType.Player
            or entityType == EntityType.PlayerOtherMp
            or entityType == EntityType.PlayerMp
            or entityType == EntityType.PlayerSp
            or entityType == EntityType.PlayerSpMp
end

function EntityDefine:registerEntityType(type, class)
    Creators[type] = class
end

function EntityDefine:getCreator(type)
    return Creators[type] or IEntity
end