---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 10184.
--- DateTime: 2020/6/16 14:04
---
GMSetting:addTab("起床战争", 1)
GMSetting:addItem("起床战争", "开始游戏", "startGame")
GMSetting:addItem("起床战争", "道具商店", "openGoodsShop")
GMSetting:addItem("起床战争", "升级商店", "openUpgradeShop")
GMSetting:addItem("起床战争", "改铁锻炉表现", "changeTeamResourceMode")
GMSetting:addItem("起床战争", "", "")
GMSetting:addItem("起床战争", "+铁定", "addGameItem", ItemID.INGOT_IRON)
GMSetting:addItem("起床战争", "+金锭", "addGameItem", ItemID.INGOT_GOLD)
GMSetting:addItem("起床战争", "+钻石", "addGameItem", ItemID.DIAMOND)
GMSetting:addItem("起床战争", "+绿宝石", "addGameItem", ItemID.EMERALD)
GMSetting:addItem("起床战争", "", "")
GMSetting:addItem("起床战争", "红队出生点", "teleTeamPos", 1)
GMSetting:addItem("起床战争", "蓝队出生点", "teleTeamPos", 2)
GMSetting:addItem("起床战争", "绿队出生点", "teleTeamPos", 3)
GMSetting:addItem("起床战争", "黄队出生点", "teleTeamPos", 4)
GMSetting:addItem("起床战争", "", "")
GMSetting:addItem("起床战争", "青队出生点", "teleTeamPos", 5)
GMSetting:addItem("起床战争", "白队出生点", "teleTeamPos", 6)
GMSetting:addItem("起床战争", "粉队出生点", "teleTeamPos", 7)
GMSetting:addItem("起床战争", "黑队出生点", "teleTeamPos", 8)
GMSetting:addItem("起床战争", "", "")
GMSetting:addItem("起床战争", "毁掉红队床", "destroyBed", 1)
GMSetting:addItem("起床战争", "毁掉蓝队床", "destroyBed", 2)
GMSetting:addItem("起床战争", "毁掉绿队床", "destroyBed", 3)
GMSetting:addItem("起床战争", "毁掉黄队床", "destroyBed", 4)
GMSetting:addItem("起床战争", "", "")
GMSetting:addItem("起床战争", "毁掉青队床", "destroyBed", 5)
GMSetting:addItem("起床战争", "毁掉白队床", "destroyBed", 6)
GMSetting:addItem("起床战争", "毁掉粉队床", "destroyBed", 7)
GMSetting:addItem("起床战争", "毁掉黑队床", "destroyBed", 8)
GMSetting:addItem("起床战争", "毁掉所有床", "destroyAllBed")
GMSetting:addItem("起床战争", "随机杀敌人", "killPlayer")
GMSetting:addItem("起床战争", "自杀", "killSelf")
GMSetting:addItem("起床战争", "杀死所有敌人", "killAllPlayer")
GMSetting:addItem("起床战争", "", "")
GMSetting:addItem("起床战争", "换头盔", "changeHelmet")
GMSetting:addItem("起床战争", "换成男模型", "changePlayerActor", 1)
GMSetting:addItem("起床战争", "换成女模型", "changePlayerActor", 2)
GMSetting:addItem("起床战争", "清除钥匙", "cleanYaoShi")
GMSetting:addItem("起床战争", "+50经验", "addExp")
GMSetting:addItem("起床战争", "添加基础怪物", "addMonster")
GMSetting:addItem("起床战争", "清除怪物", "clearMonster")
GMSetting:addItem("起床战争", "添加雪球囊虫", "SnowBallInsect")
GMSetting:addItem("起床战争", "巫毒药水Buff", "addBanCureBuff")
GMSetting:addItem("起床战争", "回城卷轴Buff", "addBackHomeBuff")

function GMHelper:openGoodsShop()
    GUIGMControlPanel:hide()
    GUIStore:show(StoreId.GoodsStore)
end

function GMHelper:openUpgradeShop()
    GUIGMControlPanel:hide()
    GUIUpgradeStore:show(true)
end

function GMHelper:changePlayerActor(sex)
    if isGameStart then
        if sex == 1 then
            ClientHelper.putStringPrefs("BoyActorName", "boy.actor")
            ClientHelper.putStringPrefs("GirlActorName", "boy.actor")
        else
            ClientHelper.putStringPrefs("BoyActorName", "girl.actor")
            ClientHelper.putStringPrefs("GirlActorName", "girl.actor")
        end
    else
        if sex == 1 then
            ClientHelper.putStringPrefs("BoyActorName", "boy.actor")
            ClientHelper.putStringPrefs("GirlActorName", "boy.actor")
        else
            ClientHelper.putStringPrefs("BoyActorName", "girl.actor")
            ClientHelper.putStringPrefs("GirlActorName", "girl.actor")
        end
    end
    local players = PlayerManager:getPlayers()
    for _, player in pairs(players) do
        if player.Player then
            player.Player.m_isPeopleActor = false
            EngineWorld:restorePlayerActor(player)
        end
    end
end

function GMHelper:changeTeamResourceMode()
    if TeamResourceMode == 1 then
        TeamResourceMode = 2
    else
        TeamResourceMode = 1
    end
end