---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 10184.
--- DateTime: 2020/7/21 17:34
---
---获取北京跟当前服务器时间戳的差值
local function getBeiJingDiffTime()
    return os.time(os.date("*t")) - os.time(os.date("!*t")) - 28800
end

---根据date获取北京时间戳
---@param date table 某个北京时间日期的table
---eg: { year = 2020, month = 1, day = 20, hour = 1, min = 1, sec = 0 }
function DateUtil.date2BeiJingTime(date)
    date.isdst = false
    return os.time(date) + getBeiJingDiffTime()
end

require "common.data.ICustomShop"
require "common.data.IBlockShop"
require "common.config.CustomShopConfig"
require "common.config.BlockShopConfig"
require "common.config.SoundConfig"
require "common.packet.CommonPacketSender"
require "common.packet.CommonPacketHandler"

if isClient then
    require "common.config.RewardConfig"
    require "common.data.ClientCustomShop"
    require "common.data.ClientBlockShop"
    require "common.data.ClientStore"
else
    require "common.data.ServerCustomShop"
    require "common.data.ServerBlockShop"
    require "common.data.GameStore"
end

require "common.config.ItemConfig"
require "common.config.StoreConfig"
require "common.config.LicenseConfig"