---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 10184.
--- DateTime: 2020/11/18 10:21
---
GUIMustLotteryItem = class("GUIMustLotteryItem", IGUIWindow) ---@class GUIMustLotteryItem

---@param parent GUIMustLotteryPanel
function GUIMustLotteryItem:onLoad(parent)
    self.parent = parent
    self.llRoot = DynamicCast.dynamicCastWindow(GUIType.Layout, self.root)
    self.ivImage = self:getChildWindowByName("MustLotteryItem-Image", GUIType.StaticImage)
    self.tvCount = self:getChildWindowByName("MustLotteryItem-Count", GUIType.StaticText)
    self.ivSelected = self:getChildWindowByName("MustLotteryItem-Selected", GUIType.StaticImage)
    self.btnSelected = self:getChildWindowByName("MustLotteryItem-Selected-Click", GUIType.Button)
    self.llMask = self:getChildWindowByName("MustLotteryItem-Mask", GUIType.Layout)
    self.ivMaskIcon = self:getChildWindowByName("MustLotteryItem-Mask-Icon", GUIType.StaticImage)
    self.ivEffect = self:getChildWindowByName("MustLotteryItem-Effect", GUIType.StaticImage)
    self.llMask:SetVisible(false)
    self.llRoot:registerEvent(GUIEvent.Click, function()
        self.parent:clickItem(self)
    end)
    self.btnSelected:registerEvent(GUIEvent.ButtonClick, function()
        self.parent:selectItem(self)
    end)
    self:setEffect(false)
end

function GUIMustLotteryItem:onDataChanged(data)
    self.isGrandPrize = data.isGrandPrize
    self.groupSeq = data.groupSeq
    self.reward = data.reward
    UIHelper:setImageAdjustSize(self.ivImage, self.reward.image)
    if not self.reward.numLang or self.reward.numLang == "#" then
        self.tvCount:SetText("x" .. self.reward.num)
    else
        self.tvCount:SetText(Lang:getString(self.reward.numLang))
    end
    self.llRoot:SetBackImage("set:common_activity.json image:img_iconboard_" .. data.reward.quality)
    if self.isGrandPrize then
        self.ivSelected:SetVisible(false)
    end
end

function GUIMustLotteryItem:setSelected(selected)
    if selected then
        self.ivSelected:SetImage("set:common_activity.json image:chb_0_selected")
    else
        self.ivSelected:SetImage("set:common_activity.json image:chb_0_normal")
    end
end

---设置成被删除
function GUIMustLotteryItem:setDelete(deleted)
    self.ivSelected:SetVisible(false)
    self.llMask:SetVisible(deleted)
    if deleted then
        self.ivMaskIcon:SetImage("set:common_activity.json image:img_0_item_remove")
        self.ivMaskIcon:SetWidth({ 0, 24 })
        self.ivMaskIcon:SetHeight({ 0, 23 })
    else
        if self.isGet then
            self:setGet()
        end
    end
end

---设置成已获得
function GUIMustLotteryItem:setGet()
    self.isGet = true
    self.llMask:SetVisible(true)
    self.ivMaskIcon:SetImage("set:common_activity.json image:img_0_item_get")
    self.ivMaskIcon:SetWidth({ 0, 29 })
    self.ivMaskIcon:SetHeight({ 0, 21 })
    self.ivEffect:SetVisible(false)
end

function GUIMustLotteryItem:setEffect(effect)
    self.ivEffect:SetVisible(effect)
end