---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jimmy.
--- DateTime: 2019/9/3 0003 10:01
---
PluginMain = {}

function PluginMain:init()
    ClientHelper.putBoolPrefs("IsActorAction", false)
    ClientHelper.putBoolPrefs("IsRedAim", false)
    for blockId = 1, 256 do
        local block = BlockManager.getBlockById(blockId)
        if block then
            block:setHardness(10000)
        end
    end
end

PluginMain:init()

return PluginMain