---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jimmy.
--- DateTime: 2019/10/9 0009 9:50
---

local UITycoonToolBar = require "ui.layout.GUITycoonToolBar"
GUITycoonToolBar = UITycoonToolBar.new("TycoonToolBar.json", GUIManager:getToolBar())
GUITycoonToolBar:show()